### ISSUE TITLE
Rebuilding messages

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#1006]
I get this error when rebuilding custom pages messages. Any reasons why? The file clearly exists as far as I know.

```txt
PHP Error[2]: include(CustomPages.php): failed to open stream: No such file or directory
    in file /home/.../.../...//public_shtml/protected/vendors/yii/YiiBase.php at line 427
#0 /home/.../.../...//public_shtml/protected/vendors/yii/YiiBase.php(427): autoload()
#1 unknown(0): autoload()
#2 unknown(0): spl_autoload_call()
#3 /home/.../.../...//public_shtml/protected/commands/shell/ZMessageCommand.php(92): ReflectionClass->__construct()
#4 /home/.../.../...//public_shtml/protected/vendors/yii/console/CConsoleCommandRunner.php(71): ZMessageCommand->run()
#5 /home/.../.../...//public_shtml/protected/vendors/yii/console/CConsoleApplication.php(92): CConsoleCommandRunner->run()
#6 /home/.../.../...//public_shtml/protected/vendors/yii/base/CApplication.php(180): HConsoleApplication->processRequest()
#7 /home/.../.../...//public_shtml/protected/yiic.php(26): HConsoleApplication->run()
#8 /home/.../.../...//public_shtml/protected/yiic(5): require_once()
```

**Comment by luke-** [comment]
Maybe there is somewhere a wrong Translation Namespace used in Yii::t?

**Comment by WASasquatch** [comment]
Yep, sure was. Thanks.
