### ISSUE TITLE
wrong database connect during installation (humhub 0.20.0-beta1)

### ISSUE THREAD

**Issue by tobciu** [humhub/humhub#1173]
after the installation of humhub 0.20.0-beta1, there was the follogin message in the log...

the database connection was initiatet with the ROOT_PASSWORT as username and no password...

Access denied for user **'ROOT_PASSWORD'@'localhost'** (using password: NO)' 

```
2015-09-07 08:18:15 [192.168.33.1][-][-][info][application] $_GET = [
    'r' => 'installer/index'
]

$_SERVER = [
    'HTTP_HOST' => 'humhub2.local'
    'HTTP_CONNECTION' => 'keep-alive'
    'HTTP_CACHE_CONTROL' => 'max-age=0'
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch'
    'HTTP_ACCEPT_LANGUAGE' => 'de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,und;q=0.2'
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    'SERVER_SIGNATURE' => '<address>Apache/2.4.7 (Ubuntu) Server at humhub2.local Port 80</address>
'
    'SERVER_SOFTWARE' => 'Apache/2.4.7 (Ubuntu)'
    'SERVER_NAME' => 'humhub2.local'
    'SERVER_ADDR' => '192.168.33.10'
    'SERVER_PORT' => '80'
    'REMOTE_ADDR' => '192.168.33.1'
    'DOCUMENT_ROOT' => '/var/www/humhub2'
    'REQUEST_SCHEME' => 'http'
    'CONTEXT_PREFIX' => ''
    'CONTEXT_DOCUMENT_ROOT' => '/var/www/humhub2'
    'SERVER_ADMIN' => '[no address given]'
    'SCRIPT_FILENAME' => '/var/www/humhub2/index.php'
    'REMOTE_PORT' => '61367'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => 'r=installer%2Findex'
    'REQUEST_URI' => '/index.php?r=installer%2Findex'
    'SCRIPT_NAME' => '/index.php'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1441613895.629
    'REQUEST_TIME' => 1441613895
]
2015-09-07 08:18:16 [192.168.33.1][-][-][warning][yii\log\Dispatcher::dispatch] Unable to send log via yii\log\DbTarget: Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[28000] [1045] Access denied for user 'ROOT_PASSWORD'@'localhost' (using password: NO)' 

in /var/www/humhub2/protected/vendor/yiisoft/yii2/db/Connection.php:534

Stack trace:
#0 /var/www/humhub2/protected/vendor/yiisoft/yii2/db/Connection.php(836): yii\db\Connection->open()
#1 /var/www/humhub2/protected/vendor/yiisoft/yii2/db/Connection.php(823): yii\db\Connection->getMasterPdo()
#2 /var/www/humhub2/protected/vendor/yiisoft/yii2/db/Schema.php(477): yii\db\Connection->getSlavePdo()
#3 /var/www/humhub2/protected/vendor/yiisoft/yii2/db/Connection.php(732): yii\db\Schema->quoteValue('yii\debug\Modul...')
#4 /var/www/humhub2/protected/vendor/yiisoft/yii2/db/Command.php(172): yii\db\Connection->quoteValue('yii\debug\Modul...')
#5 /var/www/humhub2/protected/vendor/yiisoft/yii2/db/Command.php(767): yii\db\Command->getRawSql()
#6 /var/www/humhub2/protected/vendor/yiisoft/yii2/log/DbTarget.php(83): yii\db\Command->execute()
#7 /var/www/humhub2/protected/vendor/yiisoft/yii2/log/Target.php(111): yii\log\DbTarget->export()
#8 /var/www/humhub2/protected/vendor/yiisoft/yii2/log/Dispatcher.php(183): yii\log\Target->collect(Array, true)
#9 /var/www/humhub2/protected/vendor/yiisoft/yii2/log/Logger.php(173): yii\log\Dispatcher->dispatch(Array, true)
#10 [internal function]: yii\log\Logger->flush(true)
#11 {main}
```

**Comment by 2monkey** [comment]
Same problem!
Status on this problem ? 13 days ago...

**Comment by luke-** [comment]
Is this just a "Log" Problem?

**Comment by 2monkey** [comment]
no .. script error after database migration.
(from 0.11 to 0.20beta)

**Comment by luke-** [comment]
Can you provide the error message?

**Comment by swapnil2sutar** [comment]
Any Solution on this ?
