### ISSUE TITLE
500 Internal Server Error (Timeout) when installing modues

### ISSUE THREAD

**Issue by julianpollmann** [humhub/humhub#1289]
Hey,

i've got a Internal Server Error when installing modules from remote. Uploading the modules and enable them in the backend does work.

Administration -> Logging puts out the following:

```
exception 'Zend\Http\Client\Adapter\Exception\RuntimeException' with message 'Error in cURL request: Connection timed out after 30001 milliseconds' in /var/www/html/humhub/protected/vendor/zendframework/zend-http/src/Client/Adapter/Curl.php:425 Stack trace:
#0 /var/www/html/humhub/protected/vendor/zendframework/zend-http/src/Client.php(1387): Zend\Http\Client\Adapter\Curl->write('GET', Object(Zend\Uri\Http), '1.1', Array, '')
#1 /var/www/html/humhub/protected/vendor/zendframework/zend-http/src/Client.php(893): Zend\Http\Client->doRequest(Object(Zend\Uri\Http), 'GET', true, Array, '')
#2 /var/www/html/humhub/protected/humhub/modules/admin/libs/OnlineModuleManager.php(82): Zend\Http\Client->send()
#3 /var/www/html/humhub/protected/humhub/modules/admin/controllers/ModuleController.php(97): humhub\modules\admin\libs\OnlineModuleManager->install('wiki')
#4 [internal function]: humhub\modules\admin\controllers\ModuleController->actionInstall()
#5 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#6 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#7 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('install', Array)
#8 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('admin/module/in...', Array)
#9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /var/www/html/humhub/index.php(25): yii\base\Application->run()
#11 {main}
```

I guess our hosting provider has blocked outgoing cURL. Which host must be allowed to solve this problem?

**Comment by luke-** [comment]
www.humhub.org / www.humhub.com / api.humhub.com
