### ISSUE TITLE
Could not find BaseActivity NoteUpdated for Activity Record.

### ISSUE THREAD

**Issue by 0berst** [humhub/humhub#1293]
I tried to upgrade from 0.11.2 to 0.20.0. After the upgrade the streams on the dashboard and in the spaces will not load. It only shows the three loading dots. Everything else seems to work.

In both cases I get the following two server errors (internal server error 500):

__Could not find BaseActivity NoteUpdated for Activity Record__
/var/www/humhub2/protected/humhub/modules/activity/models/Activity.php (line 81)
stacktrace:
```
0:"#0 /var/www/humhub2/protected/humhub/modules/activity/models/Activity.php(93): humhub\modules\activity\models\Activity->getActivityBaseClass()"
1:"#1 /var/www/humhub2/protected/humhub/modules/content/components/actions/Stream.php(259): humhub\modules\activity\models\Activity->getWallOut()"
2:"#2 [internal function]: humhub\modules\content\components\actions\Stream->run()"
3:"#3 /var/www/humhub2/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array)"
4:"#4 /var/www/humhub2/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\Action->runWithParams(Array)"
5:"#5 /var/www/humhub2/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('stream', Array)"
6:"#6 /var/www/humhub2/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('dashboard/dashb...', Array)"
7:"#7 /var/www/humhub2/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request))"
8:"#8 /var/www/humhub2/index.php(25): yii\base\Application->run()"
9:"#9 {main}"
```

__Could not get contents underlying object!__
/var/www/humhub2/protected/humhub/modules/content/components/actions/Stream.php (line 249)
stacktrace
```
0:"#0 [internal function]: humhub\modules\content\components\actions\Stream->run()"
1:"#1 /var/www/humhub2/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array)"
2:"#2 /var/www/humhub2/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\Action->runWithParams(Array)"
3:"#3 /var/www/humhub2/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('stream', Array)"
4:"#4 /var/www/humhub2/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('dashboard/dashb...', Array)"
5:"#5 /var/www/humhub2/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request))"
6:"#6 /var/www/humhub2/index.php(25): yii\base\Application->run()"
7:"#7 {main}"
```

**Comment by luke-** [comment]
Please ensure that migrations ran, all NoteUpdated activities should be deleted on update.

https://github.com/humhub/humhub-modules-notes/blob/master/migrations/m150726_182212_namespace.php#L17-L19

On Activity table there should be no type=NoteUpdated records.

You can also try run the db integrity checker.

```
cd protected
php yii integrity/run
```
