### ISSUE TITLE
CHttpException

### ISSUE THREAD

**Issue by pedrommone** [humhub/humhub#131]
Im getting a lot of CHttpException on logs files

```
2014/09/08 09:06:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resol                                                ve the request "assets/c33dcf56/userpicker.js".' in /home/x/web/social.x.com/public_html/protected/vend                                                ors/yii/web/CWebApplication.php:288
Stack trace:
#0 /home/x/web/social.x.com/public_html/protected/vendors/yii/web/CWebApplication.php(141): CWebApplica                                                tion->runController('assets/c33dcf56...')
#1 /home/x/web/social.x.com/public_html/protected/vendors/yii/base/CApplication.php(169): CWebApplicati                                                on->processRequest()
#2 /home/x/web/social.x.com/public_html/index.php(39): CApplication->run()
#3 {main}
REQUEST_URI=/assets/c33dcf56/userpicker.js
HTTP_REFERER=http://social.x.com/dashboard

---
2014/09/08 09:08:39 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'The CSRF token                                                 could not be verified.' in /home/x/web/social.x.com/public_html/protected/vendors/yii/web/CHttpRequest.                                                php:1042
Stack trace:
#0 /home/x/web/social.x.com/public_html/protected/vendors/yii/base/CComponent.php(559): CHttpRequest->v                                                alidateCsrfToken(Object(CEvent))
#1 /home/x/web/social.x.com/public_html/protected/vendors/yii/base/CApplication.php(196): CComponent->r                                                aiseEvent('onBeginRequest', Object(CEvent))
#2 /home/x/web/social.x.com/public_html/protected/vendors/yii/base/CApplication.php(167): CApplication-                                                >onBeginRequest(Object(CEvent))
#3 /home/x/web/social.x.com/public_html/index.php(39): CApplication->run()
#4 {main}
```

**Comment by taha-azzabi** [comment]
I got the same issue you need to increase upload_max_filesize and post_max_filesize in your server
http://stackoverflow.com/questions/2184513/php-change-the-maximum-upload-file-size

**Comment by christophlehmann** [comment]
@taha-azzabi I have both values > 100M
