### ISSUE TITLE
Cron jobs failed to send e-mails to some users.

### ISSUE THREAD

**Issue by badis** [humhub/humhub#1413]
I'm not sure if it's related to this issue :  https://github.com/humhub/humhub/issues/1412
 
or

to a bug on the SQL Query ( Column 'status' is ambiguous [ see the error excerpt  below found in the logging zone ] )
 
............
..........
.........   public_html/app/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(339): yii\db\Query->queryScalar('COUNT(*)', NULL) #4 /home/booking1/public_html/app/protected/vendor/yiisoft/yii2/db/Query.php(296): yii\db\ActiveQuery->queryScalar('COUNT(*)', NULL) #5 /home/booking1/public_html/app/protected/humhub/modules/content/Events.php(138): yii\db\Query->count() #6 [internal function]: humhub\modules\content\Events::onCronRun(Object(yii\base\Event)) #7 /home/booking1/public_html/app/protected/vendor/yiisoft/yii2/base/Event.php(188): call_user_func(Array, Object(yii\base\Event)) #8 /home/booking1/public_html/app/protected/vendor/yiisoft/yii2/base/Component.php(549): yii\base\Event::trigger(Object(humhub\commands\CronController), 'hourly', NULL) #9 
...........
...........
 'yii\db\IntegrityException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'status' in where clause is ambiguous The SQL being executed was: SELECT COUNT(*) FROM `user` LEFT JOIN `user_http_session` ON `user`.`id` = `user_http_session`.`user_id` LEFT JOIN `profile` ON `user`.`id` = `profile`.`user_id` WHERE `status`=1' 

.........

**Comment by badis** [comment]
This error shows up when we add a profile field with name status . so where ever we use JOIN between USER and PROFILE it will result in a [ .. SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'status' in where clause is ambiguous  ..]

My suggestion is to add table name before all User table columns on every function on the platform.
