### ISSUE TITLE
Cron jobs weird behavior. ( possiblity of a bug )

### ISSUE THREAD

**Issue by badis** [humhub/humhub#1505]
Here are the details : 
- humhub version : 0.20.0.
- cron job were working on old hosting server . not working on new hosting server.
- I have runned : php yii integrity/run and everything is consistent.
- cron job run correctly on new server with command : php yii cron/hourly.
- the main problem is when the server try to run cron job the error

`exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: yii\console\Request::get()`

 occured in script :

`humhub/protected/humhub/modules/content/components/actions/Stream.php`  Line : 115

I think the script shouldn't reach this line in the first place.

I can give more details if it's necessary to investigate this issue.

Thank you.

**Comment by luke-** [comment]
Can you try a newer version?

These version should be more stable...

**Comment by badis** [comment]
Same thing happen with another website based on version 0.20.1
Unfortunately , i can't update these websites because they are in production and newer versions of humhub are in beta.
May be it's not related to humhub . I think it's a bug on Yii framework.
This line 114 in Stream.php doesn't recognize the request from server as a console request.
`Yii::$app->request->isConsoleRequest`

**Comment by dexalin** [comment]
Experiencing the same issue in 1.0.0-beta.3 & 4. Nothing was changed with our configuration, hourly cron hasn't run since the 26th.

**Comment by 2monkey** [comment]
orginal (114):</br>
```php
if (!Yii::$app->request->isConsoleRequest)
```
 fixed it, but only a workaround:
```php
if (Yii::$app->request->isConsoleRequest)
```

**Comment by thomaswillecomme** [comment]
I Have the same problem in Humhub 1.1.2
My cron jobs are executed through the following php script (my host only provide php cron jobs):

```
<?php
	$output = shell_exec('~/www/humhub/protected/yii cron/hourly');
	echo "<pre>$output</pre>";
?>
```
Here is the trace
```
Executing hourly tasks:


Sending update e-mails to users... 0% (0/38) ETA: n/a   
Sending update e-mails to users... 2% (1/38) ETA: n/a   
Sending update e-mails to users... 5% (2/38) ETA: n/a   
Sending update e-mails to users... 7% (3/38) ETA: n/a   
Sending update e-mails to users... 10% (4/38) ETA: n/a   
Sending update e-mails to users... 13% (5/38) ETA: n/a   
Sending update e-mails to users... 15% (6/38) ETA: n/a   
Sending update e-mails to users... 18% (7/38) ETA: n/a   
Sending update e-mails to users... 21% (8/38) ETA: n/a   
Sending update e-mails to users... 23% (9/38) ETA: n/a   
Sending update e-mails to users... 26% (10/38) ETA: n/a   
Sending update e-mails to users... 28% (11/38) ETA: n/a   
Sending update e-mails to users... 31% (12/38) ETA: n/a   
Sending update e-mails to users... 34% (13/38) ETA: n/a   
Sending update e-mails to users... 36% (14/38) ETA: n/a   
Sending update e-mails to users... 39% (15/38) ETA: n/a   
Sending update e-mails to users... 42% (16/38) ETA: n/a   
Sending update e-mails to users... 44% (17/38) ETA: n/a   Status: 500 Internal Server Error
X-Powered-By: PHP/5.4.45
Content-type: text/html

Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: yii\console\Request::get()'

in /home/grenoblea/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php:285

Stack trace:
#0 /home/grenoblea/www/humhub/protected/humhub/modules/content/components/actions/Stream.php(115): yii\base\Component->__call('get', Array)
#1 /home/grenoblea/www/humhub/protected/humhub/modules/content/components/actions/Stream.php(115): yii\console\Request->get('from', 0)
#2 /home/grenoblea/www/humhub/protected/humhub/modules/dashboard/components/actions/DashboardStream.php(28): humhub\modules\content\components\actions\Stream->init()
#3 /home/grenoblea/www/humhub/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\modules\dashboard\components\actions\DashboardStream->init()
#4 /home/grenoblea/www/humhub/protected/vendor/yiisoft/yii2/base/Action.php(60): yii\base\Object->__construct(Array)
#5 /home/grenoblea/www/humhub/protected/humhub/modules/activity/Module.php(69): yii\base\Action->__construct('stream', Object(humhub\commands\CronController))
#6 /home/grenoblea/www/humhub/protected/humhub/modules/content/components/MailUpdateSender.php(155): humhub\modules\activity\Module->getMailActivities(Object(humhub\modules\user\models\User), 2)
#7 /home/grenoblea/www/humhub/protected/humhub/modules/content/components/MailUpdateSender.php(95): humhub\modules\content\components\MailUpdateSender->renderActivities()
#8 /home/grenoblea/www/humhub/protected/humhub/modules/content/components/MailUpdateSender.php(66): humhub\modules\content\components\MailUpdateSender->send()
#9 /home/grenoblea/www/humhub/protected/humhub/modules/content/Events.php(122): humhub\modules\content\components\MailUpdateSender::processCron(Object(humhub\commands\CronController))
#10 [internal function]: humhub\modules\content\Events::onCronRun(Object(yii\base\Event))
#11 /home/grenoblea/www/humhub/protected/vendor/yiisoft/yii2/base/Event.php(216): call_user_func(Array, Object(yii\base\Event))
#12 /home/grenoblea/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php(548): yii\base\Event::trigger(Object(humhub\commands\CronController), 'hourly', NULL)
#13 /home/grenoblea/www/humhub/protected/humhub/commands/CronController.php(41): yii\base\Component->trigger('hourly')
#14 [internal function]: humhub\commands\CronController->actionHourly()
#15 /home/grenoblea/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#16 /home/grenoblea/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#17 /home/grenoblea/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('hourly', Array)
#18 /home/grenoblea/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('hourly', Array)
#19 /home/grenoblea/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('cron/hourly', Array)
#20 /home/grenoblea/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('cron/hourly', Array)
#21 /home/grenoblea/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#22 /home/grenoblea/www/humhub/protected/yii(28): yii\base\Application->run()
#23 {main}
```

**Comment by buddh4** [comment]
Make sure your cron is called with the right php executable: http://php.net/manual/en/migration5.cli-cgi.php
