### ISSUE TITLE
Space creation form freezes after setting invitation user

### ISSUE THREAD

**Issue by buddha87** [humhub/humhub#1519]
Unfortunately I don't know how to reproduce this but after setting the invitation for a new space (the last step of the space creation process) and pressing send, the lightbox seems to load forever. This happened two times in two different humhub test instances. Here is the server error returned for the ajax call:

```
<pre>Exception &#039;yii\base\UnknownMethodException&#039; with message &#039;Calling unknown method
: yii\widgets\ActiveForm::error()&#039; 

in /srv/www/staff.humhub.org/htdocs/protected/vendor/yiisoft/yii2/base/Component.php:285

Stack trace:
#0 /srv/www/staff.humhub.org/htdocs/protected/humhub/modules/space/views/create/invite.php(104): yii
\base\Component-&gt;__call(&#039;error&#039;, Array)
#1 /srv/www/staff.humhub.org/htdocs/protected/humhub/modules/space/views/create/invite.php(104): yii
\widgets\ActiveForm-&gt;error(Object(humhub\modules\space\models\forms\InviteForm), &#039;inviteExternal
&#039;)
#2 /srv/www/staff.humhub.org/htdocs/protected/vendor/yiisoft/yii2/base/View.php(325): require(&#039;
/srv/www/staff....&#039;)
#3 /srv/www/staff.humhub.org/htdocs/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View-
&gt;renderPhpFile(&#039;/srv/www/staff....&#039;, Array)
#4 /srv/www/staff.humhub.org/htdocs/protected/vendor/yiisoft/yii2/web/View.php(210): yii\base\View-&gt
;renderFile(&#039;/srv/www/staff....&#039;, Array, Object(humhub\modules\space\controllers\CreateController
))
#5 /srv/www/staff.humhub.org/htdocs/protected/vendor/yiisoft/yii2/web/Controller.php(47): yii\web\View-
&gt;renderAjax(&#039;invite&#039;, Array, Object(humhub\modules\space\controllers\CreateController))

#6 /srv/www/staff.humhub.org/htdocs/protected/humhub/modules/space/controllers/CreateController.php(128
): yii\web\Controller-&gt;renderAjax(&#039;invite&#039;, Array)
#7 [internal function]: humhub\modules\space\controllers\CreateController-&gt;actionInvite()
#8 /srv/www/staff.humhub.org/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array
(Array, Array)
#9 /srv/www/staff.humhub.org/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base
\InlineAction-&gt;runWithParams(Array)
#10 /srv/www/staff.humhub.org/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller-
&gt;runAction(&#039;invite&#039;, Array)
#11 /srv/www/staff.humhub.org/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base
\Module-&gt;runAction(&#039;space/create/in...&#039;, Array)
#12 /srv/www/staff.humhub.org/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web
\Application-&gt;handleRequest(Object(humhub\components\Request))
#13 /srv/www/staff.humhub.org/htdocs/index.php(25): yii\base\Application-&gt;run()
#14 {main}</pre>
```

**Comment by luke-** [comment]
Fixed in: https://github.com/humhub/humhub/commit/6223375df3b342b38d33df424c3fce7dd0babb8c
