### ISSUE TITLE
Error in cURL request: SSL certificate problem: certificate is not yet valid

### ISSUE THREAD

**Issue by ychoucha** [humhub/humhub#1574]
Hello,

so i m on frech install of humub on ubuntu serveur 14.04 LTS
and i m using stable humhub version humhub-0.20.1.zip

and when i go in administration module i have this error : 

```
 Error  Thu, 03 Mar 2016 09:44:23 +0100  Zend\Http\Client\Adapter\Exception\RuntimeException
exception 'Zend\Http\Client\Adapter\Exception\RuntimeException' with message 'Error in cURL request: SSL certificate problem: certificate is not yet valid' in /var/www/html/humhub/protected/vendor/zendframework/zend-http/src/Client/Adapter/Curl.php:425 Stack trace: #0 /var/www/html/humhub/protected/vendor/zendframework/zend-http/src/Client.php(1387): Zend\Http\Client\Adapter\Curl->write('GET', Object(Zend\Uri\Http), '1.1', Array, '') #1 /var/www/html/humhub/protected/vendor/zendframework/zend-http/src/Client.php(893): Zend\Http\Client->doRequest(Object(Zend\Uri\Http), 'GET', true, Array, '') #2 /var/www/html/humhub/protected/humhub/modules/admin/libs/OnlineModuleManager.php(239): Zend\Http\Client->send() #3 /var/www/html/humhub/protected/humhub/modules/admin/controllers/AboutController.php(31): humhub\modules\admin\libs\OnlineModuleManager->getLatestHumHubVersion() #4 [internal function]: humhub\modules\admin\controllers\AboutController->actionIndex() #5 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #6 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array) #7 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('', Array) #8 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('admin/about', Array) #9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /var/www/html/humhub/index.php(25): yii\base\Application->run() #11 {main} 
```

what's happening please ?

**Comment by Madko** [comment]
Same here after updating from 0.20 to 1.0.0. It was working pretty well before. Can't update any module, seems modules are removed when this error occurs. Proxy is configured in the admin interface.
