### ISSUE TITLE
Open public space as guest.

### ISSUE THREAD

**Issue by buddha87** [humhub/humhub#1602]
Tested in v1.1 and v1.2, if I change the visibility of a space to public and try to access this space as a guest user through the directory the activities and the stream are not loading with error:

<pre>PHP Notice &#039;yii\base\ErrorException&#039; with message &#039;Trying to get property of non-object
&#039; 

in /codebase/humhub/v1.2-dev/protected/humhub/modules/content/components/actions/ContentContainerStream
.php:56

Stack trace:
#0 /codebase/humhub/v1.2-dev/protected/vendor/yiisoft/yii2/base/Action.php(60): yii\base\Object-&gt;__construct
()
#1 /codebase/humhub/v1.2-dev/protected/vendor/yiisoft/yii2/di/Container.php(374): yii\base\Action-&gt
;__construct()
#2 /codebase/humhub/v1.2-dev/protected/vendor/yiisoft/yii2/di/Container.php(374): ReflectionClass-&gt
;newInstanceArgs()
#3 /codebase/humhub/v1.2-dev/protected/vendor/yiisoft/yii2/di/Container.php(153): yii\di\Container-&gt
;build()
#4 /codebase/humhub/v1.2-dev/protected/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container-&gt;get
()
#5 /codebase/humhub/v1.2-dev/protected/vendor/yiisoft/yii2/base/Controller.php(222): yii\BaseYii::createObject
()
#6 /codebase/humhub/v1.2-dev/protected/vendor/yiisoft/yii2/base/Controller.php(123): yii\base\Controller-
&gt;createAction()
#7 /codebase/humhub/v1.2-dev/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller-
&gt;runAction()
#8 /codebase/humhub/v1.2-dev/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module-
&gt;runAction()
#9 /codebase/humhub/v1.2-dev/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application-
&gt;handleRequest()
#10 /codebase/humhub/v1.2-dev/index.php(25): yii\base\Application-&gt;run()
#11 {main}</pre>

**Comment by buddha87** [comment]
Also happens for user profiles, which are allowed for guests:

```
<pre>PHP Notice &#039;yii\base\ErrorException&#039; with message &#039;Trying to get property of non-object&#039; 

in /codebase/humhub/v1.1-dev/protected/humhub/modules/content/components/actions/ContentContainerStream.php:56

Stack trace:
#0 /codebase/humhub/v1.1-dev/protected/vendor/yiisoft/yii2/base/Action.php(60): yii\base\Object-&gt;__construct()
#1 /codebase/humhub/v1.1-dev/protected/vendor/yiisoft/yii2/di/Container.php(374): yii\base\Action-&gt;__construct()
#2 /codebase/humhub/v1.1-dev/protected/vendor/yiisoft/yii2/di/Container.php(374): ReflectionClass-&gt;newInstanceArgs()
#3 /codebase/humhub/v1.1-dev/protected/vendor/yiisoft/yii2/di/Container.php(153): yii\di\Container-&gt;build()
#4 /codebase/humhub/v1.1-dev/protected/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container-&gt;get()
#5 /codebase/humhub/v1.1-dev/protected/vendor/yiisoft/yii2/base/Controller.php(222): yii\BaseYii::createObject()
#6 /codebase/humhub/v1.1-dev/protected/vendor/yiisoft/yii2/base/Controller.php(123): yii\base\Controller-&gt;createAction()
#7 /codebase/humhub/v1.1-dev/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller-&gt;runAction()
#8 /codebase/humhub/v1.1-dev/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module-&gt;runAction()
#9 /codebase/humhub/v1.1-dev/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application-&gt;handleRequest()
#10 /codebase/humhub/v1.1-dev/index.php(25): yii\base\Application-&gt;run()
#11 {main}</pre>
```
