### ISSUE TITLE
Viewing Space Members

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#1647]
When trying to view users I get the following error: Internal Server Error. I was instructed to create another issue for this here.

### Logs

```
exception 'yii\base\ErrorException' with message 'Trying to get property of non-object' in /home/USER/public_html/beta/protected/humhub/modules/space/modules/manage/views/member/index.php:35 Stack trace: #0 /home/USER/public_html/beta/protected/humhub/modules/space/modules/manage/views/member/index.php(35): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/home/futayuri/...', 35, Array) #1 [internal function]: yii\base\View->{closure}(Object(humhub\modules\space\models\Membership), Array, 1, Object(humhub\libs\DropDownGridColumn)) #2 /home/USER/public_html/beta/protected/humhub/libs/DropDownGridColumn.php(100): call_user_func(Object(Closure), Object(humhub\modules\space\models\Membership), Array, 1, Object(humhub\libs\DropDownGridColumn)) #3 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/grid/Column.php(108): humhub\libs\DropDownGridColumn->renderDataCellContent(Object(humhub\modules\space\models\Membership), Array, 1) #4 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/grid/GridView.php(504): yii\grid\Column->renderDataCell(Object(humhub\modules\space\models\Membership), Array, 1) #5 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/grid/GridView.php(473): yii\grid\GridView->renderTableRow(Object(humhub\modules\space\models\Membership), Array, 1) #6 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/grid/GridView.php(344): yii\grid\GridView->renderTableBody() #7 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/widgets/BaseListView.php(151): yii\grid\GridView->renderItems() #8 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/grid/GridView.php(313): yii\widgets\BaseListView->renderSection('{items}') #9 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/widgets/BaseListView.php(126): yii\grid\GridView->renderSection('{items}') #10 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array) #11 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/widgets/BaseListView.php(129): preg_replace_callback('/{\\w+}/', Object(Closure), '{summary}\n{item...') #12 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/grid/GridView.php(288): yii\widgets\BaseListView->run() #13 /home/USER/public_html/beta/protected/humhub/widgets/GridView.php(46): yii\grid\GridView->run() #14 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/Widget.php(98): humhub\widgets\GridView->run() #15 /home/USER/public_html/beta/protected/humhub/modules/space/modules/manage/views/member/index.php(78): yii\base\Widget::widget(Array) #16 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/base/View.php(325): require('/home/futayuri/...') #17 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/futayuri/...', Array) #18 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/home/futayuri/...', Array, Object(humhub\modules\space\modules\manage\controllers\MemberController)) #19 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/base/Controller.php(377): yii\base\View->render('index', Array, Object(humhub\modules\space\modules\manage\controllers\MemberController)) #20 /home/USER/public_html/beta/protected/humhub/modules/space/modules/manage/controllers/MemberController.php(59): yii\base\Controller->render('index', Array) #21 [internal function]: humhub\modules\space\modules\manage\controllers\MemberController->actionIndex() #22 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #23 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #24 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('', Array) #25 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('space/manage/me...', Array) #26 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #27 /home/USER/public_html/beta/index.php(25): yii\base\Application->run() #28 {main}
```

```
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "space/manage/members".' in /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/base/Module.php:460 Stack trace: #0 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('space/manage/me...', Array) #1 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #2 /home/USER/public_html/beta/index.php(25): yii\base\Application->run() #3 {main} Next exception 'yii\web\NotFoundHttpException' with message 'Page not found.' in /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/web/Application.php:96 Stack trace: #0 /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #1 /home/USER/public_html/beta/index.php(25): yii\base\Application->run() #2 {main}

```

HumHub v1.0.0

**Comment by buddha87** [comment]
can you check if the following path is working space/manage/member instead of members, perhaps its a theme issue

**Comment by Felli** [comment]
I've tried every theme possible, even the default one, all end up in this error.

**Comment by buddha87** [comment]
please copy the url which is called

**Comment by Felli** [comment]
Here's the url http://beta.futayuriverse.com/s/futayuriverse/space/manage/member (I am using the NiceSpaceUrl Module and this error happens even with it disabled.)

**Comment by buddha87** [comment]
Hmm, could you execute an integrity check on your data, go to your protected directory and execute:

php yii integrity/run

**Comment by nathanverrill** [comment]
Hmm...

*** Performing database integrity checks


Validating: Polls Module - Answers (0 entries)

Validating: Polls Module - Answers User (0 entries)

Validating: ReportContent Module (0 entries)

Validating: Activity Module (19 entries)

Validating: Comment Module (4 entries)

Validating: Content Module - Wall Entries 24 entries)

Validating: Content Objects (27 entries)

Validating: File Module (14 entries)

Validating: Like (2 entries)

Validating: Notification Module (9 entries)

Validating: Space Module - Spaces (2 entries)

Validating: Space Module - Module (7 entries)

Deleting space module7 without existing space! (yes|no) [no]:

**Comment by Felli** [comment]
I think I found the problem, when the HumHub servers went down I was doing an update with the updater module, so I'm just guessing this would be the reason why this is happening, but I'll go over it later, and try your recommendation. :+1:
