### ISSUE TITLE
An internal server error occurred after v1.1.0-beta.1 update

### ISSUE THREAD

**Issue by ledyspa** [humhub/humhub#1762]
Hi. Big problem... afer upgrade to v1.1.0 from admin panel, now appears "An internal server error occurred" message and can't access to humhub... any idea? :(

**Comment by buddha87** [comment]
Are there any further information about the error ?

**Comment by ledyspa** [comment]
We have restored a backup from last monday, and now is possible to access but all is empty and appears an error message. I attach screenshot.
![error_-_as_de_led_ _-_intranet](https://cloud.githubusercontent.com/assets/18555049/15779115/c37cf37a-299a-11e6-8733-667485036835.jpg)

**Comment by Censtudios** [comment]
Got the same indeed. I started the updater module, after 10 seconds or so I get error 524, which is timeout, but that's weird, because when I update I set max timeout to 600 seconds.

Anyways, when I then go to any page I just see a blank page saying "An internal server error occurred." Nothing in the logs because I can't access them. In the apache logs I see atleast 400 lines of error. I didn't check how many more lines there are.

**Comment by Penguinexpert1** [comment]
I'm having the same error! Help please, having to restore from backup!

**Comment by Censtudios** [comment]
@Penguinexpert1 did you wait before restoring the backup? I myself was on the point of restoring the backup about 15-20 min later when all of a sudden it worked again

**Comment by Penguinexpert1** [comment]
@Censtudios Yeah I waited. I didn't get a friendly error like that, I just got a blank page with "An Internal Server Error Occurred"

**Comment by Penguinexpert1** [comment]
I'm so close to just going with another social network provided, these errors seems to be happening every time...

**Comment by Censtudios** [comment]
Yeah I also had a blank page with that error. But 15-20 min later it suddenly worked again. I think it was still running the update in the background. I think it will only fuck up more if you restore a backup during that time.

**Comment by buddha87** [comment]
@Penguinexpert1 sorry to hear that, but note the version you installed as well as the updater module are in beta phase and are not declared as stable. Some people seem to have timeout issues with the updater, and we try to provide a solution for this as fast as possible. I would recommend to try manually executing the migration by running `php yii migrate/up --includeModuleMigrations=1` within your protected directory, but its possible that this fails if a migration did not complete in the update process. Or restore your backup and either wait for a stable release or try the manual (and currently more reliable) update described here: https://www.humhub.org/docs/guide-admin-updating.html

**Comment by Penguinexpert1** [comment]
Thanks for replying, I've downgraded at the moment and FTP is re-uploading
Humhub as we speak. Lets hope for the best!

**Comment by devcline** [comment]
Hello i run a update backuped a sql base and forget to back up files

i get a An internal server error occurred.

in the command line 

i get php yii migrate/up --includeModuleMigrations=1

```
Yii Migration Tool (based on Yii v2.0.8)

Total 14 new migrations to be applied:
	m151226_164234_authclient
	m160216_160119_initial
	m160217_161220_addCanLeaveFlag
	m160220_013525_contentcontainer_id
	m160221_222312_public_permission_change
	m160225_180229_remove_website
	m160229_162959_multiusergroups
	m160309_141222_longerUserName
	m160408_100725_rename_groupadmin_to_manager
	m160507_202611_settings
	m160508_005740_settings_cleanup
	m160509_214811_spaceurl
	m160517_132535_group
	m160523_105732_profile_searchable

Apply the above migrations? (yes|no) [no]:
```

**_When i do this update, i get a timeout even if i put timeout on 5 min, os i think it was also the reason why update is failed_**

and with php yii integrity/run

```
*** Performing database integrity checks

Validating: Polls Module - Answers (9 entries)
Validating: Polls Module - Answers User (4 entries)
Validating: Activity Module (222 entries)
Validating: Comment Module (1 entries)
Validating: Content Module - Wall Entries 271 entries)
Validating: Content Objects (377 entries)
Validating: File Module (75 entries)
Validating: Like (0 entries)
Validating: Notification Module (19 entries)
Validating: Space Module - Spaces (30 entries)
Validating: Space Module - Module (120 entries)
Deleting space module 10 without existing space! (yes|no) [no]:Deleting space module 11 without existing space! (yes|no) [no]:Deleting space module 12 without existing space! (yes|no) [no]:Deleting space module 13 without existing space! (yes|no) [no]:Deleting space module 14 without existing space! (yes|no) [no]:Deleting space module 15 without existing space! (yes|no) [no]:Deleting space module 16 without existing space! (yes|no) [no]:Deleting space module 17 without existing space! (yes|no) [no]:Deleting space module 18 without existing space! (yes|no) [no]:Deleting space module 19 without existing space! (yes|no) [no]:Deleting space module 20 without existing space! (yes|no) [no]:Deleting space module 21 without existing space! (yes|no) [no]:Deleting space module 102 without existing space! (yes|no) [no]:Deleting space module 103 without existing space! (yes|no) [no]:Deleting space module 104 without existing space! (yes|no) [no]:Deleting space module 105 without existing space! (yes|no) [no]:Deleting space module 106 without existing space! (yes|no) [no]:Deleting space module 107 without existing space! (yes|no) [no]:Deleting space module 110 without existing space! (yes|no) [no]:Deleting space module 111 without existing space! (yes|no) [no]:Deleting space module 112 without existing space! (yes|no) [no]:Deleting space module 113 without existing space! (yes|no) [no]:Deleting space module 114 without existing space! (yes|no) [no]:Deleting space module 115 without existing space! (yes|no) [no]:Validating: Space Module - Memberships (60 entries)
Validating: User Module - Users (16 entries)
Exception 'yii\db\Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'base_lab.group_user' doesn't exist
The SQL being executed was: SELECT `group_user`.* FROM `group_user` LEFT JOIN `user` ON `group_user`.`user_id` = `user`.`id`'

in /home//public_html//lab/protected/vendor/yiisoft/yii2/db/Schema.php:633

Error Info:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'base_lab.group_user' doesn't exist
)

Stack trace:
#0 /home//public_html//lab/protected/vendor/yiisoft/yii2/db/Command.php(915): yii\db\Schema->convertException(Object(PDOException), 'SELECT `group_u...')
#1 /home//public_html//lab/protected/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL)
#2 /home//public_html//lab/protected/vendor/yiisoft/yii2/db/Query.php(210): yii\db\Command->queryAll()
#3 /home//public_html//lab/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#4 /home//public_html//lab/protected/humhub/modules/user/Events.php(60): yii\db\ActiveQuery->all()
#5 [internal function]: humhub\modules\user\Events::onIntegrityCheck(Object(yii\base\Event))
#6 /home//public_html//lab/protected/vendor/yiisoft/yii2/base/Event.php(205): call_user_func(Array, Object(yii\base\Event))
#7 /home//public_html//lab/protected/vendor/yiisoft/yii2/base/Component.php(549): yii\base\Event::trigger(Object(humhub\commands\IntegrityController), 'run', NULL)
#8 /home//public_html//lab/protected/humhub/commands/IntegrityController.php(39): yii\base\Component->trigger('run')
#9 [internal function]: humhub\commands\IntegrityController->actionRun()
#10 /home//public_html//lab/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#11 /home//public_html//lab/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#12 /home//public_html//lab/protected/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('run', Array)
#13 /home//public_html//lab/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('run', Array)
#14 /home//public_html//lab/protected/vendor/yiisoft/yii2/console/Application.php(176): yii\base\Module->runAction('integrity/run', Array)
#15 /home//public_html//lab/protected/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('integrity/run', Array)
#16 /home//public_html//lab/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#17 /home//public_html//lab/protected/yii(29): yii\base\Application->run()
#18 {main}
```

how should i proceed to restore to the previous version? or update with my currently configuration with my old backup of sql only

thanks

**Comment by luke-** [comment]
Did you ran the missing migrations?

**Comment by devcline** [comment]
Ok i managed to back to the old version with my old database.
No i will backup all and how to investigate the update

The missing migrations are making me a timeout 30 secs, fatal error, from the phpshell even if i put a timeout to 300 seconds

**Comment by devcline** [comment]
```
 php yii migrate/up --includeModuleMigrations=1
Yii Migration Tool (based on Yii v2.0.8)

Total 14 new migrations to be applied:
        m151226_164234_authclient
        m160216_160119_initial
        m160217_161220_addCanLeaveFlag
        m160220_013525_contentcontainer_id
        m160221_222312_public_permission_change
        m160225_180229_remove_website
        m160229_162959_multiusergroups
        m160309_141222_longerUserName
        m160408_100725_rename_groupadmin_to_manager
        m160507_202611_settings
        m160508_005740_settings_cleanup
        m160509_214811_spaceurl
        m160517_132535_group
        m160523_105732_profile_searchable

Apply the above migrations? (yes|no) [no]:
```

```
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'user_auth' already exists
The SQL being executed was: CREATE TABLE `user_auth` (


```

and when i remove user_auth i get this:


```
  > add foreign key fk_user_id: user_auth (user_id) references user (id) ...Exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table `lab`.`#sql-aaa01_6787759` (errno: 150 "Foreign key constraint is incorrectly formed")
The SQL being executed was: ALTER TABLE `user_auth` ADD CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE'

in /home//public_html/lab/protected/vendor/yiisoft/yii2/db/Schema.php:633

Error Info:
Array
(
    [0] => HY000
    [1] => 1005
    [2] => Can't create table `lab`.`#sql-aaa01_6787759` (errno: 150 "Foreign key constraint is incorrectly formed")
)

Stack trace:
#0 /home//public_html//lab/protected/vendor/yiisoft/yii2/db/Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `us...')
#1 /home//public_html//lab/protected/vendor/yiisoft/yii2/db/Migration.php(414): yii\db\Command->execute()
#2 /home//public_html//lab/protected/humhub/modules/user/migrations/m151226_164234_authclient.php(17): yii\db\Migration->addForeignKey('fk_user_id', 'user_auth', 'user_id', 'user', 'id', 'CASCADE', 'CASCADE')
#3 /home//public_html//lab/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(509): m151226_164234_authclient->up()
#4 /home//public_html//lab/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m151226_164234_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 /home//public_html//lab/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#7 /home//public_html//lab/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#8 /home//public_html//lab/protected/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('up', Array)
#9 /home//public_html//lab/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('up', Array)
#10 /home//public_html//lab/protected/vendor/yiisoft/yii2/console/Application.php(176): yii\base\Module->runAction('migrate/up', Array)
#11 /home//public_html//lab/protected/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('migrate/up', Array)
#12 /home//public_html//lab/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 /home//public_html//lab/protected/yii(29): yii\base\Application->run()
#14 {main}

```

**Comment by buddha87** [comment]
We are currently working on the updater/timeout issue, till the udpater is fixed I would suggest to restore your backup and either wait for a stable version or manually update your installation as described here: https://www.humhub.org/docs/guide-admin-updating.html#option-2-manual-update

**Comment by devcline** [comment]
@buddha87 Do i need to backup my database sql? If yes how to import a date to a new sql database from the last version ? thanks
