### ISSUE TITLE
Creating new space - ERROR 500

### ISSUE THREAD

**Issue by inigosola** [humhub/humhub#1798]
I fill all fields to create a new space and when I click on button I get the following response:

```
PHP Notice 'yii\base\ErrorException' with message 'Undefined variable: canInviteExternal' 

in /var/hum/protected/humhub/modules/space/views/create/invite.php:20

Stack trace:
#0 /var/hum/protected/humhub/modules/space/views/create/invite.php(20): yii\base\ErrorHandler->handleError(8, 'Undefined varia...', '/var/hum/protec...', 20, Array)
#1 /var/hum/protected/vendor/yiisoft/yii2/base/View.php(325): require('/var/hum/protec...')
#2 /var/hum/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/hum/protec...', Array)
#3 /var/hum/protected/vendor/yiisoft/yii2/web/View.php(210): yii\base\View->renderFile('/var/hum/protec...', Array, Object(humhub\modules\space\controllers\CreateController))
#4 /var/hum/protected/vendor/yiisoft/yii2/web/Controller.php(47): yii\web\View->renderAjax('invite', Array, Object(humhub\modules\space\controllers\CreateController))
#5 /var/hum/protected/humhub/modules/space/controllers/CreateController.php(97): yii\web\Controller->renderAjax('invite', Array)
#6 /var/hum/protected/humhub/modules/space/controllers/CreateController.php(62): humhub\modules\space\controllers\CreateController->actionModules(6)
#7 [internal function]: humhub\modules\space\controllers\CreateController->actionCreate()
#8 /var/hum/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#9 /var/hum/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#10 /var/hum/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('create', Array)
#11 /var/hum/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('space/create/cr...', Array)
#12 /var/hum/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request))
#13 /var/hum/index.php(25): yii\base\Application->run()
#14 {main}

```

**Comment by buddha87** [comment]
I think this bug is already fixed but is not yet included in any release (not even v1.1 beta)
This should happen if there is no available module for spaces. You should get rid of this error if you install a module which can be enabled for spaces as the wiki or files module.
