### ISSUE TITLE
contentcontainer in database missing for few users/cron job fails

### ISSUE THREAD

**Issue by caspre24** [humhub/humhub#1811]
Since the update to Humhub 1.1.0-beta.1, the hourly and daily cron jobs for sending notification mails fail with the following trace:

```
$ /home/www/humhub/protected/yii cron/hourly
Executing hourly tasks:

Sending update e-mails to users... 94% (18/19) ETA: n/a   PHP Notice 'yii\base\ErrorException' with message 'Trying to get property of non-object'

in /home/www/humhub/protected/humhub/modules/content/components/ContentContainerSettingsManager.php:47

Stack trace:
#0 /home/www/humhub/protected/humhub/modules/content/components/ContentContainerSettingsManager.php(47): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/home/www/humhu...', 47, Array)
#1 /home/www/humhub/protected/humhub/libs/BaseSettingsManager.php(122): humhub\modules\content\components\ContentContainerSettingsManager->find()
#2 /home/www/humhub/protected/humhub/libs/BaseSettingsManager.php(47): humhub\libs\BaseSettingsManager->loadValues()
#3 /home/www/humhub/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\libs\BaseSettingsManager->init()
#4 /home/www/humhub/protected/humhub/components/SettingsManager.php(45): yii\base\Object->__construct(Array)
#5 /home/www/humhub/protected/humhub/modules/notification/Module.php(40): humhub\components\SettingsManager->contentContainer(Object(humhub\modules\user\models\User))
#6 /home/www/humhub/protected/humhub/modules/content/components/MailUpdateSender.php(134): humhub\modules\notification\Module->getMailNotifications(Object(humhub\modules\user\models\User), 2)
#7 /home/www/humhub/protected/humhub/modules/content/components/MailUpdateSender.php(96): humhub\modules\content\components\MailUpdateSender->renderNotifications()
#8 /home/www/humhub/protected/humhub/modules/content/components/MailUpdateSender.php(68): humhub\modules\content\components\MailUpdateSender->send()
#9 /home/www/humhub/protected/humhub/modules/content/Events.php(126): humhub\modules\content\components\MailUpdateSender::processCron(Object(humhub\commands\CronController))
#10 [internal function]: humhub\modules\content\Events::onCronRun(Object(yii\base\Event))
#11 /home/www/humhub/protected/vendor/yiisoft/yii2/base/Event.php(205): call_user_func(Array, Object(yii\base\Event))
#12 /home/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php(549): yii\base\Event::trigger(Object(humhub\commands\CronController), 'hourly', NULL)
#13 /home/www/humhub/protected/humhub/commands/CronController.php(41): yii\base\Component->trigger('hourly')
#14 [internal function]: humhub\commands\CronController->actionHourly()
#15 /home/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#16 /home/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#17 /home/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('hourly', Array)
#18 /home/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('hourly', Array)
#19 /home/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(176): yii\base\Module->runAction('cron/hourly', Array)
#20 /home/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('cron/hourly', Array)
#21 /home/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#22 /home/www/humhub/protected/yii(29): yii\base\Application->run()
#23 {main}
```

I think I tracked down the error to two users missing a `contentcontainer_id` value in the database and no corresponding entry in the `contentcontainer`-table. If I disable those users, the cron jobs run fine. Those users where created way before the update. Maybe there is a way to recreate these entries? A newly created test-user does have those correctly set.

My specs:
PHP 5.6.20-0+deb8u1
Humhub 1.1.0-beta.1 (Installed via download archive, updated via Humhub-Updater)
OS: Debian Jessie
Webserver:  nginx/1.10.1
mysql  Ver 14.14 Distrib 5.5.49

**Comment by caspre24** [comment]
Could it be that some db migrations didn't run properly? Is there a way to rerun the migrations?

**Comment by zhelyabuzhsky** [comment]
The same problem

**Comment by luke-** [comment]
Did you used the updater module? If yes, the latest version?
Were there any errors during the update progress (also logfile)?

**Comment by zhelyabuzhsky** [comment]
No, I don't use the updater module.
This user was created by logging with ldap.

**Comment by luke-** [comment]
Can you provide steps to reproduce this error?

**Comment by zhelyabuzhsky** [comment]
User logged in using ldap in the first time, a record was created in the user table, but field contentcontainer_id remained not filled. It was one of thousand of users. For others users everything was correct.
