### ISSUE TITLE
500 error on dashboard

### ISSUE THREAD

**Issue by TheNornWarrior** [humhub/humhub#1929]
[version 1.1.0 beta 2
PHP - Version - 5.5.35
Database - Version - 5.5]

When i log in this appears on the dasboard:
![error1](https://cloud.githubusercontent.com/assets/21043983/17675398/e7f3ed8a-6329-11e6-9ed3-2d3fb098b815.png)

And this is the error we are getting:

exception 'yii\base\ErrorException' with message 'Trying to get property of non-object' in /home/futayuri/public_html/beta/protected/humhub/modules/content/components/ContentContainerSettingsManager.php:47 Stack trace: #0 /home/futayuri/public_html/beta/protected/humhub/modules/content/components/ContentContainerSettingsManager.php(47): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/home/futayuri/...', 47, Array) #1 /home/futayuri/public_html/beta/protected/humhub/libs/BaseSettingsManager.php(122): humhub\modules\content\components\ContentContainerSettingsManager->find() #2 /home/futayuri/public_html/beta/protected/humhub/libs/BaseSettingsManager.php(47): humhub\libs\BaseSettingsManager->loadValues() #3 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\libs\BaseSettingsManager->init() #4 /home/futayuri/public_html/beta/protected/humhub/components/SettingsManager.php(45): yii\base\Object->__construct(Array) #5 /home/futayuri/public_html/beta/protected/humhub/components/SettingsManager.php(56): humhub\components\SettingsManager->contentContainer(Object(humhub\modules\user\models\User)) #6 /home/futayuri/public_html/beta/protected/humhub/modules/tour/Module.php(26): humhub\components\SettingsManager->user() #7 [internal function]: humhub\modules\tour\Module::onDashboardSidebarInit(Object(yii\base\Event)) #8 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/Event.php(205): call_user_func(Array, Object(yii\base\Event)) #9 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/Component.php(549): yii\base\Event::trigger(Object(humhub\modules\dashboard\widgets\Sidebar), 'init', NULL) #10 /home/futayuri/public_html/beta/protected/humhub/widgets/BaseStack.php(73): yii\base\Component->trigger('init') #11 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\widgets\BaseStack->init() #12 [internal function]: yii\base\Object->__construct(Array) #13 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/di/Container.php(379): ReflectionClass->newInstanceArgs(Array) #14 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/di/Container.php(154): yii\di\Container->build('humhub\modules\...', Array, Array) #15 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('humhub\modules\...', Array, Array) #16 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/Widget.php(101): yii\BaseYii::createObject(Array) #17 /home/futayuri/public_html/beta/protected/humhub/modules/dashboard/views/dashboard/index.php(22): yii\base\Widget::widget(Array) #18 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/View.php(325): require('/home/futayuri/...') #19 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/futayuri/...', Array) #20 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/home/futayuri/...', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #21 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/Controller.php(378): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #22 /home/futayuri/public_html/beta/protected/humhub/modules/dashboard/controllers/DashboardController.php(64): yii\base\Controller->render('index', Array) #23 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex() #24 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #25 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #26 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('', Array) #27 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('dashboard/dashb...', Array) #28 /home/futayuri/public_html/beta/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #29 /home/futayuri/public_html/beta/index.php(25): yii\base\Application->run() #30 {main} 

I'm not sure what is going on here.

**Comment by buddha87** [comment]
please check if your user has an existing contentcontainer_id value in the database.

**Comment by JoshuaQuinlan** [comment]
I am having the same issue, and the user in question does not have an existing contentcontainer_id

**Comment by buddh4** [comment]
@JoshuaQuinlan how has the user been created? By a normal registration process or did you create the user? Are there any further errors in the logs?

**Comment by JoshuaQuinlan** [comment]
@buddh4 The account was created via an invitation sent through SMTP. The error showed to the user is as follows:
```Error
PHP Notice – yii\base\ErrorException
Trying to get property of non-object
1. in install-dir/protected/humhub/modules/content/components/ContentContainerSettingsManager.php at line 80
71727374757677787980818283848586878889        $record->contentcontainer_id = $this->contentContainer->contentContainerRecord->id;
        return $record;
    }
 
    /**
     * @inheritdoc
     */
    protected function find()
    {
        return parent::find()->andWhere(['contentcontainer_id' => $this->contentContainer->contentContainerRecord->id]);
    }
 
    /**
     * @inheritdoc
     */
    protected function getCacheKey()
    {
        return parent::getCacheKey() . '-' . $this->contentContainer->contentcontainer_id;
    }
2. in install-dir/protected/humhub/modules/content/components/ContentContainerSettingsManager.php at line 80 – yii\base\ErrorHandler::handleError(8, 'Trying to get property of non-ob...', 'install-dir/p...', 80, ...)
74757677787980818283848586 
    /**
     * @inheritdoc
     */
    protected function find()
    {
        return parent::find()->andWhere(['contentcontainer_id' => $this->contentContainer->contentContainerRecord->id]);
    }
 
    /**
     * @inheritdoc
     */
    protected function getCacheKey()
3. in install-dir/protected/humhub/libs/BaseSettingsManager.php at line 169 – humhub\modules\content\components\ContentContainerSettingsManager::find()
163164165166167168169170171172173174175        if ($cached === false) {
            $this->_loaded = [];
            $settings = &$this->_loaded;
 
            array_map(function ($record) use(&$settings ) {
                $settings[$record->name] = $record->value;
            }, $this->find()->all());
 
            Yii::$app->cache->set($this->getCacheKey(), $this->_loaded);
        } else {
            $this->_loaded = $cached;
        }
    }
4. in install-dir/protected/humhub/libs/BaseSettingsManager.php at line 49 – humhub\libs\BaseSettingsManager::loadValues()
43444546474849505152535455    public function init()
    {
        if ($this->moduleId === null) {
            throw new Exception('Could not determine module id');
        }
 
        $this->loadValues();
 
        parent::init();
    }
 
    /**
     * Sets a settings value
5. in install-dir/protected/vendor/yiisoft/yii2/base/Object.php at line 107 – humhub\libs\BaseSettingsManager::init()
6. in install-dir/protected/humhub/components/SettingsManager.php at line 44 – yii\base\Object::__construct(['moduleId' => 'tour', 'contentContainer' => humhub\modules\user\models\User])
38394041424344454647484950        if (isset($this->contentContainers[$container->contentcontainer_id])) {
            return $this->contentContainers[$container->contentcontainer_id];
        }
 
        $this->contentContainers[$container->contentcontainer_id] = new ContentContainerSettingsManager([
            'moduleId' => $this->moduleId,
            'contentContainer' => $container,
        ]);
 
        return $this->contentContainers[$container->contentcontainer_id];
    }
 
    /**
7. in install-dir/protected/humhub/components/SettingsManager.php at line 60 – humhub\components\SettingsManager::contentContainer(humhub\modules\user\models\User)
54555657585960616263646566    public function user($user = null)
    {
        if(!$user) {
            $user = Yii::$app->user->getIdentity();
        }
 
        return $this->contentContainer($user);
    }
 
    /**
     * Returns ContentContainerSettingsManager for the given $space or current controller space
     * @return ContentContainerSettingsManager
     */
8. in install-dir/protected/humhub/modules/tour/Module.php at line 26 – humhub\components\SettingsManager::user()
202122232425262728293031    public static function onDashboardSidebarInit($event)
    {
        if (Yii::$app->user->isGuest)
            return;
 
        $settings = Yii::$app->getModule('tour')->settings;
        if ($settings->get('enable') == 1 && $settings->user()->get("hideTourPanel") != 1) {
            $event->sender->addWidget(Dashboard::className(), array(), array('sortOrder' => 100));
        }
    }
 
}
9. humhub\modules\tour\Module::onDashboardSidebarInit(yii\base\Event)
10. in install-dir/protected/vendor/yiisoft/yii2/base/Event.php at line 220 – call_user_func(['humhub\modules\tour\Module', 'onDashboardSidebarInit'], yii\base\Event)
11. in install-dir/protected/vendor/yiisoft/yii2/base/Component.php at line 553 – yii\base\Event::trigger('humhub\modules\dashboard\widgets...', 'init', yii\base\Event)
12. in install-dir/protected/vendor/yiisoft/yii2/base/Widget.php at line 72 – yii\base\Component::trigger('init')
13. in install-dir/protected/humhub/widgets/BaseStack.php at line 67 – yii\base\Widget::init()
61626364656667686970717273 
        // Yii 2.0.11 introduced own init event
        if (version_compare(Yii::getVersion(), '2.0.11', '<')) {
            $this->trigger(self::EVENT_INIT);
        }
 
        parent::init();
    }
 
    /**
     * Runs the Navigation
     */
    public function run()
14. in install-dir/protected/vendor/yiisoft/yii2/base/Object.php at line 107 – humhub\widgets\BaseStack::init()
15. yii\base\Object::__construct(['widgets' => [['humhub\modules\activity\widgets\...', ['streamAction' => '/dashboard/dashboard/stream'], ['sortOrder' => 150]]]])
16. in install-dir/protected/vendor/yiisoft/yii2/di/Container.php at line 381 – ReflectionClass::newInstanceArgs([['widgets' => [['humhub\modules\activity\widgets\...', ['streamAction' => '/dashboard/dashboard/stream'], ['sortOrder' => 150]]]]])
17. in install-dir/protected/vendor/yiisoft/yii2/di/Container.php at line 156 – yii\di\Container::build('humhub\modules\dashboard\widgets...', [], ['widgets' => [['humhub\modules\activity\widgets\...', ['streamAction' => '/dashboard/dashboard/stream'], ['sortOrder' => 150]]]])
18. in install-dir/protected/vendor/yiisoft/yii2/BaseYii.php at line 348 – yii\di\Container::get('humhub\modules\dashboard\widgets...', [], ['widgets' => [['humhub\modules\activity\widgets\...', ['streamAction' => '/dashboard/dashboard/stream'], ['sortOrder' => 150]]]])
19. in install-dir/protected/vendor/yiisoft/yii2/base/Widget.php at line 136 – yii\BaseYii::createObject(['widgets' => [['humhub\modules\activity\widgets\...', ['streamAction' => '/dashboard/dashboard/stream'], ['sortOrder' => 150]]]])
20. in install-dir/protected/humhub/modules/dashboard/views/dashboard/index.php at line 20 – yii\base\Widget::widget(['widgets' => [['humhub\modules\activity\widgets\...', ['streamAction' => '/dashboard/dashboard/stream'], ['sortOrder' => 150]]], 'class' => 'humhub\modules\dashboard\widgets...'])
14151617181920212223242526                'showProfilePostForm' => $showProfilePostForm
            ])?>
        </div>
        <div class="col-md-4 layout-sidebar-container">
            <?php
            echo \humhub\modules\dashboard\widgets\Sidebar::widget([
                'widgets' => [
                    [
                        \humhub\modules\activity\widgets\Stream::className(),
                        ['streamAction' => '/dashboard/dashboard/stream'],
                        ['sortOrder' => 150]
                    ]
                ]
21. in install-dir/protected/vendor/yiisoft/yii2/base/View.php at line 330 – require('install-dir/p...')
22. in install-dir/protected/vendor/yiisoft/yii2/base/View.php at line 250 – yii\base\View::renderPhpFile('install-dir/p...', ['showProfilePostForm' => '1', 'contentContainer' => humhub\modules\user\models\User])
23. in install-dir/protected/vendor/yiisoft/yii2/base/View.php at line 152 – yii\base\View::renderFile('install-dir/p...', ['showProfilePostForm' => '1', 'contentContainer' => humhub\modules\user\models\User], humhub\modules\dashboard\controllers\DashboardController)
24. in install-dir/protected/vendor/yiisoft/yii2/base/Controller.php at line 381 – yii\base\View::render('index', ['showProfilePostForm' => '1', 'contentContainer' => humhub\modules\user\models\User], humhub\modules\dashboard\controllers\DashboardController)
25. in install-dir/protected/humhub/modules/dashboard/controllers/DashboardController.php at line 62 – yii\base\Controller::render('index', ['showProfilePostForm' => '1', 'contentContainer' => humhub\modules\user\models\User])
565758596061626364656667    {
        if (Yii::$app->user->isGuest) {
            return $this->render('index_guest', []);
        } else {
            return $this->render('index', [
                'showProfilePostForm' => Yii::$app->getModule('dashboard')->settings->get('showProfilePostForm'),
                'contentContainer' => Yii::$app->user->getIdentity()
            ]);
        }
    }
 
}
26. humhub\modules\dashboard\controllers\DashboardController::actionIndex()
27. in install-dir/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([humhub\modules\dashboard\controllers\DashboardController, 'actionIndex'], [])
28. in install-dir/protected/vendor/yiisoft/yii2/base/Controller.php at line 156 – yii\base\InlineAction::runWithParams(['r' => 'dashboard/dashboard'])
29. in install-dir/protected/vendor/yiisoft/yii2/base/Module.php at line 523 – yii\base\Controller::runAction('', ['r' => 'dashboard/dashboard'])
30. in install-dir/protected/vendor/yiisoft/yii2/web/Application.php at line 102 – yii\base\Module::runAction('dashboard/dashboard', ['r' => 'dashboard/dashboard'])
31. in install-dir/protected/vendor/yiisoft/yii2/base/Application.php at line 380 – yii\web\Application::handleRequest(humhub\components\Request)
32. in install-dir/index.php at line 25 – yii\base\Application::run()
19202122232425    require(__DIR__ . '/protected/humhub/config/web.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);
 
(new humhub\components\Application($config))->run();
 Yii Framework
2018-07-18, 15:55:41

Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.0.25

Yii Framework/2.0.12```

The contentcontainer_id column for the user has a value of 'null'

The apache error log displays the following:
```[Mon Mar 12 15:01:06.008704 2018] [:error] [pid 27746] [client IPADDR:54790] script 'install-dir/xmlrpc.php' not found or unable to stat
```

This file (xmlrpc.php) does not exist, and I am therefore assuming that this is an issue (if not the issue causing this entire situation). How might this be resolved.

In addition to this, why am I able to login while no other users are able to do so? Simply because this user was setup during installation?

Thanks!
