### ISSUE TITLE
Still trying to update.. to the last version , no luck

### ISSUE THREAD

**Issue by devcline** [humhub/humhub#1935]
Ok i will try to structure everything i do.
1. i have a  1.0.1 version with all modules updated, self test is ok and everything is upto date
2. I do a update to v1.1.0-beta.1
3. i get the error.

```
Error!
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'user_auth' already exists The SQL being executed was: CREATE TABLE `user_auth` ( `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, `user_id` int(11) NOT NULL, `source` varchar(255) NOT NULL, `source_id` varchar(255) NOT NULL )
```
1. I do _php yii migrate/up --includeModuleMigrations=1_ command in protected folder throu a console and i get a 

```
Yii Migration Tool (based on Yii v2.0.8)

Total 14 new migrations to be applied:
        m151226_164234_authclient
        m160216_160119_initial
        m160217_161220_addCanLeaveFlag
        m160220_013525_contentcontainer_id
        m160221_222312_public_permission_change
        m160225_180229_remove_website
        m160229_162959_multiusergroups
        m160309_141222_longerUserName
        m160408_100725_rename_groupadmin_to_manager
        m160507_202611_settings
        m160508_005740_settings_cleanup
        m160509_214811_spaceurl
        m160517_132535_group
        m160523_105732_profile_searchable

Apply the above migrations? (yes|no) [no]:yes
*** applying m151226_164234_authclient
    > create table user_auth ...Exception 'yii\db\Exception' with message 'SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'user_auth' already exists
The SQL being executed was: CREATE TABLE `user_auth` (
        `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `user_id` int(11) NOT NULL,
        `source` varchar(255) NOT NULL,
        `source_id` varchar(255) NOT NULL
)'

in /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/db/Schema.php:633

Error Info:
Array
(
    [0] => 42S01
    [1] => 1050
    [2] => Table 'user_auth' already exists
)

Stack trace:
#0 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/db/Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `u...')
#1 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/db/Migration.php(260): yii\db\Command->execute()
#2 /home/host/public_html/host/lab/protected/humhub/modules/user/migrations/m151226_164234_authclient.php(16): yii\db\Migration->createTable('user_auth', Array)
#3 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(509): m151226_164234_authclient->up()
#4 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m151226_164234_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#7 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#8 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('up', Array)
#9 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('up', Array)
#10 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/console/Application.php(176): yii\base\Module->runAction('migrate/up', Array)
#11 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('migrate/up', Array)
#12 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 /home/host/public_html/host/lab/protected/yii(29): yii\base\Application->run()
#14 {main}

```

And if i delete user_auth

i get 

```

Apply the above migrations? (yes|no) [no]:yes
*** applying m151226_164234_authclient
    > create table user_auth ... done (time: 0.047s)
    > add foreign key fk_user_id: user_auth (user_id) references user (id) ...Exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table `host_lab`.`#sql-85080_1141a3f` (errno: 150 "Foreign key constraint is incorrectly formed")
The SQL being executed was: ALTER TABLE `user_auth` ADD CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE'

in /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/db/Schema.php:633

Error Info:
Array
(
    [0] => HY000
    [1] => 1005
    [2] => Can't create table `host_lab`.`#sql-85080_1141a3f` (errno: 150 "Foreign key constraint is incorrectly formed")
)

Stack trace:
#0 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/db/Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `us...')
#1 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/db/Migration.php(414): yii\db\Command->execute()
#2 /home/host/public_html/host/lab/protected/humhub/modules/user/migrations/m151226_164234_authclient.php(17): yii\db\Migration->addForeignKey('fk_user_id', 'user_auth', 'user_id', 'user', 'id', 'CASCADE', 'CASCADE')
#3 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(509): m151226_164234_authclient->up()
#4 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m151226_164234_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#7 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#8 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('up', Array)
#9 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('up', Array)
#10 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/console/Application.php(176): yii\base\Module->runAction('migrate/up', Array)
#11 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('migrate/up', Array)
#12 /home/host/public_html/host/lab/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 /home/host/public_html/host/lab/protected/yii(29): yii\base\Application->run()
#14 {main}



```

and the the error after log in 

```
PHP Strict Warning – yii\base\ErrorException

Non-static method humhub\modules\user\models\Setting::getModule() should not be called statically

```

_i want to properly install a new version with all my user and data databases and files._
thanks

**Comment by buddha87** [comment]
which mysql version are you using?

**Comment by devcline** [comment]
```
Server: Localhost via UNIX socket
Server type: MariaDB
Server version: 10.1.14-MariaDB - MariaDB Server
Protocol version: 10
User: host@localhost
Server charset: UTF-8 Unicode (utf8)
Web server

cpsrvd 11.58.0.20
Database client version: libmysql - 5.1.73
PHP extension: mysqli Documentation
```

**Comment by frey1esm** [comment]
Any resolution to this? I just ran into the same issues.

**Comment by devcline** [comment]
i tryed to change things, via sql 
but there was too much errors, too much crazy erros . I gave up and fresh install.
