### ISSUE TITLE
Error 500 in beta version after upgrade

### ISSUE THREAD

**Issue by camillagds** [humhub/humhub#2265]
{
    "url": "/index.php?r=dashboard%2Fdashboard%2Fstream&mode=normal",
    "status": 500,
    "response": {
        "name": "Exception",
        "message": "Could not get contents underlying object!",
        "code": 0,
        "type": "yii\\base\\Exception",
        "file": "/opt/humhub/protected/humhub/modules/stream/actions/Stream.php",
        "line": 281,
        "stack-trace": [
            "#0 /opt/humhub/protected/humhub/modules/stream/actions/Stream.php(233): humhub\\modules\\stream\\actions\\Stream::getContentResultEntry(Object(humhub\\modules\\content\\models\\Content))",
            "#1 [internal function]: humhub\\modules\\stream\\actions\\Stream->run()",
            "#2 /opt/humhub/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)",
            "#3 /opt/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\Action->runWithParams(Array)",
            "#4 /opt/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller->runAction('stream', Array)",
            "#5 /opt/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module->runAction('dashboard/dashb...', Array)",
            "#6 /opt/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
            "#7 /opt/humhub/index.php(25): yii\\base\\Application->run()",
            "#8 {main}"
        ]
    },
    "textStatus": "error",
    "dataType": "json",
    "name": "Exception",
    "message": "Could not get contents underlying object!",
    "code": 0,
    "type": "yii\\base\\Exception",
    "file": "/opt/humhub/protected/humhub/modules/stream/actions/Stream.php",
    "line": 281,
    "stack-trace": [
        "#0 /opt/humhub/protected/humhub/modules/stream/actions/Stream.php(233): humhub\\modules\\stream\\actions\\Stream::getContentResultEntry(Object(humhub\\modules\\content\\models\\Content))",
        "#1 [internal function]: humhub\\modules\\stream\\actions\\Stream->run()",
        "#2 /opt/humhub/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)",
        "#3 /opt/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\Action->runWithParams(Array)",
        "#4 /opt/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller->runAction('stream', Array)",
        "#5 /opt/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module->runAction('dashboard/dashb...', Array)",
        "#6 /opt/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
        "#7 /opt/humhub/index.php(25): yii\\base\\Application->run()",
        "#8 {main}"
    ],
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

**Comment by camillagds** [comment]
I reinstall the File module and all ok.
