### ISSUE TITLE
Linked List 

### ISSUE THREAD

**Issue by NENJAK** [humhub/humhub#2283]
Hello everyone,
Since I installed Ver. 1.2. I can not use 
embeded link previews, also if I try to set Linklist as always enabled I 
get following Error:

 Error  Sat, 18 Feb 2017 18:42:52 +0100  yii\db\IntegrityException
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`humhub`.`space_module`, CONSTRAINT `fk_space_module-space_id` FOREIGN KEY (`space_id`) REFERENCES `space` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)' in /var/www/html/protected/vendor/yiisoft/yii2/db/Command.php:846 Stack trace: #0 /var/www/html/protected/vendor/yiisoft/yii2/db/Command.php(846): PDOStatement->execute() #1 /var/www/html/protected/vendor/yiisoft/yii2/db/Schema.php(454): yii\db\Command->execute() #2 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(494): yii\db\Schema->insert('space_module', Array) #3 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(461): yii\db\ActiveRecord->insertInternal(NULL) #4 /var/www/html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(635): yii\db\ActiveRecord->insert(true, NULL) #5 /var/www/html/protected/humhub/modules/admin/controllers/ModuleController.php(330): yii\db\BaseActiveRecord->save() #6 [internal function]: humhub\modules\admin\controllers\ModuleController->actionSetAsDefault() #7 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #8 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #9 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('set-as-default', Array) #10 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('admin/module/se...', Array) #11 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #12 /var/www/html/index.php(25): yii\base\Application->run() #13 {main} Next exception 'yii\db\IntegrityException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`humhub`.`space_module`, CONSTRAINT `fk_space_module-space_id` FOREIGN KEY (`space_id`) REFERENCES `space` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) The SQL being executed was: INSERT INTO `space_module` (`module_id`, `space_id`, `state`) VALUES ('linklist', 0, 2)' in /var/www/html/protected/vendor/yiisoft/yii2/db/Schema.php:636 Stack trace: #0 /var/www/html/protected/vendor/yiisoft/yii2/db/Command.php(856): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `sp...') #1 /var/www/html/protected/vendor/yiisoft/yii2/db/Schema.php(454): yii\db\Command->execute() #2 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(494): yii\db\Schema->insert('space_module', Array) #3 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(461): yii\db\ActiveRecord->insertInternal(NULL) #4 /var/www/html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(635): yii\db\ActiveRecord->insert(true, NULL) #5 /var/www/html/protected/humhub/modules/admin/controllers/ModuleController.php(330): yii\db\BaseActiveRecord->save() #6 [internal function]: humhub\modules\admin\controllers\ModuleController->actionSetAsDefault() #7 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #8 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #9 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('set-as-default', Array) #10 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('admin/module/se...', Array) #11 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #12 /var/www/html/index.php(25): yii\base\Application->run() #13 {main} Additional Information: Array ( [0] => 23000 [1] => 1452 [2] => Cannot add or update a child row: a foreign key constraint fails (`humhub`.`space_module`, CONSTRAINT `fk_space_module-space_id` FOREIGN KEY (`space_id`) REFERENCES `space` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ) 

I also purchased Linklist Preview but it is also not working :(

Thanks to all who reply.
Nenad

**Comment by NENJAK** [comment]
OK ... I solved so that I had to delete few Foreign Keys 
:dancing_men:
