### ISSUE TITLE
session_regenerate_id(): Session write failed.

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2402]
I'm having this in the logs after last `master` git pull.
```
yii\base\ErrorException: session_regenerate_id(): Session write failed. ID: user (path: /tmp/humhub) in public/protected/vendor/yiisoft/yii2/web/Session.php:283

Stack trace:

#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'session_regener...', '/public...', 283, Array)
#1 public/protected/vendor/yiisoft/yii2/web/Session.php(283): session_regenerate_id(false)
#2 public/protected/vendor/yiisoft/yii2/web/DbSession.php(103): yii\web\Session->regenerateID(false)
#3 public/protected/vendor/yiisoft/yii2/web/User.php(618): yii\web\DbSession->regenerateID(true)
#4 public/protected/vendor/yiisoft/yii2/web/User.php(292): yii\web\User->switchIdentity(Object(humhub\modules\user\models\User), 2592000)
#5 public/protected/vendor/yiisoft/yii2/web/User.php(674): yii\web\User->loginByCookie()
#6 public/protected/vendor/yiisoft/yii2/web/User.php(188): yii\web\User->renewAuthStatus()
#7 public/protected/vendor/yiisoft/yii2/web/User.php(333): yii\web\User->getIdentity()
#8 public/protected/vendor/yiisoft/yii2/base/Component.php(132): yii\web\User->getIsGuest()
#9 public/protected/humhub/components/i18n/I18N.php(32): yii\base\Component->__get('isGuest')
#10 public/protected/humhub/components/bootstrap/LanguageSelector.php(28): humhub\components\i18n\I18N->autosetLocale()
#11 public/protected/vendor/yiisoft/yii2/base/Application.php(320): humhub\components\bootstrap\LanguageSelector->bootstrap(Object(humhub\components\Application))
#12 public/protected/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#13 public/protected/humhub/components/Application.php(46): yii\web\Application->bootstrap()
#14 public/protected/vendor/yiisoft/yii2/base/Application.php(272): humhub\components\Application->bootstrap()
#15 public/protected/vendor/yiisoft/yii2/base/Object.php(107): yii\base\Application->init()
#16 public/protected/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
#17 public/index.php(25): yii\base\Application->__construct(Array)
#18 {main} 
```

**Comment by acs-ferreira** [comment]
Aditionnal info:

```
Exception (Integrity constraint violation) 'yii\db\IntegrityException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'a94fe4ca775bf4bd6d41a2aeb6cf071b' for key 'PRIMARY'
The SQL being executed was: INSERT INTO `user_http_session` (`id`, `data`, `expire`, `user_id`) VALUES ('a94fe4ca775bf4bd6d41a2aeb6cf071b', '__flash|a:0:{}', 1490731188, 1)' 

in protected/vendor/yiisoft/yii2/db/Schema.php:636

Stack trace:
#0 protected/vendor/yiisoft/yii2/db/Command.php(856): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `us...')
#1 protected/humhub/modules/user/components/Session.php(64): yii\db\Command->execute()
#2 [internal function]: humhub\modules\user\components\Session->writeSession('a94fe4ca775bf4b...', '__flash|a:0:{}')
#3 protected/vendor/yiisoft/yii2/web/Session.php(283): session_regenerate_id(false)
#4 protected/vendor/yiisoft/yii2/web/DbSession.php(103): yii\web\Session->regenerateID(false)
#5 protected/vendor/yiisoft/yii2/web/User.php(618): yii\web\DbSession->regenerateID(true)
#6 protected/vendor/yiisoft/yii2/web/User.php(292): yii\web\User->switchIdentity(Object(humhub\modules\user\models\User), 2592000)
#7 protected/vendor/yiisoft/yii2/web/User.php(674): yii\web\User->loginByCookie()
#8 protected/vendor/yiisoft/yii2/web/User.php(188): yii\web\User->renewAuthStatus()
#9 protected/vendor/yiisoft/yii2/web/User.php(333): yii\web\User->getIdentity()
#10 protected/vendor/yiisoft/yii2/base/Component.php(132): yii\web\User->getIsGuest()
#11 protected/humhub/components/i18n/I18N.php(32): yii\base\Component->__get('isGuest')
#12 protected/humhub/components/bootstrap/LanguageSelector.php(29): humhub\components\i18n\I18N->autosetLocale()
#13 protected/vendor/yiisoft/yii2/base/Application.php(320): humhub\components\bootstrap\LanguageSelector->bootstrap(Object(humhub\components\Application))
#14 protected/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#15 protected/humhub/components/Application.php(46): yii\web\Application->bootstrap()
#16 protected/vendor/yiisoft/yii2/base/Application.php(272): humhub\components\Application->bootstrap()
#17 protected/vendor/yiisoft/yii2/base/Object.php(107): yii\base\Application->init()
#18 protected/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
#19 index.php(25): yii\base\Application->__construct(Array)
#20 {main}
```

**Comment by samdark** [comment]
How's your server set up? How many clients? What type of MySQL tables do you have? InnoDB or MyISAM? What's the version of MySQL?

**Comment by acs-ferreira** [comment]
Server setup (DBMS) is 3x [MariaDB 10.1.22](https://mariadb.com/kb/en/mariadb/mariadb-10122-changelog/) configured in a [Galera Cluster](https://mariadb.com/kb/en/mariadb/what-is-mariadb-galera-cluster/) (multi-master) backed up by a [MaxScale](https://mariadb.com/products/mariadb-maxscale) dedicated server _(DBMS is not dedicated to HumHub, perhaps, this issue is only related to this software)_.

**Clients** are between 2.000 and 5.000 (peak hours).

All tables are **InnoDB**.

**Comment by samdark** [comment]
How many frontend servers? How do you balance? How do you handle sessions? Sticky ID via cookie?

**Comment by acs-ferreira** [comment]
There are 2 dedicated frontend servers, _(8 cores, 32Gb RAM)_ _(PHP7.1, Apache 2.4 + nGinx 1.11 as reverse-proxy)_ "balanced" by a Cloud service _(LBaaS)_: https://www.incapsula.com/load-balancer.html

> Please note that there is no balancing but **Failover** only _(if server A in a datacenter A stops responding or one of whose services, then server B handles requests - at this time, the last Failover action has taken place at June 16, 2016)_

An additional server (no cluster at the moment) is Redis powered, used also by HumHub as a Data Cache (no query cache or sessions).

````
'cache' => [
    'class' => 'yii\redis\Cache',
    'redis' => [
        'hostname' => '10.99.0.16',
        'port' => 6379,
        'database' => 1,
    ]
],
````

Sessions are handled via cookie (both Phabricator and HumHub).

**Comment by samdark** [comment]
Issue linked is relevant. That's concurrency issue. While it's hard to fix that in the framework itself cause we can't do it for one specific database, it could be done in HumHub session component by using MySQL-specific `REPLACE INTO`. That would ensure atomicity:

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/components/Session.php#L51

**Comment by samdark** [comment]
As for general solution: https://github.com/yiisoft/yii2/issues/13879

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/issues/9438
