### ISSUE TITLE
Stream could not be initialized

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2408]
```
Error: Class 'humhub\modules\post\widgets\WallEntry' not found in /home/USER/SITE/protected/humhub/modules/content/components/ContentActiveRecord.php:147 Stack trace: #0 /home/USER/SITE/protected/humhub/modules/content/components/ContentActiveRecord.php(130): humhub\modules\content\components\ContentActiveRecord->getWallEntryWidget() #1 /home/USER/SITE/protected/humhub/modules/stream/actions/Stream.php(288): humhub\modules\content\components\ContentActiveRecord->getWallOut() #2 /home/USER/SITE/protected/humhub/modules/stream/actions/Stream.php(319): humhub\modules\stream\actions\Stream::renderEntry(Object(humhub\modules\post\models\Post), false) #3 /home/USER/SITE/protected/humhub/modules/stream/actions/Stream.php(234): humhub\modules\stream\actions\Stream::getContentResultEntry(Object(humhub\modules\content\models\Content)) #4 [internal function]: humhub\modules\stream\actions\Stream->run() #5 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/Action.php(94): call_USER_func_array(Array, Array) #6 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array) #7 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('stream', Array) #8 /home/USER/SITE/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('USER/profile/st...', Array) #9 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /home/USER/SITE/index.php(25): yii\base\Application->run() #11 {main}
```

**Comment by Felli** [comment]
I did recently update, but would seem after updating the wallEntry files something went wrong...

**Comment by Felli** [comment]
It would seem to besomething to do with 4f6a3098ce7ca81493e67e9cb88355b1410bd02f

**Comment by Felli** [comment]
I've gotten around to this commint that is causing my issue... 250a6bf1e7228bd3597267801b8c5e8ac0750741

**Comment by luke-** [comment]
Hmm, this is really strange - do you using any custom modules or views?

The class 'humhub\modules\post\widgets\WallEntry' should exists.

**Comment by Felli** [comment]
I'm using custom modules made by @GreenVolume as well as a custom theme by @jeremiahtenbrink but the only custom views is [/views/user/registration](https://github.com/jeremiahtenbrink/HumhubPurpleTheme/tree/master/PurpleTheme/views/user/registration)

**Comment by luke-** [comment]
I could not reproduce this - can you reproduce this on a fresh installation?

**Comment by Felli** [comment]
Hmm... It looks to have been fixed somehow with beta 4, I'm not 100% sure but it doesn't look to appear again.

**Comment by hazmaniameur** [comment]
Same error here, any idea 
php 7.0
humhub 1.3.1
