### ISSUE TITLE
Meetings Module - Error on Share

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2422]
When clicking on **Share Meeting** link at the right bottom of a Meeting, i get an error:
````
TypeError: $(...).find(...).flatelements is not a function@/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730 line 19 > eval:2:5

.globalEval@/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:19:14515
w@/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:19:4608

.append@/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:30:6129
m.prototype.setDialog@/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:217:26600
r/
````

This has been produced on a HumHub Free instance.

**Comment by Felli** [comment]
I'm not getting this error, can you provide steps as well as browsers you're using?

**Comment by acs-ferreira** [comment]
1. Create a meeting (basic info)
2. Go inside that meeting and click Share meeting
![image](https://cloud.githubusercontent.com/assets/12234510/24483460/92460504-14f8-11e7-9464-9afebf7933a9.png)
3. I get this

![image](https://cloud.githubusercontent.com/assets/12234510/24483485/bd3b512e-14f8-11e7-86ad-31068afc3c50.png)

**Firefox 52**

**Comment by acs-ferreira** [comment]
Also, none of the actions on that modal works after that error.

**Comment by Felli** [comment]
I'm still not able to reproduce this... The only issue that I'm seeing is via console errors.

### Chrome
```
The behavior that Selection.addRange() merges existing Range and the specified Range is deprecated and will be removed in M58, around April 2017. See https://www.chromestatus.com/features/6680566019653632 for more details.
```

### Firefox
```
Unknown property ‘-moz-box-shadow’.  Declaration dropped.  theme.css:1:42478
Unknown property ‘-moz-box-shadow’.  Declaration dropped.  theme.css:1:44850
Unknown pseudo-class or pseudo-element ‘-webkit-input-placeholder’.  Ruleset ignored due to bad selector.  theme.css:1:47713
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.  theme.css:1:47843
Error in parsing value for ‘cursor’.  Declaration dropped.  view
Error in parsing value for ‘width’.  Declaration dropped. view
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.
```

**Comment by acs-ferreira** [comment]
Same on **Chrome**

```
TypeError: $(...).find(...).flatelements is not a functionTypeError: $(...).find(...).flatelements is not a function
    at eval (eval at globalEval (https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:19:14515), :2:41)
    at eval ()
    at Function.globalEval (https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:19:14515)
    at w (https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:19:4611)
    at fa.fn.init.append (https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:30:6129)
    at m.setDialog (https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:217:26615)
    at https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:217:29196
    at d (https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:175:9365)
    at e._settlePromiseFromHandler (https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:174:14566)
    at e._settlePromise (https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:174:15369)
    at e._settlePromise0 (https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:174:16070)
    at e._settlePromises (https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:174:17400)
    at d._drainQueue (https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:173:3046)
    at d._drainQueues (https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:173:3107)
    at drainQueues (https://easycloud.humhub.com/static/js/all-05277b1a16b58bb28938b1561d10a390.js?v=1490178730:173:1228)
```

**Comment by Felli** [comment]
I'm thinking it's because of the front-end JavaScript changes, I just now created a new hosted site and now see the errors you're getting.

**Comment by Felli** [comment]
## Full error stack

```
exception 'yii\base\InvalidConfigException' with message 'Please configure UrlManager::baseUrl correctly as you are running a console application.' in /srv/humhub/protected/vendor/yiisoft/yii2/web/UrlManager.php:458 Stack trace: #0 /srv/humhub/protected/vendor/yiisoft/yii2/web/UrlManager.php(321): yii\web\UrlManager->getBaseUrl() #1 /srv/humhub/protected/vendor/yiisoft/yii2/helpers/BaseUrl.php(103): yii\web\UrlManager->createUrl(Array) #2 /srv/humhub/protected/vendor/yiisoft/yii2/helpers/BaseUrl.php(209): yii\helpers\BaseUrl::toRoute(Array, false) #3 /srv/humhub/protected/humhub/modules/installer/Module.php(128): yii\helpers\BaseUrl::to(Array) #4 /srv/humhub/protected/humhub/modules/installer/Module.php(47): humhub\modules\installer\Module->initConfigSteps() #5 /srv/humhub/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\modules\installer\Module->init() #6 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(138): yii\base\Object->__construct(Array) #7 [internal function]: yii\base\Module->__construct('installer', Object(humhub\components\console\Application), Array) #8 /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php(379): ReflectionClass->newInstanceArgs(Array) #9 /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php(154): yii\di\Container->build('humhub\\modules\\...', Array, Array) #10 /srv/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('humhub\\modules\\...', Array, Array) #11 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(353): yii\BaseYii::createObject(Array, Array) #12 /srv/humhub/protected/humhub/libs/ThemeHelper.php(36): yii\base\Module->getModule('installer') #13 /srv/humhub/protected/humhub/libs/ThemeHelper.php(84): humhub\libs\ThemeHelper::getThemes() #14 /srv/humhub/protected/humhub/components/Theme.php(193): humhub\libs\ThemeHelper::getThemeByName('HumHub') #15 /srv/humhub/protected/humhub/migrations/m150928_140718_setColorVariables.php(10): humhub\components\Theme::setColorVariables('HumHub') #16 /srv/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(509): m150928_140718_setColorVariables->up() #17 /srv/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m150928_140718_...') #18 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0) #19 /srv/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #20 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #21 /srv/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('up', Array) #22 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('up', Array) #23 /srv/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/up', Array) #24 /srv/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/up', Array) #25 /srv/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request)) #26 /srv/www/htdocs/xxxyyy/yii.php(27): yii\base\Application->run() #27 {main}
```

**Comment by acs-ferreira** [comment]
Nothing in HumHub logs here.

**Comment by acs-ferreira** [comment]
>I'm thinking it's because of the front-end JavaScript changes

What changes?

For the record:
`Currently installed version: 1.2.0-beta.3`

**Comment by Felli** [comment]
Humhub v1.2 had front-end JavaScript changes this is why the module works with v1.1.2 and not with the beta versions.

**Comment by buddh4** [comment]
There is a new module version available, which should fix the issue.

**Comment by acs-ferreira** [comment]
I can confirm, fixed.
