### ISSUE TITLE
Cron - ZendSearch: 'segments_mw' is not readable

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2458]
Info: The specified file (`segments_mw`) is not present on the filesystem.

Full stack:

```
ZendSearch\Lucene\Exception\InvalidArgumentException: File 'protected/runtime/searchdb/segments_mw' is not readable.
in protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Storage/File/Filesystem.php:45

Stack trace:
#0 protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Storage/Directory/Filesystem.php(348): ZendSearch\Lucene\Storage\File\Filesystem->__construct('...')
#1 protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php(267): ZendSearch\Lucene\Storage\Directory\Filesystem->getFileObject('segments_mw')
#2 protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php(420): ZendSearch\Lucene\Index->_readSegmentsFile()
#3 protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Lucene.php(67): ZendSearch\Lucene\Index->__construct('...', false)
#4 protected/humhub/modules/search/engine/ZendLuceneSearch.php(289): ZendSearch\Lucene\Lucene::open('/srv/users/ekin...')
#5 protected/humhub/modules/search/engine/ZendLuceneSearch.php(274): humhub\modules\search\engine\ZendLuceneSearch->getIndex()
#6 protected/humhub/modules/search/Events.php(39): humhub\modules\search\engine\ZendLuceneSearch->optimize()
#7 [internal function]: humhub\modules\search\Events::onHourlyCron(Object(yii\base\Event))
#8 protected/vendor/yiisoft/yii2/base/Event.php(217): call_user_func(Array, Object(yii\base\Event))
#9 protected/vendor/yiisoft/yii2/base/Component.php(553): yii\base\Event::trigger('humhub\\commands...', 'hourly', Object(yii\base\Event))
#10 protected/humhub/commands/CronController.php(40): yii\base\Component->trigger('hourly')
#11 [internal function]: humhub\commands\CronController->actionHourly()
#12 protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#14 protected/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('hourly', Array)
#15 protected/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('hourly', Array)
#16 protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('cron/hourly', Array)
#17 protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('cron/hourly', Array)
#18 protected/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#19 protected/yii(29): yii\base\Application->run()
#20 {main}
```

**Comment by Felli** [comment]
Would changing `Lucene\Exception\InvalidArgumentException` to `ZendSearch\Lucene\Exception\InvalidArgumentException` line 45, as well as `ZendSearch\Lucene\Exception\RuntimeException` instead of `Lucene\Exception\RuntimeException` on line 55? Of course you'd also have to go through all of the other files within `nqxcode` and fix them as well.

**Comment by luke-** [comment]
Please make sure all files are readable by the console user and the web application.

You may can also try to rebuild the search index: http://docs.humhub.org/admin-search.html

**Comment by acs-ferreira** [comment]
@luke- i've rebuild the index (output OK) but this error came after each hourly `cron` run.

The message `File 'protected/runtime/searchdb/segments_mw' is not readable.`

This file is not on the filsystem, is it normal?

![image](https://cloud.githubusercontent.com/assets/12234510/24752491/54fddb32-1ace-11e7-8d62-b48f9d89907f.png)

**Comment by acs-ferreira** [comment]
Message changes today:

`ZendSearch\Lucene\Exception\InvalidArgumentException: File 'protected/runtime/searchdb/segments_p' is not readable.`

**Comment by acs-ferreira** [comment]
Solved by cleaning all searchdb folder content and rebuild cache.
