### ISSUE TITLE
Since this afternoon: many Error: Getting unknown property: humhub\modules\user\models\Follow::content

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2464]
Since this afternoon my log shows many errors like this. Any idea?

`exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: humhub\modules\user\models\Follow::content' in /var/www/bsmug.nl/httpdocs/protected/vendor/yiisoft/yii2/base/Component.php:147 Stack trace: #0 /var/www/bsmug.nl/httpdocs/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(286): yii\base\Component->__get('content') #1 /var/www/bsmug.nl/httpdocs/protected/humhub/modules/activity/controllers/LinkController.php(48): yii\db\BaseActiveRecord->__get('content') #2 [internal function]: humhub\modules\activity\controllers\LinkController->actionIndex() #3 /var/www/bsmug.nl/httpdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #4 /var/www/bsmug.nl/httpdocs/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #5 /var/www/bsmug.nl/httpdocs/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('', Array) #6 /var/www/bsmug.nl/httpdocs/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('activity/link', Array) #7 /var/www/bsmug.nl/httpdocs/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #8 /var/www/bsmug.nl/httpdocs/index.php(24): yii\base\Application->run() #9 {main}`

**Comment by martinbeek** [comment]
Database integrity run solved this problem
