### ISSUE TITLE
Issues After 1.2.0 Update

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2509]
Full Error Stack, worked before updating to 1.2.0 stable.
```
yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\user\models\Profile::headline in /home/USER/SITE/protected/vendor/yiisoft/yii2/base/Component.php:147 Stack trace:
#0 /home/USER/SITE/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(286): yii\base\Component->__get('headline')
#1 /home/USER/USERft/yii2/helpers/BaseHtml.php(2081): yii\db\BaseActiveRecord->__get('headline')
#2 /home/USER/SITE/protected/vendor/yiisoft/yii2/helpers/BaseHtml.php(1264): yii\helpers\BaseHtml::getAttributeValue(Object(humhub\modules\user\models\Profile), 'headline')
#3 /home/USER/SITE/protected/vendor/yiisoft/yii2/helpers/BaseHtml.php(1313): yii\helpers\BaseHtml::activeInput('text', Object(humhub\modules\user\models\Profile), 'headline', Array)
#4 /home/USER/SITE/protected/vendor/yiisoft/yii2/widgets/ActiveField.php(395): yii\helpers\BaseHtml::activeTextInput(Object(humhub\modules\user\models\Profile), 'headline', Array)
#5 /home/USER/SITE/protected/humhub/compat/HForm.php(224): yii\widgets\ActiveField->textInput(Array)
#6 /home/USER/SITE/protected/humhub/compat/HForm.php(138): humhub\compat\HForm->renderField('headline', Array, Array)
#7 /home/USER/SITE/protected/humhub/compat/HForm.php(134): humhub\compat\HForm->renderElements(Array, Array)
#8 /home/USER/SITE/protected/humhub/compat/HForm.php(120): humhub\compat\HForm->renderElements(Array)
#9 /home/USER/SITE/protected/humhub/modules/user/views/account/edit.php(6): humhub\compat\HForm->render(Object(yii\widgets\ActiveForm))
#10 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/View.php(328): require('/home/USER/...')
#11 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/USER/...', Array)
#12 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/USER/...', Array, Object(humhub\modules\user\controllers\AccountController))
#13 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/Controller.php(381): yii\base\View->render('edit', Array, Object(humhub\modules\user\controllers\AccountController))
#14 /home/USER/SITE/protected/humhub/modules/user/controllers/AccountController.php(85): yii\base\Controller->render('edit', Array)
#15 [internal function]: humhub\modules\user\controllers\AccountController->actionEdit()
#16 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#18 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('edit', Array)
#19 /home/USER/SITE/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('user/account/ed...', Array)
#20 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#21 /home/USER/SITE/index.php(25): yii\base\Application->run()
#22 {main}
```

**Comment by acs-ferreira** [comment]
Try to run migrations manually:

```
cd protected
php yii migrate/up --includeModuleMigrations=1
```

and run database integrity checks:

```
cd protected
php yii integrity/run
```

**Comment by Felli** [comment]
I was able to fix this once I removed some broken `profile attributes` that were created by a LinkedIn module that I have been working on fixing up.
