### ISSUE TITLE
HH 1.2 cron jobs Not working - SOLVED

### ISSUE THREAD

**Issue by eddiepiazza** [humhub/humhub#2522]
Hi, I recently manually updated my HH and I have some errors.

Cron Jobs are being executed by the server but HH is processing errors and not registring the hours and also not sending the mails. I get this two errors every hour:

INFO  Fri, 28 Apr 2017 00:30:01 +0000  application

`$_GET = [ '/home/opengrow/public_html/es/community/protected/yii' => '' 'cron/hourly' => '' ] $_SERVER = [ 'SHELL' => '/bin/bash' 'MAILTO' => 'noreply@gropedia.com' 'USER' => 'opengrow' 'PATH' => '/usr/bin:/bin' 'PWD' => '/home/opengrow' 'LANG' => 'en_US.UTF-8' 'SHLVL' => '1' 'HOME' => '/home/opengrow' 'LOGNAME' => 'opengrow' '_' => '/usr/bin/php' 'PHP_SELF' => '' 'REQUEST_TIME_FLOAT' => 1493339401.8718 'REQUEST_TIME' => 1493339401 ]`

ERROR  Fri, 28 Apr 2017 00:30:02 +0000   yii\base\InvalidConfigException
`exception 'yii\base\InvalidConfigException' with message 'Unable to determine the entry script file path.' in /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Request.php:64 Stack trace: #0 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Component.php(132): yii\base\Request->getScriptFile() #1 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(542): yii\base\Component->__get('scriptFile') #2 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(345): yii\console\controllers\HelpController->getScriptName() #3 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp() #4 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL) #5 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #6 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #7 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('', Array) #8 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('', Array) #9 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('', Array) #10 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('', Array) #11 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request)) #12 /home/opengrow/public_html/es/community/protected/yii(28): yii\base\Application->run() #13 {main}
`

Some ideas solutions ?

Thank you very much.

**Comment by eddiepiazza** [comment]
UPDATE

If I execute threw SSH The next command nothing happens: 

`php /home/opengrow/public_html/es/community/protected/yii cron/daily >/dev/null 2>&1`

But if I execute this one works perfectly and I recieve the daily mail:

`php /home/opengrow/public_html/es/community/protected/yii cron/daily`

The funny thing is that if I create a Cron Job in Cpanel with nect code:

`php /home/opengrow/public_html/es/community/protected/yii cron/hourly`

I get this log:
![image](https://cloud.githubusercontent.com/assets/8577866/25523418/87407d66-2bfe-11e7-9df7-3a60a36a4316.png)

And also I recieve this email:

![image](https://cloud.githubusercontent.com/assets/8577866/25523459/a68f6826-2bfe-11e7-9c58-d6204db476ff.png)


But HH doesn´t register the execution:

![image](https://cloud.githubusercontent.com/assets/8577866/25523492/c1828424-2bfe-11e7-96ea-9fb72d5f5622.png)

I am getting crazy because If I execute by SSH 

`php /home/opengrow/public_html/es/community/protected/yii cron/hourly`

Works perfectly !!!! wtf ? XD

Thanks.

**Comment by eddiepiazza** [comment]
![image](https://cloud.githubusercontent.com/assets/8577866/25526018/98cafac4-2c09-11e7-8e8b-bf2fb7e12b85.png)

**Comment by eddiepiazza** [comment]
**SOLUTION:**

**/usr/local/bin/php** /home/opengrow/public_html/es/community/protected/yii cron/hourly >/dev/null 2>&1
