### ISSUE TITLE
Solved:  Exception in search, please help!

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2526]
On our website, every search query (search box on dashboard) with the Dutch word "en" in it, results in an exception error. The word 'en' in dutch means "and" / "und", so it appears in a lot of posts.  Also a search for "martin en piet" results in an exception, as long as the word 'en' is present! Any other search seems to work fine.

Error:

```
exception 'ZendSearch\Lucene\Exception\OutOfBoundsException' with message 'Terms per query limit is reached.' in /var/www/pryv.nl/httpdocs/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Search/Query/Wildcard.php:183
Stack trace:
#0 /var/www/pryv.nl/httpdocs/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Search/Query/Boolean.php(132): ZendSearch\Lucene\Search\Query\Wildcard-&gt;rewrite(Object(ZendSearch\Lucene\Index))
#1 /var/www/pryv.nl/httpdocs/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php(669): ZendSearch\Lucene\Search\Query\Boolean-&gt;rewrite(Object(ZendSearch\Lucene\Index))
#2 /var/www/pryv.nl/httpdocs/protected/humhub/modules/search/engine/ZendLuceneSearch.php(120): ZendSearch\Lucene\Index-&gt;find(Object(ZendSearch\Lucene\Search\Query\Boolean))
#3 /var/www/pryv.nl/httpdocs/protected/humhub/modules/search/controllers/SearchController.php(78): humhub\modules\search\engine\ZendLuceneSearch-&gt;find('en', Array)
#4 [internal function]: humhub\modules\search\controllers\SearchController-&gt;actionIndex()
#5 /var/www/pryv.nl/httpdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /var/www/pryv.nl/httpdocs/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction-&gt;runWithParams(Array)
#7 /var/www/pryv.nl/httpdocs/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller-&gt;runAction('index', Array)
#8 /var/www/pryv.nl/httpdocs/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module-&gt;runAction('search/search/i...', Array)
#9 /var/www/pryv.nl/httpdocs/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application-&gt;handleRequest(Object(humhub\components\Request))
#10 /var/www/pryv.nl/httpdocs/index.php(24): yii\base\Application-&gt;run()
#11 {main} 
```

**Comment by martinbeek** [comment]
Ps. i ran a integrity test throug the yii.bat with no resolve

**Comment by martinbeek** [comment]
Same as #1971 ?

**Comment by martinbeek** [comment]
Aha.... i found something in my webserver's error log: 
 PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted 

I'll continue to research this...

**Comment by martinbeek** [comment]
Changing 1024 to 2048
`    private static $_termsPerQueryLimit = 2048; // was 1024`
in ./protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Lucene.php
solves the problem !

**Comment by EtienneDemers** [comment]
FYI
Had the same issue on my production server (oddly, not on the test one) and while changing to 2048 fixed many of the problematic search queries, some persisted. I changed the value to 4096 and the problem stopped (for now).

**Comment by 001101** [comment]
Is not working for me, not with 2048 or 4096
