### ISSUE TITLE
NGINX - 502 Bad Request

### ISSUE THREAD

**Issue by gfelot** [humhub/humhub#2544]
Hey.. I follow this resolved issue : https://github.com/humhub/humhub/issues/257
and copy/paste the Nginx server block.

I got a 502 when I try to access the service.

```
server {
    listen 80;
    listen [::]:80;

    server_name hub.habitatdurable.pro default;

    root /var/www/html/humhub;

    location / {
        index index.php;

        if (!-e $request_filename) {
            rewrite ^/(.*) /index.php?query=$1 last;
        }
    }

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) {
                return 404;
        }

        fastcgi_pass 127.0.0.1:9001;
        fastcgi_index index.php;

        include /etc/nginx/fastcgi_params;
        fastcgi_param HTTP_MOD_REWRITE 1;
    }

    location ~* \.(?:ico|css|js|gif|jpe?g|png|ttf|woff)$ {
        access_log off;
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "public, mustrevalidate, proxy-revalidate";
    }

    location ~ /\.ht {
        deny all;
    }

    location /protected {
        deny all;
    }

    location /uploads/file {
        deny all;
    }
}
```

What's wrong with this block ? I can ping hub.habitatdurable.pro

**Comment by martinbeek** [comment]
Your nginx php block looks fine, although basic. 

Try to solve the problem here by changing
        fastcgi_pass 127.0.0.1:9001;
to:
       fastcgi_pass /var/run/php5-fpm.sock

And then go to /etc/php5/fpm/pool.d/www.conf 
and change the line 
   listen = 127.0.0.1:9000 
to
   listen = /var/run/php5-fpm.sock 

run sudo service php5-fpm reload 
and sudo service nginx reload 


If the problem still exists, you further have to suspect your php5-fpm's  setup in  /etc/php5/fpm/pool.d/www.conf 

Some more info here: https://www.datadoghq.com/blog/nginx-502-bad-gateway-errors-php-fpm/

**Comment by gfelot** [comment]
I wasn't able to install `php5-fpm` on my 16.04 Ubuntu. `apt` pointed out that this package is deprecated and I have to install `php-fpm` instead, which is the php7.

So I changed your recommandation to : `fastcgi_pass unix:/run/php/php7.0-fpm.sock;`

But I couldn't find a `listen` key to `/etc/php/7.0/fpm/php-fpm.conf`, even already commented.

so the .php part of my web server is like this :

```
location ~ [^/]\.php(/|$) {
                 fastcgi_split_path_info ^(.+?\.php)(/.*)$;
                 if (!-f $document_root$fastcgi_script_name) {
                    return 404;
                }

                fastcgi_pass unix:/run/php/php7.0-fpm.sock;
                include snippets/fastcgi-php.conf;
                fastcgi_param HTTP_MOD_REWRITE 1;
	}
```
 
I made a info.php file on the root and can access it => `baseURL/info.php`

But try to reach humhub I got a bunch of error :

```
1. in /var/www/humhub/protected/humhub/components/bootstrap/LanguageSelector.php at line 27
181920212223242526272829303132 */
class LanguageSelector implements BootstrapInterface
{
 
    /**
     * @inheritdoc
     */
    public function bootstrap($app)
    {
        mb_internal_encoding('UTF-8');
 
        $app->i18n->autosetLocale();
    }
 
}
2. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 320 – humhub\components\bootstrap\LanguageSelector::bootstrap(humhub\components\Application)
3. in /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 69 – yii\base\Application::bootstrap()
4. in /var/www/humhub/protected/humhub/components/Application.php at line 46 – yii\web\Application::bootstrap()
40414243444546474849505152        }
 
        if (Yii::getAlias('@webroot-static', false) === false) {
            Yii::setAlias('@webroot-static', '@webroot/static');
        }
 
        parent::bootstrap();
    }
 
    /**
     * @return string the homepage URL
     */
    public function getHomeUrl()
5. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 272 – humhub\components\Application::bootstrap()
6. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Object.php at line 107 – yii\base\Application::init()
7. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 205 –
An Error occurred while handling another error:
Error: Call to undefined function yii\web\mb_strlen() in /var/www/humhub/protected/vendor/yiisoft/yii2/web/ErrorHandler.php:416
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(423): yii\web\ErrorHandler->argumentsToString(Array)
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php(26): yii\web\ErrorHandler->argumentsToString(Array)
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(328): require('/var/www/humhub...')
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/humhub...', Array)
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(253): yii\base\View->renderFile('/var/www/humhub...', Array, Object(yii\web\ErrorHandler))
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(307): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/views/errorHandler/exception.php(385): yii\web\ErrorHandler->renderCallStackItem('/var/www/humhub...', 204, 'yii\\base\\Object', '__construct', Array, 7)
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(328): require('/var/www/humhub...')
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/humhub...', Array)
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(253): yii\base\View->renderFile('/var/www/humhub...', Array, Object(yii\web\ErrorHandler))
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(113): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(Error))
#12 [internal function]: yii\base\ErrorHandler->handleException(Object(Error))
#13 {main}
Previous exception:
Error: Call to undefined function humhub\components\bootstrap\mb_internal_encoding() in /var/www/humhub/protected/humhub/components/bootstrap/LanguageSelector.php:27
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(320): humhub\components\bootstrap\LanguageSelector->bootstrap(Object(humhub\components\Application))
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#2 /var/www/humhub/protected/humhub/components/Application.php(46): yii\web\Application->bootstrap()
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(272): humhub\components\Application->bootstrap()
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Object.php(107): yii\base\Application->init()
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
#6 /var/www/humhub/index.php(25): yii\base\Application->__construct(Array)
#7 {main}
```

**Comment by gfelot** [comment]
Ok I don't why but refreshing the page serval times on I didn't go this message... just some php module not installer (like zip, mbstring...) I had to install them manually and everything is working now.

I'm posting my nginx block server here if someone wants to have a template with php7 activated : 

```
server {
       server_name hub.habitatdurable.pro;
       listen 80;
       listen [::]:80;
       root /var/www/humhub/;
       index index.php;

       location / {
               index index.php;
               if (!-e $request_filename) {
               rewrite ^/(.*) /index.php?query=$1 last;
               }
        }

        location ~ [^/]\.php(/|$) {
                 fastcgi_split_path_info ^(.+?\.php)(/.*)$;
                 if (!-f $document_root$fastcgi_script_name) {
                    return 404;
                }

                fastcgi_pass unix:/run/php/php7.0-fpm.sock;
                include snippets/fastcgi-php.conf;
                fastcgi_param HTTP_MOD_REWRITE 1;
        }

        location ~* \.(?:ico|css|js|gif|jpe?g|png|ttf|woff)$ {
                access_log off;
                expires 30d;
                add_header Pragma public;
                add_header Cache-Control "public, mustrevalidate, pro\
xy-revalidate";
                }

       location ~ /\.ht {
                deny all;
                }

        location /protected {
                deny all;
                }

        location /uploads/file {
                deny all;
                }
}
```
