### ISSUE TITLE
Wall posts are gone; 500 on POST /s/${SPACE}/post/post/post

### ISSUE THREAD

**Issue by alxwr** [humhub/humhub#2586]
Since 20438916b112decb1cae233d45d8acd9c769407b all wall posts are gone and I can't create new ones. (500 Internal Server Error)

Tested with: master / 3d86175a91e0d22785f8554b7b2a9e01132d8606
When I switch back to b7d1328fcbf358ca642f7de11e4be275db3f52ca everything is fine again and I even see my (given up for lost) test posts. :-)

Log: **class 'humhub\modules\content\Events' does not have a method 'onWallEntryControlsInit'**

```
yii\base\ErrorException: call_user_func() expects parameter 1 to be a valid callback, class 'humhub\modules\content\Events' does not have a method 'onWallEntryControlsInit' in /opt/humhub/protected/vendor/yiisoft/yii2/base/Event.php:217 Stack trace: 
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'call_user_func(...', '/opt/humhub/pro...', 217, Array)  
#1 /opt/humhub/protected/vendor/yiisoft/yii2/base/Event.php(217): call_user_func(Array, Object(yii\base\Event)) 
#2 /opt/humhub/protected/vendor/yiisoft/yii2/base/Component.php(553): yii\base\Event::trigger('humhub\\modules\\...', 'init', Object(yii\base\Event)) 
#3 /opt/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(72): yii\base\Component->trigger('init') 
#4 /opt/humhub/protected/humhub/widgets/BaseStack.php(67): yii\base\Widget->init() 
#5 /opt/humhub/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\widgets\BaseStack->init() 
#6 [internal function]: yii\base\Object->__construct(Array) 
#7 /opt/humhub/protected/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array) 
#8 /opt/humhub/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('humhub\\modules\\...', Array, Array)  
#9 /opt/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('humhub\\modules\\...', Array, Array)  
#10 /opt/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(136): yii\BaseYii::createObject(Array) 
#11 /opt/humhub/protected/humhub/modules/content/widgets/views/wallEntry.php(27): yii\base\Widget::widget(Array) 
#12 /opt/humhub/protected/vendor/yiisoft/yii2/base/View.php(328): require('/opt/humhub/pro...') #13 /opt/humhub/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/opt/humhub/pro...', Array) 
#14 /opt/humhub/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/opt/humhub/pro...', Array, Object(humhub\modules\post\widgets\WallEntry)) 
#15 /opt/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(234): yii\base\View->render('@humhub/modules...', Array, Object(humhub\modules\post\widgets\WallEntry)) 
#16 /opt/humhub/protected/humhub/modules/content/widgets/WallEntry.php(165): yii\base\Widget->render('@humhub/modules...', Array) 
#17 /opt/humhub/protected/humhub/modules/content/components/ContentActiveRecord.php(185): humhub\modules\content\widgets\WallEntry->renderWallEntry() 
#18 /opt/humhub/protected/humhub/modules/stream/actions/Stream.php(286): humhub\modules\content\components\ContentActiveRecord->getWallOut() 
#19 /opt/humhub/protected/humhub/modules/stream/actions/Stream.php(319): humhub\modules\stream\actions\Stream::renderEntry(Object(humhub\modules\post\models\Post), false) 
#20 /opt/humhub/protected/humhub/modules/content/widgets/WallCreateContentForm.php(144): humhub\modules\stream\actions\Stream::getContentResultEntry(Object(humhub\modules\content\models\Content)) 
#21 /opt/humhub/protected/humhub/modules/post/controllers/PostController.php(39): humhub\modules\content\widgets\WallCreateContentForm::create(Object(humhub\modules\post\models\Post), Object(humhub\modules\space\models\Space)) 
#22 [internal function]: humhub\modules\post\controllers\PostController->actionPost()
#23 /opt/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) 
#24 /opt/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) 
#25 /opt/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('post', Array) 
#26 /opt/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('post/post/post', Array) 
#27 /opt/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) 
#28 /opt/humhub/index.php(25): yii\base\Application->run()
#29 {main}
```

**Comment by buddh4** [comment]
Try clearing your cache "Administration -> Settings -> Advanced -> Cache"

**Comment by alxwr** [comment]
Wow, that did the trick! Thank you!

Now, is there a way to programmatically clear the cache? (In Rails I'd call a Rake task. What do I do in HumHub/Yii?)

**Comment by alxwr** [comment]
Nevermind. Found it. 

```
php yii cache/flush-all
```
