### ISSUE TITLE
Error upgrading from 1.1.1 to 1.1.2:   Exception (Unknown Property) 

### ISSUE THREAD

**Issue by frey1esm** [humhub/humhub#2619]
```
Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Setting unknown property: humhub\components\Application::version' 

in /protected/vendor/yiisoft/yii2/base/Component.php:197

Stack trace:
#0 /protected/vendor/yiisoft/yii2/BaseYii.php(521): yii\base\Component->__set('version', '1.1.2')
#1 /protected/vendor/yiisoft/yii2/base/Object.php(105): yii\BaseYii::configure(Object(humhub\components\Application), Array)
#2 /protected/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
#3 /index.php(25): yii\base\Application->__construct(Array)
#4 {main}
```

**Comment by frey1esm** [comment]
PHP Version 7.1.5

**Comment by buddh4** [comment]
Did you manually update? Perhaps you have to run a composer update.

**Comment by frey1esm** [comment]
It's weird. I can do successive updates automatically from within Humhub admin area from version 1.1beta2 to 1.1 and then to 1.1.1.

But trying an auto update from this point generates the error above. I have to manually update from this point, and that does not generate any errors.
