### ISSUE TITLE
Issue at first execution 

### ISSUE THREAD

**Issue by alberto98fx** [humhub/humhub#2626]
PHP 7.0.18-0ubuntu0.17.04.1 (cli) 
Ubuntu 17.04

```
Permission for write and read of 

assets
protected/config/
protected/modules
protected/runtime
uploads/


made executable

protected/yii

```
```
Error

Call to undefined function humhub\components\bootstrap\mb_internal_encoding()
1. in /var/www/html/protected/humhub/components/bootstrap/LanguageSelector.php at line 27
181920212223242526272829303132 */
class LanguageSelector implements BootstrapInterface
{
 
    /**
     * @inheritdoc
     */
    public function bootstrap($app)
    {
        mb_internal_encoding('UTF-8');
 
        $app->i18n->autosetLocale();
    }
 
}
2. in /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php at line 320 – humhub\components\bootstrap\LanguageSelector::bootstrap(humhub\components\Application)
3. in /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php at line 69 – yii\base\Application::bootstrap()
4. in /var/www/html/protected/humhub/components/Application.php at line 46 – yii\web\Application::bootstrap()
40414243444546474849505152        }
 
        if (Yii::getAlias('@webroot-static', false) === false) {
            Yii::setAlias('@webroot-static', '@webroot/static');
        }
 
        parent::bootstrap();
    }
 
    /**
     * @return string the homepage URL
     */
    public function getHomeUrl()
5. in /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php at line 272 – humhub\components\Application::bootstrap()
6. in /var/www/html/protected/vendor/yiisoft/yii2/base/Object.php at line 107 – yii\base\Application::init()
7. in /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php at line 205 –
An Error occurred while handling another error:
Error: Call to undefined function yii\web\mb_strlen() in /var/www/html/protected/vendor/yiisoft/yii2/web/ErrorHandler.php:416
Stack trace:
#0 /var/www/html/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(423): yii\web\ErrorHandler->argumentsToString(Array)
#1 /var/www/html/protected/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php(26): yii\web\ErrorHandler->argumentsToString(Array)
#2 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(328): require('/var/www/html/p...')
#3 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/html/p...', Array)
#4 /var/www/html/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(253): yii\base\View->renderFile('/var/www/html/p...', Array, Object(yii\web\ErrorHandler))
#5 /var/www/html/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(307): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#6 /var/www/html/protected/vendor/yiisoft/yii2/views/errorHandler/exception.php(385): yii\web\ErrorHandler->renderCallStackItem('/var/www/html/p...', 204, 'yii\\base\\Object', '__construct', Array, 7)
#7 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(328): require('/var/www/html/p...')
#8 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/html/p...', Array)
#9 /var/www/html/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(253): yii\base\View->renderFile('/var/www/html/p...', Array, Object(yii\web\ErrorHandler))
#10 /var/www/html/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(113): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#11 /var/www/html/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(Error))
#12 [internal function]: yii\base\ErrorHandler->handleException(Object(Error))
#13 {main}
Previous exception:
Error: Call to undefined function humhub\components\bootstrap\mb_internal_encoding() in /var/www/html/protected/humhub/components/bootstrap/LanguageSelector.php:27
Stack trace:
#0 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(320): humhub\components\bootstrap\LanguageSelector->bootstrap(Object(humhub\components\Application))
#1 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#2 /var/www/html/protected/humhub/components/Application.php(46): yii\web\Application->bootstrap()
#3 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(272): humhub\components\Application->bootstrap()
#4 /var/www/html/protected/vendor/yiisoft/yii2/base/Object.php(107): yii\base\Application->init()
#5 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
#6 /var/www/html/index.php(25): yii\base\Application->__construct(Array)
#7 {main}
```

**Comment by buddh4** [comment]
http://docs.humhub.org/admin-requirements.html#required-php-extensions - Probably missed to install PHP Multibyte String Support package

**Comment by alberto98fx** [comment]
Thanks!
