### ISSUE TITLE
yii\console\Exception: Unable to compress JavaScript files

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2705]
Each time i run

`php yii asset humhub/config/assets.php humhub/config/assets-prod.php`

i get

```
yii\console\Exception: Unable to compress JavaScript files into '/protected/humhub/config/../../../static/js/all-temp.js'. in /protected/vendor/yiisoft/yii2/console/controllers/AssetController.php:525
Stack trace:
#0 /protected/vendor/yiisoft/yii2/console/controllers/AssetController.php(369): yii\console\controllers\AssetController->compressJsFiles(Array, '/protected...')
#1 /protected/vendor/yiisoft/yii2/console/controllers/AssetController.php(195): yii\console\controllers\AssetController->buildTarget(Object(yii\web\AssetBundle), 'js', Array)
#2 [internal function]: yii\console\controllers\AssetController->actionCompress('humhub/config/a...', 'humhub/config/a...')
#3 /protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#5 /protected/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('', Array)
#6 /protected/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('', Array)
#7 /protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('asset', Array)
#8 /protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('asset', Array)
#9 /protected/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#10 /protected/yii(29): yii\base\Application->run()
#11 {main}
```

**Comment by githubjeka** [comment]
This can only do the @buddh4 )

**Comment by buddh4** [comment]
You probably need to install grunt as desribed [here](https://github.com/humhub/humhub/blob/master/protected/humhub/docs/guide/developer/environment.md#setup)

**Comment by acs-ferreira** [comment]
Grunt is installed but i'm not talking about Grunt generation but manual Yii generation (Grunt is - _or should be_ - useless in this case)

**Comment by buddh4** [comment]
Grunt is used for the compression part there is no build in yii tool for this.

**Comment by acs-ferreira** [comment]
`npm install grunt --save-dev` fixed it, thanks 👍

**Comment by buddh4** [comment]
You can also use `grunt build-assets` within your humhub root, think its a bit more comfortable

**Comment by acs-ferreira** [comment]
It throws an error:

```
grunt build-assets
/srv/users/humhub/node_modules/findup-sync/node_modules/glob/sync.js:321
        throw er
        ^

Error: EACCES: permission denied, scandir '/srv/users'
  at Error (native)
  at Object.fs.readdirSync (fs.js:952:18)
  at GlobSync._readdir (/srv/users/humhub/node_modules/findup-sync/node_modules/glob/sync.js:275:41)
  at GlobSync._processReaddir (/srv/users/humhub/node_modules/findup-sync/node_modules/glob/sync.js:135:22)
  at GlobSync._process (/srv/users/humhub/node_modules/findup-sync/node_modules/glob/sync.js:130:10)
  at new GlobSync (/srv/users/humhub/node_modules/findup-sync/node_modules/glob/sync.js:46:10)
  at Function.globSync [as sync] (/srv/users/humhub/node_modules/findup-sync/node_modules/glob/sync.js:24:10)
  at /srv/users/humhub/node_modules/findup-sync/lib/findup-sync.js:31:19
  at Array.map (native)
  at Object.module.exports [as findup] (/srv/users/humhub/node_modules/findup-sync/lib/findup-sync.js:30:22)
  at Task.task.init (/srv/users/humhub/node_modules/grunt/lib/grunt/task.js:424:18)
  at Object.grunt.tasks (/srv/users/humhub/node_modules/grunt/lib/grunt.js:111:8)
  at Object.module.exports [as cli] (/srv/users/humhub/node_modules/grunt/lib/grunt/cli.js:27:9)
  at Object.<anonymous> (/usr/lib/node_modules/grunt-cli/bin/grunt:44:20)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:389:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:504:3
```

**Comment by buddh4** [comment]
It's not a problem honestly don't know where it comes from.
