### ISSUE TITLE
Unable to verify data submission when pressing "Like" on iOS/Safari

### ISSUE THREAD

**Issue by svigerske** [humhub/humhub#2808]
### What steps will reproduce the problem?

Accessing HumHub via the Safari browser on iOS and press "Like" on a post.

### What is the expected result?

To have the user registered as someone who liked the post.

### What do you get instead?

The user gets the error message "An unexpected error occured. If this keeps happening, please contact a site administrator."

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   |  1.2.2
| PHP version      | 5.6.31-6+ubuntu14.04.1+deb.sury.org+1
| Operating system | GNU/Linux Ubuntu 14.04.5 LTS

Logging:
```
exception 'yii\web\BadRequestHttpException' with message 'Unable to verify your data submission.' in /var/www/humhub/protected/vendor/yiisoft/yii2/web/Controller.php:166
Stack trace:
#0 /var/www/humhub/protected/humhub/components/Controller.php(187): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /var/www/humhub/protected/humhub/modules/content/components/ContentAddonController.php(107): humhub\components\Controller->beforeAction(Object(yii\base\InlineAction))
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): humhub\modules\content\components\ContentAddonController->beforeAction(Object(yii\base\InlineAction))
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('like', Array)
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('like/like/like', Array)
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#6 /var/www/humhub/index.php(25): yii\base\Application->run()
#7 {main}
```
and
```
$_GET = [ 'contentModel' => 'humhub\\modules\\post\\models\\Post' 'contentId' => '555' ]
$_SERVER = [
  'REDIRECT_SCRIPT_URL' => '/like/like/like'
  'REDIRECT_SCRIPT_URI' => 'https://xyz.domain.com/like/like/like'
  'REDIRECT_HTTPS' => 'on'
  'REDIRECT_SSL_TLS_SNI' => 'xyz.domain.com'
  'REDIRECT_STATUS' => '200'
  'SCRIPT_URL' => '/like/like/like'
  'SCRIPT_URI' => 'https://xyz.domain.com/like/like/like'
  'HTTPS' => 'on'
  'HTTP_HOST' => 'xyz.domain.com'
  'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest'
  'HTTP_ACCEPT_LANGUAGE' => 'de-de'
  'HTTP_ACCEPT_ENCODING' => 'br, gzip, deflate'
  'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01'
  'HTTP_ORIGIN' => 'https://xyz.domain.com'
  'CONTENT_LENGTH' => '0'
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0_3 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A432 Safari/604.1' 
  'HTTP_REFERER' => 'https://xyz.domain.com/dashboard'
  'HTTP_DNT' => '1'
  'HTTP_CONNECTION' => 'keep-alive'
  'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  'SERVER_SIGNATURE' => '<address>Apache/2.4.7 (Ubuntu) Server at xyz.domain.com Port 443</address> '
  'SERVER_SOFTWARE' => 'Apache/2.4.7 (Ubuntu)'
  'SERVER_NAME' => 'xyz.domain.com'
  'SERVER_PORT' => '443'
  'DOCUMENT_ROOT' => '/var/www/humhub'
  'REQUEST_SCHEME' => 'https'
  'CONTEXT_PREFIX' => ''
  'CONTEXT_DOCUMENT_ROOT' => '/var/www/humhub'
   'SCRIPT_FILENAME' => '/var/www/humhub/index.php'
  'REMOTE_PORT' => '56095'
  'REDIRECT_QUERY_STRING' => 'contentModel=humhub%5Cmodules%5Cpost%5Cmodels%5CPost&contentId=555'
  'REDIRECT_URL' => '/like/like/like'
  'GATEWAY_INTERFACE' => 'CGI/1.1'
  'SERVER_PROTOCOL' => 'HTTP/1.1'
  'REQUEST_METHOD' => 'POST' 'QUERY_STRING' => 'contentModel=humhub%5Cmodules%5Cpost%5Cmodels%5CPost&contentId=555'
  'REQUEST_URI' => '/like/like/like?contentModel=humhub%5Cmodules%5Cpost%5Cmodels%5CPost&contentId=555'
  'SCRIPT_NAME' => '/index.php'
  'PHP_SELF' => '/index.php'
  'REQUEST_TIME_FLOAT' => 1509546294.075
  'REQUEST_TIME' => 1509546294
]```
(some entries removed or domain replaced for privacy issues)

**Comment by buddh4** [comment]
Did you recently update your installation?
Could you reproduce this on another browsers?
Try clearing the cache "Administration -> Settings  -> Cache -> Flush Cache".

**Comment by svigerske** [comment]
Clearing the cache worked to like a post that couldn't be liked before by that user on that browser. We'll keep monitoring whether this will happen again, also after the upgrade to 1.2.3.

We could not reproduce this with other browsers and the issue came up since upgrading to 1.2.2, I think.

**Comment by svigerske** [comment]
We got the same problem again (same user, same brower, different humhub-post). This time, also clearing the cache did not help. We are still at 1.2.2, so I don't reopen yet.
