### ISSUE TITLE
Space chooser search crashes when more than 1024 spaces match a search

### ISSUE THREAD

**Issue by cebe** [humhub/humhub#2834]
### What steps will reproduce the problem?

1. create more than 1024 spaces and add a term in the description for all of them.
2. searching for that term will crash the search engine.

### What is the expected result?

Search success.

### What do you get instead?

Exception:

```
{
"name":"Exception",
"message":"Terms per query limit is reached",
"code":0,
"type":"ZendSearch\\Lucene\\Exception\\InvalidArgumentException",
"file":"/home/cebe/dev/humhub/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Search/Query/MultiTerm.php",
"line":99,
"stack-trace":[
"#0 /home/cebe/dev/humhub/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Search/Query/MultiTerm.php(245): ZendSearch\\Lucene\\Search\\Query\\MultiTerm->__construct(Array, Array)",
"#1 /home/cebe/dev/humhub/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Search/Query/Boolean.php(152): ZendSearch\\Lucene\\Search\\Query\\MultiTerm->optimize(Object(ZendSearch\\Lucene\\Index))",
"#2 /home/cebe/dev/humhub/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Search/Query/Boolean.php(152): ZendSearch\\Lucene\\Search\\Query\\Boolean->optimize(Object(ZendSearch\\Lucene\\Index))",
"#3 /home/cebe/dev/humhub/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Search/Query/Boolean.php(152): ZendSearch\\Lucene\\Search\\Query\\Boolean->optimize(Object(ZendSearch\\Lucene\\Index))",
"#4 /home/cebe/dev/humhub/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php(669): ZendSearch\\Lucene\\Search\\Query\\Boolean->optimize(Object(ZendSearch\\Lucene\\Index))",
"#5 /home/cebe/dev/humhub/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php(120): ZendSearch\\Lucene\\Index->find(Object(ZendSearch\\Lucene\\Search\\Query\\Boolean))",
"#6 /home/cebe/dev/humhub/humhub/protected/humhub/modules/space/controllers/BrowseController.php(53): humhub\\modules\\search\\engine\\ZendLuceneSearch->find('offi', Array)",
"#7 [internal function]: humhub\\modules\\space\\controllers\\BrowseController->actionSearchJson()",
"#8 /home/cebe/dev/humhub/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)",
"#9 /home/cebe/dev/humhub/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\InlineAction->runWithParams(Array)",
"#10 /home/cebe/dev/humhub/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller->runAction('search-json', Array)",
"#11 /home/cebe/dev/humhub/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module->runAction('space/browse/se...', Array)",
"#12 /home/cebe/dev/humhub/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
"#13 /home/cebe/dev/humhub/humhub/index.php(25): yii\\base\\Application->run()",
"#14 {main}"
]}
```

### Additional info

This issue has been reported in #2526 and #1971 before.
As it is a scaling issue its hard to reproduce without adding a lot of content to humhub.
As far as I see this affects all places where search is used, not only space chooser.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2 / master at a5559da7a958360298f9a42d31ef6020f670868d
| PHP version      | 7.1
| Operating system | Debian GNU/Linux

**Comment by cebe** [comment]
As mentioned in the related issues a workaround is to the set limit to a higher value:

```diff
diff --git a/protected/humhub/modules/search/engine/ZendLuceneSearch.php b/protected/humhub/modules/search/engine/ZendLuceneSearch.php
index b20c502..60e4aff 100644
--- a/protected/humhub/modules/search/engine/ZendLuceneSearch.php
+++ b/protected/humhub/modules/search/engine/ZendLuceneSearch.php
@@ -285,6 +285,8 @@ class ZendLuceneSearch extends Search
         \ZendSearch\Lucene\Analysis\Analyzer\Analyzer::setDefault(new \ZendSearch\Lucene\Analysis\Analyzer\Common\Utf8Num\CaseInsensitive());
         \ZendSearch\Lucene\Search\QueryParser::setDefaultOperator(\ZendSearch\Lucene\Search\QueryParser::B_AND);
 
+        \ZendSearch\Lucene\Lucene::setTermsPerQueryLimit(20001);
+
         try {
             $index = \ZendSearch\Lucene\Lucene::open($this->getIndexPath());
         } catch (\ZendSearch\Lucene\Exception\RuntimeException $ex) {
```

The number 20001 comes from having 20000 test spaces + the welcome space.

**Comment by cebe** [comment]
Sent a pull request to make the value configurable: https://github.com/humhub/humhub/pull/2836

However considering the limitation it might be useful to provide other search backends, such as elasticsearch. Do these exist? I did not find anything yet.

**Comment by Buliwyfa** [comment]
thanks @cebe

**Comment by acs-ferreira** [comment]
Does this only affect Lucene?
What about Elasticsearch or Solr?

**Comment by 001101** [comment]
not working

v 1.2.4

**Comment by cebe** [comment]
> not working

how did you configure the limit?

**Comment by 001101** [comment]
configured with web and common config file

what items do you mean exactly?
content - 14,272
activity - 13,062
space_membership - 8,008
user_follow - 3,684
likes - 1,310

it is not soo big

**Comment by 001101** [comment]
so some more infos, got this error in log:
`
ZendSearch\Lucene\Exception\OutOfBoundsException: Terms per query limit is reached. in /home/admin/web/band9.net/public_html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Search/Query/Wildcard.php:183 Stack trace: #0 
`
the search string which causing it is 37 chars long

**Comment by 001101** [comment]
Is there any update or hotfix possible?

Now the users also reported that searches which includes a minus in names, like 'Double-Name', will not get find and the prename for the person is also excluded from results, which is kind a strange behaviour.

**Comment by cebe** [comment]
which value did you set for `ZendLuceneSearch::$searchItemLimit`?
