### ISSUE TITLE
Windows 10 - Exception 'ReflectionException' with message 'Class humhub\modules\custom_pages\components\PageUrlRule does not exist'

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [humhub/humhub#2876]
### What is the expected result?
[Manual update](http://docs.humhub.org/admin-updating.html) should work.

### What do you get instead?
```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Suriyaa>cd C:\Server\wamp64\www\~JDSF\sn\protected

C:\Server\wamp64\www\~JDSF\sn\protected>php yii migrate/up --includeModuleMigrations=1
Exception 'ReflectionException' with message 'Class humhub\modules\custom_pages\components\PageUrlRule does not exist'

in C:\Server\wamp64\www\~JDSF\sn\protected\vendor\yiisoft\yii2\di\Container.php:424

Stack trace:
#0 C:\Server\wamp64\www\~JDSF\sn\protected\vendor\yiisoft\yii2\di\Container.php(424): ReflectionClass->__construct('humhub\\modules\\...')
#1 C:\Server\wamp64\www\~JDSF\sn\protected\vendor\yiisoft\yii2\di\Container.php(364): yii\di\Container->getDependencies('humhub\\modules\\...')
#2 C:\Server\wamp64\www\~JDSF\sn\protected\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('humhub\\modules\\...', Array, Array)
#3 C:\Server\wamp64\www\~JDSF\sn\protected\vendor\yiisoft\yii2\BaseYii.php(348): yii\di\Container->get('humhub\\modules\\...', Array, Array)
#4 C:\Server\wamp64\www\~JDSF\sn\protected\vendor\yiisoft\yii2\web\UrlManager.php(248): yii\BaseYii::createObject(Array)
#5 C:\Server\wamp64\www\~JDSF\sn\protected\vendor\yiisoft\yii2\web\UrlManager.php(215): yii\web\UrlManager->buildRules(Array)
#6 C:\Server\wamp64\www\~JDSF\sn\protected\humhub\components\ModuleManager.php(146): yii\web\UrlManager->addRules(Array, false)
#7 C:\Server\wamp64\www\~JDSF\sn\protected\humhub\components\ModuleManager.php(88): humhub\components\ModuleManager->register('C:\\Server\\wamp6...', Array)
#8 C:\Server\wamp64\www\~JDSF\sn\protected\humhub\components\bootstrap\ModuleAutoLoader.php(51): humhub\components\ModuleManager->registerBulk(Array)
#9 C:\Server\wamp64\www\~JDSF\sn\protected\vendor\yiisoft\yii2\base\Application.php(320): humhub\components\bootstrap\ModuleAutoLoader->bootstrap(Object(humhub\components\console\Application))
#10 C:\Server\wamp64\www\~JDSF\sn\protected\vendor\yiisoft\yii2\base\Application.php(272): yii\base\Application->bootstrap()
#11 C:\Server\wamp64\www\~JDSF\sn\protected\vendor\yiisoft\yii2\console\Application.php(124): yii\base\Application->init()
#12 C:\Server\wamp64\www\~JDSF\sn\protected\humhub\components\console\Application.php(35): yii\console\Application->init()
#13 C:\Server\wamp64\www\~JDSF\sn\protected\vendor\yiisoft\yii2\base\Object.php(107): humhub\components\console\Application->init()
#14 C:\Server\wamp64\www\~JDSF\sn\protected\vendor\yiisoft\yii2\base\Application.php(205): yii\base\Object->__construct(Array)
#15 C:\Server\wamp64\www\~JDSF\sn\protected\vendor\yiisoft\yii2\console\Application.php(89): yii\base\Application->__construct(Array)
#16 C:\Server\wamp64\www\~JDSF\sn\protected\yii(28): yii\console\Application->__construct(Array)
#17 {main}

C:\Server\wamp64\www\~JDSF\sn\protected>
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.1.2 to 1.2.4
| PHP version      | 5.6.16
| Operating system | Windows 10

**Comment by githubjeka** [comment]
Problem in `modules\custom_pages` not in HumHub
