### ISSUE TITLE
[1.3-dev] Missing required parameters: section

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2900]
```
yii\web\BadRequestHttpException: Missing required parameters: section in protected/vendor/yiisoft/yii2/web/Controller.php:149
Stack trace:
#0 protected/vendor/yiisoft/yii2/base/InlineAction.php(51): yii\web\Controller->bindActionParams(Object(yii\base\InlineAction), Array)
#1 protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#2 protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('open', Array)
#3 protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('admin/space/ope...', Array)
#4 protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#5 index.php(24): yii\base\Application->run()
#6 {main}
```

**Comment by buddh4** [comment]
How to reproduce?

**Comment by acs-ferreira** [comment]
Sorry, no idea. It has been logged, i've just posted it :(

**Comment by buddh4** [comment]
Seems to be thrown for [this](https://github.com/humhub/humhub/blob/v1.3-dev/protected/humhub/modules/admin/controllers/SpaceController.php#L77) action.
