### ISSUE TITLE
Export users CSV/XLSX

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2964]
Using latest master.
PR : #2948 by @danielkesselberg

If the folder "/**protected/runtime/data_export/**" is not created (manually):

Exporting XLSX:

```
yii\base\ErrorException: ZipArchive::close(): Failure to create temporary file: No such file or directory in /protected/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php:374
Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError(2, 'ZipArchive::clo...', '/srv/users/ekin...', 374, Array)
#1 /protected/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php(374): ZipArchive->close()
#2 /protected/humhub/components/export/ExportResult.php(114): PhpOffice\PhpSpreadsheet\Writer\Xlsx->save('/srv/users/ekin...')
#3 /protected/humhub/components/export/ExportResult.php(128): humhub\components\export\ExportResult->saveAs('/srv/users/ekin...')
#4 /protected/humhub/modules/admin/controllers/UserController.php(276): humhub\components\export\ExportResult->send()
#5 [internal function]: humhub\modules\admin\controllers\UserController->actionExport('xlsx')
#6 /protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#8 /protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('export', Array)
#9 /protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('admin/user/expo...', Array)
#10 /protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#11 /index.php(24): yii\base\Application->run()
#12 {main} 
```

Exporting CSV:

```
yii\base\ErrorException: fopen(protected/runtime/data_export/15167118905a672fd2a7a0c2.45896209): failed to open stream: No such file or directory in protected/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Csv.php:95
Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError(2, 'fopen(/srv/user...', '/srv/users/ekin...', 95, Array)
#1 protected/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Csv.php(95): fopen('/srv/users/ekin...', 'wb+')
#2 protected/humhub/components/export/ExportResult.php(114): PhpOffice\PhpSpreadsheet\Writer\Csv->save('/srv/users/ekin...')
#3 protected/humhub/components/export/ExportResult.php(128): humhub\components\export\ExportResult->saveAs('/srv/users/ekin...')
#4 protected/humhub/modules/admin/controllers/UserController.php(276): humhub\components\export\ExportResult->send()
#5 [internal function]: humhub\modules\admin\controllers\UserController->actionExport('csv')
#6 protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#8 protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('export', Array)
#9 protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('admin/user/expo...', Array)
#10 protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#11 index.php(24): yii\base\Application->run()
#12 {main}
```

**Comment by acs-ferreira** [comment]
Fixed by https://github.com/humhub/humhub/commit/01221851e4a5b25ceebe0bad25ef9c27b2ddc90f

**Comment by danielkesselberg** [comment]
Thank you! I thought I forgot something ;-)
