### ISSUE TITLE
Internal server errors

### ISSUE THREAD

**Issue by ellingen** [humhub/humhub#2984]
### What steps will reproduce the problem?

With a fresh install, as soon as I’m registering a second user, HumHub is intermittently causing Internal Server errors.

### What is the expected result?

No errors.

### What do you get instead?

From PHP error logs:

```
[05-Feb-2018 16:46:31] WARNING: [pool www] child 4187 said into stderr: "NOTICE: PHP message: An Error occurred while handling another error:"
[05-Feb-2018 16:46:31] WARNING: [pool www] child 4187 said into stderr: "PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Connection.php:646"
[05-Feb-2018 16:46:31] WARNING: [pool www] child 4187 said into stderr: "Stack trace:"
[05-Feb-2018 16:46:31] WARNING: [pool www] child 4187 said into stderr: "#0 /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Connection.php(646): PDO->__construct('mysql:host=loca...', 'linden90', 'xOPHYSXkE6xvuGm...', NULL)"
[05-Feb-2018 16:46:31] WARNING: [pool www] child 4187 said into stderr: "#1 /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Connection.php(579): yii\db\Connection->createPdoInstance()"
[05-Feb-2018 16:46:31] WARNING: [pool www] child 4187 said into stderr: "#2 /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Connection.php(928): yii\db\Connection->open()"
[05-Feb-2018 16:46:31] WARNING: [pool www] child 4187 said into stderr: "#3 /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Connection.php(915): yii\db\Connection->getMasterPdo()"
[05-Feb-2018 16:46:31] WARNING: [pool www] child 4187 said into stderr: "#4 /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Schema.php(483): yii\db\Connection->getSlavePdo()"
[05-Feb-2018 16:46:31] WARNING: [pool www] child 4187 said into stderr: "#5 /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Connection.php(824): yii\db\Schema->quoteValue('TopMenuWidget')"
[05-Feb-2018 16:46:31] WARNING: [pool www] child 4187 said into stderr: "#6 /var/www/virtua..."
````

From Apache error logs:
```
[Mon Feb 05 16:46:31 2018] [error] [pid 18987] mod_proxy_fcgi.c(834): [client 91.65.0.0] AH01071: Got error 'PHP message: An Error occurred while handling another error:\nPDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Connection.php:646\nStack trace:\n#0 /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Connection.php(646): PDO->__construct('mysql:host=loca...', 'linden90', 'XXXXXXXXXX...', NULL)\n#1 /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Connection.php(579): yii\\db\\Connection->createPdoInstance()\n#2 /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Connection.php(928): yii\\db\\Connection->open()\n#3 /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Connection.php(915): yii\\db\\Connection->getMasterPdo()\n#4 /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Schema.php(483): yii\\db\\Connection->getSlavePdo()\n#5 /var/www/virtual/linden90/html/protected/vendor/yiisoft/yii2/db/Connection.php(824): yii\\db\\Schema->quoteValue('TopMenuWidget')\n#6 /var/www/virtual/linden...\n'
```

FWIW, when reloading the page, it almost always works again. But the error still occurs far too frequently in order for HumHub to still be usable.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| Maria DB | 10.1.30
| PHP version      | 7.1.13
| Operating system | CentOS 7

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by danielkesselberg** [comment]
This looks like an issue with your sql connection.

**Comment by ellingen** [comment]
Thanks, Daniel! Any ideas of how I could investigate this further? Haven’t experienced any SQL connection issues with this web host before so not sure what to do about it?

**Comment by danielkesselberg** [comment]
Could you try 127.0.0.1 as database host instead of localhost? What kind of server/webspace is this?

**Comment by ellingen** [comment]
The [docs](https://manual.uberspace.de/en/database-mysql.html?highlight=mysql) advise for `localhost` but I changed it to `127.0.0.1`, it’s only happening intermittently and not when there is only one user (me) registered with HumHub. It’s hosted with [Uberspace](https://manual.uberspace.de) which is usually very smooth.

**Comment by ellingen** [comment]
Unfortunately the error occured once more, after using `127.0.0.1` for the DB host. 
I’ve enabled APC(u) caching, it was "File" before. Maybe that helps?

**Comment by danielkesselberg** [comment]
I dont think so. The real problem is hidden behind another problem ;-) While rendering the error view the layout tries to render the TopMenuWidget. If the previous error (the real one :D) has something todo with an sql connection it fails again while rendering the TopMenuWidget. In fact is a bit trickier to find the problem. 

@luke- i guess we need a reduced layout/view for cases like this.

**Comment by buddh4** [comment]
Can you check if there is a more detailed error stack e.g. in "Administration ->Information -> Logging"

**Comment by ellingen** [comment]
@buddh4 There’s nothing in there, unfortunately. Do I have to put the app back from production into development again for to enable logging?

**Comment by danielkesselberg** [comment]
Could you please edit this file: https://github.com/humhub/humhub/blob/master/protected/humhub/views/layouts/main.php

Please look for: `<?= \humhub\widgets\TopMenu::widget(); ?>`
and replace with `<?php try { echo \humhub\widgets\TopMenu::widget(); } catch (\Exception $e) { echo $e->getMessage(); } ?> `

**Comment by ellingen** [comment]
@danielkesselberg Thanks, I did that. I guess now I have to wait for it to error again and then check the logs?

**Comment by danielkesselberg** [comment]
Exactly

**Comment by ellingen** [comment]
FWIW, unfortunately (or fortunately ;-)) it no longer errors.
