### ISSUE TITLE
IntlException: Constructor failed

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3065]
I just don't know why this is happening, can't easily reproduce.
I just have this stack in logs:
```
IntlException: Constructor failed in /protected/vendor/yiisoft/yii2/i18n/Formatter.php:608

Stack trace: #0 /protected/vendor/yiisoft/yii2/i18n/Formatter.php(608): IntlDateFormatter->__construct('en-US', 2, -1, 'America/New_Yor...', NULL)
#1 /protected/vendor/yiisoft/yii2/i18n/Formatter.php(493): yii\i18n\Formatter->formatDateTimeValue('2018-03-02T11:5...', 'medium', 'date')
#2 /protected/humhub/widgets/TimeAgo.php(102): yii\i18n\Formatter->asDate('2018-03-02T11:5...', 'medium')
#3 /protected/humhub/widgets/TimeAgo.php(70): humhub\widgets\TimeAgo->getFullDateTime()
#4 /protected/humhub/widgets/TimeAgo.php(51): humhub\widgets\TimeAgo->renderTimeAgo()
#5 /protected/vendor/yiisoft/yii2/base/Widget.php(139): humhub\widgets\TimeAgo->run()
#6 /protected/humhub/modules/activity/views/layouts/web.php(50): yii\base\Widget::widget(Array)
#7 /protected/vendor/yiisoft/yii2/base/View.php(330): require('/srv/users/ekin...')
#8 /protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/srv/users/ekin...', Array)
#9 /protected/humhub/components/rendering/LayoutRenderer.php(60): yii\base\View->renderFile('/srv/users/ekin...', Array, Object(humhub\modules\space\activities\MemberAdded))
#10 /protected/humhub/modules/activity/components/ActivityWebRenderer.php(52): humhub\components\rendering\LayoutRenderer->render(Object(humhub\modules\space\activities\MemberAdded), Array)
#11 /protected/humhub/modules/activity/models/Activity.php(116): humhub\modules\activity\components\ActivityWebRenderer->render(Object(humhub\modules\space\activities\MemberAdded))
#12 /protected/humhub/modules/stream/actions/Stream.php(324): humhub\modules\activity\models\Activity->getWallOut(Array)
#13 /protected/humhub/modules/stream/actions/Stream.php(358): humhub\modules\stream\actions\Stream::renderEntry(Object(humhub\modules\activity\models\Activity), Array)
#14 /protected/humhub/modules/stream/actions/Stream.php(233): humhub\modules\stream\actions\Stream::getContentResultEntry(Object(humhub\modules\content\models\Content))
#15 [internal function]: humhub\modules\stream\actions\Stream->run()
#16 /protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#17 /protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array)
#18 /protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('stream', Array)
#19 /protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('dashboard/dashb...', Array)
#20 /protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#21 /index.php(27): yii\base\Application->run()
#22 {main} 
```

**Comment by buddh4** [comment]
Hmm the full date string would be interesting "'2018-03-02T11:5...'" which Intl version are you running?

**Comment by acs-ferreira** [comment]
```
PHP - INTL Extension - ICU Version (55.1)
PHP - INTL Extension - ICU Data Version (55.1) 
```

**Comment by acs-ferreira** [comment]
Users that have this problem see an EMPTY Dashboard, no Spaces, etc...and each action of them triggers that error.
