### ISSUE TITLE
Standard vanilla web installation fails to show users' posts

### ISSUE THREAD

**Issue by rhisss** [humhub/humhub#3073]
**What steps will reproduce the problem?**
Fresh install of latest 1.2.4 via the web installer. Not in debug mode. Cache clean. No extra modules. Create an user ABC (first name and last name not set, as user creation when submitted leads to a white screen, and when refreshed user is ABC already created without first and last names)

**What is the expected result?**
user ABC will be able to post and see status message or any other content in his stream and elsewhere without any error message.

 **What do you get instead?**
user ABC  sees "Stream could not be initialized!" and below the page "An unexpected server error occurred. If this keeps happening, please contact a site administrator." She does not see the message she posted in her stream.

Additional info
The latest activity side block does show user ABC's status messages. The site admin, when logged in as one of the pre-existing default user can post status message but gets ""An unexpected server error occurred. If this keeps happening, please contact a site administrator." first, and then when the page is refreshed manually is able to see the status post.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | 5.6.33
| Operating system | Lamp stack, `siteground` host

Standard webhosting and installing via web : gives above error
Softaculous install : gives above error after any module is added
The PHP versions and pre-requisites are apparently at par with those at humhub
So this is confusing and depressing as to why this should happen, when under same conditions other installs of Elgg / Idno Known etc occur without any problem.
If admin access and password needed please let me know - this bug or whatever it is should be immediately killed.

>  error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
`exception 'yii\base\ErrorException' with message 'Argument 1 passed to humhub\libs\Html::containerLink() must be an instance of humhub\modules\content\components\ContentContainerActiveRecord, null given, called in /home/mmarchiv/public_html/hum/protected/humhub/modules/content/widgets/views/wallEntry.php on line 72 and defined' in /home/mmarchiv/public_html/hum/protected/humhub/libs/Html.php:95 Stack trace: #0 /home/mmarchiv/public_html/hum/protected/humhub/libs/Html.php(95): yii\base\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/mmarchiv/...', 95, Array) #1 /home/mmarchiv/public_html/hum/protected/humhub/modules/content/widgets/views/wallEntry.php(72): humhub\libs\Html::containerLink(NULL) #2 /home/mmarchiv/public_html/hum/protected/vendor/yiisoft/yii2/base/View.php(330): require('/home/mmarchiv/...') #3 /home/mmarchiv/public_html/hum/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/mmarchiv/...', Array) #4 /home/mmarchiv/public_html/hum/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/mmarchiv/...', Array, Object(humhub\modules\post\widgets\WallEntry)) #5 /home/mmarchiv/public_html/hum/protected/vendor/yiisoft/yii2/base/Widget.php(234): yii\base\View->render('@humhub/modules...', Array, Object(humhub\modules\post\widgets\WallEntry)) #6 /home/mmarchiv/public_html/hum/protected/humhub/modules/content/widgets/WallEntry.php(225): yii\base\Widget->render('@humhub/modules...', Array) #7 /home/mmarchiv/public_html/hum/protected/humhub/modules/content/components/ContentActiveRecord.php(283): humhub\modules\content\widgets\WallEntry->renderWallEntry() #8 /home/mmarchiv/public_html/hum/protected/humhub/modules/stream/actions/Stream.php(324): humhub\modules\content\components\ContentActiveRecord->getWallOut(Array) #9 /home/mmarchiv/public_html/hum/protected/humhub/modules/stream/actions/Stream.php(358): humhub\modules\stream\actions\Stream::renderEntry(Object(humhub\modules\post\models\Post), false) #10 /home/mmarchiv/public_html/hum/protected/humhub/modules/stream/actions/Stream.php(233): humhub\modules\stream\actions\Stream::getContentResultEntry(Object(humhub\modules\content\models\Content)) #11 [internal function]: humhub\modules\stream\actions\Stream->run() #12 /home/mmarchiv/public_html/hum/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array) #13 /home/mmarchiv/public_html/hum/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array) #14 /home/mmarchiv/public_html/hum/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('stream', Array) #15 /home/mmarchiv/public_html/hum/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('dashboard/dashb...', Array) #16 /home/mmarchiv/public_html/hum/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #17 /home/mmarchiv/public_html/hum/index.php(25): yii\base\Application->run() #18 {main} `

**Comment by buddh4** [comment]
You mean posting a post on his own wall or on a space?
