### ISSUE TITLE
Error while watching Notifications

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3132]
```
humhub\modules\calendar\interfaces\FilterNotSupportedException: Global filter not supported for this query in /public/protected/modules/calendar/integration/BirthdayCalendarQuery.php:70
Stack trace:
#0 /public/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(682): humhub\modules\calendar\integration\BirthdayCalendarQuery->filterDashboard()
#1 /public/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(578): humhub\modules\calendar\interfaces\AbstractCalendarQuery->setupFilters()
#2 /public/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(561): humhub\modules\calendar\interfaces\AbstractCalendarQuery->setupQuery()
#3 /public/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(141): humhub\modules\calendar\interfaces\AbstractCalendarQuery->all()
#4 /public/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(150): humhub\modules\calendar\interfaces\AbstractCalendarQuery::findForFilter(Object(DateTime), Object(DateTime), NULL, Array, '5')
#5 /public/protected/modules/calendar/integration/BirthdayCalendar.php(57): humhub\modules\calendar\interfaces\AbstractCalendarQuery::findForEvent(Object(humhub\modules\calendar\interfaces\CalendarItemsEvent))
#6 /public/protected/modules/calendar/Events.php(35): humhub\modules\calendar\integration\BirthdayCalendar::addItems(Object(humhub\modules\calendar\interfaces\CalendarItemsEvent))
#7 [internal function]: humhub\modules\calendar\Events::onFindCalendarItems(Object(humhub\modules\calendar\interfaces\CalendarItemsEvent))
#8 /public/protected/vendor/yiisoft/yii2/base/Event.php(220): call_user_func(Array, Object(humhub\modules\calendar\interfaces\CalendarItemsEvent))
#9 /public/protected/vendor/yiisoft/yii2/base/Component.php(553): yii\base\Event::trigger('humhub\\modules\\...', 'findItems', Object(humhub\modules\calendar\interfaces\CalendarItemsEvent))
#10 /public/protected/modules/calendar/interfaces/CalendarService.php(110): yii\base\Component->trigger('findItems', Object(humhub\modules\calendar\interfaces\CalendarItemsEvent))
#11 /public/protected/modules/calendar/interfaces/CalendarService.php(148): humhub\modules\calendar\interfaces\CalendarService->getCalendarItems(Object(DateTime), Object(DateTime), Array, NULL, '5')
#12 /public/protected/modules/calendar/widgets/UpcomingEvents.php(40): humhub\modules\calendar\interfaces\CalendarService->getUpcomingEntries(NULL, '31', '5')
#13 /public/protected/humhub/components/Widget.php(57): humhub\modules\calendar\widgets\UpcomingEvents->run()
#14 /public/protected/humhub/widgets/BaseStack.php(85): humhub\components\Widget::widget(Array)
#15 /public/protected/vendor/yiisoft/yii2/base/Widget.php(139): humhub\widgets\BaseStack->run()
#16 /public/themes/myTheme/views/dashboard/dashboard/index.php(20): yii\base\Widget::widget(Array)
#17 /public/protected/vendor/yiisoft/yii2/base/View.php(330): require('/srv/users/ekin...')
#18 /public/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/srv/users/ekin...', Array)
#19 /public/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/srv/users/ekin...', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) 
#20 /public/protected/vendor/yiisoft/yii2/base/Controller.php(381): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController))
#21 /public/protected/humhub/modules/dashboard/controllers/DashboardController.php(64): yii\base\Controller->render('index', Array)
#22 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex()
#23 /public/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#24 /public/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#25 /public/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('', Array)
#26 /public/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('dashboard/dashb...', Array)
#27 /public/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#28 /public/index.php(27): yii\base\Application->run()
#29 {main} 
```

**Comment by acs-ferreira** [comment]
Fixed by https://github.com/humhub/humhub-modules-calendar/commit/675b6f86cfb9dc285881083be931b4d084986d97
