### ISSUE TITLE
Errors with the Notifications

### ISSUE THREAD

**Issue by Richies97** [humhub/humhub#3194]
### What steps will reproduce the problem?

Some users get this Error when scrolling down in the notifications and the older ones should load, and some users just can't open the notifications but get the same error.

### What is the expected result?

Open Notification bar like this (Some users don't have any problems):

![notifacation_1](https://user-images.githubusercontent.com/11535546/42209092-1ae566e6-7eae-11e8-8a19-b43ce4267ea1.PNG)

### What do you get instead?

Some users get this  empty Notification bar:

![notifacation_2](https://user-images.githubusercontent.com/11535546/42212860-9a5bacce-7eb7-11e8-8467-d922ccdd8db1.PNG)

And some users just get the error on scrolling down to older Notifications

But both type of errors lead to this what you so in the background if you click on "Alle Benachrichtigungen anzeigen"

Additionally we also get this in the HumHub Log also with both types of users:

`Error: Call to a member function getUrl() on null in our/Path/protected/humhub/modules/user/notifications/Followed.php:45 Stack trace: #0 our/Path/protected/humhub/components/SocialActivity.php(148): humhub\modules\user\notifications\Followed->getUrl() #1 our/Path/protected/humhub/modules/notification/components/BaseNotification.php(138): humhub\components\SocialActivity->getViewParams(Array) #2 our/Path/protected/humhub/components/rendering/ViewPathRenderer.php(69): humhub\modules\notification\components\BaseNotification->getViewParams(Array) #3 our/Path/protected/humhub/modules/notification/components/BaseNotification.php(349): humhub\components\rendering\ViewPathRenderer->render(Object(humhub\modules\user\notifications\Followed)) #4 our/Path/protected/humhub/modules/notification/controllers/ListController.php(48): humhub\modules\notification\components\BaseNotification->render() #5 [internal function]: humhub\modules\notification\controllers\ListController->actionIndex() #6 our/Path/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #7 our/Path/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #8 
our/Path/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('', Array) #9 
our/Path/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('notification/li...', Array) #10 our/Path/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #11 our/Path/index.php(25): yii\base\Application->run() #12 {main}`

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.7
| PHP version      |  7.1

**Comment by Richies97** [comment]
Even after the just released 1.2.8 version of Humhub we still got this problem.

**Comment by Felli** [comment]
Most likely do to custom theme, sometimes you have to add a view overwrite for such things.

**Comment by Richies97** [comment]
Think the problem had something to do with my double users with I could fix with #2794 . THANKS.

**Comment by Richies97** [comment]
Again after a few days we get the same issue. But now the rebuild doesn't word for us.

Some users get this:

![notifacation_3](https://user-images.githubusercontent.com/11535546/42441754-3a23786c-8369-11e8-9274-afd5f68023c5.PNG)

And this Error-message if you click on the error on the bottom of the screen.

`
{

    "url": "/HH/index.php?r=notification%2Flist",

    "status": 500,

    "response": "",

    "textStatus": "error",

    "xhr": {

        "readyState": 4,

        "responseText": "",

        "status": 500,

        "statusText": "error"

    },

    "dataType": "html",

    "html": "",

    "error": {},

    "errorThrown": "",

    "validationError": false

}
`

**Comment by heikostueber** [comment]
Hi,

I've the same Problem with the 1.3 beta.

It seems to be a issue with the user rights, because as admin there is no issue. 
Have anybody a idea how to fix?

**Comment by buddh4** [comment]
Try running : `php yii integrity/run` within your protected directory. It seems you have inconsistent data.

**Comment by Richies97** [comment]
Running this doesn't fix the problem. But i found the inconsistent data in the database notification table. I hope that, something like this doesn't happen too often cause i don't think i can find any error in the database.

**Comment by buddh4** [comment]
We'll have to add the integrity check for this case. And also integrate an automatic integrity check for notifications into the cron.

**Comment by Richies97** [comment]
The additional information i can give to you is that the table that was inconsistent was `notification` and especially the column `originator_user_id` where sometimes the field was `NULL` even if there was a contributor

**Comment by luke-** [comment]
Hmm, we can't find any situation where the originator_user_id is set to "NULL".
Anyway I've added an integrity check for a valid originator_id.

**Comment by Richies97** [comment]
Well it worked very well for a longer time now, but again we have the notification bug. This time the error is not the `originator_user_id`. If i find the piece of data i will inform you as soon as possible.

**Comment by dakur** [comment]
I don't know, if it is the same bug, but after iteratively upgrade from 1.2.3 to 1.3.0, I am not able to see any notifications. The popup is empty, there is the same error as @Richies97 described at the bottom of the page and in Logs, there is: `exception 'yii\base\ErrorException' with message 'Class 'Yii\db\IntegrityException' not found' in /var/www/humhub/protected/humhub/components/behaviors/PolymorphicRelation.php:70 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}`

I've already run `integrity/run` task, it proposed me some deletions, I accepted it, but still the bug appears. The only thing left in integrity check is ` Warning: User with id 26 has no profile record!` which I have no idea what does it mean and what to do with it.

**Comment by danielkesselberg** [comment]
@dakur could you change 
`use Yii\db\IntegrityException;` to `use yii\db\IntegrityException;` in protected/humhub/components/behaviors/PolymorphicRelation.php line 18 and see if it works?

**Comment by dakur** [comment]
@danielkesselberg Partially. Now the popup is OK, but if I click `Display all notifications`, it display e500 page and logs: `exception 'yii\db\IntegrityException' with message 'Call to an inconsistent polymorphic relation detected on humhub\modules\notification\models\Notification (source_class : source_pk)' in /var/www/humhub/protected/humhub/components/behaviors/PolymorphicRelation.php:70 Stack trace: #0 [internal function]: humhub\components\behaviors\PolymorphicRelation->getPolymorphicRelation() #1 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php(297): call_user_func_array(Array, Array) #2 /var/www/humhub/protected/humhub/modules/notification/models/Notification.php(118): yii\base\Component->__call('getPolymorphicR...', Array) #3 /var/www/humhub/protected/humhub/modules/notification/models/Notification.php(118): humhub\modules\notification\models\Notification->getPolymorphicRelation() #4 /var/www/humhub/protected/humhub/modules/notification/controllers/OverviewController.php(79): humhub\modules\notification\models\Notification->getBaseModel() #5 [internal function]: humhub\modules\notification\controllers\OverviewController->actionIndex() #6 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #7 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #9 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('notification/ov...', Array) #10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #11 /var/www/humhub/index.php(25): yii\base\Application->run() #12 {main} Additional Information: Array ( ) `

**Comment by danielkesselberg** [comment]
Could you run `integrity/run` again?

**Comment by dakur** [comment]
Yep, nothing changed.

**Comment by dakur** [comment]
`bool(true) NULL string(12) "source_class" string(9) "source_pk"`

Or maybe you would not be lazy and try it on your own? :-) I can not bring down the production all the time. ;-)

**Comment by danielkesselberg** [comment]
Im still unsure howto reproduce this issue. I prepared a pr with a possible patch but this is only a workaround and i dont what breaks with this: https://github.com/humhub/humhub/pull/3239.patch

You can apply this patch with `patch -p1 3239.patch` in humhub root directory.

**Comment by danielkesselberg** [comment]
@dakur @Richies97 could you update to humhub 1.3.1 and run integrity/run again? (like @luke- said in https://github.com/humhub/humhub/pull/3239#issuecomment-411627662 integrity/run should detect and fix this case now).

**Comment by informatico-madrid** [comment]
@dakur you have calendar module enabled? i have same issue and i think meaby this its related with calendar module

**Comment by danielkesselberg** [comment]
Are u running 1.3.1? Does it work after integrity/run?

**Comment by blu-IT** [comment]
I also have the problem regarding notifications. Cron jobs are configured and running, integrity/run was fine and now I wanted to test if I can diable calendar - but when I want to do this, HumHub warns me that all Calendar data will be lost. That's not good. I just want to disable for a test, but not remove the calendar addon.
