### ISSUE TITLE
Activity stream in right column for a given space gives ajax Server error. 

### ISSUE THREAD

**Issue by olekrisek** [humhub/humhub#3216]
### What steps will reproduce the problem?
Select a space with some activity, look in the right column under "Activities" Its a running Ajax loading - and a error notice in the footer. 
### What is the expected result?
List of what members have added. 

### What do you get instead?
a running Ajax loading - and a error notice in the footer. 

### Additional info
The error log shows this message: 
```
"url": "/index.php?r=activity%2Fstream%2Fstream&mode=activity&cguid=c5cb4160-0c5d-4ace-8f6c-d35bf5b7e6ad",
    "status": 500,
    "response": {
        "name": "PHP Warning",
        "message": "The use statement with non-compound name 'Yii' has no effect",
        "code": 2,
        "type": "yii\\base\\ErrorException",
        "file": "/var/www/clients/client3/web17/web/protected/humhub/modules/space/activities/views/memberAdded.php",
        "line": 5,
        "stack-trace": [
            "#0 /var/www/clients/client3/web17/web/protected/vendor/yiisoft/yii2/base/View.php(336): yii\\base\\ErrorHandler->handleError(2, 'The use stateme...', '/var/www/client...', 5, Array)",
            "#1 /var/www/clients/client3/web17/web/protected/vendor/yiisoft/yii2/base/View.php(336): require()",
            "#2 /var/www/clients/client3/web17/web/protected/vendor/yiisoft/yii2/base/View.php(254): yii\\base\\View->renderPhpFile('/var/www/client...', Array)",
            "#3 /var/www/clients/client3/web17/web/protected/humhub/components/rendering/ViewPathRenderer.php(83): yii\\base\\View->renderFile('/var/www/client...', Array, Object(humhub\\modules\\space\\activities\\MemberAdded))",
            "#4 /var/www/clients/client3/web17/web/protected/humhub/components/rendering/LayoutRenderer.php(53): humhub\\components\\rendering\\ViewPathRenderer->renderView(Object(humhub\\modules\\space\\activities\\MemberAdded), Array)",
            "#5 /var/www/clients/client3/web17/web/protected/humhub/modules/activity/components/ActivityWebRenderer.php(52): humhub\\components\\rendering\\LayoutRenderer->render(Object(humhub\\modules\\space\\activities\\MemberAdded), Array)",
            "#6 /var/www/clients/client3/web17/web/protected/humhub/modules/activity/models/Activity.php(116): humhub\\modules\\activity\\components\\ActivityWebRenderer->render(Object(humhub\\modules\\space\\activities\\MemberAdded))",
            "#7 /var/www/clients/client3/web17/web/protected/humhub/modules/stream/actions/Stream.php(316): humhub\\modules\\activity\\models\\Activity->getWallOut(Array)",
            "#8 /var/www/clients/client3/web17/web/protected/humhub/modules/stream/actions/Stream.php(350): humhub\\modules\\stream\\actions\\Stream::renderEntry(Object(humhub\\modules\\activity\\models\\Activity), Array)",
            "#9 /var/www/clients/client3/web17/web/protected/humhub/modules/stream/actions/Stream.php(225): humhub\\modules\\stream\\actions\\Stream::getContentResultEntry(Object(humhub\\modules\\content\\models\\Content))",
            "#10 [internal function]: humhub\\modules\\stream\\actions\\Stream->run()",
            "#11 /var/www/clients/client3/web17/web/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)",
            "#12 /var/www/clients/client3/web17/web/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\Action->runWithParams(Array)",
            "#13 /var/www/clients/client3/web17/web/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller->runAction('stream', Array)",
            "#14 /var/www/clients/client3/web17/web/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction('activity/stream...', Array)",
            "#15 /var/www/clients/client3/web17/web/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
            "#16 /var/www/clients/client3/web17/web/index.php(25): yii\\base\\Application->run()",
            "#17 {main}"
        ]

```
| Q                | A
| ---------------- | ---
| HumHub version   | 1.3. Beta
| PHP version      | 7.0
| Operating system | Debian 9

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by olekrisek** [comment]
I am going to upload a pull request for the fix of this now.
