### ISSUE TITLE
The table does not exist: queue_exclusive

### ISSUE THREAD

**Issue by chrisdecker1201** [humhub/humhub#3233]
### What steps will reproduce the problem?
Upgrade from 1.2.x to 1.3.0
Then add a post in a stream.

### What is the expected result?
No error message.

### What do you get instead?
An error message with the following text:
The table does not exist: queue_exclusive

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3
| PHP version      | 7.0.30
| Operating system | Ubuntu 16.04 LTS

Also the sites Administration -> Information -> Database and Cronjobs are leads to an error.

Here the full error message.
~~~
yii\base\InvalidConfigException: The table does not exist: queue_exclusive in /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php:382 Stack trace: #0 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(210): yii\db\ActiveRecord::getTableSchema() #1 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(190): yii\db\ActiveRecord::filterCondition(Array) #2 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(112): yii\db\ActiveRecord::findByCondition(Array) #3 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/humhub/modules/queue/helpers/QueueHelper.php(28): yii\db\BaseActiveRecord::findOne(Array) #4 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/humhub/modules/queue/Events.php(61): humhub\modules\queue\helpers\QueueHelper::isQueued(Object(humhub\modules\search\jobs\DeleteDocument)) #5 [internal function]: humhub\modules\queue\Events::onQueueBeforePush(Object(yii\queue\PushEvent)) #6 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(yii\queue\PushEvent)) #7 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('yii\\queue\\Queue', 'beforePush', Object(yii\queue\PushEvent)) #8 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2-queue/src/Queue.php(150): yii\base\Component->trigger('beforePush', Object(yii\queue\PushEvent)) #9 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/humhub/modules/content/Events.php(145): yii\queue\Queue->push(Object(humhub\modules\search\jobs\DeleteDocument)) #10 [internal function]: humhub\modules\content\Events::onContentActiveRecordDelete(Object(yii\base\Event)) #11 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(yii\base\Event)) #12 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\modules\\...', 'afterDelete', Object(yii\base\Event)) #13 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1032): yii\base\Component->trigger('afterDelete') #14 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/humhub/modules/content/components/ContentActiveRecord.php(402): yii\db\BaseActiveRecord->afterDelete() #15 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(710): humhub\modules\content\components\ContentActiveRecord->afterDelete() #16 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(664): yii\db\ActiveRecord->deleteInternal() #17 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/humhub/modules/content/models/Content.php(257): yii\db\ActiveRecord->delete() #18 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(710): humhub\modules\content\models\Content->afterDelete() #19 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(664): yii\db\ActiveRecord->deleteInternal() #20 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/humhub/modules/content/controllers/ContentController.php(87): yii\db\ActiveRecord->delete() #21 [internal function]: humhub\modules\content\controllers\ContentController->actionDelete() #22 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #23 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #24 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('delete', Array) #25 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('content/content...', Array) #26 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #27 /var/www/vhosts/decker-software-solutions.de/humhub.decker-software-solutions.de/humhub/index.php(25): yii\base\Application->run() #28 {main} 
~~~

**Comment by danielkesselberg** [comment]
Could you try to run migrations from cli? There is a migration to create this table ([here](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/queue/migrations/m171027_220519_exclusive_jobs.php))

`cd protected/`
`php yii.php migrate/up --includeModuleMigrations=1`

**Comment by luke-** [comment]
How did you updated your installation?

You can also install missings migrations at: Administration -> Information -> Database

**Comment by chrisdecker1201** [comment]
I installed humhub via Webinstaller. And the link to Administration -> Information -> Database is dead/broken...

**Comment by chrisdecker1201** [comment]
I want to Administration -> Update HumHub and upgraded to 1.3. So yes I used Humhub Updater.

**Comment by chrisdecker1201** [comment]
The migration from cli did it. Thank you a lot.
