### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by exocode** [humhub/humhub#3254]
### What steps will reproduce the problem?
Search anything
### What is the expected result?
Some results
### What do you get instead?
error page
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.1 |
| PHP version      |  7.0-fpm |
| Operating system | ubuntu |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

### LOGS 

```
INFO  Sun, 19 Aug 2018 07:34:55 +0200  application $_GET = [ 'SearchForm' => [ 'keyword' => 'hessen' 'limitSpaceGuids' => '' ] ] $_SERVER = [ 'USER' => 'www-data' 'HOME' => '/var/www' 'HTTP_COOKIE' => 'cookieconsent_status=dismiss; language=035bd8f54353fda6c44bc11cfd70c5ebe4b92ba2c0af20691a1f0508e24d1eb7a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22de%22%3B%7D; _ga=GA1.2.2095624586.1534491753; _gid=GA1.2.470129112.1534491753; pm_calendar-upcoming-events-snippet=expanded; pm_panel-discordapp=expanded; pm_panel-facebook=expanded; pm_new-people-panel=expanded; pm_new-spaces-panel=expanded; pm_space-members-panel=expanded; pm_spaces-statistics-panel=expanded; pm_groups-statistics-panel=expanded; pm_getting-started-panel=expanded; PHPSESSID=h70ioogj3okm5r9tbm1dmc2vl4; _csrf=4d5d24a72ad213fdf05da122640181e7ce6c96c1179858691e8855a5d8e194afa%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22AYEdxoaAqhg_lLPX159a8mRWAVuPvFJS%22%3B%7D' 'HTTP_ACCEPT_LANGUAGE' => 'de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6,es;q=0.5,id;q=0.4,zh-CN;q=0.3,zh;q=0.2,el;q=0.1' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_REFERER' => 'https://www.mehralseins.one/search' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_HOST' => 'www.mehralseins.one' 'SCRIPT_FILENAME' => '/var/www/html/humhub/index.php' 'REDIRECT_STATUS' => '200' 'SERVER_NAME' => 'localhost' 'SERVER_PORT' => '443' 'SERVER_ADDR' => '95.216.173.28' 'REMOTE_PORT' => '65238' 'REMOTE_ADDR' => '84.113.179.246' 'SERVER_SOFTWARE' => 'nginx/1.14.0' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'HTTPS' => 'on' 'REQUEST_SCHEME' => 'https' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'DOCUMENT_ROOT' => '/var/www/html/humhub' 'DOCUMENT_URI' => '/index.php' 'REQUEST_URI' => '/search?SearchForm%5Bkeyword%5D=hessen&SearchForm%5BlimitSpaceGuids%5D=' 'SCRIPT_NAME' => '/index.php' 'CONTENT_LENGTH' => '' 'CONTENT_TYPE' => '' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'SearchForm%5Bkeyword%5D=hessen&SearchForm%5BlimitSpaceGuids%5D=' 'FCGI_ROLE' => 'RESPONDER' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1534656895.469 'REQUEST_TIME' => 1534656895 ]
ERROR  Sun, 19 Aug 2018 07:34:55 +0200  yii\base\ErrorException:8 yii\base\ErrorException: Undefined variable: lin¡kPreview in /var/www/html/humhub/protected/modules/linkpreview/widgets/views/view.php:19 Stack trace: #0 /var/www/html/humhub/protected/modules/linkpreview/widgets/views/view.php(19): yii\base\ErrorHandler->handleError(8, 'Undefined varia...', '/var/www/html/h...', 19, Array) #1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/html/h...') #2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/html/h...', Array) #3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/h...', Array, Object(humhub\modules\linkpreview\widgets\Viewer)) #4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('view', Array, Object(humhub\modules\linkpreview\widgets\Viewer)) #5 /var/www/html/humhub/protected/modules/linkpreview/widgets/Viewer.php(50): yii\base\Widget->render('view', Array) #6 /var/www/html/humhub/protected/humhub/components/Widget.php(57): humhub\modules\linkpreview\widgets\Viewer->run() #7 /var/www/html/humhub/protected/modules/linkpreview/Module.php(30): humhub\components\Widget::widget(Array) #8 [internal function]: humhub\modules\linkpreview\Module::onRichTextOutput(Object(humhub\libs\ParameterEvent)) #9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(humhub\libs\ParameterEvent)) #10 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\modules\\...', 'beforeOutput', Object(humhub\libs\ParameterEvent)) #11 /var/www/html/humhub/protected/humhub/modules/content/widgets/richtext/ProsemirrorRichText.php(165): yii\base\Component->trigger('beforeOutput', Object(humhub\libs\ParameterEvent)) #12 /var/www/html/humhub/protected/humhub/components/Widget.php(57): humhub\modules\content\widgets\richtext\ProsemirrorRichText->run() #13 [internal function]: humhub\components\Widget::widget(Array) #14 /var/www/html/humhub/protected/humhub/modules/content/widgets/richtext/RichText.php(64): call_user_func('humhub\\modules\\...', Array) #15 /var/www/html/humhub/protected/humhub/modules/content/widgets/richtext/AbstractRichText.php(230): humhub\modules\content\widgets\richtext\RichText::widget(Array) #16 /var/www/html/humhub/protected/humhub/modules/post/widgets/views/wallEntry.php(9): humhub\modules\content\widgets\richtext\AbstractRichText::output('[https://www.me...', Array) #17 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/html/h...') #18 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/html/h...', Array) #19 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/h...', Array, Object(humhub\modules\post\widgets\WallEntry)) #20 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('wallEntry', Array, Object(humhub\modules\post\widgets\WallEntry)) #21 /var/www/html/humhub/protected/humhub/modules/post/widgets/WallEntry.php(27): yii\base\Widget->render('wallEntry', Array) #22 /var/www/html/humhub/protected/humhub/modules/content/widgets/WallEntry.php(264): humhub\modules\post\widgets\WallEntry->run() #23 /var/www/html/humhub/protected/humhub/modules/content/widgets/WallEntry.php(228): humhub\modules\content\widgets\WallEntry->getWallEntryViewParams() #24 /var/www/html/humhub/protected/humhub/modules/content/components/ContentActiveRecord.php(322): humhub\modules\content\widgets\WallEntry->renderWallEntry() #25 /var/www/html/humhub/protected/humhub/modules/stream/actions/Stream.php(310): humhub\modules\content\components\ContentActiveRecord->getWallOut(Array) #26 /var/www/html/humhub/protected/humhub/modules/search/views/search/index.php(112): humhub\modules\stream\actions\Stream::renderEntry(Object(humhub\modules\post\models\Post)) #27 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/html/h...') #28 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/html/h...', Array) #29 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/h...', Array, Object(humhub\modules\search\controllers\SearchController)) #30 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('index', Array, Object(humhub\modules\search\controllers\SearchController)) #31 /var/www/html/humhub/protected/humhub/modules/search/controllers/SearchController.php(99): yii\base\Controller->render('index', Array) #32 [internal function]: humhub\modules\search\controllers\SearchController->actionIndex() #33 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #34 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #35 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('index', Array) #36 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('search/search/i...', Array) #37 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #38 /var/www/html/humhub/index.php(25): yii\base\Application->run() #39 {main}

```

**Comment by Felli** [comment]
Rebuild your search index.
```
cd /path/to/humhub/protected
php yii search/rebuild
```

**Comment by exocode** [comment]
Did this. When I search something which exists, it works, when I search something which does not exist, I get this error

**Comment by Felli** [comment]
That's rather strange, does this also happen within the HumHub [community site](https://community.humhub.com/dashboard)?

**Comment by danielkesselberg** [comment]
Could you disable link preview module and try again?

**Comment by exocode** [comment]
I deactivated at, and activated it now it works...
