### ISSUE TITLE
Notifications of new posts are not working

### ISSUE THREAD

**Issue by blu-IT** [humhub/humhub#3271]
### What steps will reproduce the problem?
After update from HumHub v. 1.2.8 to HumHub v. 1.3.1 notifications of new posts in spaces are not working any more. Nothing is send out.
Cron jobs are configured as required and I can see in the backend that they are working, but the "Reserved" counter is at 700 (background jobs). Don't know what jobs these are. 
Direct messages from member to member still work, so I don't think it is a e-mail server config problem (PHP Mail Transport). This wasn't changed/touched and fully working with v. 1.2.8 

### What is the expected result?
Notifications to other members are sent out with a new post.

### What do you get instead?
Nothing. No notification. Also desktop notifications aren't working.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.1.
| PHP version      |  5.x
| Operating system | n.a.

**Comment by Felli** [comment]
Please check #3263 & #3194

**Comment by danielkesselberg** [comment]
Here is a good starting point when updating from 1.2 to 1.3: http://docs.humhub.org/admin-updating-130.html

Did you setup cronjobs like described in http://docs.humhub.org/admin-installation-configuration.html?

**Comment by blu-IT** [comment]
Hi,

yes I did, but I found out now, that there might be a problem with the queue/run job.
I set the job verbose and saw this for two times:

```
No input file specified.
Status: 404 Not Found
X-Powered-By: PHP/5.6.31
Content-type: text/html; charset=UTF-8

No input file specified.
^CException 'Symfony\Component\Process\Exception\RuntimeException' with message 'The process has been signaled with signal "2".'

    in /kunden/548428_64711/forum-test/protected/vendor/symfony/process/Process.php:434

    Stack trace:
    #0 /kunden/548428_64711/forum-test/protected/vendor/symfony/process/Process.php(212): Symfony\Component\Process\Process->wait()
    #1 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(175): Symfony\Component\Process\Process->run(Object(Closure))
    #2 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(106): yii\queue\cli\Command->handleMessage('608', 'O:44:"humhub\mo...', '300', 246)
    #3 [internal function]: yii\queue\cli\Command->yii\queue\cli{closure}('608', 'O:44:"humhub\mo...', '300', 246)
    #4 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(136): call_user_func(Object(Closure), '608', 'O:44:"humhub\mo...', '300', 246)
    #5 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(85): yii\queue\cli\Queue->handleMessage('608', 'O:44:"humhub\mo...', '300', 246)
    #6 [internal function]: yii\queue\db\Queue->yii\queue\db{closure}(Object(yii\queue\cli\SignalLoop))
    #7 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(108): call_user_func(Object(Closure), Object(yii\queue\cli\SignalLoop))
    #8 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(94): yii\queue\cli\Queue->runWorker(Object(Closure))
    #9 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false)
    #10 [internal function]: yii\queue\db\Command->actionRun()
    #11 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
    #12 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
    #13 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('run', Array)
    #14 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array)
    #15 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array)
    #16 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array)
    #17 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
    #18 /kunden/548428_64711/forum-test/protected/yii(28): yii\base\Application->run()
    #19 {main}
```

There is a loop with this output:

```
No input file specified.
Status: 404 Not Found
X-Powered-By: PHP/5.6.31
Content-type: text/html; charset=UTF-8
```

Why this? I configured the cron jobs like in the manual and with the syntax they where running before in v.1.2.8

**Comment by danielkesselberg** [comment]
Could you change this file https://github.com/humhub/humhub/blob/1073f6b1ddbe153948484a54b993a815ae8810e6/protected/humhub/modules/installer/controllers/ConfigController.php#L518 and replace `throw new CException` with `throw new Exception`?

**Comment by danielkesselberg** [comment]
Does it work when u disable the online user module? The module looks a bit outdated.

**Comment by blu-IT** [comment]
I disabled online user module, run queue/run manually - the task took some seconds, then status of Backgound jobs -> Reserved was about 739 but jumped back to 812 after some seconds.
Started queue/run a second time, finished immediately and no status change in the Backgound jobs section. Counter of completed still at 1.

**Comment by danielkesselberg** [comment]
Any error messages?

**Comment by Felli** [comment]
Comment out the following 2 lines in [index.php](https://github.com/humhub/humhub/blob/master/index.php#L10) to disable test mode.

**Comment by blu-IT** [comment]
What also makes me wonder: 
I configured cron jobs queue/run and cron/run to run every 5 minutes, but the backend still tells me that the are run every hour and once a day. How can this be?
The old cron jobs run in v.1.2.8 have been stopped, so this can't be. Or is the time now hard coded in v.1.3.1?
Counter at reserved queue still increasing. Is there a way to check what kind of jobs are waiting there?

**Comment by blu-IT** [comment]
The documentation also says:

`Note: If you on a shared hosting environment, you may need to add the --isolated=0 option to the queue/run. e.g. /usr/bin/php /path/to/humhub/protected/yii queue/run`

My cron jobs look like this:
```
#! /bin/bash
env -i /usr/local/bin/php56 -f /mywebspace/humhub/protected/yii cron/run >/dev/null 2>&1
```

So where do I have to set the _--isolated=0_ option in the script?

Thanks!

**Comment by buddh4** [comment]
Have you read and followed the [1.3+ Install Guide](http://docs.humhub.org/admin-installation-configuration.html#cronjobs-and-asynchronous-job-processing-v13) especially regarding the queue?

**Comment by blu-IT** [comment]
@buddh4 Yes, I followed the Install Guide 1.3+
@acs-ferreira Yes, I set the two cron jobs like in the first example, according to my system paths.
I had problems to set the option _--isolated=0_ but I will try again.

**Comment by blu-IT** [comment]
OK, I updated to V. 1.3.2 hoping that this would solve my problem. 
First thing I did is using the new function "Clear queue" and got rid of 1631 jobs in reserved queue.

After that I posted a new message and 2 new jobs were displayed in the waiting queue.

My log gives me more output now:

```
Error  Sat, 08 Sep 2018 22:50:10 +0200  queue
Could not execute queued job! Message: The command "'/usr/local/bin/php5.6.31' '' 'queue/exec' '1632' '300' '1' '7913' '--color='" failed. Exit Code: 255(Unknown error) Working directory: /kunden/548428_64711/forum-test/protected Output: ================ Status: 404 Not Found X-Powered-By: PHP/5.6.31 Content-type: text/html; charset=UTF-8 No input file specified. Error Output: ================ Trace:#0 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(125): humhub\modules\queue\driver\MySQLCommand->handleMessage('1632', 'O:41:"humhub\\mo...', '300', 1) #1 [internal function]: yii\queue\cli\Command->yii\queue\cli\{closure}('1632', 'O:41:"humhub\\mo...', '300', 1) #2 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(144): call_user_func(Object(Closure), '1632', 'O:41:"humhub\\mo...', '300', 1) #3 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(84): yii\queue\cli\Queue->handleMessage('1632', 'O:41:"humhub\\mo...', '300', 1) #4 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure)) #5 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure)) #6 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker(Object(Closure)) #7 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false) #8 [internal function]: yii\queue\db\Command->actionRun() #9 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #10 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #11 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('run', Array) #12 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array) #13 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array) #14 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array) #15 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #16 /kunden/548428_64711/forum-test/protected/yii(28): yii\base\Application->run() #17 {main}
``` 

Has somebody a idea about that error?

**Comment by Felli** [comment]
In shared hosting environments, I find the following two Cron Jobs to only work.

```
* * * * * /usr/local/bin/php /home/futayuri/path/to/humhub/protected/yii queue/run

* * * * * /usr/local/bin/php /home/path/to/humhub/protected/yii cron/run
```

**Comment by luke-** [comment]
@blu-IT 

Can you please post a screenshot of your cronjob configuration?

I think there's maybe a space in there too much.
![image](https://user-images.githubusercontent.com/4736168/45278528-cdde6680-b4cd-11e8-8147-271b7d425805.png)

**Comment by blu-IT** [comment]
@luke- 

This is a screenshot of the two scripts
![script-screen](https://user-images.githubusercontent.com/13665806/45317579-b093b180-b53a-11e8-9a5f-1fcbb339ee75.png)
![script-screen-cron](https://user-images.githubusercontent.com/13665806/45317725-1d0eb080-b53b-11e8-8692-0e262ac97cae.png)

With v. 1.2.8 the script was running perfect (cron/daily & cron/hourly). Just modified it slighly to fit with v. 1.3.1/1.3.2 now...

What makes me still really wonder: My HumHub-backend tells me, that the scripts are run every hour and once a day - but I configured cron to run both scripts every 5 minutes!
So, is the time hard coded?

The jobs in the queue are marked now as "Done" (no more jobs in the reserved queue), but the notifications with new posts still don't work.

**Comment by acs-ferreira** [comment]
You should set them to run every minute (* * * * *).

For the daily time:
https://github.com/humhub/humhub/blob/7d9cc4c49f3d65bee28f2a821c8ecf4ad42d54d1/protected/humhub/config/common.php#L252

You can override it in your `config/common.php`

**Comment by blu-IT** [comment]
@acs-ferreira 

Unfortunately I can set cron jobs only to run every 5 minutes. This is the minimum time span. But that should not affect the system. The log shows every hour the error...

And 'dailyCronExecutionTime' has already been set to 18:00. Thanks!

**Comment by acs-ferreira** [comment]
Not sure about this, but in your command, can you remove the `-f` part; or try with the `-q` option instead? Just try both.

This has to do with CGI headers. These ones:
```
No input file specified.
Status: 404 Not Found
X-Powered-By: PHP/5.6.31
Content-type: text/html; charset=UTF-8
```

_(and you can also remove the `>/dev/null 2>&1`)_

**Comment by acs-ferreira** [comment]
Also, if you manually go to `/kunden/548428_64711/forum-test/protected` and then you run `./yii cron/run` and `./yii queue/run`, does it run?

**Comment by acs-ferreira** [comment]
If the above does not work, try this (copy and replace):

```
#!/bin/bash
cd /kunden/548428_64711/forum-test/protected; /usr/local/bin/php56 ./yii cron/run
```

and

```
#!/bin/bash
cd /kunden/548428_64711/forum-test/protected; /usr/local/bin/php56 ./yii queue/run
```

Hope it helps.

**Comment by blu-IT** [comment]
@acs-ferreira

OK, I tried changing the script like you suggested above. Well, it works in both ways when no job is waiting in the queue:

```
(21:49:39) [protected] ./yii queue/run
X-Powered-By: PHP/5.6.31
Content-type: text/html; charset=UTF-8

(21:50:26) [protected] ./yii cron/run
X-Powered-By: PHP/5.6.31
Content-type: text/html; charset=UTF-8
```

but when I have a new post and it is waiting in the queue, I run the commands again and get

```
(21:48:15) [protected] ./yii queue/run
Status: 404 Not Found
X-Powered-By: PHP/5.6.31
Content-type: text/html; charset=UTF-8

No input file specified.
Status: 404 Not Found
X-Powered-By: PHP/5.6.31
Content-type: text/html; charset=UTF-8

No input file specified.
X-Powered-By: PHP/5.6.31
Content-type: text/html; charset=UTF-8

(21:49:28) [protected] ./yii cron/run
X-Powered-By: PHP/5.6.31
Content-type: text/html; charset=UTF-8
```
**Still no messages about new posts are sent** (only private messages work).

Log says:

```
Error  Sun, 16 Sep 2018 21:49:28 +0200  queue
Could not execute queued job! Message: The command "'/usr/local/bin/php5.6.31' '' 'queue/exec' '2419' '300' '1' '31000' '--color=1'" failed. Exit Code: 255(Unknown error) Working directory: /kunden/548428_64711/forum-test/protected Output: ================ Status: 404 Not Found X-Powered-By: PHP/5.6.31 Content-type: text/html; charset=UTF-8 No input file specified. Error Output: ================ Trace:#0 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(125): humhub\modules\queue\driver\MySQLCommand->handleMessage('2419', 'O:41:"humhub\\mo...', '300', 1) #1 [internal function]: yii\queue\cli\Command->yii\queue\cli\{closure}('2419', 'O:41:"humhub\\mo...', '300', 1) #2 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(144): call_user_func(Object(Closure), '2419', 'O:41:"humhub\\mo...', '300', 1) #3 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(84): yii\queue\cli\Queue->handleMessage('2419', 'O:41:"humhub\\mo...', '300', 1) #4 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure)) #5 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure)) #6 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker(Object(Closure)) #7 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false) #8 [internal function]: yii\queue\db\Command->actionRun() #9 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #10 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #11 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('run', Array) #12 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array) #13 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array) #14 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array) #15 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #16 /kunden/548428_64711/forum-test/protected/yii(28): yii\base\Application->run() #17 {main}
``` 

Also tested this

`./yii test/email info@blu-it.de`

it works! So it is definitly **not** a SMTP issue...

Regards

**Comment by danielkesselberg** [comment]
Could you share `php -v`?

**Comment by blu-IT** [comment]
@danielkesselberg 

`php -v` says:

```
PHP 4.4.9 (cgi) (built: Jan 13 2016 11:52:37)
Copyright (c) 1997-2008 The PHP Group
Zend Engine v1.3.0, Copyright (c) 1998-2004 Zend Technologies
    with Zend Optimizer v3.3.3, Copyright (c) 1998-2007, by Zend Technologies
```

**Comment by acs-ferreira** [comment]
Is HumHub running under PHP5.6 as you commands suggests or PHP4?

HumHum requires 5.6 minimum!

**Comment by blu-IT** [comment]
My cron jobs were running fine with Humhub v.1.2.8 . I modified them regarding the guidelines for the update to v.1.3.1  / v. 1.3.2 . I'am using PHP 5.6:

```
#! /bin/bash
env -i /usr/local/bin/php56 -f /mywebspace/humhub/protected/yii cron/run >/dev/null 2>&1
```

**Comment by webikasite** [comment]
> OK, so I found out now with **the help of a lot of folks** here #3308 , especially @danielkesselberg - **thanks again**!!!! - I have to call my php in another way:
> 
> ```
> /usr/local/bin/php5.6.34-cli ./yii queue/run --isolate=0
> /usr/local/bin/php5.6.34-cli ./yii cron/run
> ```
> On the console the notifications are triggered and sent now and also via cron job!
> 
> **Thanks for your support and patience!**

Good Day!
we have problem with humhub also Warning incomplete setup!
The cron job for the background jobs (queue) does not seem to work properly.
The cron job for the regular tasks (cron) does not seem to work properly.

pls help me

**Comment by wepals** [comment]
I have been struggleing for days trying to make that work but it does not Kills me :-(
Is there something simple atht works about this cron syndrome? I am on an shared host, i have follwed all i could use here but it still does not work for me

**Comment by blu-IT** [comment]
@wepals Do you have some output from your logfiles?

**Comment by wepals** [comment]
Ho wow thanks for answering I have added env -I  I had env -1 it works now thanks

**Comment by ahmadalwa** [comment]
> In shared hosting environments, I find the following two Cron Jobs to only work.
> 
> ```
> * * * * * /usr/local/bin/php /home/futayuri/path/to/humhub/protected/yii queue/run
> 
> * * * * * /usr/local/bin/php /home/path/to/humhub/protected/yii cron/run
> ```
> 
> or in dedicated servers the following.
> 
> ```
> * * * * * /usr/bin/php /path/to/humhub/protected/yii queue/run
> 
> * * * * * /usr/bin/php /path/to/humhub/protected/yii cron/run
> ```

what the steps to add this line to cpanel in share host please

**Comment by alexito2** [comment]
Hola, alguien podria apoyarme en solucionar el tema de cron job :c e intentado de todo y no funciona..
Estoy por explotar

**Comment by blu-IT** [comment]
@alexito2 

Can you please post some details how you configured your cron jobs? Is it an dedicated server or shared hosting environment, etc.?

**Comment by alexito2** [comment]
Se encuentra en un alojamiento compartido

**Comment by blu-IT** [comment]
@alexito2 Sorry, I don't speak spanish. I don't understand what you wrote. Can you write in english (or italian) please?

**Comment by alexito2** [comment]
@blu-IT 
Hello, if I'm honest, I don't know a little about the subject.
I started getting this popup window and from there I started reading about the possible error and tried something, but it didn't even work


----picture---
Attention Configuration incomplete!
The cron task that runs tasks in the background (queue) does not seem to be working correctly.
The cron task that runs normal tasks (cron) does not seem to be working correctly.
----picture---
