### ISSUE TITLE
Not the correct file when download

### ISSUE THREAD

**Issue by karimbernardet** [humhub/humhub#3317]
Hi

We have deployed Humhub + OnlyOffice. We have noticed that when we modify a file using OnlyOffice, the file uploaded thru Humhub is not the modified one but the original file uploaded at the beginning. But if we edit the file (clicking on Edit), we have the correct modified file.
Is it a normal behavior ?
(humhub version 1.2.7, onlyoffice module 1.0.2)
Thanks for any tip.

Karim

**Comment by buddh4** [comment]
The synchronization of edited documents can take some time I'am currently not sure if this is an onlyoffice configuration issue, but I've also noticed this. Do you always click the save button, if not does it synchronize after clcking this button?

**Comment by buddh4** [comment]
The synchronization of edited documents can take some time I'am currently not sure if this is an onlyoffice configuration issue, but I've also noticed this. Do you always click the save button, if not does it synchronize after clcking this button?

**Comment by karimbernardet** [comment]
Hi
Sorry for the late reply ...
It never synchronizes. 
When I click on the Save button there is an error code -331 (modifications are saved automaticaly)
Cheers
Karim

**Comment by karimbernardet** [comment]
I see this error when clicking on the Save button 

[2019-04-24 14:51:44.634] [ERROR] nodeJS - sendServerRequest error: docId = 5897486101c568e71438;url = https://xxxxxxx/onlydocuments/backend/track?key=5897486101c568e71438;data = {"key":"5837486101c568e71438","status":6,"url":"https://xxxxxxxx/cache/files/5837486101c568e71438_5601/output.docx/output.docx?md5=lUov-ORDZJsws_-47ZfIlQ==&expires=1556111205&disposition=attachment&ooname=output.docx","changesurl":"https://xxxxxxx/cache/files/5897486101c568e71438_5601/changes.zip/changes.zip?md5=I9vZMyNfvAQ_9nxYh6qOfg==&expires=1556111205&disposition=attachment&ooname=output.zip","history":{"serverVersion":"5.1.5","changes":[{"created":"2019-04-24 12:31:22","user":{"id":"70123106-06b6-4655-98d4-03eae6fd4f63","name":"Karim xxxxxx"}}]},"users":["70123106-06b6-4655-98d4-03eae6fd4f63"],"lastsave":"2019-04-24T12:33:31.095Z","forcesavetype":1}
Error: Error response: statusCode:500 ;body:
{"name":"Internal Server Error","message":"An internal server error occurred.","code":0,"status":500}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:283:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1079:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

We use https

**Comment by karimbernardet** [comment]
Same problem here
https://forum.seafile.com/t/files-edited-into-onlyoffice-are-not-versionned-correctly-into-seafile/7077/14
