### ISSUE TITLE
The table does not exist: queue_exclusive on fresh install

### ISSUE THREAD

**Issue by hbbk** [humhub/humhub#3335]
hi everybody, 

I know there is already and issue with the same title but it seems that issue was for an upgrade, mine is for a fresh install.

Just dl and tried to install but i'v got this error, near the end (i suppose) of the web install process
The database seems to have installed all the tables except the queue_exclusive one :( (there is one named queue) 
I followed all the recommanded steps in the install guide (db utf8mb4 and so on)

thanks for any help

### What steps will reproduce the problem?
Fresh install

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.6
| PHP version      |  7.0.30-0+deb9u1
| Operating system | Debian

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by luke-** [comment]
Is there any error in the file `protected/runtime/logs/app.log` ?

**Comment by hbbk** [comment]
yes the 1st one is

```
2018-10-15 14:58:04 [10.196.35.75][-][-][error][application] SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
The SQL being executed was: ALTER TABLE `space_module` ADD CONSTRAINT `fk_space_module-module_id` FOREIGN KEY (`module_id`) REFERENCES `module_enabled` (`module_id`) ON DELETE CASCADE ON UPDATE CASCADE
    in /www/sites/intranet/tests/humhub-1.3.6/protected/humhub/modules/space/migrations/m160205_203913_foreign_keys.php:45
    in /www/sites/intranet/tests/humhub-1.3.6/protected/humhub/commands/MigrateController.php:184
    in /www/sites/intranet/tests/humhub-1.3.6/protected/humhub/modules/installer/controllers/SetupController.php:127
2018-10-15 14:58:03 [10.196.35.75][-][-][info][application] $_GET = [
    'r' => 'installer/setup/init'
]
```

**Comment by luke-** [comment]
Thank you, can you please send us further error messages?

**Comment by hbbk** [comment]
ok

```
2018-10-15 15:01:25 [10.196.35.75][-][3n2nm0aenl82pv3qps4vk11rp6][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: The table does not exist: queue_exclusive in /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/db/ActiveRecord.php:382
Stack trace:
#0 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(210): yii\db\ActiveRecord::getTableSchema()
#1 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(190): yii\db\ActiveRecord::filterCondition(Array)
#2 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(112): yii\db\ActiveRecord::findByCondition(Array)
#3 /www/sites/intranet/tests/humhub-1.3.6/protected/humhub/modules/queue/helpers/QueueHelper.php(29): yii\db\BaseActiveRecord::findOne(Array)
#4 /www/sites/intranet/tests/humhub-1.3.6/protected/humhub/modules/queue/Events.php(61): humhub\modules\queue\helpers\QueueHelper::isQueued(Object(humhub\modules\search\jobs\UpdateDocument))
#5 [internal function]: humhub\modules\queue\Events::onQueueBeforePush(Object(yii\queue\PushEvent))
#6 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(yii\queue\PushEvent))
#7 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('yii\\queue\\Queue', 'beforePush', Object(yii\queue\PushEvent))
#8 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2-queue/src/Queue.php(152): yii\base\Component->trigger('beforePush', Object(yii\queue\PushEvent))
#9 /www/sites/intranet/tests/humhub-1.3.6/protected/humhub/modules/user/models/User.php(483): yii\queue\Queue->push(Object(humhub\modules\search\jobs\UpdateDocument))
#10 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(555): humhub\modules\user\models\User->afterSave(true, Array)
#11 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(510): yii\db\ActiveRecord->insertInternal(NULL)
#12 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\db\ActiveRecord->insert(true, NULL)
#13 /www/sites/intranet/tests/humhub-1.3.6/protected/humhub/modules/installer/controllers/ConfigController.php(448): yii\db\BaseActiveRecord->save()
#14 [internal function]: humhub\modules\installer\controllers\ConfigController->actionAdmin()
#15 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('admin', Array)
#18 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('installer/confi...', Array)
#19 /www/sites/intranet/tests/humhub-1.3.6/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#20 /www/sites/intranet/tests/humhub-1.3.6/index.php(25): yii\base\Application->run()
#21 {main}
2018-10-15 15:01:25 [10.196.35.75][-][3n2nm0aenl82pv3qps4vk11rp6][info][application] $_GET = [
    'r' => 'installer/config/admin'
]
```

then

```
2018-10-15 15:24:41 [10.196.35.75][-][-][error][application] Could not store setting: passwordRecoveryToken
    in /www/sites/intranet/tests/humhub-1.3.6/protected/humhub/libs/BaseSettingsManager.php:80
    in /www/sites/intranet/tests/humhub-1.3.6/protected/humhub/modules/user/models/forms/AccountRecoverPassword.php:81
    in /www/sites/intranet/tests/humhub-1.3.6/protected/humhub/modules/user/controllers/PasswordRecoveryController.php:51
2018-10-15 15:24:41 [10.196.35.75][-][-][info][application] $_GET = [
    'r' => 'user/password-recovery'
]
```
all these twice (probably because i tried to reload pages :)
anyway now i have a running humhub except that i can't log in with admin account :)
i'll try a new fresh reinstall

**Comment by hbbk** [comment]
hi tried a new fresh install with carrefuly following all the recommended steps - in case I missed something the last time - and the problem is the same. Apparently what is recommended elsewhere when getting this index colum size too large is to switch to uft8 instead of utf8mb4 ... I that the solution you humhub people recomend too ?
cheers

**Comment by hbbk** [comment]
I installed using utf8-unicode-ci and it works perfectly... for now ;-)

**Comment by buddh4** [comment]
I think the migration in question is not required anymore and should be dropped. Note that with uf8-unicode-ci you won't be able to use utf8 emojis in humhub content etc.

**Comment by hbbk** [comment]
sorry wich migration are you talking about please ? My question was based on a fresh install problem. BTW if emoji are the only reasons for using utfmb4, for my testing app i really can manage without :) Will wait for a new version with this issue solved for production.

**Comment by buddh4** [comment]
I meant [this](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/space/migrations/m160205_203913_foreign_keys.php#L44) migration, lucas already removed the affected part, so it should work with HumHub 1.3.7. I'll close the issue for now.

**Comment by hbbk** [comment]
hi @buddh4 i'm sorry but the problem is still here, except that i now have only one error (the other with maximum colum size is no more here) . Still fresh install with all cleaned up before. 

```
2018-10-26 14:34:48 [10.196.35.75][-][dumqlnbj0e2g4endtb89i9al51][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: The table does not exist: queue_exclusive in /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/db/ActiveRecord.php:382
Stack trace:
#0 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(210): yii\db\ActiveRecord::getTableSchema()
#1 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(190): yii\db\ActiveRecord::filterCondition(Array)
#2 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(112): yii\db\ActiveRecord::findByCondition(Array)
#3 /www/sites/intranet/tests/humhub-1.3.7/protected/humhub/modules/queue/helpers/QueueHelper.php(29): yii\db\BaseActiveRecord::findOne(Array)
#4 /www/sites/intranet/tests/humhub-1.3.7/protected/humhub/modules/queue/Events.php(61): humhub\modules\queue\helpers\QueueHelper::isQueued(Object(humhub\modules\search\jobs\UpdateDocument))
#5 [internal function]: humhub\modules\queue\Events::onQueueBeforePush(Object(yii\queue\PushEvent))
#6 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(yii\queue\PushEvent))
#7 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('yii\\queue\\Queue', 'beforePush', Object(yii\queue\PushEvent))
#8 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2-queue/src/Queue.php(152): yii\base\Component->trigger('beforePush', Object(yii\queue\PushEvent))
#9 /www/sites/intranet/tests/humhub-1.3.7/protected/humhub/modules/user/models/User.php(483): yii\queue\Queue->push(Object(humhub\modules\search\jobs\UpdateDocument))
#10 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(555): humhub\modules\user\models\User->afterSave(true, Array)
#11 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(510): yii\db\ActiveRecord->insertInternal(NULL)
#12 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\db\ActiveRecord->insert(true, NULL)
#13 /www/sites/intranet/tests/humhub-1.3.7/protected/humhub/modules/installer/controllers/ConfigController.php(448): yii\db\BaseActiveRecord->save()
#14 [internal function]: humhub\modules\installer\controllers\ConfigController->actionAdmin()
#15 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('admin', Array)
#18 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('installer/confi...', Array)
#19 /www/sites/intranet/tests/humhub-1.3.7/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#20 /www/sites/intranet/tests/humhub-1.3.7/index.php(25): yii\base\Application->run()
#21 {main}
2018-10-26 14:34:47 [10.196.35.75][-][dumqlnbj0e2g4endtb89i9al51][info][application] $_GET = [
    'r' => 'installer/config/admin'
]

```

**Comment by luke-** [comment]
Hi @hbbk, just to clarify it, if you make a completely fresh installation (empty database, original files) - this error is displayed?

Actually, the missing table from the error message should have been created few steps earlier.

Can you please look into the file here (protected/runtime/logs/app.log) and check if there was an error before?

**Comment by hbbk** [comment]
yes this is what I did :  empty database, new files, and the queue_exclusive table is not created (37 tables - before modules installation - are actualy in the brand new humhub database but no queue_exclusive - 70 tables after intalling some modules) and absolutely no errors anywhere (no php_erros in the apache log, nothing in runtime/log) except the on indicating queu_exclusive could not be found  ...

**Comment by luke-** [comment]
Hmm the standard installation without modules should currently contain exactly 38 tables.

Does the table "space_membership" have a column named "id" in your installation?

**Comment by hbbk** [comment]
this is all the columns in space_membership (no id alone)
space_id	user_id	originator_user_id	status	request_message	last_visit	created_at	created_by	updated_at	updated_by	group_id	show_at_dashboard	can_cancel_membership	send_notifications

**Comment by luke-** [comment]
Can you please retry the installation (with a clean db/files) and replace the file "protected\humhub\modules\queue\migrations\m171027_220519_exclusive_jobs.php" with the attached file before start the installer?

[m171027_220519_exclusive_jobs.php.txt](https://github.com/humhub/humhub/files/2525851/m171027_220519_exclusive_jobs.php.txt)

**Comment by hbbk** [comment]
hi did all that but am sorry the pb and erros are the same... and still no queue_exclusive table in db :(

**Comment by luke-** [comment]
@hbbk hmm, this is very strange.

If you're running an installation with the modified "m171027_220519_exclusive_jobs.php" migration, does the system creates the column 'id' in the table 'space_membership'?

**Comment by hbbk** [comment]
yes i exactly did what you told me and no 'id' row in space_membership and even I don't find any 'Could not create primar key:...' error message anywhere, like if this m171027_220519_exclusive_jobs.php file is not used ...
