### ISSUE TITLE
prevent timeout on shared hosting

### ISSUE THREAD

**Issue by devcline** [humhub/humhub#3337]
Hello
what can i do to prevent a timeout on a shared hosting
i cant update and i cant install any plugins, always timeout

```
exception 'Zend\Http\Client\Adapter\Exception\TimeoutException' with message 'Read timed out' in /home/XXX/public_html/XXX/lab/protected/vendor/zendframework/zend-http/src/Client/Adapter/Curl.php:457
Stack trace:
#0 /home/XXX/public_html/XXX/lab/protected/vendor/zendframework/zend-http/src/Client.php(1453): Zend\Http\Client\Adapter\Curl->write('GET', Object(Zend\Uri\Http), '1.1', Array, '')
#1 /home/XXX/public_html/XXX/lab/protected/vendor/zendframework/zend-http/src/Client.php(936): Zend\Http\Client->doRequest(Object(Zend\Uri\Http), 'GET', true, Array, '')
#2 /home/XXX/public_html/XXX/lab/protected/humhub/modules/admin/libs/OnlineModuleManager.php(77): Zend\Http\Client->send()
#3 /home/XXX/public_html/XXX/lab/protected/humhub/modules/admin/controllers/ModuleController.php(142): humhub\modules\admin\libs\OnlineModuleManager->install('tasks')
#4 [internal function]: humhub\modules\admin\controllers\ModuleController->actionInstall()
#5 /home/XXX/public_html/XXX/lab/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /home/XXX/public_html/XXX/lab/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 /home/XXX/public_html/XXX/lab/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('install', Array)
#8 /home/XXX/public_html/XXX/lab/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/module/in...', Array)
#9 /home/XXX/public_html/XXX/lab/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#10 /home/XXX/public_html/XXX/lab/index.php(25): yii\base\Application->run()
#11 {main}
Copy Stacktrace Search Stackoverflow Search Google Exception
Zend\Http\Client\Adapter\Exception\TimeoutException
Read timed out
```

**Comment by Felli** [comment]
Increase `max_execution_time` in your `php.ini`, if you can't then I suggest you find a new server that allows you to.
