### ISSUE TITLE
Enhancement / Bug: Emoji in Hub names

### ISSUE THREAD

**Issue by devcline** [humhub/humhub#3340]
Is it possible to make hub names with emojis? Anyway it gives a error.
```

Database Exception – yii\db\Exception
SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
The SQL being executed was: SELECT `space`.`id` FROM `space` WHERE `space`.`name`='📚 Books' LIMIT 2
Error Info: Array
(
    [0] => HY000
    [1] => 1267
    [2] => Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
)
↵
Caused by: PDOException
SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
in /var/www/XXX/protected/vendor/yiisoft/yii2/db/Command.php at line 1258
```

**Comment by devcline** [comment]
You are totally right! I had a old installation of humhub so the old encoding
So i encoded everything to a utf8mb4

```
character_set_client:  utf8mb4
character_set_connection:  utf8mb4
character_set_database:  utf8mb4
character_set_filesystem:  binary
character_set_results:  utf8mb4
character_set_server:  utf8mb4
character_set_system:  utf8
collation_connection:  utf8mb4_unicode_ci
collation_database:  utf8mb4_unicode_ci
collation_server: utf8mb4_unicode_ci
```

But still a error:

```
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='' in /var/www/XXX/protected/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /var/www/XXX/protected/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /var/www/XXX/protected/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `space`....')
#2 /var/www/XXX/protected/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /var/www/XXX/protected/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /var/www/XXX/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#5 /var/www/XXX/protected/vendor/yiisoft/yii2/validators/UniqueValidator.php(198): yii\db\ActiveQuery->all()
#6 /var/www/XXX/protected/vendor/yiisoft/yii2/validators/UniqueValidator.php(145): yii\validators\UniqueValidator->modelExists('humhub\\modules\\...', Array, Object(humhub\modules\space\models\Space))
#7 [internal function]: yii\validators\UniqueValidator->yii\validators\{closure}(Object(yii\db\Connection))
#8 /var/www/XXX/protected/vendor/yiisoft/yii2/db/Connection.php(1059): call_user_func(Object(Closure), Object(yii\db\Connection))
#9 /var/www/XXX/protected/vendor/yiisoft/yii2/validators/UniqueValidator.php(146): yii\db\Connection->useMaster(Object(Closure))
#10 /var/www/XXX/protected/vendor/yiisoft/yii2/validators/Validator.php(267): yii\validators\UniqueValidator->validateAttribute(Object(humhub\modules\space\models\Space), 'name')
#11 /var/www/XXX/protected/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(humhub\modules\space\models\Space), Array)
#12 /var/www/XXX/protected/humhub/modules/space/modules/manage/controllers/DefaultController.php(52): yii\base\Model->validate()
#13 [internal function]: humhub\modules\space\modules\manage\controllers\DefaultController->actionIndex()
#14 /var/www/XXX/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /var/www/XXX/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /var/www/XXX/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('index', Array)
#17 /var/www/XXX/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('space/manage/de...', Array)
#18 /var/www/XXX/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#19 /var/www/XXX/index.php(25): yii\base\Application->run()
#20 {main}

Next exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
The SQL being executed was: SELECT `space`.`id` FROM `space` WHERE `space`.`name`='RADIO 📻 ' LIMIT 2' in /var/www/XXX/protected/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /var/www/XXX/protected/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT `space`....')
#1 /var/www/XXX/protected/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `space`....')
#2 /var/www/XXX/protected/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /var/www/XXX/protected/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /var/www/XXX/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#5 /var/www/XXX/protected/vendor/yiisoft/yii2/validators/UniqueValidator.php(198): yii\db\ActiveQuery->all()
#6 /var/www/XXX/protected/vendor/yiisoft/yii2/validators/UniqueValidator.php(145): yii\validators\UniqueValidator->modelExists('humhub\\modules\\...', Array, Object(humhub\modules\space\models\Space))
#7 [internal function]: yii\validators\UniqueValidator->yii\validators\{closure}(Object(yii\db\Connection))
#8 /var/www/XXX/protected/vendor/yiisoft/yii2/db/Connection.php(1059): call_user_func(Object(Closure), Object(yii\db\Connection))
#9 /var/www/XXX/protected/vendor/yiisoft/yii2/validators/UniqueValidator.php(146): yii\db\Connection->useMaster(Object(Closure))
#10 /var/www/XXX/protected/vendor/yiisoft/yii2/validators/Validator.php(267): yii\validators\UniqueValidator->validateAttribute(Object(humhub\modules\space\models\Space), 'name')
#11 /var/www/XXX/protected/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(humhub\modules\space\models\Space), Array)
#12 /var/www/XXX/protected/humhub/modules/space/modules/manage/controllers/DefaultController.php(52): yii\base\Model->validate()
#13 [internal function]: humhub\modules\space\modules\manage\controllers\DefaultController->actionIndex()
#14 /var/www/XXX/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /var/www/XXX/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /var/www/XXX/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('index', Array)
#17 /var/www/XXX/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('space/manage/de...', Array)
#18 /var/www/XXX/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#19 /var/www/XXX/index.php(25): yii\base\Application->run()
#20 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 1267
    [2] => Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
)

```

thanks, any clues?

**Comment by devcline** [comment]
show full columns from space

![image](https://user-images.githubusercontent.com/617020/47426436-78180200-d78d-11e8-91df-9845a594c848.png)


I tested this error on another dedicated server with another SQL installation and OS . Its the same error.

**Comment by devcline** [comment]
When i restart MYSQL All my values that i changed to a utf8mb4_unicode_ci are resets to the defaults...

![image](https://user-images.githubusercontent.com/617020/47429215-eeb8fd80-d795-11e8-8132-2c1a2fcaeb7d.png)

**Comment by devcline** [comment]
Any tests / news on this issue? thanks

**Comment by buddh4** [comment]
Try to set the db connection charset to utf8mb4 as described here: https://github.com/humhub/humhub/issues/2129

**Comment by devcline** [comment]
thank you very much @buddh4 , it was so simple as this:) haha it works 😍

**Comment by buddh4** [comment]
Did you use the SQL mentioned in the [Installation Guide](http://docs.humhub.org/admin-installation.html#database-setup)? If yes, the default db encoding should be utf7mb4.

Or do you mean the connection encoding mentioned in https://github.com/humhub/humhub/issues/2129#issuecomment-439892385
