### ISSUE TITLE
'yii\base\ErrorException' with message 'Undefined offset: 0'

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3363]
Running `./yii cron/run`

```
PHP Notice 'yii\base\ErrorException' with message 'Undefined offset: 0'

in /protected/humhub/components/ModuleManager.php:191

Stack trace:
#0 /protected/humhub/components/ModuleManager.php(191): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/home/eki/w...', 191, Array)
#1 /protected/humhub/components/ModuleManager.php(110): humhub\components\ModuleManager->register('/home/eki/w...', Array)
#2 /protected/humhub/components/bootstrap/ModuleAutoLoader.php(34): humhub\components\ModuleManager->registerBulk(Array)
#3 /protected/vendor/yiisoft/yii2/base/Application.php(327): humhub\components\bootstrap\ModuleAutoLoader->bootstrap(Object(humhub\components\console\Application))
#4 /protected/vendor/yiisoft/yii2/base/Application.php(273): yii\base\Application->bootstrap()
#5 /protected/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
#6 /protected/humhub/components/console/Application.php(63): yii\console\Application->init()
#7 /protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\components\console\Application->init()
#8 /protected/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#9 /protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#10 /protected/yii(28): yii\console\Application->__construct(Array)
#11 {main}
```
https://github.com/humhub/humhub/blob/ad27dc6b30252735ca0d3cc6c6fc7db8486e8e52/protected/humhub/components/ModuleManager.php#L185-L194

`./yii integrity/run`

```
*** Performing database integrity checks

Validating: Tasks Module - Entries (0 entries)
Validating: Tasks Module (0 entries)
Validating: Activity Module (1331 entries)
Validating: Comment Module (9 entries)
Validating: Content Objects (1510 entries)
Validating: File Module (74 entries)
Validating: Like (38 entries)
Validating: Notification Module (1414 entries)
Validating: User Module - ContentContainer (95 entries)
Validating: User Module - Users (95 entries)
Validating: User Module - Password (230 entries)
Validating: User Module - Profile (95 entries)
Validating: User Module - Mentioning (0 entries)
Validating: User Module - Follow (213 entries)
Validating: User Module - Content container (106 entries)

*** All integrity checks done
```

**Comment by buddh4** [comment]
Which modules do you have installed (enabled or disabled) any third party modules?

**Comment by acs-ferreira** [comment]
All modules come from the Marketplace (like Calendar, Tasks, Birthday, etc).
Do you need a full list?

**Comment by buddh4** [comment]
- Which HumHub Version
- Did you recently update your installation or any modules? 
- Since when does it happen
- Does it only affect the integrity check and not the web

**Comment by acs-ferreira** [comment]
- HumHub v1.3.7
- Server has been migrated (from one provider to another, same configuration (Apache, PHP, Redis...)
- After the migration (deleting lines from 190-192 solves it)
- It affects everything (with those two lines in place)

**Comment by buddh4** [comment]
Did you clear the cache after migration to the other server?

**Comment by acs-ferreira** [comment]
Yes, all caches.
Basically `rsync -ar` from A to B, and MySQLDump from A to B.

A = OK
B = KO

**Comment by buddh4** [comment]
In order to debug can you try the following:

```
 if (isset($event['class'])) {
    Event::on($event['class'], $event['event'], $event['callback']);
 } else if(isset($event[0], $event[1], $event[2])) {
   Event::on($event[0], $event[1], $event[2]);
} else {
  print_r($config);die();
}
```

**Comment by acs-ferreira** [comment]
Opps...it comes from an external module: https://github.com/bumrufus/humhub-modules-phonebook

Fixed on their repo.

Thanks
