### ISSUE TITLE
Error in email setup produces error code output to browser

### ISSUE THREAD

**Issue by Crisses** [humhub/humhub#3483]
### What steps will reproduce the problem?
Error during admin's set-up of application email throws problems onto the screen.

I set it up to external web address (not localhost) i.e. mail.mydomain.tld and wrong port (993) (oops!)

### What is the expected result?
Probably should say it couldn't get a connection or otherwise gently chastise the admin user to change the details, rather than dump a mess to the browser.

### What do you get instead?
Loads of stuff this is the summary report of problems:

```
Swift_TransportException: Connection to tcp://mail.mydomain.tld:993 Timed Out in /my/humhub/root/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:404
Stack trace:
#0 /my/humhub/root/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(289): Swift_Transport_AbstractSmtpTransport->_getFullResponse(0)
#1 /my/humhub/root/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(117): Swift_Transport_AbstractSmtpTransport->_readGreeting()
#2 /my/humhub/root/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#3 /my/humhub/root/protected/vendor/yiisoft/yii2-swiftmailer/Mailer.php(146): Swift_Mailer->send(Object(Swift_Message))
#4 /my/humhub/root/protected/humhub/components/mail/Mailer.php(91): yii\swiftmailer\Mailer->sendMessage(Object(humhub\components\mail\Message))
#5 /my/humhub/root/protected/vendor/yiisoft/yii2/mail/BaseMailer.php(263): humhub\components\mail\Mailer->sendMessage(Object(humhub\components\mail\Message))
#6 /my/humhub/root/protected/vendor/yiisoft/yii2/mail/BaseMessage.php(49): yii\mail\BaseMailer->send(Object(humhub\components\mail\Message))
#7 /my/humhub/root/protected/humhub/modules/user/models/Invite.php(148): yii\mail\BaseMessage->send()
#8 /my/humhub/root/protected/humhub/modules/admin/controllers/PendingRegistrationsController.php(96): humhub\modules\user\models\Invite->sendInviteMail()
#9 [internal function]: humhub\modules\admin\controllers\PendingRegistrationsController->actionResend('1')
#10 /my/humhub/root/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /my/humhub/root/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /my/humhub/root/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('resend', Array)
#13 /my/humhub/root/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/pending-r...', Array)
#14 /my/humhub/root/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#15 /my/humhub/root/index.php(25): yii\base\Application->run()
#16 {main}
```

### Additional info
sparkling new install.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.10
| PHP version      |  PHP 7.0.33-0+deb9u1
| Operating system | Debian 9.6

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
If you enabled production mode, such error details shouldn't displayed anymore.

http://docs.humhub.org/admin-security.html#enable-production-mode
