### ISSUE TITLE
E-Mail Summary is not generated (Error: Could not send activity mail to: xyz (Calling unknown method: yii\console\Request::get())

### ISSUE THREAD

**Issue by spst** [humhub/humhub#3505]
### Description

E-Mail summary of activities fails to be generated. Instead the error `Could not send activity mail to: usernameXYZ (Calling unknown method: yii\console\Request::get()) ` is generated

(E-Mail Notifications do work, so the problem is not related to sending Mails)

The cron job command line defined in the hoster's user interface is
`/bin/php ./humhub/protected/yii queue/run --isolate=0`

I have tried to find a `php-cli`, but without success (that was discussed here: https://github.com/humhub/humhub/issues/2573 )

### Log info

![screenshot-05](https://user-images.githubusercontent.com/3089168/53744730-df616380-3e9d-11e9-88fe-88f628b01ba9.jpg)

INFO in UX:
`$_GET = [ '_/humhub/protected/yii' => '' 'queue/run' => '' '--isolate' => '0' ] $_SERVER = [ 'DOCUMENT_ROOT' => '/mnt/rid/71/32/5xyz2/htdocs/.' 'HTTP_HOST' => '5xyz2.de.strato-hosting.eu' 'PATH' => '/bin:/usr/bin:.' 'SCRIPT_FILENAME' => '/mnt/rid/71/32/5xyz2/htdocs/.' 'TZ' => 'localtime' 'USER' => 'httpd' 'PHP_SELF' => '' 'REQUEST_TIME_FLOAT' => 1551712982.6453 'REQUEST_TIME' => 1551712982 'argv' => [ 0 => './humhub/protected/yii' 1 => 'queue/run' 2 => '--isolate=0' ] 'argc' => 3 ] `

ERROR in UX:
`Could not send activity mail to: usernameXYZ (Calling unknown method: yii\console\Request::get()) `

Excerpt from` /humhub/protected/runtime/logs/app.log`:
```
2019-03-04 16:23:03 [-][-][-][error][activity] Could not send activity mail to: Stefan Spreng (Calling unknown method: yii\console\Request::get())
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummaryProcessor.php:71
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/jobs/SendMailSummary.php:36
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/queue/ActiveJob.php:33
2019-03-04 16:23:04 [-][-][-][error][activity] Could not send activity mail to: Stefan Test (Calling unknown method: yii\console\Request::get())
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummaryProcessor.php:71
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/jobs/SendMailSummary.php:36
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/queue/ActiveJob.php:33
2019-03-04 16:23:02 [-][-][-][info][application] $_GET = [
    '_/humhub/protected/yii' => ''
    'queue/run' => ''
    '--isolate' => '0'
]

$_SERVER = [
    'DOCUMENT_ROOT' => '/mnt/rid/71/32/5xyz2/htdocs/.'
    'HTTP_HOST' => '5xyz2.de.strato-hosting.eu'
    'PATH' => '/bin:/usr/bin:.'
    'SCRIPT_FILENAME' => '/mnt/rid/71/32/5xyz2/htdocs/.'
    'TZ' => 'localtime'
    'USER' => 'httpd'
    'PHP_SELF' => ''
    'REQUEST_TIME_FLOAT' => 1551712982.6453
    'REQUEST_TIME' => 1551712982
    'argv' => [
        0 => './humhub/protected/yii'
        1 => 'queue/run'
        2 => '--isolate=0'
    ]
    'argc' => 3
]
```

### Additional info

I am running Humhub on a shared hosting environment, so I dont have all that much control over all the settings.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.10
| PHP version      | 7.2.15
| Operating system | Shared Hosting at strato.de

Humhub screenshots:

![screenshot-02](https://user-images.githubusercontent.com/3089168/53744580-9b6e5e80-3e9d-11e9-9772-b61b700bc851.jpg)

Screenshot of cron job definition:
![screenshot-03](https://user-images.githubusercontent.com/3089168/53744755-edaf7f80-3e9d-11e9-8107-c0b72003f0d9.jpg)

**Comment by luke-** [comment]
Unfortunately, some details about the error are not correctly logged.

Can you please add following statement after the marked line:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/activity/components/MailSummaryProcessor.php#L71

```
Yii::error($ex)
```

This should produces a more detailled error message.

Thanks!

**Comment by spst** [comment]
Ok, now the error message is a lot longer!

UX log entry:
`Could not send activity mail to: UserXYZ (Calling unknown method: yii\console\Request::get())`

`yii\base\UnknownMethodException: Calling unknown method: yii\console\Request::get() in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Component.php:300 Stack trace: #0 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/stream/actions/Stream.php(165): yii\base\Component->__call('get', Array) #1 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/stream/actions/ContentContainerStream.php(35): humhub\modules\stream\actions\Stream->init() #2 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/dashboard/components/actions/DashboardStreamAction.php(38): humhub\modules\stream\actions\ContentContainerStream->init() #3 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\dashboard\components\actions\DashboardStreamAction->init() #4 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Action.php(62): yii\base\BaseObject->__construct(Array) #5 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummary.php(136): yii\base\Action->__construct('stream', Object(humhub\modules\queue\driver\MySQLCommand)) #6 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummary.php(78): humhub\modules\activity\components\MailSummary->getActivities() #7 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummaryProcessor.php(66): humhub\modules\activity\components\MailSummary->send() #8 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/jobs/SendMailSummary.php(36): humhub\modules\activity\components\MailSummaryProcessor::process(2) #9 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/queue/ActiveJob.php(33): humhub\modules\activity\jobs\SendMailSummary->run() #10 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/Queue.php(214): humhub\modules\queue\ActiveJob->execute(Object(humhub\modules\queue\driver\MySQL)) #11 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('4486', 'O:44:"humhub\\mo...', '300', 1) #12 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83): yii\queue\cli\Queue->handleMessage('4486', 'O:44:"humhub\\mo...', '300', 1) #13 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure)) #14 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure)) #15 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker(Object(Closure)) #16 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false) #17 [internal function]: yii\queue\db\Command->actionRun() #18 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #19 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #20 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('run', Array) #21 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array) #22 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array) #23 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array) #24 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #25 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/yii(28): yii\base\Application->run() #26 {main}`


and in the `app.log` file:

```
2019-03-05 18:23:03 [-][-][-][error][activity] Could not send activity mail to: UserXYZ (Calling unknown method: yii\console\Request::get())
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummaryProcessor.php:71
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/jobs/SendMailSummary.php:36
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/queue/ActiveJob.php:33
2019-03-05 18:23:03 [-][-][-][error][application] yii\base\UnknownMethodException: Calling unknown method: yii\console\Request::get() in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/stream/actions/Stream.php(165): yii\base\Component->__call('get', Array)
#1 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/stream/actions/ContentContainerStream.php(35): humhub\modules\stream\actions\Stream->init()
#2 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/dashboard/components/actions/DashboardStreamAction.php(38): humhub\modules\stream\actions\ContentContainerStream->init()
#3 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\dashboard\components\actions\DashboardStreamAction->init()
#4 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Action.php(62): yii\base\BaseObject->__construct(Array)
#5 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummary.php(136): yii\base\Action->__construct('stream', Object(humhub\modules\queue\driver\MySQLCommand))
#6 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummary.php(78): humhub\modules\activity\components\MailSummary->getActivities()
#7 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummaryProcessor.php(66): humhub\modules\activity\components\MailSummary->send()
#8 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/jobs/SendMailSummary.php(36): humhub\modules\activity\components\MailSummaryProcessor::process(2)
#9 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/queue/ActiveJob.php(33): humhub\modules\activity\jobs\SendMailSummary->run()
#10 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/Queue.php(214): humhub\modules\queue\ActiveJob->execute(Object(humhub\modules\queue\driver\MySQL))
#11 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('4486', 'O:44:"humhub\\mo...', '300', 1)
#12 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83): yii\queue\cli\Queue->handleMessage('4486', 'O:44:"humhub\\mo...', '300', 1)
#13 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure))
#14 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#15 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker(Object(Closure))
#16 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false)
#17 [internal function]: yii\queue\db\Command->actionRun()
#18 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#20 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('run', Array)
#21 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array)
#22 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array)
#23 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array)
#24 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#25 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/yii(28): yii\base\Application->run()
#26 {main}
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummaryProcessor.php:72
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/jobs/SendMailSummary.php:36
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/queue/ActiveJob.php:33
2019-03-05 18:23:02 [-][-][-][info][application] $_GET = [
    '_/humhub/protected/yii' => ''
    'queue/run' => ''
    '--isolate' => '0'
]

$_SERVER = [
    'DOCUMENT_ROOT' => '/mnt/rid/71/32/5xyz2/htdocs/.'
    'HTTP_HOST' => '5xyz2.de.strato-hosting.eu'
    'PATH' => '/bin:/usr/bin:.'
    'SCRIPT_FILENAME' => '/mnt/rid/71/32/5xyz2/htdocs/.'
    'TZ' => 'localtime'
    'USER' => 'httpd'
    'PHP_SELF' => ''
    'REQUEST_TIME_FLOAT' => 1551806581.96
    'REQUEST_TIME' => 1551806581
    'argv' => [
        0 => './humhub/protected/yii'
        1 => 'queue/run'
        2 => '--isolate=0'
    ]
    'argc' => 3
]
```

**Comment by luke-** [comment]
Hmm, seems you're using the wrong PHP executable.

Can you try to replace following line 
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/stream/actions/Stream.php#L164

with

`if (!Yii::$app->request->isConsoleRequest && !(Yii::$app instanceof \humhub\components\console\Application)) {`

**Comment by spst** [comment]
Here's the latest log entry after changing the piece of code:

```
2019-03-07 14:53:04 [-][-][-][error][activity] Could not send activity mail to: UserXYZ (Calling unknown method: yii\console\Request::get())
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummaryProcessor.php:71
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/jobs/SendMailSummary.php:36
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/queue/ActiveJob.php:33
2019-03-07 14:53:04 [-][-][-][error][application] yii\base\UnknownMethodException: Calling unknown method: yii\console\Request::get() in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/ui/filter/models/Filter.php(39): yii\base\Component->__call('get', Array)
#1 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/stream/models/filters/DefaultStreamFilter.php(54): humhub\modules\ui\filter\models\Filter->init()
#2 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\stream\models\filters\DefaultStreamFilter->init()
#3 [internal function]: yii\base\BaseObject->__construct(Array)
#4 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#5 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('humhub\\modules\\...', Array, Array)
#6 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('humhub\\modules\\...', Array, Array)
#7 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/stream/models/StreamQuery.php(373): yii\BaseYii::createObject(Array)
#8 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/stream/models/StreamQuery.php(283): humhub\modules\stream\models\StreamQuery->setupFilters()
#9 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/stream/models/StreamQuery.php(261): humhub\modules\stream\models\StreamQuery->setupQuery()
#10 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/stream/actions/Stream.php(175): humhub\modules\stream\models\StreamQuery->query(true)
#11 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/stream/actions/ContentContainerStream.php(35): humhub\modules\stream\actions\Stream->init()
#12 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/dashboard/components/actions/DashboardStreamAction.php(38): humhub\modules\stream\actions\ContentContainerStream->init()
#13 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\dashboard\components\actions\DashboardStreamAction->init()
#14 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Action.php(62): yii\base\BaseObject->__construct(Array)
#15 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummary.php(136): yii\base\Action->__construct('stream', Object(humhub\modules\queue\driver\MySQLCommand))
#16 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummary.php(78): humhub\modules\activity\components\MailSummary->getActivities()
#17 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummaryProcessor.php(66): humhub\modules\activity\components\MailSummary->send()
#18 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/jobs/SendMailSummary.php(36): humhub\modules\activity\components\MailSummaryProcessor::process(1)
#19 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/queue/ActiveJob.php(33): humhub\modules\activity\jobs\SendMailSummary->run()
#20 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/Queue.php(214): humhub\modules\queue\ActiveJob->execute(Object(humhub\modules\queue\driver\MySQL))
#21 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('4641', 'O:44:"humhub\\mo...', '300', 1)
#22 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83): yii\queue\cli\Queue->handleMessage('4641', 'O:44:"humhub\\mo...', '300', 1)
#23 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure))
#24 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#25 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker(Object(Closure))
#26 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false)
#27 [internal function]: yii\queue\db\Command->actionRun()
#28 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#29 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#30 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('run', Array)
#31 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array)
#32 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array)
#33 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array)
#34 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#35 /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/yii(28): yii\base\Application->run()
#36 {main}
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/components/MailSummaryProcessor.php:72
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/activity/jobs/SendMailSummary.php:36
    in /mnt/web023/b1/32/5xyz2/htdocs/humhub/protected/humhub/modules/queue/ActiveJob.php:33
2019-03-07 14:53:02 [-][-][-][info][application] $_GET = [
    '_/humhub/protected/yii' => ''
    'queue/run' => ''
    '--isolate' => '0'
]

$_SERVER = [
    'DOCUMENT_ROOT' => '/mnt/rid/71/32/5xyz2/htdocs/.'
    'HTTP_HOST' => '5xyz2.de.strato-hosting.eu'
    'PATH' => '/bin:/usr/bin:.'
    'SCRIPT_FILENAME' => '/mnt/rid/71/32/5xyz2/htdocs/.'
    'TZ' => 'localtime'
    'USER' => 'httpd'
    'PHP_SELF' => ''
    'REQUEST_TIME_FLOAT' => 1551966782.8136
    'REQUEST_TIME' => 1551966782
    'argv' => [
        0 => './humhub/protected/yii'
        1 => 'queue/run'
        2 => '--isolate=0'
    ]
    'argc' => 3
]
```

**Comment by spst** [comment]
Concerning the php executable:

this ist the cron job command:
`/bin/php ./humhub/protected/yii queue/run --isolate=0`

the results of some ssh commands are


```
me> which php
/bin/php


me> php -v
PHP 7.2.15 (cgi-fcgi) (built: Feb 20 2019 16:10:24)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies


me> ls /usr/bin/php* -al
-rwx--x--x 1 0 1 20116 Oct  5  2017 /usr/bin/php
lrwxrwxrwx 1 0 0     3 Mar 23  2018 /usr/bin/php3 -> php
lrwxrwxrwx 1 0 0     3 Mar 23  2018 /usr/bin/php4 -> php
lrwxrwxrwx 1 0 0     3 Mar 23  2018 /usr/bin/php43 -> php
lrwxrwxrwx 1 0 0     3 Mar 23  2018 /usr/bin/php43pl -> php
lrwxrwxrwx 1 0 0     3 Mar 23  2018 /usr/bin/php44 -> php
lrwxrwxrwx 1 0 0     3 Mar 23  2018 /usr/bin/php44pl -> php
lrwxrwxrwx 1 0 0    20 Mar 23  2018 /usr/bin/php5 -> /opt/RZphp56/bin/php
lrwxrwxrwx 1 0 0     5 Mar 23  2018 /usr/bin/php52 -> php53
-rwx--x--x 1 0 1 20488 Oct  5  2017 /usr/bin/php53
lrwxrwxrwx 1 0 0    19 Mar 23  2018 /usr/bin/php53es -> /opt/RZphp5/bin/php
lrwxrwxrwx 1 0 0     5 Mar 23  2018 /usr/bin/php55 -> php56
lrwxrwxrwx 1 0 0    20 Mar 23  2018 /usr/bin/php56 -> /opt/RZphp56/bin/php
lrwxrwxrwx 1 0 0     4 Mar 23  2018 /usr/bin/php5pl -> php5
lrwxrwxrwx 1 0 0    20 Mar 23  2018 /usr/bin/php70 -> /opt/RZphp70/bin/php
lrwxrwxrwx 1 0 0    20 Mar 23  2018 /usr/bin/php71 -> /opt/RZphp71/bin/php
lrwxrwxrwx 1 0 0    20 Mar 23  2018 /usr/bin/php72 -> /opt/RZphp72/bin/php
lrwxrwxrwx 1 0 0    20 Dec 12 13:49 /usr/bin/php73 -> /opt/RZphp73/bin/php
lrwxrwxrwx 1 0 0    23 Mar 23  2018 /usr/bin/phpdbg56 -> /opt/RZphp56/bin/phpdbg
lrwxrwxrwx 1 0 0    23 Mar 23  2018 /usr/bin/phpdbg70 -> /opt/RZphp70/bin/phpdbg
lrwxrwxrwx 1 0 0    23 Mar 23  2018 /usr/bin/phpdbg71 -> /opt/RZphp71/bin/phpdbg
lrwxrwxrwx 1 0 0    23 Mar 23  2018 /usr/bin/phpdbg72 -> /opt/RZphp72/bin/phpdbg
lrwxrwxrwx 1 0 0    23 Dec 12 13:49 /usr/bin/phpdbg73 -> /opt/RZphp73/bin/phpdbg


me> ls /bin/php* -al
-rwx--x--x 1 0 1 20116 Oct  5  2017 /bin/php
lrwxrwxrwx 1 0 0     3 Mar 23  2018 /bin/php3 -> php
lrwxrwxrwx 1 0 0     3 Mar 23  2018 /bin/php4 -> php
lrwxrwxrwx 1 0 0     3 Mar 23  2018 /bin/php43 -> php
lrwxrwxrwx 1 0 0     3 Mar 23  2018 /bin/php43pl -> php
lrwxrwxrwx 1 0 0     3 Mar 23  2018 /bin/php44 -> php
lrwxrwxrwx 1 0 0     3 Mar 23  2018 /bin/php44pl -> php
lrwxrwxrwx 1 0 0    20 Mar 23  2018 /bin/php5 -> /opt/RZphp56/bin/php
lrwxrwxrwx 1 0 0     5 Mar 23  2018 /bin/php52 -> php53
-rwx--x--x 1 0 1 20488 Oct  5  2017 /bin/php53
lrwxrwxrwx 1 0 0    19 Mar 23  2018 /bin/php53es -> /opt/RZphp5/bin/php
lrwxrwxrwx 1 0 0     5 Mar 23  2018 /bin/php55 -> php56
lrwxrwxrwx 1 0 0    20 Mar 23  2018 /bin/php56 -> /opt/RZphp56/bin/php
lrwxrwxrwx 1 0 0     4 Mar 23  2018 /bin/php5pl -> php5
lrwxrwxrwx 1 0 0    20 Mar 23  2018 /bin/php70 -> /opt/RZphp70/bin/php
lrwxrwxrwx 1 0 0    20 Mar 23  2018 /bin/php71 -> /opt/RZphp71/bin/php
lrwxrwxrwx 1 0 0    20 Mar 23  2018 /bin/php72 -> /opt/RZphp72/bin/php
lrwxrwxrwx 1 0 0    20 Dec 12 13:49 /bin/php73 -> /opt/RZphp73/bin/php
lrwxrwxrwx 1 0 0    23 Mar 23  2018 /bin/phpdbg56 -> /opt/RZphp56/bin/phpdbg
lrwxrwxrwx 1 0 0    23 Mar 23  2018 /bin/phpdbg70 -> /opt/RZphp70/bin/phpdbg
lrwxrwxrwx 1 0 0    23 Mar 23  2018 /bin/phpdbg71 -> /opt/RZphp71/bin/phpdbg
lrwxrwxrwx 1 0 0    23 Mar 23  2018 /bin/phpdbg72 -> /opt/RZphp72/bin/phpdbg
lrwxrwxrwx 1 0 0    23 Dec 12 13:49 /bin/phpdbg73 -> /opt/RZphp73/bin/phpdbg


me> ls /usr/local/bin/php* -al
lrwxrwxrwx 1 0 0 12 Mar 23  2018 /usr/local/bin/php -> /usr/bin/php


```

**Comment by spst** [comment]
Seems like a problem with the hoster...

I decided to move to another provider. Now, it is working.
