### ISSUE TITLE
Database migration tool on command line fails with SQL error when performing a manual update

### ISSUE THREAD

**Issue by benedetto** [humhub/humhub#3548]
### What steps will reproduce the problem?
1. Follow the steps from http://docs.humhub.org/admin-updating.html for a manual update
2. Run the database migration tool from the console:
```
cd protected
php yii migrate/up --includeModuleMigrations=1
``` 

### What is the expected result?
The migration tool runs successfully.

### What do you get instead?
The migration fails with the following console output:
```
[user@server protected]$ php yii module/update-all
Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)'

in /<path to humhub root>/protected/vendor/yiisoft/yii2/db/Connection.php:624

Stack trace:
#0 /<path to humhub root>/protected/vendor/yiisoft/yii2/db/Connection.php(996): yii\db\Connection->open()
#1 /<path to humhub root>/protected/vendor/yiisoft/yii2/db/Connection.php(983): yii\db\Connection->getMasterPdo()
#2 /<path to humhub root>/protected/vendor/yiisoft/yii2/db/Command.php(253): yii\db\Connection->getSlavePdo()
#3 /<path to humhub root>/protected/vendor/yiisoft/yii2/db/Command.php(1143): yii\db\Command->prepare(true)
#4 /<path to humhub root>/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#5 /<path to humhub root>/protected/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#6 /<path to humhub root>/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#7 /<path to humhub root>/protected/humhub/models/ModuleEnabled.php(71): yii\db\ActiveQuery->all()
#8 /<path to humhub root>/protected/humhub/modules/admin/commands/ModuleController.php(158): humhub\models\ModuleEnabled::getEnabledIds()
#9 [internal function]: humhub\modules\admin\commands\ModuleController->actionUpdateAll()
#10 /<path to humhub root>/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /<path to humhub root>/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /<path to humhub root>/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('update-all', Array)
#13 /<path to humhub root>/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('update-all', Array)
#14 /<path to humhub root>/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('module/update-a...', Array)
#15 /<path to humhub root>/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('module/update-a...', Array)
#16 /<path to humhub root>/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#17 /<path to humhub root>/protected/yii(29): yii\base\Application->run()
#18 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.9 installed, Update to 1.3.12
| PHP version      |  PHP 5.6.40
| Operating system | CentOS 6

**Comment by luke-** [comment]
Is there a file protected/config/dynamic.php in your installation?

**Comment by benedetto** [comment]
@luke- Yes, there is.

**Comment by luke-** [comment]
"'SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' " indicates that the database connection settings are not loaded correctly.

Before update to 1.3.12, are you able to execute: php yii module/update-all ?

**Comment by benedetto** [comment]
@luke- Yes, that works with the following output:
````
php yii module/update-all
Module auto-patch already up to date!
Module birthday already up to date!
Module calendar already up to date!
Module cfiles already up to date!
Module gallery already up to date!
Module linklist already up to date!
Module mail already up to date!
Module mostactiveusers already up to date!
Module polls already up to date!
Module tasks already up to date!
Module updater already up to date!
Module wiki already up to date!
````
Hope that helps.

**Comment by luke-** [comment]
Hmm, are you really sure you have completed step 3 of the upgrade documentation?

**Comment by luke-** [comment]
Can you please retry the update and send me each taken step?

**Comment by benedetto** [comment]
Hm, this time it worked without any problems and I could update to 1.3.14. Maybe I had a fault in the restoration of backups the last time I tried.

Thanks for your help and patience.
