### ISSUE TITLE
Messages / Update Internal Server Error

### ISSUE THREAD

**Issue by vandenbos** [humhub/humhub#3563]
I have set up messaging using Amazon SES, since then when I try to open a message I am getting internal server errors. The logs don't appear to be capturing anything of use. I am also getting an internal server error when I try upgrading :s

```
TypeError: Cannot read property 'timeout' of undefinedTypeError: Cannot read property 'timeout' of undefined
    at Object.g [as redirect] (https://hub.tools.naimuri.dev/static/js/all-b16b15e020a27ecd7f9a9d8eb08d9cde.js?v=1554068868:272:3220)
    at Object.loadMessage (https://hub.tools.naimuri.dev/assets/46475554/js/humhub.mail.wall.js?v=1557325568:283:25)
    at r (https://hub.tools.naimuri.dev/static/js/all-b16b15e020a27ecd7f9a9d8eb08d9cde.js?v=1554068868:259:23796)
    at q.handle (https://hub.tools.naimuri.dev/static/js/all-b16b15e020a27ecd7f9a9d8eb08d9cde.js?v=1554068868:259:23467)
    at HTMLAnchorElement. (https://hub.tools.naimuri.dev/static/js/all-b16b15e020a27ecd7f9a9d8eb08d9cde.js?v=1554068868:259:25811)
    at HTMLDocument.dispatch (https://hub.tools.naimuri.dev/static/js/all-b16b15e020a27ecd7f9a9d8eb08d9cde.js?v=1554068868:30:2807)
    at HTMLDocument.q.handle (https://hub.tools.naimuri.dev/static/js/all-b16b15e020a27ecd7f9a9d8eb08d9cde.js?v=1554068868:30:816)
```

For the update internal server error I am getting this in the logs.
`yii\base\ErrorException: rename(): The first argument to copy() function cannot be a directory in /var/www/localhost/htdocs/protected/modules/updater/libs/UpdatePackage.php:151 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError(2, 'rename(): The f...', '/var/www/localh...', 151, Array) #1 /var/www/localhost/htdocs/protected/modules/updater/libs/UpdatePackage.php(151): rename('/var/www/localh...', '/var/www/localh...') #2 /var/www/localhost/htdocs/protected/modules/updater/modules/packageinstaller/controllers/InstallController.php(71): humhub\modules\updater\libs\UpdatePackage->install() #3 [internal function]: humhub\modules\updater\modules\packageinstaller\controllers\InstallController->actionInstallFiles() #4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('install-files', Array) #7 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('package-install...', Array) #8 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #9 /var/www/localhost/htdocs/index.php(25): yii\base\Application->run() #10 {main}`

**Comment by luke-** [comment]
Can you please open a separate issue for each problem? 
Please also use our bug template.

Thanks!
