### ISSUE TITLE
"Array to string conversion" on Ldap register

### ISSUE THREAD

**Issue by karl007** [humhub/humhub#3584]
Hi.

I have a humhub installation with a ldap backend with profile-sync option.

Only first and lastname are mapped to ldap field.

On first login with an account there occurs a "Array to string conversion".

I debugged this a little bit and it seems that there was an empty array for the `street` column.

With this code snippet at `/protected/vendor/yiisoft/yii2/db/mysql/ColumnSchema.php` line 159, everything worked, but the profile street col contains 'XXX'.
```php
               if (is_array($value) && empty($value)) {
                    return 'XXX';
                }
```

### Debug Backtrace
```
2019-06-19 21:26:21 [87.122.196.216][-][ka20mlgg2871c5h50ansarjsc9][error][yii\base\ErrorException:8] yii\base\ErrorException: Array to string conversion in /var/www/humhub/protected/vendor/yiisoft/yii2/db/ColumnSchema.php:167
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ColumnSchema.php(167): yii\base\ErrorHandler->handleError(8, 'Array to string...', '/var/www/humhub...', 167, Array)
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/db/mysql/ColumnSchema.php(47): yii\db\ColumnSchema->typecast(Array)
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/db/QueryBuilder.php(375): yii\db\mysql\ColumnSchema->dbTypecast(Array)
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(249): yii\db\QueryBuilder->prepareInsertValues('profile', Array, Array)
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/db/QueryBuilder.php(345): yii\db\mysql\QueryBuilder->prepareInsertValues('profile', Array, Array)
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(470): yii\db\QueryBuilder->insert('profile', Array, Array)
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Schema.php(432): yii\db\Command->insert('profile', Array)
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(544): yii\db\Schema->insert('profile', Array)
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(510): yii\db\ActiveRecord->insertInternal(NULL)
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\db\ActiveRecord->insert(true, NULL)
#10 /var/www/humhub/protected/humhub/modules/user/models/forms/Registration.php(260): yii\db\BaseActiveRecord->save()
#11 /var/www/humhub/protected/humhub/modules/user/authclient/AuthClientHelpers.php(191): humhub\modules\user\models\forms\Registration->register(Object(humhub\modules\ldap\authclient\LdapAuth))
#12 /var/www/humhub/protected/humhub/modules/user/controllers/AuthController.php(145): humhub\modules\user\authclient\AuthClientHelpers::createUser(Object(humhub\modules\ldap\authclient\LdapAuth))
#13 /var/www/humhub/protected/humhub/modules/user/controllers/AuthController.php(78): humhub\modules\user\controllers\AuthController->onAuthSuccess(Object(humhub\modules\ldap\authclient\LdapAuth))
#14 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin()
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('login', Array)
#18 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/auth/login', Array)
#19 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#20 /var/www/humhub/index.php(25): yii\base\Application->run()
#21 {main}
```

**Comment by luke-** [comment]
Can you please try the new version release again?

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/a3b44d88f1242cd9b30fffad77325a1ef32f965b
