### ISSUE TITLE
PDOException: SQLSTATE[42S22]: Column not found

### ISSUE THREAD

**Issue by NENJAK** [humhub/humhub#3724]
### What steps will reproduce the problem?

PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'target' in 'where clause' in /var/www/html/protected/vendor/yiisoft/yii2/db/Command.php:1258 Stack trace: #0 /var/www/html/protected/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute() #1 /var/www/html/protected/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `custom_...') #2 /var/www/html/protected/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL) #3 /var/www/html/protected/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll() #4 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL) #5 /var/www/html/protected/modules/custom_pages/Events.php(51): yii\db\ActiveQuery->all() #6 [internal function]: humhub\modules\custom_pages\Events::onSpaceMenuInit(Object(yii\base\Event)) #7 /var/www/html/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(yii\base\Event)) #8 /var/www/html/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\modules\\...', 'init', Object(yii\base\Event)) #9 /var/www/html/protected/vendor/yiisoft/yii2/base/Widget.php(72): yii\base\Component->trigger('init') #10 /var/www/html/protected/humhub/widgets/BaseMenu.php(78): yii\base\Widget->init() #11 /var/www/html/protected/humhub/modules/space/widgets/Menu.php(57): humhub\widgets\BaseMenu->init() #12 /var/www/html/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\space\widgets\Menu->init() #13 [internal function]: yii\base\BaseObject->__construct(Array) #14 /var/www/html/protected/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array) #15 /var/www/html/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('humhub\\modules\\...', Array, Array) #16 /var/www/html/protected/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('humhub\\modules\\...', Array, Array) #17 /var/www/html/protected/vendor/yiisoft/yii2/base/Widget.php(137): yii\BaseYii::createObject(Array) #18 /var/www/html/protected/humhub/modules/space/views/space/_layout.php(27): yii\base\Widget::widget(Array) #19 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/html/p...') #20 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/html/p...', Array) #21 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/p...', Array, Object(humhub\modules\space\controllers\SpaceController)) #22 /var/www/html/protected/humhub/components/Controller.php(124): yii\base\View->render('@humhub/modules...', Array, Object(humhub\modules\space\controllers\SpaceController)) #23 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(385): humhub\components\Controller->renderContent('\n<div class="pa...') #24 /var/www/html/protected/humhub/modules/space/controllers/SpaceController.php(106): yii\base\Controller->render('home', Array) #25 /var/www/html/protected/humhub/modules/space/controllers/SpaceController.php(88): humhub\modules\space\controllers\SpaceController->actionHome() #26 [internal function]: humhub\modules\space\controllers\SpaceController->actionIndex() #27 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #28 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #29 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #30 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('space/space', Array) #31 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #32 /var/www/html/index.php(25): yii\base\Application->run() #33 {main} Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'target' in 'where clause' The SQL being executed was: SELECT `custom_pages_container_page`.* FROM `custom_pages_container_page` LEFT JOIN `content` ON `custom_pages_container_page`.`id` = `content`.`object_id` LEFT JOIN `contentcontainer` ON `content`.`contentcontainer_id` = `contentcontainer`.`id` LEFT JOIN `user` ON `content`.`created_by` = `user`.`id` WHERE ((`contentcontainer`.`pk`=20) AND (`contentcontainer`.`class`='humhub\\modules\\space\\models\\Space')) AND (`target`='SpaceMenu') AND (`content`.`object_model`='humhub\\modules\\custom_pages\\models\\ContainerPage') in /var/www/html/protected/vendor/yiisoft/yii2/db/Schema.php:664 Stack trace: #0 /var/www/html/protected/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT `custom_...') #1 /var/www/html/protected/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `custom_...') #2 /var/www/html/protected/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL) #3 /var/www/html/protected/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll() #4 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL) #5 /var/www/html/protected/modules/custom_pages/Events.php(51): yii\db\ActiveQuery->all() #6 [internal function]: humhub\modules\custom_pages\Events::onSpaceMenuInit(Object(yii\base\Event)) #7 /var/www/html/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(yii\base\Event)) #8 /var/www/html/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\modules\\...', 'init', Object(yii\base\Event)) #9 /var/www/html/protected/vendor/yiisoft/yii2/base/Widget.php(72): yii\base\Component->trigger('init') #10 /var/www/html/protected/humhub/widgets/BaseMenu.php(78): yii\base\Widget->init() #11 /var/www/html/protected/humhub/modules/space/widgets/Menu.php(57): humhub\widgets\BaseMenu->init() #12 /var/www/html/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\space\widgets\Menu->init() #13 [internal function]: yii\base\BaseObject->__construct(Array) #14 /var/www/html/protected/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array) #15 /var/www/html/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('humhub\\modules\\...', Array, Array) #16 /var/www/html/protected/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('humhub\\modules\\...', Array, Array) #17 /var/www/html/protected/vendor/yiisoft/yii2/base/Widget.php(137): yii\BaseYii::createObject(Array) #18 /var/www/html/protected/humhub/modules/space/views/space/_layout.php(27): yii\base\Widget::widget(Array) #19 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/html/p...') #20 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/html/p...', Array) #21 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/p...', Array, Object(humhub\modules\space\controllers\SpaceController)) #22 /var/www/html/protected/humhub/components/Controller.php(124): yii\base\View->render('@humhub/modules...', Array, Object(humhub\modules\space\controllers\SpaceController)) #23 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(385): humhub\components\Controller->renderContent('\n<div class="pa...') #24 /var/www/html/protected/humhub/modules/space/controllers/SpaceController.php(106): yii\base\Controller->render('home', Array) #25 /var/www/html/protected/humhub/modules/space/controllers/SpaceController.php(88): humhub\modules\space\controllers\SpaceController->actionHome() #26 [internal function]: humhub\modules\space\controllers\SpaceController->actionIndex() #27 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #28 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #29 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #30 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('space/space', Array) #31 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #32 /var/www/html/index.php(25): yii\base\Application->run() #33 {main} Additional Information: Array ( [0] => 42S22 [1] => 1054 [2] => Unknown column 'target' in 'where clause' ) 

### What is the expected result?
to open any space
### What do you get instead?
 Oooops... It looks like you may have taken the wrong turn.
An internal server error occurred.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?  1.3.17
| PHP version      | 7.2
| Operating system | Ubuntu 16

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

I believe after updating Custom page module I am gettting this error and I am not able to open any  space. Profil page or Strim page is functioning.

**Comment by NENJAK** [comment]
and just saw migration error:

        Yii Migration Tool (based on Yii v2.0.15)

Total 5 new migrations to be applied:
	m190213_135902_align_page_types
	m190213_135903_humhub_richtext_content
	m190213_135904_page_abstract
	m190213_135905_blank_template
	m190213_135906_text_edit_mode

*** applying m190213_135902_align_page_types
    > rename column content in table custom_pages_page to page_content ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
The SQL being executed was: ALTER TABLE `custom_pages_page` CHANGE `content` `page_content` (/var/www/html/protected/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /var/www/html/protected/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `cu...')
#1 /var/www/html/protected/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE `cu...')
#2 /var/www/html/protected/vendor/yiisoft/yii2/db/Migration.php(405): yii\db\Command->execute()
#3 /var/www/html/protected/modules/custom_pages/migrations/m190213_135902_align_page_types.php(16): yii\db\Migration->renameColumn('custom_pages_pa...', 'content', 'page_content')
#4 /var/www/html/protected/vendor/yiisoft/yii2/db/Migration.php(114): m190213_135902_align_page_types->safeUp()
#5 /var/www/html/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): yii\db\Migration->up()
#6 /var/www/html/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(199): yii\console\controllers\BaseMigrateController->migrateUp('m190213_135902_...')
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#8 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('up', Array)
#11 /var/www/html/protected/humhub/commands/MigrateController.php(184): yii\console\Controller->runAction('up')
#12 /var/www/html/protected/humhub/modules/admin/controllers/InformationController.php(95): humhub\commands\MigrateController::webMigrateAll()
#13 [internal function]: humhub\modules\admin\controllers\InformationController->actionDatabase()
#14 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('database', Array)
#17 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/informati...', Array)
#18 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#19 /var/www/html/index.php(25): yii\base\Application->run()
#20 {main}
*** failed to apply m190213_135902_align_page_types (time: 0.044s)


0 from 5 migrations were applied.

Migration failed. The rest of the migrations are canceled.
