### ISSUE TITLE
HH 1.4.0-beta.1: Integrity check exception

### ISSUE THREAD

**Issue by st5000** [humhub/humhub#3729]
Getting this after validating Content Objects :

```
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: humhub\modules\content\models\Content::user'

in /humhub/protected/vendor/yiisoft/yii2/base/Component.php:154

Stack trace:
#0 /humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('user')
#1 /humhub/protected/humhub/modules/content/Events.php(77): yii\db\BaseActiveRecord->__get('user')
#2 [internal function]: humhub\modules\content\Events::onIntegrityCheck(Object(yii\base\Event))
#3 /humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event))
#4 /humhub/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\commands...', 'run', Object(yii\base\Event))
#5 /humhub/protected/humhub/commands/IntegrityController.php(39): yii\base\Component->trigger('run')
#6 [internal function]: humhub\commands\IntegrityController->actionRun()
#7 /humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /humhub/protected/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('run', Array)
#10 /humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array)
#11 /humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('integrity/run', Array)
#12 /humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('integrity/run', Array)
#13 /humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /humhub/protected/yii(29): yii\base\Application->run()
#15 {main}
```

**Comment by Ace2213** [comment]
Oh so it's not just me
