### ISSUE TITLE
LDAP authentication / import not working when LDAP object contains `guid` attribute

### ISSUE THREAD

**Issue by kbabioch** [humhub/humhub#3774]
### What steps will reproduce the problem?

Our LDAP objects contain, among many other attributes, a `guid` attribute. This has caused issues when using LDAP authentication, since the application preferred this value over the one generated by itself.

The LDIF data looks something like this:

```
# extended LDIF
#
# LDAPv3
# base <> (default) with scope subtree
# filter: uid=kbabioch
# requesting: guid 
#

# kbabioch, Novell
dn: cn=kbabioch,o=Novell
GUID:: QMHnhTo83AGAYgANnZPOEw==

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```
As you can see (`::` this is binary data). This resulted in _strange_ values in the `guid` column of the `user` table in the MySQL database. Depending on the exact value it might even break the whole application for everyone (!) with error messages like this:

```
yii\base\ErrorException: file_exists() expects parameter 1 to be a valid path, string given in /var/www/localhost/htdocs/protected/humhub/libs/ProfileImage.php:81
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'file_exists() e...', '/var/www/localh...', 81, Array)
#1 /var/www/localhost/htdocs/protected/humhub/libs/ProfileImage.php(81): file_exists('/var/www/localh...')
#2 /var/www/localhost/htdocs/protected/humhub/modules/user/widgets/Image.php(103): humhub\libs\ProfileImage->getUrl()
#3 /var/www/localhost/htdocs/protected/humhub/components/Widget.php(58): humhub\modules\user\widgets\Image->run()
#4 /var/www/localhost/htdocs/protected/humhub/modules/user/grid/ImageColumn.php(36): humhub\components\Widget::widget(Array)
#5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/grid/Column.php(111): humhub\modules\user\grid\ImageColumn->renderDataCellContent(Object(humhub\modules\user\models\User), 4, 0)
#6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/grid/GridView.php(520): yii\grid\Column->renderDataCell(Object(humhub\modules\user\models\User), 4, 0)
#7 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/grid/GridView.php(489): yii\grid\GridView->renderTableRow(Object(humhub\modules\user\models\User), 4, 0)
#8 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/grid/GridView.php(353): yii\grid\GridView->renderTableBody()
#9 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/widgets/BaseListView.php(160): yii\grid\GridView->renderItems()
#10 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/grid/GridView.php(321): yii\widgets\BaseListView->renderSection('{items}')
#11 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/widgets/BaseListView.php(135): yii\grid\GridView->renderSection('{items}')
#12 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array)
#13 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/widgets/BaseListView.php(138): preg_replace_callback('/{\\w+}/', Object(Closure), '{summary}\n{item...')
#14 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/grid/GridView.php(296): yii\widgets\BaseListView->run()
#15 /var/www/localhost/htdocs/protected/humhub/widgets/GridView.php(33): yii\grid\GridView->run()
#16 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Widget.php(140): humhub\widgets\GridView->run()
#17 /var/www/localhost/htdocs/protected/humhub/modules/admin/views/user/list.php(53): yii\base\Widget::widget(Array)
#18 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/localh...')
#19 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/localh...', Array)
#20 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/localh...', Array, Object(humhub\modules\admin\controllers\UserController))
#21 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('list', Array, Object(humhub\modules\admin\controllers\UserController))
#22 /var/www/localhost/htdocs/protected/humhub/modules/admin/controllers/UserController.php(87): yii\base\Controller->render('list', Array)
#23 [internal function]: humhub\modules\admin\controllers\UserController->actionList()
#24 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#25 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#26 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('list', Array)
#27 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/user/list', Array)
#28 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#29 /var/www/localhost/htdocs/index.php(25): yii\base\Application->run()
#30 {main}
```

This issue itself has been addressed with 59e1e399d555f9a631fd0ea0cbb6e241ac5cdfff.

59e1e399d555f9a631fd0ea0cbb6e241ac5cdfff fixed the initial issue. **However**, we were facing the same issue once we enabled the `legal` module. It seems that the source code of the legal module is not on GitHub, but by looking at the code it is obvious that the module hooks into the registration logic, rendering 59e1e399d555f9a631fd0ea0cbb6e241ac5cdfff useless.

### What is the expected result?

Application should still work, even with the `legal` module enabled.

### What do you get instead?

Application breaks as soon as we enabled the `legal` module and imported the first users.

### Additional info

We were able to resolve the issue for now by patching the LDAP code itself. This looks something like this:

```

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.18
| PHP version      |  7.2.25
| Operating system | Linux (SUSE/openSUSE/Alpine

**Comment by ArchBlood** [comment]
Here's the [legal](https://github.com/humhub-contrib/legal) module. :+1:
