### ISSUE TITLE
yii\base\InvalidConfigException

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#3888]
Performed manual update based on docs.  Front page redirects to /user/auth/login then displays this error.

```
An Error occurred while handling another error:
yii\base\InvalidConfigException: Object configuration must be an array containing a "class" or "__class" element. in /var/www/humhub/protected/vendor/yiisoft/yii2/BaseYii.php:368
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject(Array, Array)
#1 /var/www/humhub/protected/humhub/modules/web/pwa/widgets/SiteIcon.php(116): yii\base\Module->getModule('web')
#2 /var/www/humhub/protected/humhub/modules/web/pwa/widgets/SiteIcon.php(128): humhub\modules\web\pwa\widgets\SiteIcon::setDefaultIcon()
#3 /var/www/humhub/protected/humhub/modules/ui/view/components/View.php(205): humhub\modules\web\pwa\widgets\SiteIcon::registerMetaTags(Object(humhub\modules\ui\view\components\View))
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/web/View.php(180): humhub\modules\ui\view\components\View->renderHeadHtml()
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/views/errorHandler/exception.php(544): yii\web\View->endPage()
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/humhub...')
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/humhub...', Array)
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(270): yii\base\View->renderFile('/var/www/humhub...', Array, Object(yii\web\ErrorHandler))
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(127): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(123): yii\web\ErrorHandler->renderException(Object(yii\base\InvalidConfigException))
#11 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\InvalidConfigException))
#12 {main}
Previous exception:
yii\base\InvalidConfigException: Object configuration must be an array containing a "class" or "__class" element. in /var/www/humhub/protected/vendor/yiisoft/yii2/BaseYii.php:368
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject(Array, Array)
#1 /var/www/humhub/protected/humhub/modules/web/pwa/widgets/SiteIcon.php(116): yii\base\Module->getModule('web')
#2 /var/www/humhub/protected/humhub/modules/web/pwa/widgets/SiteIcon.php(128): humhub\modules\web\pwa\widgets\SiteIcon::setDefaultIcon()
#3 /var/www/humhub/protected/humhub/modules/ui/view/components/View.php(205): humhub\modules\web\pwa\widgets\SiteIcon::registerMetaTags(Object(humhub\modules\ui\view\components\View))
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/web/View.php(180): humhub\modules\ui\view\components\View->renderHeadHtml()
#5 /var/www/humhub/protected/humhub/modules/user/views/layouts/main.php(32): yii\web\View->endPage()
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/humhub...')
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/humhub...', Array)
#8 /var/www/humhub/protected/humhub/components/Controller.php(135): yii\base\View->renderFile('/var/www/humhub...', Array, Object(humhub\modules\user\controllers\AuthController))
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(387): humhub\components\Controller->renderContent('\n<div class="co...')
#10 /var/www/humhub/protected/humhub/modules/user/controllers/AuthController.php(102): yii\base\Controller->render('login', Array)
#11 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin()
#12 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('login', Array)
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/auth/login', Array)
#16 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#17 /var/www/humhub/index.php(25): yii\base\Application->run()
#18 {main}
```

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.2
| PHP version      | 7.2.24
| Operating system | Ubuntu

**Comment by luke-** [comment]
Are you using any custom configuration/modules/themes?

**Comment by miqrogroove** [comment]
Negative.  I've only added the gallery module, and I did copy it from the 1.3 to 1.4 dir.

**Comment by luke-** [comment]
Hmm, can oyu please try to remove the /protected/runtime/cache directory?

**Comment by miqrogroove** [comment]
/protected/runtime/cache does not exist.  The instructions say to copy runtime/searchdb only and the ZIP package does not include a cache dir.  Permissions are writeable in runtime dir as instructed.

**Comment by miqrogroove** [comment]
Is anyone around for realtime diagnostic?  Otherwise I will need to downgrade back to 1.3.

**Comment by luke-** [comment]
Ok, I just wanted to make sure that there isn't a cache directory.

Can you do a fresh installation of Humhub 1.4.2  on the same server for a test run?

If that works, can you try a fresh HumHub installation with an existing database?

**Comment by miqrogroove** [comment]
While setting up a second site, I noticed the production site has started working now with no further action on my part.  Could this be cron related?  Some step missing in the upgrade procedure?

**Comment by miqrogroove** [comment]
Earlier, you mentioned caching.  I have APCu installed but not sqlite.  Is it possible that an Apache restart solved the problem while I was tinkering?  Should this be necessary?

**Comment by luke-** [comment]
https://github.com/humhub/documentation/commit/65f2f23319f934746473b2ef76a504efa9fded9f
