### ISSUE TITLE
Profile Images not getting uploaded

### ISSUE THREAD

**Issue by Mazvy** [humhub/humhub#3932]
| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.3
| PHP version      | 7.3.15
| Operating system | Debian 9

Uploading a new profile image for a space or a user results in this error:

```
2020-03-18 19:47:56 [xx.xx.xx.xx][4521][jh8f8k90elrfhduj97gdneae6v][error][yii\base\ErrorException:2] yii\base\ErrorException: imagecreatefromjpeg(/var/www/hub/uploads/profile_image/c9679123-53fa-4307-b18d-e75b8e4d17df_org.jpg): failed to open stream: No such file or directory in /mnt/extended/webhosts/hub/protected/humhub/libs/ProfileImage.php:154
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'imagecreatefrom...', '/mnt/extended/w...', 154, Array)
#1 /mnt/extended/webhosts/hub/protected/humhub/libs/ProfileImage.php(154): imagecreatefromjpeg('/var/www/hub/up...')
#2 /mnt/extended/webhosts/hub/protected/humhub/modules/content/controllers/ContainerImageController.php(109): humhub\libs\ProfileImage->cropOriginal('0', '0', '150', '150')
#3 /mnt/extended/webhosts/hub/protected/humhub/modules/content/controllers/ContainerImageController.php(55): humhub\modules\content\controllers\ContainerImageController->handleCrop('image')
#4 [internal function]: humhub\modules\content\controllers\ContainerImageController->actionCrop('image')
#5 /mnt/extended/webhosts/hub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /mnt/extended/webhosts/hub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 /mnt/extended/webhosts/hub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('crop', Array)
#8 /mnt/extended/webhosts/hub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/image/crop', Array)
#9 /mnt/extended/webhosts/hub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#10 /mnt/extended/webhosts/hub/index.php(25): yii\base\Application->run()
#11 {main}
```

`uploads/profile_image` permission is set to 775, owner is www-data.

File/image uploads work everywhere else (posts, comments, etc), but not for profile images.

**FIXED**

Apparently imagemagick wasn't installed on the system. 

In the humhub admin panel dependencies page `/admin/information/prerequisites` it doesn't show that imagemagick is required in order for humhub to run. The error log was useless at providing any information as to what went wrong. 

Thankfully PHP error logged this `sh: 1: /usr/bin/convert: not found` and I immediately knew imagemagick was used by humhub. It would be nice if you updated your documentation and prerequisites page to reflect that.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/3521
