### ISSUE TITLE
Error logged when the Youtube link posted.

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub#4113]
### What steps will reproduce the problem?
Error logged:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'https://www.youtube.com/watch?v=o-RXTsVcX2k' for key 'PRIMARY' in C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\Command.php:1293 Stack trace: #0 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\Command.php(1293): PDOStatement->execute() #1 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\Command.php(1093): yii\db\Command->internalExecute('INSERT INTO `ur...') #2 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\Schema.php(432): yii\db\Command->execute() #3 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\ActiveRecord.php(600): yii\db\Schema->insert('url_oembed', Array) #4 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL) #5 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL) #6 C:\xampp\htdocs\humhubcom\protected\humhub\models\UrlOembed.php(259): yii\db\BaseActiveRecord->save() #7 C:\xampp\htdocs\humhubcom\protected\humhub\models\UrlOembed.php(158): humhub\models\UrlOembed::loadUrl('https://www.you...') #8 C:\xampp\htdocs\humhubcom\protected\humhub\controllers\OembedController.php(39): humhub\models\UrlOembed::getOEmbed('https://www.you...') #9 [internal function]: humhub\controllers\OembedController->actionIndex() #10 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array) #11 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array) #12 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('', Array) #13 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('oembed', Array) #14 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #15 C:\xampp\htdocs\humhubcom\index.php(25): yii\base\Application->run() #16 {main} Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'https://www.youtube.com/watch?v=o-RXTsVcX2k' for key 'PRIMARY' The SQL being executed was: INSERT INTO `url_oembed` (`url`, `preview`) VALUES ('https://www.youtube.com/watch?v=o-RXTsVcX2k', '<div class=\"oembed_snippet\" data-guid=\"oembed-5ebf58dd7414a9.82138506\" data-richtext-feature=\"1\" data-oembed-provider=\"youtube.com\" data-url=\"https://www.youtube.com/watch?v=o-RXTsVcX2k\"><iframe width=\"450\" height=\"253\" src=\"https://www.youtube.com/embed/o-RXTsVcX2k?feature=oembed\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe></div>') in C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\Schema.php:674 Stack trace: #0 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `ur...') #1 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\Command.php(1093): yii\db\Command->internalExecute('INSERT INTO `ur...') #2 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\Schema.php(432): yii\db\Command->execute() #3 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\ActiveRecord.php(600): yii\db\Schema->insert('url_oembed', Array) #4 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL) #5 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\db\BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL) #6 C:\xampp\htdocs\humhubcom\protected\humhub\models\UrlOembed.php(259): yii\db\BaseActiveRecord->save() #7 C:\xampp\htdocs\humhubcom\protected\humhub\models\UrlOembed.php(158): humhub\models\UrlOembed::loadUrl('https://www.you...') #8 C:\xampp\htdocs\humhubcom\protected\humhub\controllers\OembedController.php(39): humhub\models\UrlOembed::getOEmbed('https://www.you...') #9 [internal function]: humhub\controllers\OembedController->actionIndex() #10 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array) #11 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array) #12 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('', Array) #13 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('oembed', Array) #14 C:\xampp\htdocs\humhubcom\protected\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #15 C:\xampp\htdocs\humhubcom\index.php(25): yii\base\Application->run() #16 {main} Additional Information: Array ( [0] => 23000 [1] => 1062 [2] => Duplicate entry 'https://www.youtube.com/watch?v=o-RXTsVcX2k' for key 'PRIMARY' )
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
### What is the expected result?
This is just a information repot about error message.
Is that a normaly? Do we leave the post in safe?

### What do you get instead?
The error logged. But humhub is runnning, and it seems to no problem displayed the post. The link works, we can watch the movie. 

### Additional info
We use Linkpreview plugin module, we buy on Marketplace. 

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1
| PHP version      |  7.2
| Operating system | windowsserver2016, xampp

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
Run the [integrity](https://docs.humhub.org/docs/admin/console/#integrity) command from your command lines and see if that fixes it.

**Comment by tomofu74** [comment]
Hi ArchBood,

Thank you for your advice.
I run the integrity command and see, it displayed "*** All integrity checks done".
Nothing about this error. 
Do you think it is ok and we can ignore about this error?

Thank you

**Comment by aronbos** [comment]
if a post is removed and added again, you will see this error. For example, post a YouTube video, remove the post, add a new post with the same YouTube videourl and the error surfaces. Is harmless. Humhub should check the existence of key before adding it to prevent this error.

**Comment by luke-** [comment]
Can you please provide steps to reproduce?

**Comment by aronbos** [comment]
Post a YouTube URL. Delete the post. Make a new post (with other text)  and the same YouTube URL. Message is logged. Video is displayed correctly.

**Comment by tomofu74** [comment]
Yes, when post a Youtube URL (means browser's). But, posting a Youtube SHARE link may be not reported any error.
