### ISSUE TITLE
Calendar module failing constraint check

### ISSUE THREAD

**Issue by kenthejr** [humhub/humhub#4252]
### What steps will reproduce the problem?

1. Create a calendar event
2. Accept the calendar event
3. Set up a reminder for the calendar event

### What is the expected result?

A calendar event with a reminder.

### What do you get instead?

The entire platform is locked up with a server error and the following DB validation error:

```
Validating: Calendar Module (1 reminder entries)
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: constraint_name' in /var/www/html/protected/vendor/yiisoft/yii2/db/mysql/Schema.php:394
```

### Additional info
I've been running Humhub for almost a year now. I've updated/upgraded core + modules whenever prompted. This is the first time I've tried creating an event on the calendar. I'm guessing it is a failed constraint check because it triggers while testing the DB integrity on the Calendar Module (reminder entry).

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.3
| PHP version      | 7.3.14-1~deb10u1
| Operating system | Debian 10

### Full stack trace
```#0 /var/www/html/protected/vendor/yiisoft/yii2/db/mysql/Schema.php(394): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/html/p...', 394, Array)
#1 /var/www/html/protected/vendor/yiisoft/yii2/db/mysql/Schema.php(126): yii\db\mysql\Schema->findConstraints(Object(yii\db\TableSchema))
#2 /var/www/html/protected/vendor/yiisoft/yii2/db/Schema.php(754): yii\db\mysql\Schema->loadTableSchema('calendar_remind...')
#3 /var/www/html/protected/vendor/yiisoft/yii2/db/Schema.php(193): yii\db\Schema->getTableMetadata('calendar_remind...', 'schema', false)
#4 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(435): yii\db\Schema->getTableSchema('calendar_remind...')
#5 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(469): yii\db\ActiveRecord::getTableSchema()
#6 /var/www/html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(500): yii\db\ActiveRecord->attributes()
#7 /var/www/html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(291): yii\db\BaseActiveRecord->hasAttribute('active')
#8 /var/www/html/protected/modules/calendar/models/reminder/CalendarReminder.php(136): yii\db\BaseActiveRecord->__get('active')
#9 /var/www/html/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\calendar\models\reminder\CalendarReminder->init()
#10 /var/www/html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1215): yii\base\BaseObject->__construct()
#11 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveQueryTrait.php(121): yii\db\BaseActiveRecord::instantiate(Array)
#12 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(219): yii\db\ActiveQuery->createModels(Array)
#13 /var/www/html/protected/vendor/yiisoft/yii2/db/Query.php(249): yii\db\ActiveQuery->populate(Array)
#14 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#15 /var/www/html/protected/modules/calendar/Events.php(295): yii\db\ActiveQuery->all()
#16 [internal function]: humhub\modules\calendar\Events::onIntegrityCheck(Object(yii\base\Event))
#17 /var/www/html/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event))
#18 /var/www/html/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\commands...', 'run', Object(yii\base\Event))
#19 /var/www/html/protected/humhub/commands/IntegrityController.php(39): yii\base\Component->trigger('run')
#20 [internal function]: humhub\commands\IntegrityController->actionRun()
#21 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#23 /var/www/html/protected/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('run', Array)
#24 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array)
#25 /var/www/html/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('integrity/run', Array)
#26 /var/www/html/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('integrity/run', Array)
#27 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#28 /var/www/html/protected/yii(29): yii\base\Application->run()
#29 {main}```

**Comment by luke-** [comment]
Duplicate: https://github.com/humhub/humhub-modules-calendar/issues/192
