### ISSUE TITLE
Warning &#039;yii\\base\\ErrorException&#039; with message &#039;session_regenerate_id(): 

### ISSUE THREAD

**Issue by andrewua85** [humhub/humhub#4811]
Не может записать в tmp , был создан tmp и всеравно запись не происходит в указанную директорию!
Can not write to TMP, a TMP has been created and the record does not work in the specified directory!
```
{
    "url": "/index.php?r=dashboard%2Fdashboard%2Fstream",
    "status": 500,
    "response": "<pre>PHP Warning &#039;yii\\base\\ErrorException&#039; with message &#039;session_regenerate_id(): Session write failed. ID: user (path: /tmp)&#039; \n\nin /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/Session.php:300\n\nStack trace:\n#0 [internal function]: yii\\base\\ErrorHandler-&gt;handleError(2, &#039;session_regener...&#039;, &#039;/home/u31843/po...&#039;, 300, Array)\n#1 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/Session.php(300): session_regenerate_id(false)\n#...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>PHP Warning &#039;yii\\base\\ErrorException&#039; with message &#039;session_regenerate_id(): Session write failed. ID: user (path: /tmp)&#039; \n\nin /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/Session.php:300\n\nStack trace:\n#0 [internal function]: yii\\base\\ErrorHandler-&gt;handleError(2, &#039;session_regener...&#039;, &#039;/home/u31843/po...&#039;, 300, Array)\n#1 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/Session.php(300): session_regenerate_id(false)\n#2 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/DbSession.php(108): yii\\web\\Session-&gt;regenerateID(false)\n#3 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/User.php(653): yii\\web\\DbSession-&gt;regenerateID(true)\n#4 /home/u31843/post.losper.net/protected/humhub/modules/user/components/User.php(222): yii\\web\\User-&gt;switchIdentity(Object(humhub\\modules\\user\\models\\User), 2592000)\n#5 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/User.php(321): humhub\\modules\\user\\components\\User-&gt;switchIdentity(Object(humhub\\modules\\user\\models\\User), 2592000)\n#6 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/User.php(709): yii\\web\\User-&gt;loginByCookie()\n#7 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/User.php(194): yii\\web\\User-&gt;renewAuthStatus()\n#8 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/User.php(362): yii\\web\\User-&gt;getIdentity()\n#9 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/base/Component.php(139): yii\\web\\User-&gt;getIsGuest()\n#10 /home/u31843/post.losper.net/protected/humhub/components/i18n/I18N.php(53): yii\\base\\Component-&gt;__get(&#039;isGuest&#039;)\n#11 /home/u31843/post.losper.net/protected/humhub/components/bootstrap/LanguageSelector.php(29): humhub\\components\\i18n\\I18N-&gt;autosetLocale()\n#12 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/base/Application.php(327): humhub\\components\\bootstrap\\LanguageSelector-&gt;bootstrap(Object(humhub\\components\\Application))\n#13 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/Application.php(69): yii\\base\\Application-&gt;bootstrap()\n#14 /home/u31843/post.losper.net/protected/humhub/components/Application.php(46): yii\\web\\Application-&gt;bootstrap()\n#15 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/base/Application.php(273): humhub\\components\\Application-&gt;bootstrap()\n#16 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\\base\\Application-&gt;init()\n#17 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/base/Application.php(206): yii\\base\\BaseObject-&gt;__construct(Array)\n#18 /home/u31843/post.losper.net/index.php(25): yii\\base\\Application-&gt;__construct(Array)\n#19 {main}</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "html",
    "html": "<pre>PHP Warning &#039;yii\\base\\ErrorException&#039; with message &#039;session_regenerate_id(): Session write failed. ID: user (path: /tmp)&#039; \n\nin /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/Session.php:300\n\nStack trace:\n#0 [internal function]: yii\\base\\ErrorHandler-&gt;handleError(2, &#039;session_regener...&#039;, &#039;/home/u31843/po...&#039;, 300, Array)\n#1 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/Session.php(300): session_regenerate_id(false)\n#...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}
```

**Comment by ArchBlood** [comment]
Seems related to #2402

**Comment by andrewua85** [comment]
Это не то
This is not

**Comment by andrewua85** [comment]
> 
> 
> Seems related to #2402

Я использую MySQL 5.6+
I use MySQL 5.6+

**Comment by ArchBlood** [comment]
InnoDB or MyISAM?
