### ISSUE TITLE
TTR timeout for emails notifications from announcement module 

### ISSUE THREAD

**Issue by kcalvat** [humhub/humhub#4969]
### What steps will reproduce the problem?

1. Install [announcement module](https://github.com/staxDB/humhub-modules-announcements)
2. Get a space with at least 400 registered users with email notification enabled
3. Create new announcement

### What is the expected result?

Each registered user received the notification email with announcement content.

### What do you get instead?

Only some 300-350 registered users get the notification email and there is a timeout error on queue. Other users are never notified by email.

The TTR default value (300s) into **protected/vendor/yiisoft/yii2-queue/src/Queue.php** is reached and in DB (notification table) I can see that emails are sent with speed of 1 mail/seconde so that’s why we got only about 300 emails sent.

### Additional info

- HumHub version : 1.4.4
- PHP version : 7.3
- Operating system : GNU/Linux Debian 10 (buster)
- Announcement module : 0.5

### Logging

```
2021-03-17 08:23:10 [-][-][-][error][queue] Could not execute queued job! Message: The process "'/usr/bin/php7.4' '/var/www/sites/fr/nge/interactifs/protected/yii' 'queue/exec' '43620' '300' '1' '6892' '--color='" exceeded the timeout of 300 seconds. Trace:#0 /var/www/sites/fr/nge/interactifs/protected/vendor/symfony/process/Process.php(421): Symfony\Component\Process\Process->checkTimeout()
#1 /var/www/sites/fr/nge/interactifs/protected/vendor/symfony/process/Process.php(216): Symfony\Component\Process\Process->wait()
#2 /var/www/sites/fr/nge/interactifs/protected/humhub/modules/queue/driver/MySQLCommand.php(61): Symfony\Component\Process\Process->run()
#3 /var/www/sites/fr/nge/interactifs/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(125): humhub\modules\queue\driver\MySQLCommand->handleMessage()
#4 [internal function]: yii\queue\cli\Command->yii\queue\cli\{closure}()
#5 /var/www/sites/fr/nge/interactifs/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(144): call_user_func()
#6 /var/www/sites/fr/nge/interactifs/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83): yii\queue\cli\Queue->handleMessage()
#7 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}()
#8 /var/www/sites/fr/nge/interactifs/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func()
#9 /var/www/sites/fr/nge/interactifs/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker()
#10 /var/www/sites/fr/nge/interactifs/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run()
#11 [internal function]: yii\queue\db\Command->actionRun()
#12 /var/www/sites/fr/nge/interactifs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#13 /var/www/sites/fr/nge/interactifs/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#14 /var/www/sites/fr/nge/interactifs/protected/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction()
#15 /var/www/sites/fr/nge/interactifs/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction()
#16 /var/www/sites/fr/nge/interactifs/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#17 /var/www/sites/fr/nge/interactifs/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#18 /var/www/sites/fr/nge/interactifs/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#19 /var/www/sites/fr/nge/interactifs/protected/yii(29): yii\base\Application->run()
#20 {main}
    in /var/www/sites/fr/nge/interactifs/protected/humhub/modules/queue/Events.php:48
    in /var/www/sites/fr/nge/interactifs/protected/humhub/modules/queue/driver/MySQLCommand.php:68
```

**Comment by kcalvat** [comment]
In solution, we have added the following code into **config/dynamic.php** :
The TTR value need to be as high as registered users to be confiant that each user is notified.

`   'queue' =>
    array (
        'ttr' => 1500, // Max time for anything job handling
    ),
`

**Comment by luke-** [comment]
@kcalvat Thanks for the update. Maybe we should just increase the default time a bit here. Otherwise the admin has to increase this value for large installations or with e.g. slow mail servers.
