### ISSUE TITLE
Setting unknown property: humhub\modules\user\components\User::passwordStrength 

### ISSUE THREAD

**Issue by ITwrx** [humhub/humhub#5148]
### What steps will reproduce the problem?
follow docs here: https://docs.humhub.org/docs/admin/security#password-strength-configuration

### What is the expected result?
normal functioning, but with new user password requirements.

### What do you get instead?

```
yii\base\UnknownPropertyException: Setting unknown property: humhub\modules\user\components\User::passwordStrength in /srv/http/humhub/protected/vendor/yiisoft/yii2/base/Component.php:210
Stack trace:
#0 /srv/http/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('passwordStrengt...', Array)
#1 /srv/http/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(humhub\modules\user\components\User), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /srv/http/humhub/protected/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#4 /srv/http/humhub/protected/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('humhub\\modules\\...', Array, Array)
#5 /srv/http/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\modules\\...', Array, Array)
#6 /srv/http" while reading upstream, client: 192.168.1.1, server: somedomain.org, request: "GET /index.php?r=admin HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "somedomain.org", referrer: "https://somedomain.org/index.php?r=cfiles%2Fbrowse&cguid=1f52cdc4-aa4a-4197-ae31-643f5b8e074c"
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.2
| PHP version      |  7.3.11
| Operating system | arch linux

Thanks

**Comment by luke-** [comment]
Can you please post your configuration here? 
Seems you added the `passwordStrength` to the user `component` instead of the user `module`.

**Comment by ITwrx** [comment]
yes, that was what i did. :) It's working now. thanks.
