### ISSUE TITLE
Generating assets fails 

### ISSUE THREAD

**Issue by superseby2** [humhub/humhub#5226]
### What steps will reproduce the problem?

- running : php yii asset humhub/config/assets.php humhub/config/assets-prod.php

### What is the expected result?
- Command runs smoothly and bundles get created

### What do you get instead?

- command fails with message : 

Loading configuration from 'humhub/config/assets.php'...
Collecting source bundles information...
Creating output bundle 'app':
  Compressing JavaScript files...
Running "uglify:assets" (uglify) task
[D] Task source: /var/www/humhub/node_modules/grunt-contrib-uglify/tasks/uglify.js
>> 1 file created 1.25 MB → 573.53 kB

Done.
  JavaScript files compressed into '/var/www/humhub/protected/humhub/config/../../../static/js/humhub-app.js'.
  Compressing CSS files...
Running "cssmin:target" (cssmin) task
>> 1 file created. 178.41 kB → 165.9 kB

Done.
  CSS files compressed into '/var/www/humhub/protected/humhub/config/../../../static/css/humhub-app.css'.

Creating output bundle 'defer':
  Compressing JavaScript files...
Running "uglify:assets" (uglify) task
[D] Task source: /var/www/humhub/node_modules/grunt-contrib-uglify/tasks/uglify.js
JS_Parse_Error [SyntaxError]: Unexpected token: punc (})
    at JS_Parse_Error.get (eval at <anonymous> (/var/www/humhub/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:84:23)
    at formatError (internal/util/inspect.js:1164:38)
    at formatRaw (internal/util/inspect.js:937:14)
    at formatValue (internal/util/inspect.js:791:10)
    at inspect (internal/util/inspect.js:328:10)
    at formatWithOptions (internal/util/inspect.js:1989:40)
    at console.value (internal/console/constructor.js:308:14)
    at console.log (internal/console/constructor.js:343:61)
    at /var/www/humhub/node_modules/grunt-contrib-uglify/tasks/uglify.js:150:17
    at Array.forEach (<anonymous>) {
  filename: 'humhub-bundle.js.tmp',
  line: 10446,
  col: 4,
  pos: 476209
}

- some bundles seem to be copied alright
- humhub-app.js is created (and seems to be uglify ...) 
- humhub-bundle.js is not created

### Additional info

- Removing : 'jsCompressor' => 'grunt uglify:assets  --from={from} --to={to} -d', in assets.php 
triggers another weirder message : 

sh: java: not found
Error: Unable to compress JavaScript files into '/var/www/humhub/protected/humhub/config/../../../static/js/humhub-bundle.js'.

  
Any help / pointers greatly appreciated.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.0
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by superseby2** [comment]
I think I found the culprit 
  js/humhub/humhub.ui.codemirror.js
  
 Patching it like this makes grunt happy.

     module.export({
-        init
+           init:init
     });
-});

**Comment by samsheridan** [comment]
Changing `init` to `init: init` worked for me as well. This bug is still in the master branch.

**Comment by luke-** [comment]
Hmm, can't reproduce this.

@yurabakhtin Any idea what this could couse the problem?

**Comment by yurabakhtin** [comment]
@luke- I think the problem because the `grunt-contrib-uglify` cannot read ES6 syntax, probably they still use old version of the `uglify-js`, as described here https://stackoverflow.com/questions/38429567/some-es6-features-are-not-understood-by-grunt-uglify-js/44887248, and there it is written since `uglify-js@2.8.29` it works - https://stackoverflow.com/a/45549788.

Currently `master` branch (version 1.9.2 (Unreleased)) uses `"grunt-contrib-uglify": "^5.0"` that uses "uglify-js": "^3.13.3", so I cannot reproduce the error:

<img width="1065" alt="test_yii_asset" src="https://user-images.githubusercontent.com/6995524/133989208-c8812389-19db-403c-a4fe-b70ce107af4d.png">

**Comment by luke-** [comment]
@superseby2 @samsheridan Maybe you're running some old NodeJS version?

**Comment by superseby2** [comment]
Hey guys, 
Sorry for the delay in the response. and thx @yurabakhtin for digging!

The vesion I have : 
 
- Node v12.22.4
- grunt-cli@1.4.3

As for grunt-contrib-uglify.js I guess the one used is the one at humhub_root/node_modules/ ?

If that'is the case, mine seems to be very old indeed  : "version": "2.3.0". 
I usually run a composer install between updates so I am not sure why I have such an old version ? Any hint ?

**Comment by yurabakhtin** [comment]
@superseby2 If you run only `composer install` between updates then only the folder `/protected/vendor` is updated, but the node package `uglify-js` is located inside the folder `/node_modules`, so please try to run `npm install` from site root folder.
