### ISSUE TITLE
"Warning incomplete Setup" Tasks (cron) job - Notifications not seemingly working - showing up hours later.

### ISSUE THREAD

**Issue by randrums** [humhub/humhub#5286]
### What steps will reproduce the problem?
I've tried the steps mentioned in the documentation, such as adding the 
/usr/bin/php /path/to/humhub/protected/yii queue/run --isolate=0
or this
/usr/bin/php /path/to/humhub/protected/yii queue/run >/path/to/queue.log 2>&1

And then I cleared the Cron queue, but I still can't figure out why this error is happening. I'
![image](https://user-images.githubusercontent.com/73252280/132996483-e6fc1eaf-d21d-45eb-bd5e-0aae693d9443.png)

### What is the expected result?
Notifications work and that Red "Warning in complete setup" warning goes away.

### What do you get instead?
No notifications when I do some test replies to some fake users I created.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.1
| PHP version      | 7.3.30
| Operating system | (Shared hosting from A2 Hosting/Linux) - Used Softaculous insatller to install it.

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

yii\base\InvalidConfigException: Unable to determine the entry script file path. in /home/randymed/public_html/protected/vendor/yiisoft/yii2/base/Request.php:64
Stack trace:
#0 /home/randymed/public_html/protected/vendor/yiisoft/yii2/base/Component.php(140): yii\base\Request->getScriptFile()
#1 /home/randymed/public_html/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(533): yii\base\Component->__get('scriptFile')
#2 /home/randymed/public_html/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(340): yii\console\controllers\HelpController->getScriptName()
#3 /home/randymed/public_html/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#4 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)
#5 /home/randymed/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /home/randymed/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#7 /home/randymed/public_html/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('', Array)
#8 /home/randymed/public_html/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('', Array)
#9 /home/randymed/public_html/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('', Array)
#10 /home/randymed/public_html/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('', Array)
#11 /home/randymed/public_html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 /home/randymed/public_html/protected/yii(28): yii\base\Application->run()
#13 {main}

**Comment by ArchBlood** [comment]
As the error suggests you're not defining the path to your HumHub instance;

e.g. `/path/to/humhub/protected/yii` must be **_your_** file path to the directory of `/protected/yii` which in your case it would be `/home/randymed/public_html/protected/yii` if you're using say CPanel then you would want to be using `/usr/local/bin/php` not `/usr/bin/php`, I would also like to note that `--isolate=0` shouldn't be needed for most up-to-date CPanel/DirectAdmin panels

So in conclusion your Cron Job should be;
1.  `/usr/local/bin/php /home/randymed/public_html/protected/yii queue/run >/dev/null 2>&1`
or
2. `/usr/local/bin/php /home/randymed/public_html/protected/yii queue/run >/dev/null 2>&1 --isolate=0`

I would also like to note that most shared hosting providers limit their scheduled tasks to 5 minutes per run, so instead of using the default (i.e. `* * * * *`) mentioned in the docs use `*/5 * * * *`
> https://docs.humhub.org/docs/admin/cron-jobs

**Comment by ArchBlood** [comment]
As for the screenshot shown it is the `cron/run` that is causing the error and it should be done similar to the `queue/run` for the path (i.e. `/usr/local/bin/php /home/randymed/public_html/protected/yii cron/run >/dev/null 2>&1`)

**Comment by randrums** [comment]
Thank you so much for the detailed response. I have changed the settings to fix that area / path I did incorrectly. I'm still getting the error, but maybe it will goa away on the next "cron job". This is the area I have in my "Current Cron Jobs" section of my A2 Hosting cPanel. I don't have VPS, so I can't really change anything except here:

![image](https://user-images.githubusercontent.com/73252280/132999350-28bd3c55-4df9-45a4-aa95-f5520971b4e2.png)

**Comment by randrums** [comment]
I spoke too soon, the error is gone! Thank you so much for your help. I can't thank you enough.

**Comment by randrums** [comment]
The other part I feel like I need to improve with my humhub install, is the notifications. I have a dummy user I created to post replies, to my normal user account, but the notification area / bell at the top never shows any new notifications right away. It maybe takes 60 seconds. NOT a deal-breaker obviously - as I haven't found a better self-hosted Social network than HumHub in all the others I've tried / OSSN, Elgg, BuddyPress, etc.

**Comment by ArchBlood** [comment]
> The other part I feel like I need to improve with my humhub install, is the notifications. I have a dummy user I created to post replies, to my normal user account, but the notification area / bell at the top never shows any new notifications right away. It maybe takes 60 seconds. NOT a deal-breaker obviously - as I haven't found a better self-hosted Social network than HumHub in all the others I've tried / OSSN, Elgg, BuddyPress, etc.

Sorry in advance, sadly I do not have any solutions for the notifications area, we can only hope that it will be done in the core soon

**Comment by randrums** [comment]
Thank you again!

**Comment by randrums** [comment]
> > The other part I feel like I need to improve with my humhub install, is the notifications. I have a dummy user I created to post replies, to my normal user account, but the notification area / bell at the top never shows any new notifications right away. It maybe takes 60 seconds. NOT a deal-breaker obviously - as I haven't found a better self-hosted Social network than HumHub in all the others I've tried / OSSN, Elgg, BuddyPress, etc.
> 
> Sorry in advance, sadly I do not have any solutions for the notifications area, we can only hope that it will be done in the core soon

Thank you!

**Comment by FuXXz** [comment]
Hello everyone,
I have the same problem, however, my crons are running correctly. However, the message in the humhub does not disappear.
What can I do?

### **This are my Plesk Cron Jobs**
![Plesk_Cron1](https://github.com/humhub/humhub/assets/9010594/75f2a564-faad-4c4e-a1a4-61d365cde857)
![Plesk_Cron2](https://github.com/humhub/humhub/assets/9010594/7bbf05a2-274d-48f6-a33f-2e788fefcf23)
### **And the Info which appears, after running the Cron manually**
![Plesk_Cron_Run_message1](https://github.com/humhub/humhub/assets/9010594/970aabbd-adfc-4dfe-a709-14b5ee522ba9)
![Plesk_Cron_Run_message2](https://github.com/humhub/humhub/assets/9010594/e9f5f320-482d-4e00-a638-62389caabec7)

### **And the persistent humhub message**
![Humhub_message1](https://github.com/humhub/humhub/assets/9010594/6ce9d75a-9ae1-4019-bd81-84d906b3766c)
![Humhub_message2](https://github.com/humhub/humhub/assets/9010594/1c0bc296-5b74-462a-b176-3be2ef6750b0)

**Comment by felixhahnweilheim** [comment]
You should use cron/run not cron/daily

**Comment by FuXXz** [comment]
It doesnt work. I have still the notification in Humhub

I copied the "daily" from the humhub documentation
https://docs.humhub.org/docs/admin/cron-jobs/#plesk

**Comment by felixhahnweilheim** [comment]
Second error: you set the tasks to daily and hourly but both should be every minute (* * * * *)

At least this is how it works in my Plesk Installation.

**Comment by FuXXz** [comment]
Ok, that works. I set up Cron Stile *****
THX
The documentation is just wrong.

**Comment by amaret0** [comment]
Got the same error (using it with cPanel on Namecheap)
_Warning incomplete setup!
The cron job for the background jobs (queue) does not seem to work properly._

Here are my cronjobs:
![image](https://github.com/user-attachments/assets/1a8b5a7f-5d0e-427b-97ce-ecc95fae465b)

Please help.
(yesterday discovered HumHub and I like it very much).

Thank you.

**Comment by marc-farre** [comment]
@amaret0 Please take a look at:
- https://docs.humhub.org/docs/admin/cron-jobs
- https://community.humhub.com/s/installation-and-setup/wiki/51/cron-job-setup
If you still have issues with cron jobs, post your issue on https://community.humhub.com/s/installation-and-setup/ and we'll try to help you.
