### ISSUE TITLE
Cron Job is not working

### ISSUE THREAD

**Issue by jazzx7** [humhub/humhub#5308]
I have installed the latest version of HumHub, added Cron Job as following

![image](https://user-images.githubusercontent.com/91319514/134657634-dbbbd641-1272-4298-86c1-a2c514d7c8dd.png)

But I still got the error **Warning incomplete setup!** The cron job for the regular tasks (cron) does not seem to work properly.

When I click on **/yii corn/run** outputs, I get the following errors:

An Error occurred while handling another error: Error: Class "humhub\modules\rest\components\BaseController" not found in /home/u650978191/domains/almajles.live/public_html/protected/modules/mail/controllers/rest/EntryController.php:21 Stack trace: #0 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/BaseYii.php(293): include() #1 [internal function]: yii\BaseYii::autoload() #2 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(279): class_exists() #3 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(257): yii\console\controllers\HelpController->validateControllerClass() #4 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(240): yii\console\controllers\HelpController->getModuleCommands() #5 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(172): yii\console\controllers\HelpController->getModuleCommands() #6 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/UnknownCommandException.php(77): yii\console\controllers\HelpController->getCommands() #7 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/ErrorHandler.php(36): yii\console\UnknownCommandException->getSuggestedAlternatives() #8 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\console\ErrorHandler->renderException() #9 [internal function]: yii\base\ErrorHandler->handleException() #10 {main} Previous exception: yii\base\InvalidRouteException: Unable to resolve the request "corn/run". in /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/base/Module.php:543 Stack trace: #0 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction() #1 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction() #2 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest() #3 /home/u650978191/domains/almajles.live/public_html/protected/yii(29): yii\base\Application->run() #4 {main} Next yii\console\UnknownCommandException: Unknown command "corn/run". in /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/Application.php:184 Stack trace: #0 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction() #1 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest() #2 /home/u650978191/domains/almajles.live/public_html/protected/yii(29): yii\base\Application->run() #3 {main}

I tried to consult the community and based on their advice I have applied the following fixes:

Fix CLI error when no REST module is installed #244
https://github.com/humhub/calendar/pull/244/commits/6e9e46adf99ae23a04ef153dddd23db5451379e7

Fix CLI error when no REST module is installed #231
https://github.com/humhub/mail/pull/231/commits/31317c8a298219a73e7b9237d1b80d7a5f859fda

Fix CLI error when no REST module is installed #177
https://github.com/humhub/wiki/pull/177/commits/52d1246fd76fd76d95867ac952bd5ed235eb85c3

Fix CLI error when no REST module is installed #157
https://github.com/humhub/tasks/pull/157/commits/768b9f618956c8115fd888a6e6ae974647914d8b?file-filters%5B%5D=

But with no luck.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.1
| PHP version      |  8.0.7
| Operating system | C-Panel

Log Errors 

ERROR  Fri, 24 Sep 2021 10:14:02 +0000 yii\console\UnknownCommandException
yii\base\InvalidRouteException: Unable to resolve the request "corn/run". in /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction()
#1 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction()
#2 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#3 /home/u650978191/domains/almajles.live/public_html/protected/yii(29): yii\base\Application->run()
#4 {main}

Next yii\console\UnknownCommandException: Unknown command "corn/run". in /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/Application.php:184
Stack trace:
#0 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction()
#1 /home/u650978191/domains/almajles.live/public_html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#2 /home/u650978191/domains/almajles.live/public_html/protected/yii(29): yii\base\Application->run()
#3 {main}

I appreciate your help with this. Thank you!

**Comment by luke-** [comment]
There is a typo.

`corn` --> `cron`
