### ISSUE TITLE
PHP Deprecated Warning in ListController.php

### ISSUE THREAD

**Issue by onyxnz** [humhub/humhub#5442]
### What steps will reproduce the problem?
In a Space with Tasks enabled, Click Tasks
### What is the expected result?
Form to handle tasks
### What do you get instead?
Crash 
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.2
| PHP version      |  8.0.13
| Operating system | Archlinux x64

yii\base\ErrorException: Required parameter $offset follows optional parameter $id in /home/onyx/htdocs/sites/community.freenz.org/protected/modules/tasks/controllers/ListController.php:124
Stack trace:
#0 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/BaseYii.php(293): yii\web\ErrorHandler->handleError(code: '...', message: '...', file: '...', line: '...')
#1 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/base/Module.php(643): yii\BaseYii::autoload(className: '...')
#2 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/base/Module.php(643): ::class_exists(class: '...')
#3 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/base/Module.php(602): humhub\modules\tasks\Module->createControllerByID(id: '...')
#4 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/base/Module.php(594): humhub\modules\tasks\Module->createController(route: '...')
#5 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/base/Module.php(528): humhub\components\Application->createController(route: '...')
#6 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/web/Application.php(104): humhub\components\Application->runAction(route: '...', params: '...')
#7 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/base/Application.php(392): humhub\components\Application->handleRequest(request: '...')
#8 /home/onyx/htdocs/sites/community.freenz.org/index.php(25): humhub\components\Application->run()
#9 {main}

I am aware that I can turn off these warnings, and this is just my development machine, running very latest PHP; just thought you needed to know.

**Comment by onyxnz** [comment]
Merely altering line 124 to 
public function actionShowMoreCompleted($id = null, $offset = false)
is sufficient.
