### ISSUE TITLE
Migration Problem

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5453]
We should avoid to use the `Group` model in the migration. This causes such errors:

```
Yii Migration Tool (based on Yii v2.0.40)

Total 15 new migrations to be applied:
	m201228_064513_default_group
	m210111_105355_hash
	m210203_122333_profilePermissions
	m210204_054203_fix_settings_unique_index
	m210211_051243_container_tag
	m210217_055359_protected_group
	m210310_103412_fix_hash
	m210331_115144_default_timezone
	m210506_060737_profile_field_directory_filter
	m210721_055137_content_locked_comments
	m210722_180001_dbfix
	m210727_102150_follow_friend
	m210924_114847_container_blocked_users
	m211022_152413_file_history
	m211124_180441_admin_group_label

Apply the above migrations? (yes|no) [no]:y
*** applying m201228_064513_default_group
    > add column is_default_group boolean NOT NULL DEFAULT 0 AFTER `is_admin_group` to table group ... done (time: 0.013s)
Exception: Getting unknown property: humhub\modules\user\models\Group::is_protected (/srv/humhub/protected/vendor/yiisoft/yii2/base/Component.php:155)
#0 /srv/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('is_protected')
#1 /srv/humhub/protected/vendor/yiisoft/yii2/validators/Validator.php(258): yii\db\BaseActiveRecord->__get('is_protected')
#2 /srv/humhub/protected/vendor/yiisoft/yii2/base/Model.php(368): yii\validators\Validator->validateAttributes(Object(humhub\modules\user\models\Group), Array)
#3 /srv/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(670): yii\base\Model->validate(Array)
#4 /srv/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(681): yii\db\ActiveRecord->update(true, NULL)
#5 /srv/humhub/protected/humhub/migrations/m201228_064513_default_group.php(40): yii\db\BaseActiveRecord->save()
#6 /srv/humhub/protected/vendor/yiisoft/yii2/db/Migration.php(114): m201228_064513_default_group->safeUp()
#7 /srv/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): yii\db\Migration->up()
#8 /srv/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp('m201228_064513_...')
#9 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#10 /srv/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#12 /srv/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('up', Array)
#13 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('up', Array)
#14 /srv/humhub/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('migrate/up', Array)
#15 /srv/humhub/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('migrate/up', Array)
#16 /srv/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request))
#17 /srv/www/htdocs/trafohub/yii.php(38): yii\base\Application->run()
#18 {main}
*** failed to apply m201228_064513_default_group (time: 0.033s)
```

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5455: please note I didn't exclude the model `Group` from the migration because the error appeared only on call the method `$group->save()`, so I just did to use SQL commands instead of the method.

**Comment by luke-** [comment]
@yurabakhtin Thanks I think that works!
