### ISSUE TITLE
Empty RichText Error

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5465]
Logged Error: 
```
Could not execute queued job! Message: Argument 1 passed to humhub\modules\content\widgets\richtext\AbstractRichText::convert() must be of the type string, null given, called in /-hidden-/humhub/protected/humhub/modules/content/widgets/richtext/AbstractRichText.php on line 380 Trace:#0 /-hidden-/humhub/protected/humhub/modules/content/widgets/richtext/AbstractRichText.php(380): humhub\modules\content\widgets\richtext\AbstractRichText::convert()
#1 /-hidden-/humhub/protected/humhub/modules/content/activities/views/mail/created.php(17): humhub\modules\content\widgets\richtext\AbstractRichText::preview()
#2 /-hidden-/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/otf/de...')
#3 /-hidden-/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#4 /-hidden-/humhub/protected/humhub/components/rendering/ViewPathRenderer.php(83): yii\base\View->renderFile()
#5 /-hidden-/humhub/protected/humhub/components/rendering/LayoutRenderer.php(53): humhub\components\rendering\ViewPathRenderer->renderView()
#6 /-hidden-/humhub/protected/humhub/modules/activity/components/MailSummary.php(80): humhub\components\rendering\LayoutRenderer->render()
#7 /-hidden-/humhub/protected/humhub/modules/activity/components/MailSummaryProcessor.php(67): humhub\modules\activity\components\MailSummary->send()
#8 /-hidden-/humhub/protected/humhub/modules/activity/jobs/SendMailSummary.php(59): humhub\modules\activity\components\MailSummaryProcessor::process()
#9 /-hidden-/humhub/protected/humhub/modules/queue/ActiveJob.php(33): humhub\modules\activity\jobs\SendMailSummary->run()
#10 /-hidden-/humhub/protected/vendor/yiisoft/yii2-queue/src/Queue.php(246): humhub\modules\queue\ActiveJob->execute()
#11 /-hidden-/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage()
#12 /-hidden-/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute()
#13 [internal function]: yii\queue\cli\Command->actionExec()
#14 /-hidden-/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#15 /-hidden-/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#16 /-hidden-/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction()
#17 /-hidden-/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction()
#18 /-hidden-/humhub/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction()
#19 /-hidden-/humhub/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction()
#20 /-hidden-/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#21 /-hidden-/bin/yii.php(27): yii\base\Application->run()
#22 {main}
```

Seems like an error was thrown when the content is empty. Can we improve this a bit so that there is not a fatal error here?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5467.
