### ISSUE TITLE
1.11 Beta OEmbed Error

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/humhub#5604]
### What steps will reproduce the problem?
I've updated my git based installation to v1.11 but the Dashboard Stream can not be initialised with the following error:

```
TypeError: Cannot access offset of type string on string in /var/www/humhub-dev/protected/humhub/models/UrlOembed.php:364
Stack trace:
#0 /var/www/humhub-dev/protected/humhub/models/UrlOembed.php(354): humhub\models\UrlOembed::getProviderByUrl()
#1 /var/www/humhub-dev/protected/humhub/models/UrlOembed.php(159): humhub\models\UrlOembed::hasOEmbedSupport()
#2 /var/www/humhub-dev/protected/humhub/modules/content/widgets/richtext/extensions/oembed/OembedExtension.php(75): humhub\models\UrlOembed::getOEmbed()
#3 /var/www/humhub-dev/protected/humhub/modules/content/widgets/richtext/extensions/oembed/OembedExtension.php(38): humhub\modules\content\widgets\richtext\extensions\oembed\OembedExtension::parseOembeds()
#4 /var/www/humhub-dev/protected/humhub/modules/content/widgets/richtext/ProsemirrorRichText.php(166): humhub\modules\content\widgets\richtext\extensions\oembed\OembedExtension->onBeforeOutput()
#5 /var/www/humhub-dev/protected/humhub/components/Widget.php(63): humhub\modules\content\widgets\richtext\ProsemirrorRichText->run()
#6 [internal function]: humhub\components\Widget::widget()
#7 /var/www/humhub-dev/protected/humhub/modules/content/widgets/richtext/RichText.php(64): call_user_func()
#8 /var/www/humhub-dev/protected/humhub/modules/content/widgets/richtext/AbstractRichText.php(323): humhub\modules\content\widgets\richtext\RichText::widget()
#9 /var/www/humhub-dev/protected/modules/tasks/widgets/views/wallEntry.php(32): humhub\modules\content\widgets\richtext\AbstractRichText::output()
#10 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/View.php(348): require('...')
#11 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#12 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#13 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/Widget.php(237): yii\base\View->render()
#14 /var/www/humhub-dev/protected/modules/tasks/widgets/WallEntry.php(60): yii\base\Widget->render()
#15 /var/www/humhub-dev/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(187): humhub\modules\tasks\widgets\WallEntry->renderContent()
#16 /var/www/humhub-dev/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(131): humhub\modules\content\widgets\stream\WallStreamEntryWidget->renderBody()
#17 /var/www/humhub-dev/protected/humhub/components/Widget.php(63): humhub\modules\content\widgets\stream\StreamEntryWidget->run()
#18 [internal function]: humhub\components\Widget::widget()
#19 /var/www/humhub-dev/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(91): call_user_func()
#20 /var/www/humhub-dev/protected/humhub/modules/stream/actions/StreamEntryResponse.php(80): humhub\modules\content\widgets\stream\StreamEntryWidget::renderStreamEntry()
#21 /var/www/humhub-dev/protected/humhub/modules/stream/actions/Stream.php(415): humhub\modules\stream\actions\StreamEntryResponse::getAsArray()
#22 /var/www/humhub-dev/protected/humhub/modules/stream/actions/Stream.php(370): humhub\modules\stream\actions\Stream->getStreamEntryResult()
#23 /var/www/humhub-dev/protected/humhub/modules/stream/actions/Stream.php(349): humhub\modules\stream\actions\Stream->addResponseEntries()
#24 [internal function]: humhub\modules\stream\actions\Stream->run()
#25 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array()
#26 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\Action->runWithParams()
#27 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#28 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#29 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#30 /var/www/humhub-dev/index.php(25): yii\base\Application->run()
#31 {main} 
```

I think I have an embedded YouTube video somewhere in the Stream but I haven't changed the default OEmbed settings.
If I now try to go to the OEmbed settings I also get an error:

```
TypeError: Cannot access offset of type string on string in /var/www/humhub-dev/protected/humhub/modules/admin/views/setting/oembed.php:37
Stack trace:
#0 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#2 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#3 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/Controller.php(410): yii\base\View->render()
#4 /var/www/humhub-dev/protected/humhub/modules/admin/controllers/SettingController.php(316): yii\base\Controller->render()
#5 [internal function]: humhub\modules\admin\controllers\SettingController->actionOembed()
#6 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#7 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#8 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#9 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#10 /var/www/humhub-dev/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#11 /var/www/humhub-dev/index.php(25): yii\base\Application->run()
#12 {main} 
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11 beta
| PHP version      |  8.0.16
| Operating system | Ubuntu 20.04

**Comment by felixhahnweilheim** [comment]
My mistake. I forgot the database migration. Sorry.
