### ISSUE TITLE
Logging-related errors in app.log, no log messages in "Administration > Information > Logging"

### ISSUE THREAD

**Issue by heinrich-ulbricht** [humhub/humhub#5650]
### What steps will reproduce the problem?

Not sure since I discovered the problem recently and don't know exactly when it appeared. Initially I opened #5649 since app.log was missing as well but at least this seems to be solved. The browser UI is still empty though.

### What is the expected result?

Log messages being shown in _Administration > Information > Logging_

### What do you get instead?

No log messages in _Administration > Information > Logging_. But errors (well, warnings) in app.log:

```
2022-04-21 00:24:02 [-][-][-][warning][yii\log\Dispatcher::dispatch] Unable to send log via yii\log\DbTarget: Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No such file or directory' 

in /var/www/humhub/protected/vendor/yiisoft/yii2/db/Connection.php:642

Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Connection.php(1030): yii\db\Connection->open()
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Connection.php(1017): yii\db\Connection->getMasterPdo()
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Schema.php(463): yii\db\Connection->getSlavePdo()
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Connection.php(909): yii\db\Schema->quoteValue()
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(211): yii\db\Connection->quoteValue()
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1123): yii\db\Command->getRawSql()
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1088): yii\db\Command->logQuery()
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/log/DbTarget.php(93): yii\db\Command->execute()
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/log/Target.php(158): yii\log\DbTarget->export()
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/log/Dispatcher.php(191): yii\log\Target->collect()
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/log/Logger.php(177): yii\log\Dispatcher->dispatch()
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(137): yii\log\Logger->flush()
#12 [internal function]: yii\base\ErrorHandler->handleException()
#13 {main}
```

Looks like this could be the cause. Maybe somebody can tell what's broken here?

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10.4
| PHP version      | 7.4
| Operating system | Raspbian GNU/Linux 10 (buster)

**Comment by heinrich-ulbricht** [comment]
For heavens sake. Logs are now showing. Maybe the latest Apache restart did help? Who knows.
