### ISSUE TITLE
Error updating 1.10.4 to 1.11.0: "Access to undeclared static property: yii\helpers\Json::$keepObjectType"

### ISSUE THREAD

**Issue by heinrich-ulbricht** [humhub/humhub#5652]
### What steps will reproduce the problem?

Update an instance from 1.10.4 to 1.11.0. At least on my instance this caused an error.

### What is the expected result?

I expect the update to succeed.

### What do you get instead?

In the step "Installing files" (IIRC) an error message appeared. I believe it was an "internal server error".

The log shows:

```
Error: Access to undeclared static property: yii\helpers\Json::$keepObjectType in /var/www/social/protected/vendor/yiisoft/yii2/web/JsonResponseFormatter.php:128
Stack trace:
#0 /var/www/social/protected/vendor/yiisoft/yii2/web/JsonResponseFormatter.php(112): yii\web\JsonResponseFormatter->formatJson()
#1 /var/www/social/protected/vendor/yiisoft/yii2/web/Response.php(1099): yii\web\JsonResponseFormatter->format()
#2 /var/www/social/protected/vendor/yiisoft/yii2/web/Response.php(344): yii\web\Response->prepare()
#3 /var/www/social/protected/vendor/yiisoft/yii2/base/Application.php(398): yii\web\Response->send()
#4 /var/www/social/index.php(25): yii\base\Application->run()
#5 {main} 
```

Despite this error the instance shows being on version 1.11.0. Should I restore the old version (I have a backup)? Or can this error be ignored?

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10.4 / 1.11.0
| PHP version      | 7.4
| Operating system | Raspbian GNU/Linux 10 (buster)

**Comment by heinrich-ulbricht** [comment]
The log is filling with those:

```
yii\base\ErrorException: Illegal string offset 'pattern' in /var/www/social/protected/humhub/models/UrlOembed.php:365
Stack trace:
#0 /var/www/social/protected/humhub/models/UrlOembed.php(365): yii\base\ErrorHandler->handleError()
#1 /var/www/social/protected/humhub/models/UrlOembed.php(355): humhub\models\UrlOembed::getProviderByUrl()
#2 /var/www/social/protected/humhub/models/UrlOembed.php(160): humhub\models\UrlOembed::hasOEmbedSupport()
#3 /var/www/social/protected/humhub/modules/content/widgets/richtext/extensions/oembed/OembedExtension.php(75): humhub\models\UrlOembed::getOEmbed()
#4 /var/www/social/protected/humhub/modules/content/widgets/richtext/extensions/oembed/OembedExtension.php(38): humhub\modules\content\widgets\richtext\extensions\oembed\OembedExtension::parseOembeds()
#5 /var/www/social/protected/humhub/modules/content/widgets/richtext/ProsemirrorRichText.php(166): humhub\modules\content\widgets\richtext\extensions\oembed\OembedExtension->onBeforeOutput()
#6 /var/www/social/protected/humhub/components/Widget.php(63): humhub\modules\content\widgets\richtext\ProsemirrorRichText->run()
#7 [internal function]: humhub\components\Widget::widget()
#8 /var/www/social/protected/humhub/modules/content/widgets/richtext/RichText.php(64): call_user_func()
#9 /var/www/social/protected/humhub/modules/content/widgets/richtext/AbstractRichText.php(320): humhub\modules\content\widgets\richtext\RichText::widget()
#10 /var/www/social/protected/humhub/modules/post/widgets/views/wallEntry.php(14): humhub\modules\content\widgets\richtext\AbstractRichText::output()
#11 /var/www/social/protected/vendor/yiisoft/yii2/base/View.php(347): require('/var/www/social...')
#12 /var/www/social/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#13 /var/www/social/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#14 /var/www/social/protected/vendor/yiisoft/yii2/base/Widget.php(242): yii\base\View->render()
#15 /var/www/social/protected/humhub/modules/post/widgets/WallEntry.php(32): yii\base\Widget->render()
#16 /var/www/social/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(187): humhub\modules\post\widgets\WallEntry->renderContent()
#17 /var/www/social/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(131): humhub\modules\content\widgets\stream\WallStreamEntryWidget->renderBody()
#18 /var/www/social/protected/humhub/components/Widget.php(63): humhub\modules\content\widgets\stream\StreamEntryWidget->run()
#19 [internal function]: humhub\components\Widget::widget()
#20 /var/www/social/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(91): call_user_func()
#21 /var/www/social/protected/humhub/modules/stream/actions/StreamEntryResponse.php(80): humhub\modules\content\widgets\stream\StreamEntryWidget::renderStreamEntry()
#22 /var/www/social/protected/humhub/modules/stream/actions/Stream.php(415): humhub\modules\stream\actions\StreamEntryResponse::getAsArray()
#23 /var/www/social/protected/humhub/modules/stream/actions/Stream.php(370): humhub\modules\stream\actions\Stream->getStreamEntryResult()
#24 /var/www/social/protected/humhub/modules/stream/actions/Stream.php(349): humhub\modules\stream\actions\Stream->addResponseEntries()
#25 [internal function]: humhub\modules\stream\actions\Stream->run()
#26 /var/www/social/protected/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array()
#27 /var/www/social/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams()
#28 /var/www/social/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#29 /var/www/social/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#30 /var/www/social/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#31 /var/www/social/index.php(25): yii\base\Application->run()
#32 {main} 
```

**Comment by ArchBlood** [comment]
It can be ignored, this happened in the beta ran as well with no problems shown afterward.

**Comment by heinrich-ulbricht** [comment]
@ArchBlood That's good to know. The keepObjectType error, the pattern error (from my comment above), or both?

**Comment by luke-** [comment]
@yurabakhtin Any idea?

**Comment by yurabakhtin** [comment]
@luke- 

> Error: Access to undeclared static property: yii\helpers\Json::$keepObjectType in /var/www/social/protected/vendor/yiisoft/yii2/web/JsonResponseFormatter.php:128

I could not catch the error and don't find this in logs.
I tested with install v1.10.4 on empty DB, then upgrade to v1.11.1:

![update-1 11](https://user-images.githubusercontent.com/6995524/165044270-243f5fbc-157e-4d74-ac1d-10fc44bbbfeb.png)

Log after the upgrade:

![log](https://user-images.githubusercontent.com/6995524/165044342-41c8ef09-be3d-4266-a39d-ec7d3c63ebb5.png)

**Comment by yurabakhtin** [comment]
@luke- 

> `yii\base\ErrorException: Illegal string offset 'pattern' in /var/www/social/protected/humhub/models/UrlOembed.php:365`

To avoid such errors I have done this fix https://github.com/humhub/humhub/pull/5662.

**Comment by heinrich-ulbricht** [comment]
Just as info: I restored from backup after the last update so I will get another chance to update ^^ I'll wait for the "pattern-fix", then try it again - and make more screenshots (if the error is still there).

**Comment by ArchBlood** [comment]
Only way that I catch the error is updating from latest version of 1.9.x to 1.10.x which later didn't show till 1.11 beta 1

**Comment by luke-** [comment]
The problem is that the class attribute would be added to Yii only with version 2.0.44.
During the update the classes are replaced and it can be that some classes are still loaded or in the cache.

I don't know if the problem is relevant and the logged error is really critical.

**Comment by heinrich-ulbricht** [comment]
Note: same error pattern when updating from 1.11.0 to 1.11.1. From 1.11.1 to 1.11.2 it worked without error.
