### ISSUE TITLE
Improve Module Loading Error Handling

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5659]
### What steps will reproduce the problem?

See problem here: https://community.humhub.com/content/perma?id=254681

### What is the expected result?

Skipped module, entry in error log

### What do you get instead?

Fatal error

**Theme Dropdown / Settings -> Appearence**

```
FEHLER  Sat, 23 Apr 2022 08:14:48 +0200 yii\base\InvalidConfigException
yii\base\InvalidConfigException: Object configuration must be an array containing a "class" or "__class" element. in /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/BaseYii.php:368
Stack trace:
#0 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/Module.php(445): yii\BaseYii::createObject()
#1 /path_to_humhub/humhub/protected/humhub/modules/ui/view/helpers/ThemeHelper.php(45): yii\base\Module->getModule()
#2 /path_to_humhub/humhub/protected/humhub/modules/admin/models/forms/DesignSettingsForm.php(128): humhub\modules\ui\view\helpers\ThemeHelper::getThemes()
#3 /path_to_humhub/humhub/protected/humhub/modules/admin/views/setting/design.php(40): humhub\modules\admin\models\forms\DesignSettingsForm->getThemes()
#4 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/View.php(347): require('/data/web/e1063...')
#5 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#6 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#7 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render()
#8 /path_to_humhub/humhub/protected/humhub/modules/admin/controllers/SettingController.php(246): yii\base\Controller->render()
#9 [internal function]: humhub\modules\admin\controllers\SettingController->actionDesign()
#10 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#11 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#12 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#13 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#14 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#15 /path_to_humhub/humhub/index.php(26): yii\base\Application->run()
#16 {main}
``` 
**Permission Grid Widget**
```
FEHLER  Sat, 23 Apr 2022 08:22:23 +0200 yii\base\InvalidConfigException
yii\base\InvalidConfigException: Object configuration must be an array containing a "class" or "__class" element. in /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/BaseYii.php:368
Stack trace:
#0 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/Module.php(445): yii\BaseYii::createObject()
#1 /path_to_humhub/humhub/protected/humhub/modules/user/components/PermissionManager.php(381): yii\base\Module->getModule()
#2 /path_to_humhub/humhub/protected/humhub/modules/user/components/PermissionManager.php(444): humhub\modules\user\components\PermissionManager->getPermissions()
#3 /path_to_humhub/humhub/protected/humhub/modules/user/widgets/PermissionGridEditor.php(104): humhub\modules\user\components\PermissionManager->createPermissionArray()
#4 /path_to_humhub/humhub/protected/humhub/modules/user/widgets/PermissionGridEditor.php(64): humhub\modules\user\widgets\PermissionGridEditor->getDataProvider()
#5 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\user\widgets\PermissionGridEditor->init()
#6 [internal function]: yii\base\BaseObject->__construct()
#7 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#8 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#9 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#10 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(143): yii\BaseYii::createObject()
#11 /path_to_humhub/humhub/protected/humhub/modules/user/views/account/permissions.php(41): yii\base\Widget::widget()
#12 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/View.php(347): require('/data/web/e1063...')
#13 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#14 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#15 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render()
#16 /path_to_humhub/humhub/protected/humhub/modules/user/controllers/AccountController.php(212): yii\base\Controller->render()
#17 [internal function]: humhub\modules\user\controllers\AccountController->actionPermissions()
#18 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#19 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#20 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#21 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#22 /path_to_humhub/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#23 /path_to_humhub/humhub/index.php(26): yii\base\Application->run()
#24 {main}
```

Also on ThemeBuilder 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5663

I tested all modules from the screenshot below except of `auto-patch` because I don't find where it can be downloaded, I find only this page https://www.humhub.com/en/marketplace/auto-patch/, so probably the module has the issue
![image](https://user-images.githubusercontent.com/6995524/165098058-17b97594-b2c8-41c2-bc39-157791d5d130.png)

In order to reproduce the error I just added a code like `Yii::createObject(['a' => 'b']);` in a module init method.

**Comment by luke-** [comment]
Seems some users have Problems, because there used the `directory` module in the configuration files.
With v1.11 we completetly removed it.

@yurabakhtin Any idea how to solve?

**Comment by luke-** [comment]
@yurabakhtin Lets integrate your PR into Develop v1.12

**Comment by yurabakhtin** [comment]
@luke- 

> Seems some users have Problems, because there used the `directory` module in the configuration files.
With v1.11 we completetly removed it.
>
> Any idea how to solve?

Could you tell me more details where and how the `directory` module is used in the configuration files?

> Lets integrate your PR into Develop v1.12

Ok, I change base to `develop` for the PR.

**Comment by yurabakhtin** [comment]
@luke- I have debugged the case with config and detected config should have the option `class` like this:

```php
return [
    'modules' => [
        'directory' => [
            'class' => humhub\modules\directory\Module::class,
            'guestAccess' => false
        ]
    ]
];
```

![class_config_option](https://user-images.githubusercontent.com/6995524/165458451-acf7827f-a304-4242-9cd9-f4a453d7be66.png)

**Comment by dantefromhell** [comment]
> Seems some users have Problems, because there used the directory module in the configuration files.
> With v1.11 we completetly removed it.

I ran into exactly this issue, my `protected/config/common.php` contained the following section
```
    'directory' =>
    array (
      'active' => true,
      'guestAccess' => false,
    ),
```

I missed reviewing my configuration during the upgrade as the change to remove the `directory` module was not listed in the release notes of 1.11 either. At least for me, that would have been helpful.
