### ISSUE TITLE
What is happening?

### ISSUE THREAD

**Issue by marlonbjj** [humhub/humhub#5677]
Im receving this message when I try to post in a space

`
yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\space\models\Space::profile in /home/cromoysi/public_html/protected/vendor/yiisoft/yii2/base/Component.php:155
Stack trace:
#0 /home/cromoysi/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('profile')
#1 /home/cromoysi/public_html/protected/humhub/modules/content/widgets/stream/views/wallStreamEntryHeader.php(53): yii\db\BaseActiveRecord->__get('profile')
#2 /home/cromoysi/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/cromoysi/...')
#3 /home/cromoysi/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/cromoysi/...', Array)
#4 /home/cromoysi/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/cromoysi/...', Array, Object(humhub\modules\post\widgets\WallEntry))
#5 /home/cromoysi/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(237): yii\base\View->render('@content/widget...', Array, Object(humhub\modules\post\widgets\WallEntry))
#6 /home/cromoysi/public_html/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(204): yii\base\Widget->render('@content/widget...', Array)
#7 /home/cromoysi/public_html/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(188): humhub\modules\content\widgets\stream\WallStreamEntryWidget->renderHeader()
#8 /home/cromoysi/public_html/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(131): humhub\modules\content\widgets\stream\WallStreamEntryWidget->renderBody()
#9 /home/cromoysi/public_html/protected/humhub/components/Widget.php(63): humhub\modules\content\widgets\stream\StreamEntryWidget->run()
#10 [internal function]: humhub\components\Widget::widget(Array)
#11 /home/cromoysi/public_html/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(91): call_user_func('humhub\\modules\\...', Array)
#12 /home/cromoysi/public_html/protected/humhub/modules/stream/actions/StreamEntryResponse.php(80): humhub\modules\content\widgets\stream\StreamEntryWidget::renderStreamEntry(Object(humhub\modules\post\models\Post), NULL, Array)
#13 /home/cromoysi/public_html/protected/humhub/modules/content/widgets/WallCreateContentForm.php(149): humhub\modules\stream\actions\StreamEntryResponse::getAsArray(Object(humhub\modules\content\models\Content))
#14 /home/cromoysi/public_html/protected/humhub/modules/post/controllers/PostController.php(44): humhub\modules\content\widgets\WallCreateContentForm::create(Object(humhub\modules\post\models\Post), Object(humhub\modules\space\models\Space))
#15 [internal function]: humhub\modules\post\controllers\PostController->humhub\modules\post\controllers\{closure}(Object(yii\db\Connection))
#16 /home/cromoysi/public_html/protected/vendor/yiisoft/yii2/db/Connection.php(801): call_user_func(Object(Closure), Object(yii\db\Connection))
#17 /home/cromoysi/public_html/protected/humhub/modules/post/controllers/PostController.php(45): yii\db\Connection->transaction(Object(Closure))
#18 [internal function]: humhub\modules\post\controllers\PostController->actionPost()
#19 /home/cromoysi/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /home/cromoysi/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#21 /home/cromoysi/public_html/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('post', Array)
#22 /home/cromoysi/public_html/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('post/post/post', Array)
#23 /home/cromoysi/public_html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#24 /home/cromoysi/public_html/index.php(25): yii\base\Application->run()
#25 {main}
`

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10.4
| PHP version      |  7.4

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Any custom modules? Can you try it with the default theme?

**Comment by marlonbjj** [comment]
> Any custom modules? Can you try it with the default theme?

Yeah. I tried with the orginal theme, but it doesnt works.
This problem started when I updated from 1.10.3 to 1.10.4

**Comment by luke-** [comment]
Have you made any modifications?
In the original file https://github.com/humhub/humhub/blob/v1.10.4/protected/humhub/modules/content/widgets/stream/views/wallStreamEntryHeader.php from the 1.10.4 I can't find any call to "profile".
