### ISSUE TITLE
Could not execute queued job

### ISSUE THREAD

**Issue by vpadhariya** [humhub/humhub#5754]
### What steps will reproduce the problem?
1. When I Edit my profile (editing user profile)
2. The queue job ran and produce the error in logs

### What is the expected result?
1. there should be no errors in the logs after queue is ran

### What do you get instead?
1. I see error in error log after profile is updated and queue job ran.

### Additional info
1. I have properly setup the cron jobs & queue job in command line

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11.2
| PHP version      | 7.4.30
| Operating system | Linux

Error log file is attached.
[error.txt](https://github.com/humhub/humhub/files/8879695/error.txt)

**Comment by luke-** [comment]
Can you manually run the queue runner? `php protected/yii queue/run`

**Comment by vpadhariya** [comment]
@luke- thanks for prompt reply.

I am trying to get SSH access so that I can run command manually and see what is gone wrong.

**Comment by vpadhariya** [comment]
@luke- 

I just get in with SSH.

1. I ran search/rebuild
2. I ran cron/hourly and cron/daily
3. I ran queue/listen --verbose --color

and I see there are no error showing, unsure what was the issue.

I find that do I need to do search/rebuild every after some time?

**Comment by luke-** [comment]
Normally, the Search Rebuild should not be necessary on a regular basis.

When you run the commands manually there are no errors? Also when editing the profile?

**Comment by vpadhariya** [comment]
When I ran command there is no error even after updating the profile.

**Comment by luke-** [comment]
Are you using the same PHP Version in the console vs. crontab vs. web?

**Comment by vpadhariya** [comment]
Yes pho version 7.4 for both web and console

**Comment by luke-** [comment]
Hmm, but if everything works fine when you execute the commands manually in console and cron produces an error - there must be a problem there...

**Comment by vpadhariya** [comment]
> @luke-
> 
> I just get in with SSH.
> 
> 1. I ran search/rebuild
> 2. I ran cron/hourly and cron/daily
> 3. I ran queue/listen --verbose --color
> 
> and I see there are no error showing, unsure what was the issue.
> 
> I find that do I need to do search/rebuild every after some time?

When i did the above, now there are no errors.

**Comment by vpadhariya** [comment]
@luke- 

Got error messages again! and there are lots of it.

Could not execute queued job! Message: The command "'/usr/local/php74/bin/php-cli' '/home/customer/www/intranetteam.yuneco.be/public_html/protected/yii' 'queue/exec' '100' '300' '1' '55249' '--color='" failed.

Exit Code: 255(Unknown error)

Working directory: /home/customer

Output:
================


Error Output:
================
Trace:#0 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(126): yii\queue\cli\Command->handleMessage('100', 'O:41:"humhub\\mo...', '300', 1)
#1 [internal function]: yii\queue\cli\Command->yii\queue\cli\{closure}('100', 'O:41:"humhub\\mo...', '300', 1)
#2 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(144): call_user_func(Object(Closure), '100', 'O:41:"humhub\\mo...', '300', 1)
#3 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83): yii\queue\cli\Queue->handleMessage('100', 'O:41:"humhub\\mo...', '300', 1)
#4 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure))
#5 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#6 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker(Object(Closure))
#7 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false)
#8 [internal function]: yii\queue\db\Command->actionRun()
#9 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#11 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('run', Array)
#12 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('run', Array)
#13 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array)
#14 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array)
#15 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#16 /home/customer/www/intranetteam.yuneco.be/public_html/protected/yii(29): yii\base\Application->run()
#17 {main}

**Comment by vpadhariya** [comment]
And despite setup the cron jobs properly, I am seeing this error.
![screenshot-kenniskringen yuneco be-2022 06 13-18_49_30](https://user-images.githubusercontent.com/570747/173362850-d24c572c-051f-43e6-a7cc-7ccda705e301.png)

**Comment by luke-** [comment]
Can you send an overview of logged erros? Admin -> Information -> Logging?

**Comment by vpadhariya** [comment]
Overview of logged errors means?

**Comment by vpadhariya** [comment]
Here you are. let me know if you want this in a text file
![screenshot-intranetteam yuneco be-2022 06 13-20_46_57](https://user-images.githubusercontent.com/570747/173387137-55b5ddbb-776f-45f8-b3a7-774e7e9f6f22.png)
