### ISSUE TITLE
yii\base\ErrorException: rename(): The first argument to copy() function cannot be a directory

### ISSUE THREAD

**Issue by ddean6232** [humhub/humhub#5848]
**System Information**
```
HumHub docker image mriedmann/humhub:stable
HumHub Version: 1.9.3
Checking HumHub software prerequisites.
 PHP - Version - 7.4.27
 PHP - GD Extension
 PHP - GD Extension - JPEG Support
 PHP - GD Extension - PNG Support
 PHP - INTL Extension
 PHP - INTL Extension - ICU Version (69.1)
 PHP - INTL Extension - ICU Data Version (69.1)
 PHP - EXIF Extension
 PHP - XML Extension
 PHP - FileInfo Extension
 PHP - Multibyte String Functions
 PHP - iconv Extension
 PHP - cURL Extension
 PHP - ZIP Extension
 PHP - OpenSSL Extension
 PHP - ImageMagick Extension
 PHP - GraphicsMagick Extension (Hint: Optional)
 PHP - Memory Limit (64 MB) (Hint: Current limit is: 1 GB)
 PHP - LDAP Support
 PHP - APC(u) Support
 PHP - SQLite3 Support
 PHP - PDO MySQL Extension
 Database driver - MariaDB
 MariaDB - Version - 5.5.5-10.2.36-MariaDB-1:10.2.36+maria~bionic
 MariaDB - Database collation - utf8mb4_unicode_ci
 MariaDB - Table collations - utf8mb4_unicode_ci
 MariaDB - Table engines - InnoDB
 Settings - Time zone
 Permissions - Runtime
 Permissions - Assets
 Permissions - Uploads
 Permissions - Profile Image
 Permissions - Module Directory
 Permissions - Dynamic Config

```
**### What steps will reproduce the problem?**
login HumHub with Admin
Administration menu -> Settings -> Advanced -> Caching -> Cache Backend -> No Caching
Administration menu -> Modules ->install Updater module version 2.1.12
Administration menu -> Update HumHub
Start Update - 1.9.3 to v1.10.3 
Output:
```
 Downloading update package - OK
 Extracting package files - OK
 Validating package - OK
 Preparing system - OK
 Installing files - Error!  An internal server error occurred.
```

**### What is the expected result?**
Update to 1.10.3

**### What do you get instead?**
` Error!  An internal server error occurred.`
Did not update and still operational on 1.9.3

**### Additional info**
```
ERROR  Sun, 21 Aug 2022 10:51:57 -0600 yii\base\ErrorException:2
yii\base\ErrorException: rename(): The first argument to copy() function cannot be a directory in /var/www/localhost/htdocs/protected/modules/updater/libs/UpdatePackage.php:234
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /var/www/localhost/htdocs/protected/modules/updater/libs/UpdatePackage.php(234): rename()
#2 /var/www/localhost/htdocs/protected/modules/updater/modules/packageinstaller/controllers/InstallController.php(82): humhub\modules\updater\libs\UpdatePackage->install()
#3 [internal function]: humhub\modules\updater\modules\packageinstaller\controllers\InstallController->actionInstallFiles()
#4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#7 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#8 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#9 /var/www/localhost/htdocs/index.php(25): yii\base\Application->run()
#10 {main}

```

**Comment by ArchBlood** [comment]
See the following;
https://github.com/mriedmann/humhub-docker/issues/227
