### ISSUE TITLE
Error saving non-daily event

### ISSUE THREAD

**Issue by crowtc** [humhub/humhub#588]
Adding an all-day event seems to work normally, but when I try to add an event that has a start and end time, it fails and the error below is logged.

======================================================
Trying to get property of non-object (/home/site/site.org/hub/protected/modules/calendar/models/CalendarEntry.php:335) Stack trace: #0 /home/site/site.org/hub/protected/vendors/yii/db/ar/CActiveFinder.php(167): CJoinElement->afterFind() #1 /home/site/site.org/hub/protected/vendors/yii/db/ar/CActiveRecord.php(281): CActiveFinder->lazyFind() #2 /home/site/site.org/hub/protected/vendors/yii/db/ar/CActiveRecord.php(143): CalendarEntryParticipant->getRelated() #3 /home/site/site.org/hub/protected/modules/calendar/models/CalendarEntryParticipant.php(108): CalendarEntryParticipant->__get() #4 /home/site/site.org/hub/protected/vendors/yii/db/ar/CActiveRecord.php(1097): CalendarEntryParticipant->afterSave() #5 /home/site/site.org/hub/protected/vendors/yii/db/ar/CActiveRecord.php(806): CalendarEntryParticipant->insert() #6 /home/site/site.org/hub/protected/modules/calendar/models/CalendarEntry.php(377): CalendarEntryParticipant->save() #7 /home/site/site.org/hub/protected/vendors/yii/db/ar/CActiveRecord.php(1097): CalendarEntry->afterSave() #8 /home/site/site.org/hub/protected/vendors/yii/db/ar/CActiveRecord.php(806): CalendarEntry->insert() #9 /home/site/site.org/hub/protected/modules/calendar/controllers/EntryController.php(184): CalendarEntry->save() #10 /home/site/site.org/hub/protected/vendors/yii/web/actions/CInlineAction.php(49): EntryController->actionEdit() #11 /home/site/site.org/hub/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams() #12 /home/site/site.org/hub/protected/vendors/yii/web/filters/CFilterChain.php(133): EntryController->runAction() #13 /home/site/site.org/hub/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run() #14 /home/site/site.org/hub/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter() #15 /home/site/site.org/hub/protected/vendors/yii/web/filters/CInlineFilter.php(58): EntryController->filterAccessControl() #16 /home/site/site.org/hub/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter() #17 /home/site/site.org/hub/protected/vendors/yii/web/CController.php(291): CFilterChain->run() #18 /home/site/site.org/hub/protected/vendors/yii/web/CController.php(265): EntryController->runActionWithFilters() #19 /home/site/site.org/hub/protected/vendors/yii/web/CWebApplication.php(282): EntryController->run() #20 /home/site/site.org/hub/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController() #21 /home/site/site.org/hub/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest() #22 /home/site/site.org/hub/index.php(39): WebApplication->run() REQUEST_URI=/hub/index.php?r=calendar/entry/edit&id=&sguid=58571736-03ab-4cb5-ae62-d029902abe8a in /home/site/site.org/hub/protected/modules/calendar/models/CalendarEntry.php (335) in /home/site/site.org/hub/protected/modules/calendar/models/CalendarEntryParticipant.php (108) in /home/site/site.org/hub/protected/modules/calendar/models/CalendarEntry.php (377) in /home/site/site.org/hub/protected/modules/calendar/controllers/EntryController.php (184) in /home/site/site.org/hub/index.php (39)

**Comment by crowtc** [comment]
Not entirely sure what happened, but this issue no longer occurs...
