### ISSUE TITLE
Broken 1.12.1 version or broken documentation with PHP 8

### ISSUE THREAD

**Issue by liloumuloup** [humhub/humhub#5914]
I'm trying to update from 1.11 version to 1.12.1 but it doesn't seems to work. The update module doesn't find any update so i tried the "manual update" [here](https://docs.humhub.org/docs/admin/updating/#upgrade-manually).

At this point, when i try to clean the cache, i've got only PHP errors. When rollbacking to 1.11, it works again..

### What steps will reproduce the problem?
Following [this doc](https://docs.humhub.org/docs/admin/updating/#upgrade-manually) with a PHP 8.0 or PHP 8.1 version.

My bash history : 
```bash
147  wget https://github.com/humhub/humhub/archive/refs/tags/v1.12.1.zip
148  man unzip
149  unzip v1.12.1.zip 
150  mv humhub/.infomaniak-maintenance.html humhub-1.12.1/
151  rmdir humhub
152  mv  humhub-1.12.1/ humhub
153  cd humhub
154  ll
155  cd ../
156  ls -ltrah
157  cp -rfa humhub-backup/uploads humhub
158  cp -rfa humhub-backup/protected/{config,modules} humhub/protected
159  cp -a humhub-backup/.htaccess humhub
160  ll humhub
161  cd humhub/protected/
162  ll
163  /opt/php8.0/bin/php yii cache/flush-all
164  /opt/php8.1/bin/php yii cache/flush-all
167  /opt/php8.0/bin/php yii cache/flush-all
168  ll
169  ll vendor/
173  rsync -va ../../humhub-backup/protected/vendor/ vendor/
174  /opt/php8.0/bin/php yii cache/flush-all
175  /opt/php8.1/bin/php yii cache/flush-all
```

### What is the expected result?
A working up to date Humhub, i suppose, after finishing the procedure.

### What do you get instead?
When trying to clean the cache, i had this error : 
```bash
user@host:~/sites/humhub/protected$ /opt/php8.0/bin/php yii cache/flush-all
PHP Warning:  require(/home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/autoload.php): Failed to open stream: No such file or directory in /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/yii on line 17

Warning: require(/home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/autoload.php): Failed to open stream: No such file or directory in /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/yii on line 17
PHP Fatal error:  Uncaught Error: Failed opening required '/home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/autoload.php' (include_path='.:/opt/php8.0/lib/php') in /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/yii:17
Stack trace:
#0 {main}
  thrown in /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/yii on line 17

Fatal error: Uncaught Error: Failed opening required '/home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/autoload.php' (include_path='.:/opt/php8.0/lib/php') in /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/yii:17
Stack trace:
#0 {main}
  thrown in /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/yii on line 17
```

I found that the folder `vendor` stays empty so i tried to `rsync` the one from my backup and tried again with PHP 8.0 and 8.1 and got this error instead : 
```bash
user@host:~/sites/humhub/protected$ /opt/php8.1/bin/php yii cache/flush-all
Exception 'Error' with message 'Class "yii\symfonymailer\Mailer" not found'

in /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/humhub/components/mail/Mailer.php:21

Stack trace:
#0 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): include()
#1 [internal function]: yii\BaseYii::autoload('humhub\\componen...')
#2 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct('humhub\\componen...')
#3 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies('humhub\\componen...')
#4 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('humhub\\componen...', Array, Array)
#5 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\componen...', Array, Array)
#6 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#7 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/base/Module.php(766): yii\di\ServiceLocator->get('mailer', true)
#8 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get('mailer')
#9 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/humhub/modules/ui/view/bootstrap/ThemeLoader.php(46): yii\di\ServiceLocator->__get('mailer')
#10 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/base/Application.php(325): humhub\modules\ui\view\bootstrap\ThemeLoader->bootstrap(Object(humhub\components\console\Application))
#11 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/base/Application.php(271): yii\base\Application->bootstrap()
#12 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
#13 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/humhub/components/console/Application.php(94): yii\console\Application->init()
#14 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\components\console\Application->init()
#15 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#16 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#17 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/humhub/components/console/Application.php(52): yii\console\Application->__construct(Array)
#18 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/yii(28): humhub\components\console\Application->__construct(Array)
#19 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11.4 and 1.12.1
| PHP version      |  8.0 and 8.1
| Operating system | Debian 8.1

I have 2 hypothesis : 
* There is a missing step in the doc
* There is a problem with the release when the upgrade is done manually

Do not hesitate to ask for more info if needed. :smile: 

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by liloumuloup** [comment]
I don't if it helps, but when i try to go to update module (Administration > Update), here is the error i get : 
```bash
Error: Call to undefined function humhub\modules\updater\controllers\set_time_limit() in /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/modules/updater/controllers/UpdateController.php:19
Stack trace:
#0 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\updater\controllers\UpdateController->init()
#1 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(95): yii\base\BaseObject->__construct(Array)
#2 [internal function]: yii\base\Controller->__construct('update', Object(humhub\modules\updater\Module), Array)
#3 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/di/Container.php(411): ReflectionClass->newInstanceArgs(Array)
#4 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('humhub\\modules\\...', Array, Array)
#5 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('humhub\\modules\\...', Array)
#6 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/base/Module.php(666): yii\BaseYii::createObject('humhub\\modules\\...', Array)
#7 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/base/Module.php(620): yii\base\Module->createControllerByID('update')
#8 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/base/Module.php(612): yii\base\Module->createController('')
#9 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/base/Module.php(546): yii\base\Module->createController('update')
#10 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('updater/update', Array)
#11 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#12 /home/clients/eddc27b8c4490cb04cb9a5c958228cd3/sites/humhub/index.php(25): yii\base\Application->run()
#13 {main} 
```

**Comment by ArchBlood** [comment]
From the looks you're using a git based install method against a prepackaged install?

If you're wanting to install/update manually then use a prepackaged method.

https://www.humhub.com/en/download

If you're wanting to test HumHub in a test environment then it's recommended to use the git/composer based install method.

https://docs.humhub.org/docs/develop/environment/#gitcomposer-installation

**Comment by liloumuloup** [comment]
Hum. The releases on the Github and the ones from the website are not the same ?

**Comment by luke-** [comment]
The downloads on GitHub contain only the source code and no used biblitothekn. These must then be installed manually via Composer: 
https://docs.humhub.org/docs/develop/environment#gitcomposer-installation

The downloads on our website are recommended.
