### ISSUE TITLE
Adding new profile field leads to error 500 which breaks (LDAP) login

### ISSUE THREAD

**Issue by codiflow** [humhub/humhub#5927]
### What steps will reproduce the problem?
Just create a new profile field – I think it doesn't matter what settings you choose – and save it like in the screenshot:
![image](https://user-images.githubusercontent.com/43847817/201345589-f2703829-7c95-4d5c-b400-9eb2c4287b0d.png)

### What is the expected result?
The field gets saved as expected and the login (using LDAP) still works.

### What do you get instead?
You get a error 500 page.

After returning back to the page where you created the field you can see that the field got created, but some settings like the validator have not been saved properly.

You will also notice that the (LDAP) login functionality is broken from now on (see log below).

The **only way to fix this** is to remove the newly added line from the table `profile_field` in the MySQL database.

### Additional info
Editing one of the profile fields which are already there by default is working as expected and does not result in error 500.

Maybe this has to do with the installed module "Translator" looking at the additional field "Translation Category ID" in the screenshot?

All modules and the software itself are up to date.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12.1
| PHP version      | 7.4.32
| Operating system | Debian

Log excerpt:

```text
yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\user\models\Profile::im_telegram in /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\base\Component->__get('im_telegram')
#1 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/validators/Validator.php(258): yii\db\BaseActiveRecord->__get('im_telegram')
#2 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/Model.php(361): yii\validators\Validator->validateAttributes(Object(humhub\modules\user\models\Profile), Array)
#3 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(674): yii\base\Model->validate(Array)
#4 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(679): yii\db\ActiveRecord->update(true, NULL)
#5 /home/pacs/ecg00/users/humhub/humhub/protected/humhub/modules/user/authclient/AuthClientHelpers.php(146): yii\db\BaseActiveRecord->save()
#6 /home/pacs/ecg00/users/humhub/humhub/protected/humhub/modules/user/controllers/AuthController.php(225): humhub\modules\user\authclient\AuthClientHelpers::updateUser(Object(humhub\modules\ldap\authclient\LdapAuth), Object(humhub\modules\user\models\User))
#7 /home/pacs/ecg00/users/humhub/humhub/protected/humhub/modules/user/controllers/AuthController.php(167): humhub\modules\user\controllers\AuthController->login(Object(humhub\modules\user\models\User), Object(humhub\modules\ldap\authclient\LdapAuth))
#8 /home/pacs/ecg00/users/humhub/humhub/protected/humhub/modules/user/controllers/AuthController.php(103): humhub\modules\user\controllers\AuthController->onAuthSuccess(Object(humhub\modules\ldap\authclient\LdapAuth))
#9 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin()
#10 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('login', Array)
#13 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/auth/login', Array)
#14 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#15 /home/pacs/ecg00/users/humhub/humhub/index.php(25): yii\base\Application->run()
#16 {main}
```

**Comment by luke-** [comment]
It seems that the field was not correctly added to the database table `profile.im_telegram`. Can you look at the table?

Was there an error when creating the field?

Can you reproduce the problem on our demo hosting?

**Comment by codiflow** [comment]
> It seems that the field was not correctly added to the database table `profile.im_telegram`. Can you look at the table?

Exactly – the field was not added there.

This is what the log says:

```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs in /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('ALTER TABLE `pr...')
#2 /home/pacs/ecg00/users/humhub/humhub/protected/humhub/modules/user/models/fieldtype/Text.php(162): yii\db\Command->execute()
#3 /home/pacs/ecg00/users/humhub/humhub/protected/humhub/modules/admin/controllers/UserProfileController.php(159): humhub\modules\user\models\fieldtype\Text->save()
#4 [internal function]: humhub\modules\admin\controllers\UserProfileController->actionEditField(NULL, '1')
#5 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#7 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('edit-field', Array)
#8 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/user-prof...', Array)
#9 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#10 /home/pacs/ecg00/users/humhub/humhub/index.php(25): yii\base\Application->run()
#11 {main}

Next yii\db\Exception: SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
The SQL being executed was: ALTER TABLE `profile` ADD `im_telegram` VARCHAR(255) in /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `pr...')
#1 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('ALTER TABLE `pr...')
#2 /home/pacs/ecg00/users/humhub/humhub/protected/humhub/modules/user/models/fieldtype/Text.php(162): yii\db\Command->execute()
#3 /home/pacs/ecg00/users/humhub/humhub/protected/humhub/modules/admin/controllers/UserProfileController.php(159): humhub\modules\user\models\fieldtype\Text->save()
#4 [internal function]: humhub\modules\admin\controllers\UserProfileController->actionEditField(NULL, '1')
#5 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#7 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('edit-field', Array)
#8 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/user-prof...', Array)
#9 /home/pacs/ecg00/users/humhub/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#10 /home/pacs/ecg00/users/humhub/humhub/index.php(25): yii\base\Application->run()
#11 {main}
Additional Information:
Array
(
[0] => 42000
[1] => 1118
[2] => Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
)
```

**Comment by luke-** [comment]
Currently we always create 255 character columns automatically. To work around the limit, you could manually reduce the size of some columns.

**Comment by codiflow** [comment]
Good to know – I will try that, thanks.

Is it possible to include a check of the maximum row size **before** adding the profile_field to the database? Because not everyone will be able to "repair" the HumHub installation altering the database.
