### ISSUE TITLE
HELP WARNİNG..

### ISSUE THREAD

**Issue by spunkdeveloper** [humhub/humhub#5943]
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12.2
| PHP version    8.0.25   | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

HELP ME..

I detected a new bug The latest version of humhub is Version: 1.12.2 . when the administrator creates a user, the system crashes into an error and this is indicated as a server error, even if the user account seems to have been created, the created user cannot login to our humhub site, please fix it. a situation that can cause serious problems in the future. help warning !!

In addition, the system of sending invitations to the e-mails of the people who will become members from the admin panel does not work.

please help us with a humhub update..

**Comment by spunkdeveloper** [comment]
WHEN ATTEMPTING TO CREATE USER BY THE ADMINISTRATOR, AN ERROR MESSAGE IS ESTABLISHED AND THE USER CANNOT ENTER THE WEBSITE..

ALSO, AS I SAID, THE NEW USER MAIL INVITATION SYSTEM IN THE ADMIN PANEL DID NOT WORK IN VERSION 1.12.2 AND IN THE PREVIOUS VERSION.

WE LOVE YOU AND PLEASE HELP US WITH AN UPDATE SHORTLY.

YOU ARE VERY IMPORTANT TO US...

**Comment by ArchBlood** [comment]
@luke- I was able to reproduce this using the Softaculous package, using the updater module fails to update migrations with an error stating a timeout has occurred or internal server error has occurred, and sometimes a no connection to service has occurred, after manually updating the following errors happen for me as well.

### Error 1
`yii\base\ErrorException: Attempt to read property "id"`

### Error 2
`yii\base\ErrorException: Attempt to read property "tags_cached"`

**Comment by luke-** [comment]
Thanks for the info, I can't reproduce it though.

For debugging I need the detailed error message during the update process. This is either in the browser, server log or HumHub log. 

Also of course it would be interesting to know at which update package (from and to version) and on which update step the error occurs.

**Comment by spunkdeveloper** [comment]
@luke- Are you talking about humhub error messages?

I cleared the logs,  @ArchBlood if you have it can you share it?

**Comment by ArchBlood** [comment]
> Thanks for the info, I can't reproduce it though.
> 
> For debugging I need the detailed error message during the update process. This is either in the browser, server log or HumHub log.
> 
> Also of course it would be interesting to know at which update package (from and to version) and on which update step the error occurs.

Here's the current errors that I've noticed

### Error 1
```log
2022-11-24 18:31:36 [24.101.49.56][1][e8pj5ahd0e6od96ldki03r38vf][error][yii\base\ErrorException:2] yii\base\ErrorException: Attempt to read property "id" on null in /home/USER/public_html/protected/humhub/modules/content/components/ContentContainerSettingsManager.php:80
Stack trace:
#0 /home/USER/public_html/protected/humhub/modules/content/components/ContentContainerSettingsManager.php(80): yii\base\ErrorHandler->handleError()
#1 /home/USER/public_html/protected/humhub/libs/BaseSettingsManager.php(180): humhub\modules\content\components\ContentContainerSettingsManager->find()
#2 /home/USER/public_html/protected/humhub/libs/BaseSettingsManager.php(52): humhub\libs\BaseSettingsManager->loadValues()
#3 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\libs\BaseSettingsManager->init()
#4 /home/USER/public_html/protected/humhub/components/SettingsManager.php(44): yii\base\BaseObject->__construct()
#5 /home/USER/public_html/protected/humhub/modules/user/models/User.php(936): humhub\components\SettingsManager->contentContainer()
#6 /home/USER/public_html/protected/humhub/modules/content/components/ContentContainerActiveRecord.php(422): humhub\modules\user\models\User->getSettings()
#7 /home/USER/public_html/protected/humhub/modules/content/components/ContentContainerActiveRecord.php(446): humhub\modules\content\components\ContentContainerActiveRecord->getBlockedUserIds()
#8 /home/USER/public_html/protected/humhub/modules/notification/components/BaseNotification.php(259): humhub\modules\content\components\ContentContainerActiveRecord->isBlockedForUser()
#9 /home/USER/public_html/protected/humhub/modules/notification/components/BaseNotification.php(217): humhub\modules\notification\components\BaseNotification->isBlockedFromUser()
#10 /home/USER/public_html/protected/humhub/modules/user/models/Group.php(361): humhub\modules\notification\components\BaseNotification->send()
#11 /home/USER/public_html/protected/humhub/modules/user/models/User.php(651): humhub\modules\user\models\Group->addUser()
#12 /home/USER/public_html/protected/humhub/modules/user/models/User.php(593): humhub\modules\user\models\User->setUpApproved()
#13 /home/USER/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(615): humhub\modules\user\models\User->afterSave()
#14 /home/USER/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal()
#15 /home/USER/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert()
#16 /home/USER/public_html/protected/humhub/modules/user/models/forms/Registration.php(270): yii\db\BaseActiveRecord->save()
#17 /home/USER/public_html/protected/humhub/modules/admin/controllers/UserController.php(257): humhub\modules\user\models\forms\Registration->register()
#18 [internal function]: humhub\modules\admin\controllers\UserController->actionAdd()
#19 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#20 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#21 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#22 /home/USER/public_html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#23 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#24 /home/USER/public_html/index.php(25): yii\base\Application->run()
#25 {main}
```

### Error 2
```log
2022-11-24 18:33:15 [24.101.49.56][1][e8pj5ahd0e6od96ldki03r38vf][error][yii\base\ErrorException:2] yii\base\ErrorException: Attempt to read property "tags_cached" on null in /home/USER/public_html/protected/humhub/modules/content/components/ContentContainerActiveRecord.php:397
Stack trace:
#0 /home/USER/public_html/protected/humhub/modules/content/components/ContentContainerActiveRecord.php(397): yii\base\ErrorHandler->handleError()
#1 /home/USER/public_html/protected/humhub/modules/user/widgets/PeopleTagList.php(45): humhub\modules\content\components\ContentContainerActiveRecord->getTags()
#2 /home/USER/public_html/protected/humhub/components/Widget.php(63): humhub\modules\user\widgets\PeopleTagList->run()
#3 /home/USER/public_html/protected/humhub/modules/user/widgets/views/peopleCard.php(47): humhub\components\Widget::widget()
#4 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/View.php(347): require('/home/greenmet/...')
#5 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#6 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#7 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(242): yii\base\View->render()
#8 /home/USER/public_html/protected/humhub/modules/user/widgets/PeopleCard.php(39): yii\base\Widget->render()
#9 /home/USER/public_html/protected/humhub/components/Widget.php(63): humhub\modules\user\widgets\PeopleCard->run()
#10 /home/USER/public_html/protected/humhub/modules/user/views/people/index.php(46): humhub\components\Widget::widget()
#11 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/View.php(347): require('/home/greenmet/...')
#12 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#13 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#14 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render()
#15 /home/USER/public_html/protected/humhub/modules/user/controllers/PeopleController.php(70): yii\base\Controller->render()
#16 [internal function]: humhub\modules\user\controllers\PeopleController->actionIndex()
#17 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#18 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#19 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#20 /home/USER/public_html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#21 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#22 /home/USER/public_html/index.php(25): yii\base\Application->run()
#23 {main}
```
### Server Error
```log
[25-Nov-2022 10:27:26 America/New_York] An Error occurred while handling another error:
yii\web\ForbiddenHttpException: Login Required in /home/USER/public_html/protected/vendor/yiisoft/yii2/web/User.php:460
Stack trace:
#0 /home/USER/public_html/protected/humhub/modules/user/components/User.php(281): yii\web\User->loginRequired()
#1 /home/USER/public_html/protected/humhub/components/behaviors/AccessControl.php(224): humhub\modules\user\components\User->loginRequired()
#2 /home/USER/public_html/protected/humhub/components/behaviors/AccessControl.php(154): humhub\components\behaviors\AccessControl->loginRequired()
#3 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/ActionFilter.php(77): humhub\components\behaviors\AccessControl->beforeAction()
#4 [internal function]: yii\base\ActionFilter->beforeFilter()
#5 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/Component.php(633): call_user_func()
#6 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(297): yii\base\Component->trigger()
#7 /home/USER/public_html/protected/vendor/yiisoft/yii2/web/Controller.php(221): yii\base\Controller->beforeAction()
#8 /home/USER/public_html/protected/humhub/components/Controller.php(208): yii\web\Controller->beforeAction()
#9 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(176): humhub\components\Controller->beforeAction()
#10 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#11 /home/USER/public_html/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#12 /home/USER/public_html/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#13 [internal function]: yii\base\ErrorHandler->handleException()
#14 {main}
```
I looked for browser errors but didn't see any

**Comment by punkyard** [comment]
> For debugging I need the detailed error message during the update process. This is either in the browser, server log or HumHub log.
> 
> Also of course it would be interesting to know at which update package (from and to version) and on which update step the error occurs.

I don't see a log in HH
where else should i look in the server?

1.12.1 to latest 1.12.2
after 'backup' step with the updater module

**Comment by luke-** [comment]
The bug really came between version 1.12.1 and 1.12.2? There were actually only minimal changes between these versions.

Please do the following steps:

- Restore backup to v1.12.1
- Clear all logs
- Run updater to v1.12.2
- When the updater fails, create a screenshot and send logs created during the updater (not afterwards)

**Comment by luke-** [comment]
Can you reproduce this with a fresh installation? 

v1.12.2 seems to running fine on Softaculous: https://www.softaculous.com/demos/HumHub

@punkyard Are you also running an instance on Softaculous?

**Comment by spunkdeveloper** [comment]
@luke- 

While in 1.12.1, there was no problem of creating users in any admin, after the release of 1.12.2 I started getting errors from archblood, explanation of the word In version 1.12.2, the administrator cannot create a new user, please fix this with an update.🙏

**Comment by punkyard** [comment]
> * Restore backup to v1.12.1

sorry, I can't do that

**Comment by punkyard** [comment]
> @punkyard Are you also running an instance on Softaculous?

no, I used the zip install ..
then there has been an issue during the update using the updater module. Not long after, I've tried to create a new user. This is when the error came up. I had some modules installed before and they functioned for a couple of weeks. the problem seems to have appeared during the failed update.

**Comment by punkyard** [comment]
We are really blocked in our work since this. 
Is there a way to bring back datas in a fresh install?

Because I've installed a fresh version 1.12.2, create users seems to work. But I could we import our datas quickly?
Thanks

**Comment by punkyard** [comment]
> Can you reproduce this with a fresh installation?

I've installed a fresh 1.12.1, new DB
users can be created after install

change admin settings
added 2 modules (calendar and ext calendar)
another user can be created

install aut updater module
error installing 1.12.2

`install auto updater module
error installing 1.12.2

Error! {"status":"ok"}Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away The SQL being executed was: SELECT id FROM user_http_session WHERE id='kq9boqs3qqouq38ctv50m1g9h1'' in /home/protected/vendor/yiisoft/yii2/db/Schema.php:676 Stack trace: #0 /home/protected/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException() #1 /home/protected/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute() #2 /home/protected/vendor/yiisoft/yii2/db/Command.php(436): yii\db\Command->queryInternal() #3 /home/protected/humhub/modules/user/components/Session.php(61): yii\db\Command->queryScalar() #4 [internal function]: humhub\modules\user\components\Session->writeSession() #5 /home/protected/vendor/yiisoft/yii2/web/DbSession.php(166): session_write_close() #6 [internal function]: yii\web\DbSession->close() #7 {main}`

**Comment by punkyard** [comment]
my system check:
all green but 2 x

 PHP - Version - 8.1.13
 PHP - GD Extension
 PHP - GD Extension - JPEG Support
 PHP - GD Extension - PNG Support
 PHP - INTL Extension
 PHP - INTL Extension - ICU Version (70.1)
 PHP - INTL Extension - ICU Data Version (70.1)
 PHP - EXIF Extension
 PHP - XML Extension
 PHP - FileInfo Extension
 PHP - Multibyte String Functions
 PHP - iconv Extension
 PHP - cURL Extension
 PHP - ZIP Extension
 PHP - OpenSSL Extension
 PHP - ImageMagick Extension
x PHP - GraphicsMagick Extension (Hint: Optional)
 PHP - Memory Limit (64 MB) (Hint: Current limit is: 1 GB)
 PHP - LDAP Support
 PHP - APC(u) Support
x PHP - SQLite3 Support (Hint: Optional - Install SQLite3 Extension for DB Caching)
 PHP - PDO MySQL Extension
 Permissions - Runtime
 Permissions - Assets
 Permissions - Uploads
 Permissions - Profile Image
 Permissions - Module Directory
 Permissions - Dynamic Config

**Comment by punkyard** [comment]
I've installed a fresh 1.12.1, with new DB
users could be created after install

changed admin settings
added 2 modules (calendar and external calendar)
another user could be created

modified profiles, added user groups
another user could be created

**Comment by punkyard** [comment]
added modules: 

Content bookmarks
Mail
Report Content
Clean theme
Polls
New Members Widget
Jitsi Meet
Social Share
Scroll Up
Terms Box
VCard Popover
User Location Map

**Comment by punkyard** [comment]
I think I've identified my issue.

The error message appears if I change the default group and then add a user. This is when I get:

```
ERROR  Sun, 04 Dec 2022 01:07:19 +0100  yii\base\ErrorException:2
yii\base\ErrorException: Attempt to read property "id" on null in /home/protected/humhub/modules/content/components/ContentContainerSettingsManager.php:80
Stack trace:
#0 /home/protected/humhub/modules/content/components/ContentContainerSettingsManager.php(80): yii\base\ErrorHandler->handleError()
#1 /home/protected/humhub/libs/BaseSettingsManager.php(180): humhub\modules\content\components\ContentContainerSettingsManager->find()
#2 /home/protected/humhub/libs/BaseSettingsManager.php(52): humhub\libs\BaseSettingsManager->loadValues()
#3 /home/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\libs\BaseSettingsManager->init()
#4 /home/protected/humhub/components/SettingsManager.php(44): yii\base\BaseObject->__construct()
#5 /home/protected/humhub/modules/user/models/User.php(936): humhub\components\SettingsManager->contentContainer()
#6 /home/protected/humhub/modules/user/models/User.php(947): humhub\modules\user\models\User->getSettings()
#7 /home/protected/humhub/modules/admin/controllers/UserController.php(119): humhub\modules\user\models\User->mustChangePassword()
#8 [internal function]: humhub\modules\admin\controllers\UserController->actionEdit()
#9 /home/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /home/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#11 /home/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#12 /home/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#13 /home/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#14 /home/index.php(25): yii\base\Application->run()
#15 {main}
```
