### ISSUE TITLE
Error Occurred When user click on space followers button

### ISSUE THREAD

**Issue by noman-maken** [humhub/humhub#5958]
An error occurred when the guest clicked on the space follower button 

```
Error: Call to a member function isPrivileged() on null in /protected/humhub/modules/space/controllers/MembershipController.php:310
Stack trace:
#0 /protected/humhub/modules/space/controllers/MembershipController.php(266): humhub\modules\space\controllers\MembershipController->canViewMembers()
#1 [internal function]: humhub\modules\space\controllers\MembershipController->actionMembersList()
#2 /protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#4 /protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#5 /protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#6 /protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#7 /index.php(28): yii\base\Application->run()
#8 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | Version: 1.13.0-beta.2
| PHP version      | PHP - Version - 8.1.13

![image](https://user-images.githubusercontent.com/60031819/204962794-b174079d-7289-4f1d-aad4-b691358c80c8.png)

**Comment by noman-maken** [comment]
This only happen if we used the hide likes, hide follower option.

**Comment by luke-** [comment]
Should be fixed in Beta.3
