### ISSUE TITLE
Session Cookie

### ISSUE THREAD

**Issue by jayavman** [humhub/humhub#6096]
yii\base\ErrorException: session_set_cookie_params(): Session cookie parameters cannot be changed after headers have already been sent in /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/Session.php:430
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'session_set_coo...', '/home/fredons/p...', 430)
#1 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/Session.php(430): session_set_cookie_params(Array)
#2 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/Session.php(148): yii\web\Session->setCookieParamsInternal()
#3 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/Session.php(723): yii\web\Session->open()
#4 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/User.php(659): yii\web\Session->remove('__id')
#5 /home/fredons/public_html/hub/protected/humhub/modules/user/components/User.php(247): yii\web\User->switchIdentity(Object(humhub\modules\user\models\User), 2592000)
#6 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/User.php(326): humhub\modules\user\components\User->switchIdentity(Object(humhub\modules\user\models\User), 2592000)
#7 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/User.php(727): yii\web\User->loginByCookie()
#8 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/User.php(199): yii\web\User->renewAuthStatus()
#9 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/User.php(367): yii\web\User->getIdentity()
#10 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getIsGuest()
#11 /home/fredons/public_html/hub/protected/humhub/components/i18n/I18N.php(53): yii\base\Component->__get('isGuest')
#12 /home/fredons/public_html/hub/protected/humhub/components/bootstrap/LanguageSelector.php(29): humhub\components\i18n\I18N->autosetLocale()
#13 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Application.php(325): humhub\components\bootstrap\LanguageSelector->bootstrap(Object(humhub\components\Application))
#14 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#15 /home/fredons/public_html/hub/protected/humhub/components/Application.php(83): yii\web\Application->bootstrap()
#16 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Application.php(271): humhub\components\Application->bootstrap()
#17 /home/fredons/public_html/hub/protected/humhub/components/Application.php(65): yii\base\Application->init()
#18 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\components\Application->init()
#19 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#20 /home/fredons/public_html/hub/protected/humhub/components/Application.php(49): yii\base\Application->__construct(Array)
#21 /home/fredons/public_html/hub/index.php(25): humhub\components\Application->__construct(Array)
#22 {main} 

 Version: 1.13.1
 PHP - Version - 8.1.15

**Comment by jayavman** [comment]
What information do you need?

**Comment by luke-** [comment]
https://docs.humhub.org/docs/about/support#information-about-the-issue
