### ISSUE TITLE
Exception in Helpers

### ISSUE THREAD

**Issue by TheFox** [humhub/humhub#6113]
While watching `tail -f error.log` on the command-line.

I don't know when this happens.

```
2023-02-17 10:25:01 [-][-][-][error][application] yii\base\ErrorException: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/protected/humhub/libs/Helpers.php:37
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(8192, 'preg_replace():...', '/var/www/html/p...', 37)
#1 /var/www/html/protected/humhub/libs/Helpers.php(37): preg_replace('#<br */?>#i', ' ', NULL)
#2 /var/www/html/protected/humhub/widgets/mails/MailContentContainerInfoBox.php(42): humhub\libs\Helpers::trimText(NULL, 60)
#3 /var/www/html/protected/vendor/yiisoft/yii2/base/Widget.php(146): humhub\widgets\mails\MailContentContainerInfoBox->run()
#4 /var/www/html/protected/humhub/modules/user/notifications/views/mails/followed.php(34): yii\base\Widget::widget(Array)
#5 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(347): require('/var/www/html/p...')
#6 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/html/p...', Array)
#7 /var/www/html/protected/humhub/components/rendering/ViewPathRenderer.php(83): yii\base\View->renderFile('/var/www/html/p...', Array, Object(humhub\modules\user\notifications\Followed))
#8 /var/www/html/protected/humhub/components/rendering/ViewPathRenderer.php(69): humhub\components\rendering\ViewPathRenderer->renderView(Object(humhub\modules\user\notifications\Followed), Array)
#9 /var/www/html/protected/humhub/modules/notification/targets/MailTarget.php(66): humhub\components\rendering\ViewPathRenderer->render(Object(humhub\modules\user\notifications\Followed))
#10 /var/www/html/protected/humhub/modules/notification/targets/BaseTarget.php(161): humhub\modules\notification\targets\MailTarget->handle(Object(humhub\modules\user\notifications\Followed), Object(humhub\modules\user\models\User))
#11 /var/www/html/protected/humhub/modules/notification/components/NotificationManager.php(93): humhub\modules\notification\targets\BaseTarget->send(Object(humhub\modules\user\notifications\Followed), Object(humhub\modules\user\models\User))
#12 /var/www/html/protected/humhub/modules/notification/components/NotificationManager.php(112): humhub\modules\notification\components\NotificationManager->sendBulk(Object(humhub\modules\user\notifications\Followed), Object(humhub\modules\user\components\ActiveQueryUser))
#13 /var/www/html/protected/humhub/modules/notification/jobs/SendNotification.php(41): humhub\modules\notification\components\NotificationManager->send(Object(humhub\modules\user\notifications\Followed), Object(humhub\modules\user\models\User))
#14 /var/www/html/protected/humhub/modules/queue/ActiveJob.php(33): humhub\modules\notification\jobs\SendNotification->run()
#15 /var/www/html/protected/vendor/yiisoft/yii2-queue/src/Queue.php(246): humhub\modules\queue\ActiveJob->execute(Object(humhub\modules\queue\driver\MySQL))
#16 /var/www/html/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('18831', 'O:49:"humhub\\mo...', '300', '1')
#17 /var/www/html/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute('18831', 'O:49:"humhub\\mo...', '300', '1', '27')
#18 [internal function]: yii\queue\cli\Command->actionExec('18831', '300', '1', '27')
#19 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#21 /var/www/html/protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('exec', Array)
#22 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('exec', Array)
#23 /var/www/html/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/exec', Array)
#24 /var/www/html/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/exec', Array)
#25 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#26 /var/www/html/protected/yii(30): yii\base\Application->run()
#27 {main}
    in /var/www/html/protected/humhub/modules/notification/targets/BaseTarget.php:166
    in /var/www/html/protected/humhub/modules/notification/components/NotificationManager.php:93
    in /var/www/html/protected/humhub/modules/notification/components/NotificationManager.php:112
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.2
| PHP version      | 8.1
| Operating system | Debian 11

**Comment by luke-** [comment]
Seems `User Display Name Subtitle` specified in `Admin -> Settings -> Appearance` returns a NULL value. Should be fixed in the commit and will be added in v1.14.
