### ISSUE TITLE
User Page - Not Found

### ISSUE THREAD

**Issue by TheFox** [humhub/humhub#6115]
I have a user that is not different to others. The user is active and visible for members and has the default Users group assigned. As admin I can edit the user on /admin/user/edit?id=1 and also save it, and also he is visible and clickable via /people. But when I click on this user I get a "Not Found" error on /u/username1/.

The error file says:

```
2023-02-17 10:52:55 [172.21.25.1][2][db8058b6ae0fafa7fe0efd58768db20d][error][yii\web\HttpException:404] yii\web\HttpException: Die angeforderte Seite kann nicht gefunden werden. in /var/www/html/protected/humhub/modules/content/components/ContentContainerController.php:108
Stack trace:
#0 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(176): humhub\modules\content\components\ContentContainerController->beforeAction(Object(yii\base\InlineAction))
#1 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#2 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/profile', Array)
#3 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#4 /var/www/html/index.php(27): yii\base\Application->run()
#5 {main}
2023-02-17 10:52:55 [172.21.25.1][2][db8058b6ae0fafa7fe0efd58768db20d][info][application] $_GET = [
    '_pjax' => '#layout-content'
    '_' => '1676631108251'
    'cguid' => '...'
]
```

What could be the problem here?

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.2
| PHP version      | 8.1
| Operating system | Debian 11

**Comment by ArchBlood** [comment]
Could you provide the installation method used?

**Comment by TheFox** [comment]
@ArchBlood Using this GitHub repo. Cloned it and run "composer install".

**Comment by ArchBlood** [comment]
Did you follow the docs?
https://docs.humhub.org/docs/develop/environment/#gitcomposer-installation

**Comment by TheFox** [comment]
@ArchBlood Yes, this installation method was how I was installing HumHub.
