### ISSUE TITLE
Error creating new ContentContainerTagRelation

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6152]
### What steps will reproduce the problem?

I cannot tell how to reproduce, as the bug is specific to the database of the Humhub instance.
The bug occurred when adding topics to a user.

### What is the expected result?

The topic is added to the user.

### What do you get instead?

An error saving a new `ContentContainerTagRelation` because `contentcontainer_id` AND `tag_id` already exists.

```
Could not execute queued job! Message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-15' for key 'PRIMARY'
The SQL being executed was: INSERT INTO `contentcontainer_tag_relation` (`contentcontainer_id`, `tag_id`) VALUES (1, 15) Trace:#0 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException()
#1 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
#2 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/db/Schema.php(431): yii\db\Command->execute()
#3 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(604): yii\db\Schema->insert()
#4 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal()
#5 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert()
#6 /usr/www/users/space/hub.transition-space.org/humhub/protected/humhub/modules/content/models/ContentContainerTagRelation.php(93): yii\db\BaseActiveRecord->save()
#7 /usr/www/users/space/hub.transition-space.org/humhub/protected/humhub/modules/content/components/ContentContainerActiveRecord.php(227): humhub\modules\content\models\ContentContainerTagRelation::updateByContainer()
#8 /usr/www/users/space/hub.transition-space.org/humhub/protected/humhub/modules/user/models/User.php(586): humhub\modules\content\components\ContentContainerActiveRecord->afterSave()
#9 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(823): humhub\modules\user\models\User->afterSave()
#10 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(680): yii\db\BaseActiveRecord->updateInternal()
#11 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(679): yii\db\ActiveRecord->update()
#12 /usr/www/users/space/hub.transition-space.org/humhub/protected/modules/transition/helpers/MembershipHelper.php(60): yii\db\BaseActiveRecord->save()
#13 /usr/www/users/space/hub.transition-space.org/humhub/protected/modules/transition/jobs/SyncAllSpaceAdmins.php(35): humhub\modules\transition\helpers\MembershipHelper::updateMembershipToSpaceAdminsGroup()
#14 /usr/www/users/space/hub.transition-space.org/humhub/protected/humhub/modules/queue/ActiveJob.php(33): humhub\modules\transition\jobs\SyncAllSpaceAdmins->run()
#15 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2-queue/src/Queue.php(246): humhub\modules\queue\ActiveJob->execute()
#16 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage()
#17 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute()
#18 [internal function]: yii\queue\cli\Command->actionExec()
#19 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#20 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#21 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#22 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#23 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#24 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#25 /usr/www/users/space/hub.transition-space.org/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest()
#26 /usr/www/users/space/hub.transition-space.org/humhub/protected/yii(29): yii\base\Application->run()
#27 {main}
```

### Additional info

The DB for `ContentContainerTagRelation` model showing it already exists:
![image](https://user-images.githubusercontent.com/23310825/224033172-52009cbe-3b5f-4bf2-95eb-64dafdfaaa56.png)

As a temporary fix, I've replaced `$newTagRelation->save();` [here](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/models/ContentContainerTagRelation.php#L93) with:
```php
            if (ContentContainerTagRelation::findOne(['contentcontainer_id' => $newTagRelation->contentcontainer_id, 'tag_id' => $newTagRelation->tag_id]) === null) {
                $newTagRelation->save();
            }
```

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.1

**Comment by yurabakhtin** [comment]
@funkycram

> As a temporary fix, I've replaced $newTagRelation->save(); [here](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/models/ContentContainerTagRelation.php#L93) with:

Yes, the fix can solve the issue, but it is strange why records are not removed from DB by the code `self::deleteByContainer($contentContainer);` here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/models/ContentContainerTagRelation.php#L63, the method `updateByContainer()` must works like this:

- remove all previous tag relations
- insert new tag relations from the submitted form

So it seems on your side the method `deleteByContainer()` doesn't remove all previous relations properly.
Could you please try to remove some tag and check if it is removed after submit a form?
Thanks.

**Comment by funkycram** [comment]
Thanks @yurabakhtin for your investigation. Very sorry, the problem was in my code: 
```php
$user = User::findOne(1);
$user->tagsField = ['Same name', 'Same name'];
$user->save();
```

To prevent this problem, should I send a PR replacing `foreach ($newTags as $updatedTag) {` [here](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/models/ContentContainerTagRelation.php#L81) with:
```php
foreach (array_unique($newTags) as $updatedTag) {
```
?

**Comment by yurabakhtin** [comment]
@funkycram Thank you for the response, yes I think we need such additional check by `array_unique()` from PHP/server side because currently we have only avoid the tag duplicates only from JS/client seletor side, but the tags array also can be sent for example by REST API request where we cannot be sure a client does the same enough good checking as it HumHub tags picker does.
I have implemented your solution in PR https://github.com/humhub/humhub/pull/6155.

**Comment by funkycram** [comment]
Thanks @yurabakhtin
