### ISSUE TITLE
Cannot add appointments in calendar module

### ISSUE THREAD

**Issue by pelennart** [humhub/humhub#6156]
I have recently updated to PHP 8.2 (coming from 7.4) and now people cannot enter any appointments to the calendar.

In the log I get the following error:
`yii\base\ErrorException: Trying to access array offset on value of type bool in /var/www/html/protected/vendor/yiisoft/yii2/validators/DateValidator.php:445
Stack trace:
#0 /var/www/html/protected/vendor/yiisoft/yii2/validators/DateValidator.php(445): yii\base\ErrorHandler->handleError()
#1 /var/www/html/protected/vendor/yiisoft/yii2/validators/DateValidator.php(370): yii\validators\DateValidator->parseDateValuePHP()
#2 /var/www/html/protected/vendor/yiisoft/yii2/validators/DateValidator.php(343): yii\validators\DateValidator->parseDateValueFormat()
#3 /var/www/html/protected/vendor/yiisoft/yii2/validators/DateValidator.php(292): yii\validators\DateValidator->parseDateValue()
#4 /var/www/html/protected/vendor/yiisoft/yii2/validators/Validator.php(260): yii\validators\DateValidator->validateAttribute()
#5 /var/www/html/protected/vendor/yiisoft/yii2/base/Model.php(368): yii\validators\Validator->validateAttributes()
#6 /var/www/html/protected/modules/calendar/models/forms/CalendarEntryForm.php(454): yii\base\Model->validate()
#7 /var/www/html/protected/modules/calendar/controllers/EntryController.php(227): humhub\modules\calendar\models\forms\CalendarEntryForm->save()
#8 [internal function]: humhub\modules\calendar\controllers\EntryController->actionEdit()
#9 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#11 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#12 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#13 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#14 /var/www/html/index.php(33): yii\base\Application->run()
#15 {main} `

I am running humhub community edition 1.13.1 in a lxd containter with a reverse proxy doing the https.

I am lost and grateful for hints.

**Comment by ArchBlood** [comment]
See #6078
