### ISSUE TITLE
Saerch Index Rebuilding craches if cron jobs are active while indexing

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6168]
### What steps will reproduce the problem?

On Humhub instance with a large database, [rebuild the search index](https://docs.humhub.org/docs/admin/search/#index-rebuilding) in command line: `php yii search/rebuild`

### What is the expected result?

Get the message `OK!`

### What do you get instead?

This error:
```
Could not add document to
search index. Error: Can't delete file:
unlink(/home/web/www/humhub/protected/runtime/searchdb/_33x.fdx):
No such file or directory
in
/home/web/www/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php:118
in
/home/web/www/humhub/protected/humhub/modules/content/Events.php:115
in
/home/web/www/humhub/protected/humhub/modules/search/engine/Search.php:97
2023-03-14 13:51:02 [-][-][-][error][yii\base\ErrorException:2]
yii\base\ErrorException: fwrite() expects parameter 1 to be resource,
null given in
/home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Storage/File/Filesystem.php:177
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1
/home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Storage/File/Filesystem.php(177):
fwrite()
#2
/home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Storage/File/AbstractFile.php(156):
ZendSearch\Lucene\Storage\File\Filesystem->fwrite()
#3
/home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Index/SegmentWriter/AbstractSegmentWriter.php(224):
ZendSearch\Lucene\Storage\File\AbstractFile->writeLong()
#4
/home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Index/SegmentWriter/DocumentWriter.php(174):
ZendSearch\Lucene\Index\SegmentWriter\AbstractSegmentWriter->addStoredFields()
#5
/home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Index/Writer.php(238):
ZendSearch\Lucene\Index\SegmentWriter\DocumentWriter->addDocument()
#6
/home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Index.php(1169):
ZendSearch\Lucene\Index\Writer->addDocument()
#7
/home/web/www/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php(115):
ZendSearch\Lucene\Index->addDocument()
#8
/home/web/www/humhub/protected/humhub/modules/content/Events.php(115):
humhub\modules\search\engine\ZendLuceneSearch->add()
#9 [internal function]:
humhub\modules\content\Events::onSearchRebuild()
#10
/home/web/www/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312):
call_user_func()
#11
/home/web/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php(642):
yii\base\Event::trigger()
#12
/home/web/www/humhub/protected/humhub/modules/search/engine/Search.php(97):
yii\base\Component->trigger()
#13
/home/web/www/humhub/protected/humhub/modules/search/commands/SearchController.php(39):
humhub\modules\search\engine\Search->rebuild()
#14 [internal function]:
humhub\modules\search\commands\SearchController->actionRebuild()
#15
/home/web/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57):
call_user_func_array()
#16
/home/web/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178):
yii\base\InlineAction->runWithParams()
#17
/home/web/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(180):
yii\base\Controller->runAction()
#18
/home/web/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552):
yii\console\Controller->runAction()
#19
/home/web/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180):
yii\base\Module->runAction()
#20
/home/web/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147):
yii\console\Application->runAction()
#21
/home/web/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384):
yii\console\Application->handleRequest()
#22
/home/web/www/humhub/protected/yii(29):
yii\base\Application->run()
#23 {main}
2023-03-14 13:44:43 [-][-][-][info][application] $_GET = []
```

Or, on another Humhub instance:
```
Could not add document to search index. Error: Can't delete file:
TypeError: fwrite(): Argument #1 ($stream) must be of type resource, null given in /home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Storage/File/Filesystem.php:177
Stack trace:
#0 /home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Storage/File/Filesystem.php(177): fwrite()
#1 /home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Storage/File/AbstractFile.php(156): ZendSearch\Lucene\Storage\File\Filesystem->fwrite()
#2 /home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Index/SegmentWriter/AbstractSegmentWriter.php(224): ZendSearch\Lucene\Storage\File\AbstractFile->writeLong()
#3 /home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Index/SegmentWriter/DocumentWriter.php(174): ZendSearch\Lucene\Index\SegmentWriter\AbstractSegmentWriter->addStoredFields()
#4 /home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Index/Writer.php(238): ZendSearch\Lucene\Index\SegmentWriter\DocumentWriter->addDocument()
#5 /home/web/www/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Index.php(1169): ZendSearch\Lucene\Index\Writer->addDocument()
#6 /home/web/www/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php(115): ZendSearch\Lucene\Index->addDocument()
#7 /home/web/www/humhub/protected/humhub/modules/content/Events.php(115): humhub\modules\search\engine\ZendLuceneSearch->add()
#8 [internal function]: humhub\modules\content\Events::onSearchRebuild()
#9 /home/web/www/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#10 /home/web/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#11 /home/web/www/humhub/protected/humhub/modules/search/engine/Search.php(97): yii\base\Component->trigger()
#12 /home/web/www/humhub/protected/humhub/modules/search/commands/SearchController.php(39): humhub\modules\search\engine\Search->rebuild()
#13 [internal function]: humhub\modules\search\commands\SearchController->actionRebuild()
#14 /home/web/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#15 /home/web/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#16 /home/web/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#17 /home/web/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#18 /home/web/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#19 /home/web/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#20 /home/web/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest()
#21 /home/web/www/humhub/protected/yii(29): yii\base\Application->run()
#22 {main}
```

### Additional info

If the cron jobs are disabled, the search engine re-indexing works.
It seams to be because there are files changing such as `protected/runtime/searchdb/_xxxxx.fdx` during indexation because of the cron jobs.

I suggest to add the recommandation to disable cron jobs while indexing in the doc:
- https://docs.humhub.org/docs/admin/console/#search
- https://docs.humhub.org/docs/admin/search/#index-rebuilding

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.1
| PHP version      | 7.4 & 8.1
| Operating system | Ubuntu 22.04

**Comment by luke-** [comment]
Related: https://github.com/humhub/humhub/issues/5419

**Comment by funkycram** [comment]
Thanks! I remembered there already was an issue (https://github.com/humhub/humhub/issues/3847) but could not find it anymore... I tried to add as much as keywords as possible in this one so we can easily find it to have the solution when facing this bug.
