### ISSUE TITLE
Bug on saving forms: Zend OPcache API is restricted by "restrict_api"

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6229]
### What steps will reproduce the problem?

Install Humhub 1.14-beta-2 on an OVH server (web cloud) with PHP 8.0 or 8.1 or 8.2.
Save a form (any form in the admin section).

### What is the expected result?

No problem

### What do you get instead?

For form is saved, but we have an internal server error.

Logging:
```
yii\base\ErrorException: Zend OPcache API is restricted by "restrict_api" configuration directive in /var/www/protected/humhub/libs/DynamicConfig.php:75
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'Zend OPcache AP...', '/home/labosphex...', 75)
#1 /var/www/protected/humhub/libs/DynamicConfig.php(75): opcache_invalidate('/home/labosphex...')
#2 /var/www/protected/humhub/libs/DynamicConfig.php(148): humhub\libs\DynamicConfig::save(Array)
#3 /var/www/protected/humhub/modules/admin/models/forms/CacheSettingsForm.php(104): humhub\libs\DynamicConfig::rewrite()
#4 /var/www/protected/humhub/modules/admin/controllers/SettingController.php(130): humhub\modules\admin\models\forms\CacheSettingsForm->save()
#5 [internal function]: humhub\modules\admin\controllers\SettingController->actionCaching()
#6 /var/www/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /var/www/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#8 /var/www/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('caching', Array)
#9 /var/www/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/setting/c...', Array)
#10 /var/www/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#11 /var/www/index.php(26): yii\base\Application->run()
#12 {main}
```

### Additional info

Adding a `@` at the beginning of the line `opcache_invalidate($configFile);` on https://github.com/humhub/humhub/blob/master/protected/humhub/libs/DynamicConfig.php#L75 solves the problem.

I've got inspired by https://github.com/symfony/symfony/pull/35023/files

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14
| PHP version      | 8.0 to 8.2
| Operating system | unknown

**Comment by luke-** [comment]
Yes, would be ok to suppress the errors here.

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/6231
