### ISSUE TITLE
500 error when trying to post comment

### ISSUE THREAD

**Issue by bkubal** [humhub/humhub#6283]
**Issue:** 
When trying to add a comment to any post on the dashboard or profile, I was receiving a 500 error. I loaded version 1.12.3 on the same site and the error does not occur. 

**Site:** Shared hosing platform (Hostinger)
**PHP Version:** 		PHP 8.0
**HumHub Version:** 	1.14.0

**Error:** 
Class "humhub\modules\comment\widgets\Comment" not found in /home/u836835325/domains/grantees.net/public_html/palmas/protected/humhub/modules/comment/controllers/CommentController.php:141

Stack trace:
```
#0 [internal function]: humhub\modules\comment\controllers\CommentController->humhub\modules\comment\controllers\{closure}()
#1 /home/u836835325/domains/grantees.net/public_html/palmas/protected/vendor/yiisoft/yii2/db/Connection.php(818): call_user_func()
#2 /home/u836835325/domains/grantees.net/public_html/palmas/protected/humhub/modules/comment/controllers/CommentController.php(151): yii\db\Connection->transaction()
#3 [internal function]: humhub\modules\comment\controllers\CommentController->actionPost()
#4 /home/u836835325/domains/grantees.net/public_html/palmas/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /home/u836835325/domains/grantees.net/public_html/palmas/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#6 /home/u836835325/domains/grantees.net/public_html/palmas/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#7 /home/u836835325/domains/grantees.net/public_html/palmas/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#8 /home/u836835325/domains/grantees.net/public_html/palmas/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#9 /home/u836835325/domains/grantees.net/public_html/palmas/index.php(25): yii\base\Application->run()
#10 {main}
```

**Comment by yurabakhtin** [comment]
@bkubal Could you check the file https://github.com/humhub/humhub/blob/master/protected/humhub/modules/comment/widgets/Comment.php exists on your server?
