### ISSUE TITLE
Error when trying to create a new user when Humhub is on maintenance

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6349]
Very low priority!

### What steps will reproduce the problem?

1. Activate maintenance mode.
2. Login with an SSO (not tested without SSO) with a user that hasn't got an account on Humhub.

### What is the expected result?

A message saying that he has no account on the platform and that it's not possible to create one now because of maintenance period.

### What do you get instead?

```
Error: Call to a member function isSystemAdmin() on null in /var/www/humhub/protected/humhub/modules/user/controllers/AuthController.php:160
Stack trace:
#0 [internal function]: humhub\modules\user\controllers\AuthController->onAuthSuccess()
#1 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php(254): call_user_func()
#2 /var/www/humhub/protected/humhub/modules/user/authclient/AuthAction.php(51): yii\authclient\AuthAction->authSuccess()
#3 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php(423): humhub\modules\user\authclient\AuthAction->authSuccess()
#4 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php(232): yii\authclient\AuthAction->authOAuth2()
#5 /var/www/humhub/protected/humhub/modules/user/authclient/AuthAction.php(38): yii\authclient\AuthAction->auth()
#6 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php(216): humhub\modules\user\authclient\AuthAction->auth()
#7 [internal function]: yii\authclient\AuthAction->run()
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array()
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams()
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#12 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#13 /var/www/humhub/index.php(23): yii\base\Application->run()
#14 {main}


Call to a member function isSystemAdmin() on null
1. in /var/www/humhub/protected/humhub/modules/user/controllers/AuthController.phpat line 160
151152153154155156157158159160161162163164165166167168169        if (!Yii::$app->user->isGuest) {
            Yii::$app->user->getAuthClientUserService()->add($authClient);
            return $this->redirect(['/user/account/connected-accounts']);
        }
 
        $authClientService = new AuthClientService($authClient);
 
        $user = $authClientService->getUser();
 
        if (Yii::$app->settings->get('maintenanceMode') && !$user->isSystemAdmin()) {
            return $this->redirect(['/user/auth/login']);
        }
 
        // Check if e-mail is already in use with another auth method
        if ($user === null && isset($attributes['email'])) {
            $user = User::findOne(['email' => $attributes['email']]);
            if ($user !== null) {
                // Map current auth method to user with same e-mail address
                (new AuthClientUserService($user))->add($authClient);
3. humhub\modules\user\controllers\AuthController::onAuthSuccess()
4. in /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php at line 254– call_user_func()
248249250251252253254255256257258259260    protected function authSuccess($client)
    {
        if (!is_callable($this->successCallback)) {
            throw new InvalidConfigException('"' . get_class($this) . '::$successCallback" should be a valid callback.');
        }
 
        $response = call_user_func($this->successCallback, $client);
        if ($response instanceof Response) {
            return $response;
        }
 
        return $this->redirectSuccess();
    }
5. in /var/www/humhub/protected/humhub/modules/user/authclient/AuthAction.php at line 51– yii\authclient\AuthAction::authSuccess()
45464748495051525354    {
        $cookies = \Yii::$app->request->cookies;
        if (!empty($cookies['returnUrlAfterLogin'])) {
            $returnUrl = $cookies['returnUrlAfterLogin']->value;
            \Yii::$app->user->setReturnUrl($returnUrl);
        }
        return parent::authSuccess($client);
    }
 
}
6. in /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php at line 423– humhub\modules\user\authclient\AuthAction::authSuccess()
417418419420421422423424425426427428429        }
 
        // Get the access_token and save them to the session.
        if (($code = $request->get('code')) !== null) {
            $token = $client->fetchAccessToken($code);
            if (!empty($token)) {
                return $this->authSuccess($client);
            }
            return $this->authCancel($client);
        }
 
        $url = $client->buildAuthUrl($authUrlParams);
        return Yii::$app->getResponse()->redirect($url);
7. in /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php at line 232– yii\authclient\AuthAction::authOAuth2()
226227228229230231232233234235236237238     * @return Response response instance.
     * @throws \yii\base\NotSupportedException on invalid client.
     */
    protected function auth($client, $authUrlParams = [])
    {
        if ($client instanceof OAuth2) {
            return $this->authOAuth2($client, $authUrlParams);
        } elseif ($client instanceof OAuth1) {
            return $this->authOAuth1($client, $authUrlParams);
        } elseif ($client instanceof OpenId) {
            return $this->authOpenId($client);
        }
 
8. in /var/www/humhub/protected/humhub/modules/user/authclient/AuthAction.php at line 38– yii\authclient\AuthAction::auth()
32333435363738394041424344        Yii::$app->session->set('loginRememberMe', (boolean) Yii::$app->request->get('rememberMe'));
 
        if ($client instanceof StandaloneAuthClient) {
            return $client->authAction($this);
        }
 
        return parent::auth($client);
    }
 
    /**
     * @inheritdoc
     */
    public function authSuccess($client)
9. in /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php at line 216– humhub\modules\user\authclient\AuthAction::auth()
210211212213214215216217218219220221222            $collection = Yii::$app->get($this->clientCollection);
            if (!$collection->hasClient($clientId)) {
                throw new NotFoundHttpException("Unknown auth client '{$clientId}'");
            }
            $client = $collection->getClient($clientId);
 
            return $this->auth($client);
        }
 
        throw new NotFoundHttpException();
    }
 
    /**
10. yii\authclient\AuthAction::run()
11. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Action.php at line 93– call_user_func_array()
12. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 178– yii\base\Action::runWithParams()
13. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php at line 552– yii\base\Controller::runAction()
14. in /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 103– yii\base\Module::runAction()
15. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 384– yii\web\Application::handleRequest()
16. in /var/www/humhub/index.php at line 23– yii\base\Application::run()
17181920212223242526272829    require(__DIR__ . '/protected/humhub/config/web.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);
 
```

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.2

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6542.

**Comment by marc-farre** [comment]
Thanks @yurabakhtin !
