### ISSUE TITLE
Generic error on uploading profile image on some user accounts

### ISSUE THREAD

**Issue by andwei** [humhub/humhub#6416]
### What steps will reproduce the problem?
A handful of users in my humhub installation gets a generic error message when trying to upload a profile image. A newly created user with the same group memberships/spaces and similar username can upload a profile picture just fine.
The error can be reproduced by simulating the user or activating `adminCanChangeUserProfileImages` in the low-level configuration and trying to upload the image as an admin user. However, I do not know which properties of the user account cause the image upload to fail.

### What is the expected result?
The profile Image is uploaded and displayed without an error message.

### What do you get instead?
A generic error message: (German:) Ein unerwarteter Fehler ist aufgetreten. Sollte dieser weiterhin auftreten kontaktiere den Administrator.

`{
    "readyState": 4,
    "responseText": "{\"error\":true,\"message\":\"\"}",
    "responseJSON": {
        "error": true,
        "message": ""
    },
    "status": 400,
    "statusText": "Bad Request"
}`
### Additional info
I also:
- cleared the cache via CLI
- performed an integrity check via CLI (and deleted some dangling activities)
- set the `adminCanChangeUserProfileImages` parameter to true; same result when trying to upload a profile image for the affected user accounts as admin
- there are no error logs in the administration section relating to that error; changing the humhub installation to dev/debug mode and provoking the issue again did not change that
- I can not see any obvious differences between affected user accounts and a newly created testaccount that hint somewhere :(

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.2
| PHP version  | 7.4.33
| Operating system | Linux (debian bullseye)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
Does testing on a separate instance reproduce the issue as well?

On performing the action check your browser console for errors that happen as well.

I'm kind of curious if you also have the gallery module enabled, and if disabling it fixes the issue. :thinking:

**Comment by andwei** [comment]
Hi

> Does testing on a separate instance reproduce the issue as well?

I can not even reproduce the issue with a different user on the same instance. 

> On performing the action check your browser console for errors that happen as well.

There is basically only the error that Humhub throws, which is directly related to the 400 Bad Request I receive from the backend.

ERROR - humhub.modules.file: Ein unerwarteter Fehler ist aufgetreten. Sollte dieser weiterhin auftreten kontaktiere den Administrator. 

> I'm kind of curious if you also have the gallery module enabled, and if disabling it fixes the issue.

I indeed have the gallery module installed. However, disabling it does not fix the issue.

Now I thought about updating a couple of modules which were slightly outdated:
RestApi to 0.9.2
Report Content to 1.0.2
Custom Pages to 1.9.3
Polls to 1.3.3
Gallery to 1.5.4 (but after deactivating it)

However, the sitation has deteriorated. I can know no longer access the profile of several users (including all of which formerly have been affected by the "can't upload their profile iamge" issue) using an admin user. I get an error page (German again):
>  Uuuups ... Du hast womöglich den falschen Weg eingeschlagen.
> Es ist ein interner Fehler aufgetreten.
> Button <Zurück zur Übersicht>

This time, I *do* get an error in the system log:
`
Error: Call to undefined method humhub\modules\rest\models\ApiUser::find() in <redacted>/protected/humhub/modules/content/components/ContentContainerController.php:165
Stack trace:
#0 <redacted>/protected/humhub/modules/content/components/ContentContainerController.php(73): humhub\modules\content\components\ContentContainerController->getContentContainerByGuid('1d37ff21-0755-4...')
#1 <redacted>/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\content\components\ContentContainerController->init()
#2 <redacted>/protected/vendor/yiisoft/yii2/base/Controller.php(95): yii\base\BaseObject->__construct(Array)
#3 [internal function]: yii\base\Controller->__construct('profile', Object(humhub\modules\user\Module), Array)
#4 <redacted>/protected/vendor/yiisoft/yii2/di/Container.php(411): ReflectionClass->newInstanceArgs(Array)
#5 <redacted>/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('humhub\\modules\\...', Array, Array)
#6 <redacted>/protected/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('humhub\\modules\\...', Array)
#7 <redacted>/protected/vendor/yiisoft/yii2/base/Module.php(666): yii\BaseYii::createObject('humhub\\modules\\...', Array)
#8 <redacted>/protected/vendor/yiisoft/yii2/base/Module.php(620): yii\base\Module->createControllerByID('profile')
#9 <redacted>/protected/vendor/yiisoft/yii2/base/Module.php(612): yii\base\Module->createController('')
#10 <redacted>/protected/vendor/yiisoft/yii2/base/Module.php(546): yii\base\Module->createController('profile')
#11 <redacted>/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/profile', Array)
#12 <redacted>/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#13 <redacted>/index.php(25): yii\base\Application->run()
#14 {main} 
`

I also tried to again create a user to reproduce, which failed. Note that nearly all users are created using the REST-API module. However, a new user created using the same API call can view his profile and upload a profile picture.

I noticed that the users affected seem to fall into a certain time span, i.e. only users created via the REST-API module during the last two months seem to be affected. I unfortunately cannot exactly reconstruct if an update of the REST-API module was executed back then. The new users that are not affected were either created using the Admin GUI or the REST-API module version 0.9.2 (before, version 0.9.1 was installed).

Ok, following up on that: I can confirm that all users whose profile I cannot view (and I would assume that they are very likely the same set of users that could not upload a profile picture) have the value `humhub\modules\rest\models\ApiUser` in the column contentcontainer.class in the row linked to their user account. I think this would be linked to [Humhub REST API #129](https://github.com/humhub/rest/issues/129)

The question for me now would be, if I can fix that problem by just resetting that class column to `humhub\modules\user\models\User` or if that would cause some more trouble :grimacing:

**Comment by andwei** [comment]
Feeling reckless today, I can confirm that manually changing the contentcontainer.class string from
`humhub\modules\rest\models\ApiUser` to `humhub\modules\user\models\User` in the database seems to solve both issues.

I would really appreciate some further information on why would this be a bad idea or a good workaround, though :)

**Comment by luke-** [comment]
@andwei The latest REST API module version should fixes the problem: https://github.com/humhub/rest/issues/129

If the affected users were created via the REST API, it may be that an invalid "authclient" was given. In such cases, Humhub cannot check whether the user is allowed to change his profile picture.

**Comment by andwei** [comment]
Hey @luke-
the authclient_id is `NULL` for all users on that instance.

However, all users affected by 
- "cannot view the profile" after update of the REST API module to 0.9.2
- "cannot upload/edit profile image/banner" with REST API module 0.9.1

do have in common that the `contentcontainer.class` column of the referenced contentcontainer is set to `humhub\modules\rest\models\ApiUser`. If I change that manually to `humhub\modules\user\models\User` the issue can no longer be observed - user profiles can be viewed and profie images/banners edited/uploaded.

I can confirm that a user that is created using version 0.9.2 of the REST API module does indeed not show any problems (and has `contentcontainer.class = humhub\modules\user\models\User` in the referenced contentcontainer row). I am near 100% sure that all users created using the REST API module version 0.9.1 have that column set to the invalid value which causes the problem(s).

See below the output of `SELECT authclient_id, contentcontainer.class FROM user INNER JOIN contentcontainer USING (guid) WEHRE status = 1 ORDER BY created_at DESC LIMIT 50;`
```
+------+---------------------+---------------+------------------------------------+
| id   | created_at          | authclient_id | class                              |
+------+---------------------+---------------+------------------------------------+
| 1614 | 2023-07-07 23:07:47 | NULL          | humhub\modules\user\models\User    |
| 1612 | 2023-07-07 10:42:34 | NULL          | humhub\modules\rest\models\ApiUser |
| 1611 | 2023-07-07 09:38:37 | NULL          | humhub\modules\rest\models\ApiUser |
| 1610 | 2023-07-05 20:12:08 | NULL          | humhub\modules\user\models\User    |
| 1608 | 2023-07-02 22:33:14 | NULL          | humhub\modules\rest\models\ApiUser |
| 1607 | 2023-07-02 12:48:34 | NULL          | humhub\modules\rest\models\ApiUser |
| 1606 | 2023-07-01 14:17:57 | NULL          | humhub\modules\rest\models\ApiUser |
| 1605 | 2023-06-30 14:45:52 | NULL          | humhub\modules\rest\models\ApiUser |
| 1604 | 2023-06-30 12:24:27 | NULL          | humhub\modules\rest\models\ApiUser |
| 1603 | 2023-06-28 17:52:48 | NULL          | humhub\modules\rest\models\ApiUser |
| 1602 | 2023-06-28 13:58:07 | NULL          | humhub\modules\rest\models\ApiUser |
| 1601 | 2023-06-25 11:22:20 | NULL          | humhub\modules\rest\models\ApiUser |
| 1600 | 2023-06-25 11:11:22 | NULL          | humhub\modules\rest\models\ApiUser |
| 1599 | 2023-06-23 17:02:55 | NULL          | humhub\modules\rest\models\ApiUser |
| 1598 | 2023-06-22 11:46:06 | NULL          | humhub\modules\rest\models\ApiUser |
| 1597 | 2023-06-21 11:50:29 | NULL          | humhub\modules\rest\models\ApiUser |
| 1596 | 2023-06-20 10:50:39 | NULL          | humhub\modules\rest\models\ApiUser |
| 1595 | 2023-06-20 07:31:57 | NULL          | humhub\modules\rest\models\ApiUser |
| 1594 | 2023-06-17 18:11:19 | NULL          | humhub\modules\rest\models\ApiUser |
| 1593 | 2023-06-17 10:31:18 | NULL          | humhub\modules\rest\models\ApiUser |
| 1592 | 2023-06-17 07:51:14 | NULL          | humhub\modules\rest\models\ApiUser |
| 1591 | 2023-06-16 14:55:13 | NULL          | humhub\modules\rest\models\ApiUser |
| 1590 | 2023-06-15 19:34:33 | NULL          | humhub\modules\rest\models\ApiUser |
| 1589 | 2023-06-13 11:09:51 | NULL          | humhub\modules\rest\models\ApiUser |
| 1588 | 2023-06-11 12:08:15 | NULL          | humhub\modules\rest\models\ApiUser |
| 1587 | 2023-06-11 07:49:10 | NULL          | humhub\modules\rest\models\ApiUser |
| 1586 | 2023-06-09 09:19:05 | NULL          | humhub\modules\rest\models\ApiUser |
| 1585 | 2023-06-04 19:12:39 | NULL          | humhub\modules\rest\models\ApiUser |
| 1584 | 2023-06-04 13:01:50 | NULL          | humhub\modules\rest\models\ApiUser |
| 1583 | 2023-05-31 20:33:03 | NULL          | humhub\modules\rest\models\ApiUser |
| 1582 | 2023-05-29 21:27:26 | NULL          | humhub\modules\rest\models\ApiUser |
| 1581 | 2023-05-28 03:14:12 | NULL          | humhub\modules\rest\models\ApiUser |
| 1580 | 2023-05-25 10:04:00 | NULL          | humhub\modules\rest\models\ApiUser |
| 1579 | 2023-05-24 15:50:48 | NULL          | humhub\modules\rest\models\ApiUser |
| 1578 | 2023-05-22 15:30:31 | NULL          | humhub\modules\rest\models\ApiUser |
| 1577 | 2023-05-21 23:20:30 | NULL          | humhub\modules\rest\models\ApiUser |
| 1576 | 2023-05-19 07:44:48 | NULL          | humhub\modules\rest\models\ApiUser |
| 1574 | 2023-05-13 10:06:39 | NULL          | humhub\modules\rest\models\ApiUser |
| 1573 | 2023-05-08 14:27:08 | NULL          | humhub\modules\rest\models\ApiUser |
| 1570 | 2023-05-07 20:50:41 | NULL          | humhub\modules\rest\models\ApiUser |
| 1567 | 2023-05-07 18:41:52 | NULL          | humhub\modules\user\models\User    |
| 1558 | 2023-05-07 09:40:38 | NULL          | humhub\modules\rest\models\ApiUser |
| 1557 | 2023-05-07 04:05:35 | NULL          | humhub\modules\rest\models\ApiUser |
| 1544 | 2023-05-05 07:12:01 | NULL          | humhub\modules\user\models\User    |
| 1540 | 2023-05-02 16:27:03 | NULL          | humhub\modules\rest\models\ApiUser |
| 1539 | 2023-05-02 09:34:09 | NULL          | humhub\modules\rest\models\ApiUser |
| 1538 | 2023-05-01 10:27:54 | NULL          | humhub\modules\user\models\User    |
| 1536 | 2023-04-27 19:07:35 | NULL          | humhub\modules\user\models\User    |
| 1535 | 2023-04-27 19:05:00 | NULL          | humhub\modules\user\models\User    |
| 1534 | 2023-04-27 18:58:23 | NULL          | humhub\modules\user\models\User    |
+------+---------------------+---------------+------------------------------------+
```

User 1614 was created using REST API Module version 0.9.2 --> no problems
User 1610 was created using the WebUI as an admin user. --> no problems
For Users 1567 and 1544 i manually set the `contentcontainer.class` to `humhub\\modules\\user\\models\\User` --> no problems
Users 1539 to 1612 (excluding 1610) were created using the REST API module version 0.9.1 and (excluding 1567 and 1544) exhibit the errorneous behavior on their profile page
Users 1543 and below where *very likely* created with an older Version of the REST API module (<= 0.9.0) --> no problems

AFAICS, users creates via the REST API module Version 0.9.1 do at least have partially broken entries in the database, causing different depending on the currently used REST API module version errors with regard to their profile page.

I do not know how many users use the REST API to create users but from what I know at the moment I would assume they should all be affected by this, if they ever created users using the 0.9.1 version of the REST API module

**Comment by luke-** [comment]
Ok, thanks for the details.

So the problem only affects REST API version 0.9.1 and is fixed as of 0.9.2

For users created with REST API module version 0.9.1, the `object_class` in the DB must be corrected.
