### ISSUE TITLE
New Install - Cannot Delete Users

### ISSUE THREAD

**Issue by archerdanger** [humhub/humhub#6488]
### What steps will reproduce the problem?

Login to admin backend, go to user settings and attempt to delete users. Get message deletion added to queue. 

### What is the expected result?

User is deleted.

### What do you get instead?

Users are not deleted and remain in the system.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.3
| PHP version      | 7.4
| Operating system | linux

cron jobs are set
*/20 | * | * | * | * | php /home/petecom/mightyfoxtribe.org/protected/yii queue/run >/dev/null 2>&1 | 
 
3 | * | * | * | * | /opt/cpanel/ea-php74/root/usr/bin/php /home/petecom/mightyfoxtribe.org/protected/yii cron/run >/dev/null 2>&1

### FULL ERROR LOGS
INFO  Mon, 07 Aug 2023 16:00:02 -0500 application
$_GET = [
'/home/petecom/mightyfoxtribe_org/protected/yii' => ''
'queue/run' => ''
]

$_SERVER = [
'XDG_SESSION_ID' => 'c7929830'
'SHELL' => '/bin/bash'
'MAILTO' => ''
'USER' => 'petecom'
'PATH' => '/usr/bin:/bin'
'PWD' => '/home/petecom'
'LANG' => 'en_US.UTF-8'
'SHLVL' => '1'
'HOME' => '/home/petecom'
'LOGNAME' => 'petecom'
'XDG_RUNTIME_DIR' => '/run/user/3870'
'_' => '/usr/bin/php'
'PHP_SELF' => ''
'REQUEST_TIME_FLOAT' => 1691442002.5415
'REQUEST_TIME' => 1691442002
'argv' => [
0 => '/home/petecom/mightyfoxtribe.org/protected/yii'
1 => 'queue/run'
]
'argc' => 2
]
[ Collapse](https://mightyfoxtribe.org/index.php?r=admin%2Flogging#)
ERROR  Mon, 07 Aug 2023 16:00:04 -0500 queue
Could not execute queued job! Message: The command "'/opt/cpanel/ea-php74/root/usr/bin/php-cgi.cagefs' "" 'queue/exec' '91' '300' '1' '3004' '--color='" failed.

Exit Code: 255(Unknown error)

Working directory: /home/petecom/mightyfoxtribe.org/protected

Output:
================
Status: 404 Not Found
Content-type: text/html; charset=UTF-8

No input file specified.

Error Output:
================
Trace:#0 /home/petecom/mightyfoxtribe.org/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(126): yii\queue\cli\Command->handleMessage('91', 'O:41:"humhub\\mo...', '300', 1)
#1 [internal function]: yii\queue\cli\Command->yii\queue\cli\{closure}('91', 'O:41:"humhub\\mo...', '300', 1)
#2 /home/petecom/mightyfoxtribe.org/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(144): call_user_func(Object(Closure), '91', 'O:41:"humhub\\mo...', '300', 1)
#3 /home/petecom/mightyfoxtribe.org/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83): yii\queue\cli\Queue->handleMessage('91', 'O:41:"humhub\\mo...', '300', 1)
#4 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure))
#5 /home/petecom/mightyfoxtribe.org/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#6 /home/petecom/mightyfoxtribe.org/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker(Object(Closure))
#7 /home/petecom/mightyfoxtribe.org/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false)
#8 [internal function]: yii\queue\db\Command->actionRun()
#9 /home/petecom/mightyfoxtribe.org/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /home/petecom/mightyfoxtribe.org/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#11 /home/petecom/mightyfoxtribe.org/protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('run', Array)
#12 /home/petecom/mightyfoxtribe.org/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('run', Array)
#13 /home/petecom/mightyfoxtribe.org/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array)
#14 /home/petecom/mightyfoxtribe.org/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array)
#15 /home/petecom/mightyfoxtribe.org/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#16 /home/petecom/mightyfoxtribe.org/protected/yii(29): yii\base\Application->run()
#17 {main}
[ Collapse](https://mightyfoxtribe.org/index.php?r=admin%2Flogging#)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
The PHP path is being executed as CGI not CLI which is causing issues.
