### ISSUE TITLE
Error in database migration with update 1.15.0 -> 1.15.3

### ISSUE THREAD

**Issue by liloumuloup** [humhub/humhub#6857]
I encountered a blocking error during my upgrade from 1.15.0 to 1.15.3. I couldn't do the database migration command as it returned and error. Maybe i did something wrong ?

### What steps will reproduce the problem?
* Install 1.15.0
* Upgrade to 1.15.3 following the manual procedure as usual : https://docs.humhub.org/docs/admin/updating#upgrade-manually

### What is the expected result?
Humhub updated to 1.15.3

### What do you get instead?
```
uid203577@od-715f17:/var/www/humhub/protected$ /opt/php8.1/bin/php yii migrate/up --includeModuleMigrations=1
Exception 'Error' with message 'Call to a member function exec() on null'

in /var/www/humhub/protected/humhub/commands/MigrateController.php:83

Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(176): humhub\commands\MigrateController->beforeAction(Object(yii\base\InlineAction))
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('up', Array)
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('up', Array)
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/up', Array)
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#6 /var/www/humhub/protected/yii(29): yii\base\Application->run()
#7 {main}
```
And Humhub asks to setup a new database when going to the URL

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.0
| PHP version      | 8.1
| Operating system | Debian GNU/Linux 8.11

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
Just to check, are you running on InnoDB? Check ACP > Information > Prerequisites

Looking at the error stack the following lines of code is supposed to make sure to use the default table storage engine which isn't set in your case, this should have been fixed in #5054;
https://github.com/humhub/humhub/blob/c6f58b98e042ec98b972fa3f197e5d50027808e2/protected/humhub/commands/MigrateController.php#L76-L86

Another method that could be used is the following but I still believe that @yurabakhtin's method should work fine;

```php
/**
 * @inerhitdoc
 */
public function beforeAction($action)
{
    // Make sure to define default table storage engine
    if (in_array(Yii::$app->db->getDriverName(), ['mysql', 'mysqli'], true)) {
        $engine = Yii::$app->params['databaseDefaultStorageEngine'];
        Yii::$app->db->createCommand("SET default_storage_engine={$engine}")->execute();
    }
    return parent::beforeAction($action);
}
```
In this refactored version:

- We use `Yii::$app->db->createCommand()` to create a new command object for executing SQL statements. This method is Yii's preferred way of executing SQL commands because it handles things like SQL injection prevention and escaping parameters.
- We then use `execute()` to execute the SQL command.

This approach is more Yii-like and safer than directly accessing the `PDO` object and executing SQL statements. It also keeps the code more consistent with Yii's conventions.

**Comment by liloumuloup** [comment]
Hi ! 
Thank you for your answer.

I'm not sure what you need exactly. Here is a screenshot of my prerequisite page : 
![image](https://github.com/humhub/humhub/assets/4968531/7b8373db-e239-4f1e-980c-e59da42c3212)

**Comment by ArchBlood** [comment]
The error you're encountering suggests that `Yii::$app->db->pdo` is null when attempting to execute the `exec()` function in the `beforeAction()` method. This could happen if the database connection is not properly established before this method is called.

As I stated in https://github.com/humhub/humhub/issues/6857#issuecomment-1949646884 the fix would be to use Yii's database command builder `Yii::$app->db->createCommand()` instead of doing a direct SQL injection and safer, if @luke- would like a P/R can be made.

But I'd like to note that in `develop` branch this has been changed to this;
https://github.com/humhub/humhub/blob/ea8d1468d7b162c7928b3e2b6a6665698289ddbb/protected/humhub/commands/MigrateController.php#L90-L108

However, there are a couple of points to consider:

- Database Connection Error Handling: It's important to handle database connection errors gracefully, and the code does this by catching exceptions thrown by `$db->open()`. The `DatabaseHelper::handleConnectionErrors()` method should ideally provide meaningful error handling, logging, and possibly user feedback to help diagnose and resolve connection issues.

- Default Table Storage Engine Setting: The code sets the default storage engine if the database driver is either 'mysql' or 'mysqli', which is consistent with the previous implementation. However, ensure that `$db->pdo` is not null before attempting to call `exec()` on it, as this could still potentially trigger the original error.
