### ISSUE TITLE
cron Error

### ISSUE THREAD

**Issue by bond1211** [humhub/humhub#6992]
Hello, when running from the console, I get this error, what should I do about it?
```
 php /volume1/web/str/protected/yii queue/run
Exception 'Error' with message 'Only arrays and Traversables can be unpacked'

in /volume1/web/str/protected/humhub/helpers/DatabaseHelper.php:72

Stack trace:
#0 /volume1/web/str/protected/humhub/components/ApplicationTrait.php(125): humhub\helpers\DatabaseHelper::handleConnectionErrors(Object(yii\db\Exception))
#1 /volume1/web/str/protected/humhub/components/console/Application.php(43): humhub\components\console\Application->isDatabaseInstalled(true)
#2 /volume1/web/str/protected/vendor/yiisoft/yii2/base/BaseObject.php(110): humhub\components\console\Application->init()
#3 /volume1/web/str/protected/vendor/yiisoft/yii2/base/Application.php(205): yii\base\BaseObject->__construct(Array)
#4 /volume1/web/str/protected/vendor/yiisoft/yii2/console/Application.php(90): yii\base\Application->__construct(Array)
#5 /volume1/web/str/protected/humhub/components/ApplicationTrait.php(51): yii\console\Application->__construct(Array)
#6 /volume1/web/str/protected/yii(31): humhub\components\console\Application->__construct(Array)
#7 {main}
```

HumHub version   | 1.16.0-beta.2
PHP version      |  8.1.18

**Comment by yurabakhtin** [comment]
@luke- I could not reproduce when `$ex->errorInfo` is not array. Maybe some Exception has the property `errorInfo` as array when database connection has an error, so I have implemented a fix for such cases - https://github.com/humhub/humhub/pull/6993.
