### ISSUE TITLE
Space members manager crashes on HumHub 1.16.0-beta.3

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7065]
### What steps will reproduce the problem?

![image](https://github.com/humhub/humhub/assets/23310825/baae0102-69ec-48cc-b3b4-f4340b51a1a2)

E.g.:
https://community.humhub.com/s/cuzyapp/space/manage/member

### What is the expected result?

The members table is displayed

### What do you get instead?

Exception:
Serialization of 'Closure' is not allowed

### Additional info

```
Exception: Serialization of 'Closure' is not allowed in /var/www/humhub/protected/vendor/yiisoft/yii2/db/Query.php:1399
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Query.php(1399): serialize(Object(yii\db\ActiveQuery))
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/data/ActiveDataProvider.php(165): yii\db\Query->__toString()
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(173): yii\data\ActiveDataProvider->prepareTotalCount()
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(223): yii\data\BaseDataProvider->getTotalCount()
#4 [internal function]: yii\data\BaseDataProvider->yii\data\{closure}()
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/data/Pagination.php(356): call_user_func(Object(Closure))
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(136): yii\data\Pagination->getTotalCount()
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/data/ActiveDataProvider.php(105): yii\base\BaseObject->__get('totalCount')
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(102): yii\data\ActiveDataProvider->prepareModels()
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(115): yii\data\BaseDataProvider->prepare()
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(156): yii\data\BaseDataProvider->getModels()
#11 /var/www/humhub/protected/humhub/modules/space/modules/manage/widgets/MemberMenu.php(84): yii\data\BaseDataProvider->getCount()
#12 /var/www/humhub/protected/humhub/modules/space/modules/manage/widgets/MemberMenu.php(43): humhub\modules\space\modules\manage\widgets\MemberMenu->countPendingInvites()
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\space\modules\manage\widgets\MemberMenu->init()
#14 [internal function]: yii\base\BaseObject->__construct(Array)
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#16 /var/www/humhub/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('humhub\\modules\\...', Array, Array)
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\modules\\...', Array, Array)
#18 /var/www/humhub/protected/humhub/components/Widget.php(59): yii\BaseYii::createObject(Array)
#19 /var/www/humhub/protected/humhub/modules/space/modules/manage/views/member/index.php(23): humhub\components\Widget::widget(Array)
#20 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/clients/0...')
#21 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(258): yii\base\View->renderPhpFile('/home/clients/0...', Array)
#22 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(157): yii\base\View->renderFile('/home/clients/0...', Array, Object(humhub\modules\space\modules\manage\controllers\MemberController))
#23 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('index', Array, Object(humhub\modules\space\modules\manage\controllers\MemberController))
#24 /var/www/humhub/protected/humhub/modules/space/modules/manage/controllers/MemberController.php(75): yii\base\Controller->render('index', Array)
#25 [internal function]: humhub\modules\space\modules\manage\controllers\MemberController->actionIndex()
#26 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#27 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#28 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#29 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('space/manage/me...', Array)
#30 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#31 /var/www/humhub/index.php(28): yii\base\Application->run()
#32 {main}
Copy StacktraceSearch StackoverflowSearch GoogleException
Exception
Serialization of 'Closure' is not allowed
1. in /var/www/humhub/protected/vendor/yiisoft/yii2/db/Query.phpat line 1399
139013911392139313941395139613971398139914001401        ]);
    }
 
    /**
     * Returns the SQL representation of Query
     * @return string
     */
    public function __toString()
    {
        return serialize($this);
    }
}
2. in /var/www/humhub/protected/vendor/yiisoft/yii2/db/Query.php at line 1399– serialize(yii\db\ActiveQuery)
3. in /var/www/humhub/protected/vendor/yiisoft/yii2/data/ActiveDataProvider.php at line 165– yii\db\Query::__toString()
4. in /var/www/humhub/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php at line 173– yii\data\ActiveDataProvider::prepareTotalCount()
5. in /var/www/humhub/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php at line 223– yii\data\BaseDataProvider::getTotalCount()
6. yii\data\BaseDataProvider::yii\data\{closure}()
7. in /var/www/humhub/protected/vendor/yiisoft/yii2/data/Pagination.php at line 356– call_user_func(Closure)
8. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php at line 136– yii\data\Pagination::getTotalCount()
9. in /var/www/humhub/protected/vendor/yiisoft/yii2/data/ActiveDataProvider.php at line 105– yii\base\BaseObject::__get('totalCount')
10. in /var/www/humhub/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php at line 102– yii\data\ActiveDataProvider::prepareModels()
11. in /var/www/humhub/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php at line 115– yii\data\BaseDataProvider::prepare()
12. in /var/www/humhub/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php at line 156– yii\data\BaseDataProvider::getModels()
13. in /var/www/humhub/protected/humhub/modules/space/modules/manage/widgets/MemberMenu.php at line 84– yii\data\BaseDataProvider::getCount()
78798081828384858687888990    protected function countPendingInvites()
    {
        $searchModel = new MembershipSearch();
        $searchModel->space_id = $this->space->id;
        $searchModel->status = Membership::STATUS_INVITED;
 
        return $searchModel->search([])->getCount();
    }
 
    /**
     * Returns the number of currently pending approvals
     *
     * @return int currently pending approvals
14. in /var/www/humhub/protected/humhub/modules/space/modules/manage/widgets/MemberMenu.php at line 43– humhub\modules\space\modules\manage\widgets\MemberMenu::countPendingInvites()
37383940414243444546474849            'label' => Yii::t('SpaceModule.manage', 'Members'),
            'url' => $this->space->createUrl('/space/manage/member/index'),
            'sortOrder' => 100,
            'isActive' => MenuLink::isActiveState(null, 'member', 'index'),
        ]));
 
        if ($this->countPendingInvites() != 0) {
            $this->addEntry(new MenuLink([
                'label' => Yii::t('SpaceModule.manage', 'Pending Invites') . '&nbsp;&nbsp;<span class="label label-danger">' . $this->countPendingInvites() . '</span>',
                'url' => $this->space->createUrl('/space/manage/member/pending-invitations'),
                'sortOrder' => 200,
                'isActive' => MenuLink::isActiveState(null, 'member', 'pending-invitations'),
            ]));
15. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php at line 109– humhub\modules\space\modules\manage\widgets\MemberMenu::init()
16. yii\base\BaseObject::__construct(['space' => humhub\modules\space\models\Space])
17. in /var/www/humhub/protected/vendor/yiisoft/yii2/di/Container.php at line 419– ReflectionClass::newInstanceArgs([['space' => humhub\modules\space\models\Space]])
18. in /var/www/humhub/protected/vendor/yiisoft/yii2/di/Container.php at line 170– yii\di\Container::build('humhub\modules\space\modules\man...', [], ['space' => humhub\modules\space\models\Space])
19. in /var/www/humhub/protected/vendor/yiisoft/yii2/BaseYii.php at line 365– yii\di\Container::get('humhub\modules\space\modules\man...', [], ['space' => humhub\modules\space\models\Space])
20. in /var/www/humhub/protected/humhub/components/Widget.php at line 59– yii\BaseYii::createObject(['space' => humhub\modules\space\models\Space])
53545556575859606162636465        \yii\base\Event::trigger(static::class, self::EVENT_CREATE, new WidgetCreateEvent($config));
 
        ob_start();
        ob_implicit_flush(false);
        try {
            /* @var $widget Widget */
            $widget = Yii::createObject($config);
            $out = '';
            if ($widget->beforeRun()) {
                $result = (empty($widget->widgetLayout)) ? $widget->run() : $widget->render($widget->widgetLayout, $widget->getLayoutViewParams());
                $out = $widget->afterRun($result);
            }
        } catch (\Throwable $e) {
21. in /var/www/humhub/protected/humhub/modules/space/modules/manage/views/member/index.php at line 23– humhub\components\Widget::widget(['space' => humhub\modules\space\models\Space, 'class' => 'humhub\modules\space\modules\man...'])
17181920212223242526272829?>
 
<div class="panel panel-default">
    <div class="panel-heading">
        <?= Yii::t('SpaceModule.manage', '<strong>Manage</strong> members'); ?>
    </div>
    <?= MemberMenu::widget(['space' => $space]); ?>
    <div class="panel-body">
 
        <?php $form = ActiveForm::begin(['method' => 'get']); ?>
        <div class="row">
            <div class="col-md-6">
                <div class="input-group">
22. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 348– require('/home/clients/0e7d836e1d28c87120...')
23. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 258– yii\base\View::renderPhpFile('/home/clients/0e7d836e1d28c87120...', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => humhub\modules\space\modules\manage\models\MembershipSearch, 'space' => humhub\modules\space\models\Space])
24. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 157– yii\base\View::renderFile('/home/clients/0e7d836e1d28c87120...', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => humhub\modules\space\modules\manage\models\MembershipSearch, 'space' => humhub\modules\space\models\Space], humhub\modules\space\modules\manage\controllers\MemberController)
25. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 407– yii\base\View::render('index', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => humhub\modules\space\modules\manage\models\MembershipSearch, 'space' => humhub\modules\space\models\Space], humhub\modules\space\modules\manage\controllers\MemberController)
26. in /var/www/humhub/protected/humhub/modules/space/modules/manage/controllers/MemberController.php at line 75– yii\base\Controller::render('index', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => humhub\modules\space\modules\manage\models\MembershipSearch, 'space' => humhub\modules\space\models\Space])
69707172737475767778798081                return Yii::$app->request->post();
            }
 
            return $membership->getErrors();
        }
 
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'space' => $space,
        ]);
    }
 
27. humhub\modules\space\modules\manage\controllers\MemberController::actionIndex()
28. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57– call_user_func_array([humhub\modules\space\modules\manage\controllers\MemberController, 'actionIndex'], [])
29. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 178– yii\base\InlineAction::runWithParams(['cguid' => '0c4393fe-66e3-4417-aa03-7c7fed3c...'])
30. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php at line 552– yii\base\Controller::runAction('', ['cguid' => '0c4393fe-66e3-4417-aa03-7c7fed3c...'])
31. in /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 103– yii\base\Module::runAction('space/manage/member', ['cguid' => '0c4393fe-66e3-4417-aa03-7c7fed3c...'])
32. in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 384– yii\web\Application::handleRequest(humhub\components\Request)
33. in /var/www/humhub/index.php at line 28– yii\base\Application::run()
222324252627282930313233    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);
 
try {
    (new humhub\components\Application($config))->run();
} catch (\Throwable $ex) {
    if (null === DatabaseHelper::handleConnectionErrors($ex)) {
        throw $ex;
    }
}
```

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.0-beta.3
| PHP version      | 8.3
| Operating system | Ubuntu

**Comment by marc-farre** [comment]
@luke- I wanted to fix it, but the issue doesn't occur on the develop branch.

@yurabakhtin maybe you are aware of this issue, and it has been fixed somewhere?

**Comment by yurabakhtin** [comment]
> maybe you are aware of this issue, and it has been fixed somewhere?

@marc-farre Yes, it was fixed [here](https://github.com/humhub/humhub-internal/issues/279#issuecomment-2162408262).

**Comment by marc-farre** [comment]
@yurabakhtin Thanks!

@luke- I've created the PR https://github.com/humhub/humhub/pull/7076 only to mention this issue in the changelog, so that we know it is fixed in beta-4.
