### ISSUE TITLE
Crash when searching for text ending with hyphen

### ISSUE THREAD

**Issue by gramakri** [humhub/humhub#7102]
### What steps will reproduce the problem?

Search for text with hyphen to reproduce the crash

### What is the expected result?

Should not crash

### What do you get instead?

![image](https://github.com/humhub/humhub/assets/82041/376cc817-e2d5-4809-b79f-0a3c0e877ffb)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | HumHub 1.16.1
| PHP version      | PHP 8.1
| Operating system | Cloudron (Docker)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

It doesn't produce any logs despite `YII_DEBUG` set to true and `YII_ENV` set to dev.

The browser console does have crash logs:

![image](https://github.com/humhub/humhub/assets/82041/72807783-faf4-4f03-b330-848de316c8d0)

Request:
```
provider=humhub%5Cmodules%5Ccontent%5Csearch%5CContentSearchProvider&keyword=what-is-&route=%2Fcontent%2Fsearch
```

Response:
```
<h1>Invalid database configuration</h1>
<p><strong>SQLSTATE[42000]: Syntax error or access violation: 1064 syntax error, unexpected $end, expecting FTS_TERM or FTS_NUMB or '*'
The SQL being executed was: SELECT COUNT(*) FROM `content` LEFT JOIN `contentcontainer` ON `content`.`contentcontainer_id` = `contentcontainer`.`id` LEFT JOIN `content_fulltext` ON content_fulltext.content_id=content.id LEFT JOIN `space` ON contentcontainer . pk = space . id and contentcontainer .class='humhub\\modules\\space\\models\\Space' LEFT JOIN `user` `cuser` ON contentcontainer . pk = cuser . id and contentcontainer .class='humhub\\modules\\user\\models\\User' LEFT JOIN `space_membership` ON contentcontainer . pk = space_membership . space_id and contentcontainer .class='humhub\\modules\\space\\models\\Space' and space_membership . user_id =1 WHERE (content_fulltext.content_id IS NOT NULL) AND (MATCH(content_fulltext.contents, content_fulltext.comments, content_fulltext.files) AGAINST ('+what-is-*' IN BOOLEAN MODE)) AND (`content`.`state`=1) AND (space.id IS NOT NULL AND ( space_membership.status=3 OR (content.visibility=1 AND space.visibility != 0) ) OR cuser.id IS NOT NULL AND (   (content.visibility = 1) OR   (content.visibility = 0 AND content.contentcontainer_id=1))OR content.created_by=1 OR content.contentcontainer_id IS NULL)</strong></p>
<p>The following connection string was used:<br><code>mysql:host=mysql;dbname=c6fdf930db93dd29</code></p>
<br>
<h2>Technical information</h2>
<p><code>["yii\\db\\Exception","42000",1064,"syntax error, unexpected $end, expecting FTS_TERM or FTS_NUMB or '*'"]</code></p>
<p><pre>PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 syntax error, unexpected $end, expecting FTS_TERM or FTS_NUMB or '*' in /app/code/protected/vendor/yiisoft/yii2/db/Command.php:1320
Stack trace:
#0 /app/code/protected/vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement->execute()
#1 /app/code/protected/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute()
#2 /app/code/protected/vendor/yiisoft/yii2/db/Command.php(443): yii\db\Command->queryInternal()
#3 /app/code/protected/vendor/yiisoft/yii2/db/Query.php(497): yii\db\Command->queryScalar()
#4 /app/code/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(352): yii\db\Query->queryScalar()
#5 /app/code/protected/vendor/yiisoft/yii2/db/Query.php(368): yii\db\ActiveQuery->queryScalar()
#6 /app/code/protected/humhub/modules/content/search/driver/MysqlDriver.php(125): yii\db\Query->count()
#7 /app/code/protected/humhub/modules/content/search/ContentSearchProvider.php(80): humhub\modules\content\search\driver\MysqlDriver->search()
#8 /app/code/protected/humhub/services/MetaSearchService.php(60): humhub\modules\content\search\ContentSearchProvider->getResults()
#9 [internal function]: humhub\services\MetaSearchService->humhub\services\{closure}()
#10 /app/code/protected/vendor/yiisoft/yii2/caching/Cache.php(608): call_user_func()
#11 /app/code/protected/humhub/services/MetaSearchService.php(61): yii\caching\Cache->getOrSet()
#12 /app/code/protected/humhub/widgets/MetaSearchProviderWidget.php(53): humhub\services\MetaSearchService->search()
#13 /app/code/protected/humhub/widgets/MetaSearchProviderWidget.php(36): humhub\widgets\MetaSearchProviderWidget->initProvider()
#14 /app/code/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\widgets\MetaSearchProviderWidget->init()
#15 [internal function]: yii\base\BaseObject->__construct()
#16 /app/code/protected/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#17 /app/code/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#18 /app/code/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#19 /app/code/protected/humhub/components/Widget.php(59): yii\BaseYii::createObject()
#20 /app/code/protected/humhub/controllers/MetaSearchController.php(26): humhub\components\Widget::widget()
#21 [internal function]: humhub\controllers\MetaSearchController->actionIndex()
#22 /app/code/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#23 /app/code/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#24 /app/code/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#25 /app/code/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#26 /app/code/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#27 /app/code/index.php(28): yii\base\Application->run()
#28 {main}</pre></p>
```

**Comment by gramakri** [comment]
As a note, searching for strings not ending with hyphen works fine
