### ISSUE TITLE
Choice between Instant or Background Jobs

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#7134]
### Is your feature request related to a problem? Please describe.
It would be nice not just having the module disabling and uninstalling in the background, as currently this is how the process goes, but it should be configurable at the very least, the old way was instant and cleared the cache correctly, having them as background jobs depend on the Cron Jobs which do not clear the module cache after disabling or uninstalling and force using ACP > Settings > Advanced > Caching.

### Describe the solution you'd like
I'd like it so that the user could have either the background job or an instant method for disabling & uninstalling a module.

### Describe alternatives you've considered
Revert away from using background jobs or properly handle cache for jobs.

https://community.humhub.com/content/perma?id=279751

**Comment by ArchBlood** [comment]
I say this because some server providers use a cache management system that could prevent HumHub from clearing cache in the background jobs, one system that I can note that does this is Cachewall which normally the user does not have permissions to manage.

**Comment by luke-** [comment]
You are right, the APC cache cannot always be flushed outside of the WebServer process (e.g. Cron). I would therefore remove this option soon. At least in the ACP. Files/Redis can be reliable flushed.

---

In the current case, the user seems to have a problem with the queue processing/cron jobs. It is important that the user fixes this problem instead of us introducing an option to bypass it for that case.

**Comment by Robkne** [comment]
After a lot of testing the problem with the queue processing cron jobs is resolved.

Whenever the job is running I get this error message:

yii\base\ErrorException: Undefined array key "SCRIPT_FILENAME" in /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php:168
Stack trace:
#0 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(168): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/home2/organxom...', 168)
#1 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(126): yii\queue\cli\Command->handleMessage(3, 'O:48:"humhub\\mo...', 3600, 1)
#2 [internal function]: yii\queue\cli\Command->yii\queue\cli\{closure}(3, 'O:48:"humhub\\mo...', 3600, 1)
#3 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(144): call_user_func(Object(Closure), 3, 'O:48:"humhub\\mo...', 3600, 1)
#4 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(82): yii\queue\cli\Queue->handleMessage(3, 'O:48:"humhub\\mo...', 3600, 1)
#5 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure))
#6 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(114): call_user_func(Object(Closure), Object(Closure))
#7 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(79): yii\queue\cli\Queue->runWorker(Object(Closure))
#8 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(57): yii\queue\db\Queue->run(false)
#9 [internal function]: yii\queue\db\Command->actionRun()
#10 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('run', Array)
#13 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('run', Array)
#14 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array)
#15 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array)
#16 /home2/organxom/sandbox.8045.mx/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#17 /home2/organxom/sandbox.8045.mx/protected/yii(31): yii\base\Application->run()
#18 {main}

**Comment by luke-** [comment]
@Robkne Any entries in the configuration files at `protected/config`?

**Comment by Robkne** [comment]
No

**Comment by luke-** [comment]
@Robkne Hmm, it is strange why SCRIPT_NAME is not available on your system.

https://www.php.net/manual/en/reserved.variables.server.php
https://github.com/yiisoft/yii2-queue/blob/master/src/cli/Command.php#L168

**Comment by ArchBlood** [comment]
> why SCRIPT_NAME is not available

Could be an issue related to `fastcgi_params`? If it's not set there then I could see this issue happening.

**Comment by luke-** [comment]
> > why SCRIPT_NAME is not available
> 
> Could be an issue related to `fastcgi_params`? If it's not set there then I could see this issue happening.

Hmm, not sure, because it's in Console context

**Comment by ArchBlood** [comment]
> > > why SCRIPT_NAME is not available
> > 
> > 
> > Could be an issue related to `fastcgi_params`? If it's not set there then I could see this issue happening.
> 
> Hmm, not sure, because it's in Console context

The only other thing that I could think of would be an issue with the CLI and something like `$scriptFilename = $_SERVER['SCRIPT_FILENAME'] ?? null;` would be needed as a temporary fix, but I don't think that would be the best solution to actually fix the issue as it seems to be a environment configuration issue rather than a Humhub specific issue.

**Comment by Robkne** [comment]
It seem that the problem is the server. When I run the script in terminal it works.

**Comment by Robkne** [comment]
Finally I found the problem. It was the .htaccess file in the "protected" folder which says the following:

<IfModule authz_core_module>
    Require all denied
</IfModule>
<IfModule !authz_core_module>
    Deny from all
</IfModule>

I added this code and it works fine.

Order deny,allow
Allow from THIS_SERVER_IP
Allow from 127.0.0.1
Deny from all

**Comment by ArchBlood** [comment]
> Finally I found the problem. It was the .htaccess file in the "protected" folder which says the following:
> 
> `<IfModule authz_core_module> Require all denied </IfModule> <IfModule !authz_core_module> Deny from all </IfModule>`
> 
> I added this code and it works fine.
> 
> Order deny,allow Allow from THIS_SERVER_IP Allow from 127.0.0.1 Deny from all

I'm not sure this is the best of options, I'd suggest something more along the lines of the following;

### Option for servers where cron has issues
```htaccess
<IfModule authz_core_module>
    Require all denied
</IfModule>
<IfModule !authz_core_module>
    Order deny,allow
    Deny from all
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine on
    
    RewriteCond %{REQUEST_URI} ^/protected/
    RewriteCond %{ENV:REDIRECT_STATUS} !=200
    RewriteCond %{ENV:REDIRECT_STATUS} !=403
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule .* - [L,F]
</IfModule>
```

Then within the `yii` file itself something like this;

```php
#!/usr/bin/env php
<?php

/**
 * HumHub Console Bootstrap File
 */

// Ensure CLI execution only
if (php_sapi_name() !== 'cli') {
    die('This script can only be run from command line.');
}

// Verify execution context
if (isset($_SERVER['REMOTE_ADDR'])) {
    die('This script cannot be run from a web browser.');
}

// Basic path definitions
defined('ROOT_DIR') or define('ROOT_DIR', dirname(__DIR__));
defined('PROTECTED_DIR') or define('PROTECTED_DIR', __DIR__);

// Environment setup
defined('YII_DEBUG') or define('YII_DEBUG', false);
defined('YII_ENV') or define('YII_ENV', 'prod');

// Handle FCGI missing constants
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));
defined('STDERR') or define('STDERR', fopen('php://stderr', 'w'));

// Error reporting
error_reporting(E_ALL & ~E_NOTICE);
ini_set('display_errors', 1);

// Check essential files
$autoloadFile = PROTECTED_DIR . '/vendor/autoload.php';
$yiiFile = PROTECTED_DIR . '/vendor/yiisoft/yii2/Yii.php';

if (!file_exists($autoloadFile)) {
    die("Error: Composer autoloader not found.\nRun 'composer install' first.\n");
}

if (!file_exists($yiiFile)) {
    die("Error: Yii framework not found.\nRun 'composer install' first.\n");
}

// Required files
require($autoloadFile);
require($yiiFile);

// Configuration files
$configFiles = [
    PROTECTED_DIR . '/humhub/config/common.php',
    PROTECTED_DIR . '/humhub/config/console.php',
    PROTECTED_DIR . '/config/common.php',
    PROTECTED_DIR . '/config/console.php'
];

// Dynamic config if exists
$dynamicConfigFile = PROTECTED_DIR . '/config/dynamic.php';
if (is_readable($dynamicConfigFile)) {
    $configFiles[] = $dynamicConfigFile;
}

// Merge configurations
try {
    $config = array_reduce($configFiles, function ($carry, $file) {
        if (is_readable($file)) {
            return yii\helpers\ArrayHelper::merge($carry, require($file));
        }
        return $carry;
    }, []);
} catch (Exception $e) {
    die("Error loading configuration files: " . $e->getMessage() . "\n");
}

// Database connection retry logic
$maxRetries = 3;
$retryDelay = 5; // seconds

for ($retry = 0; $retry <= $maxRetries; $retry++) {
    try {
        // Create and run application
        $application = new humhub\components\console\Application($config);
        $exitCode = $application->run();
        exit($exitCode);
    } catch (Throwable $e) {
        // Handle database connection errors
        if (class_exists('humhub\helpers\DatabaseHelper') && 
            method_exists('humhub\helpers\DatabaseHelper', 'handleConnectionErrors')) {
            $handled = humhub\helpers\DatabaseHelper::handleConnectionErrors($e);
            if ($handled !== null) {
                if ($retry < $maxRetries) {
                    echo "Database connection failed. Retrying in {$retryDelay} seconds...\n";
                    sleep($retryDelay);
                    continue;
                }
                die("Maximum retry attempts reached. Database connection failed.\n");
            }
        }
        
        // Handle other errors
        $errorMessage = sprintf(
            "Error: %s\nFile: %s\nLine: %d\n",
            $e->getMessage(),
            $e->getFile(),
            $e->getLine()
        );
        
        // Log error if possible
        if (function_exists('error_log')) {
            error_log($errorMessage);
        }
        
        // Display error
        fwrite(STDERR, $errorMessage);
        exit(1);
    }
}
```
