### ISSUE TITLE
Space permissions now result in "An internal server error occurred"

### ISSUE THREAD

**Issue by WizWareTech** [humhub/humhub#7194]
### What steps will reproduce the problem?
Go to a space, select settings, then click on permissions tab.
### What is the expected result?
Permissions page shows
### What do you get instead?
Oooops... It looks like you may have taken the wrong turn.
An internal server error occurred.
### Additional info
From log:
Error  Thu, 29 Aug 2024 13:16:24 -0600 yii\base\InvalidConfigException
yii\base\InvalidConfigException: Object configuration must be an array containing a "class" or "__class" element. in /var/www/humhub/protected/vendor/yiisoft/yii2/BaseYii.php:368
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(445): yii\BaseYii::createObject()
#1 /var/www/humhub/protected/humhub/modules/user/components/PermissionManager.php(405): yii\base\Module->getModule()
#2 /var/www/humhub/protected/humhub/modules/user/components/PermissionManager.php(468): humhub\modules\user\components\PermissionManager->getPermissions()
#3 /var/www/humhub/protected/humhub/modules/user/widgets/PermissionGridEditor.php(104): humhub\modules\user\components\PermissionManager->createPermissionArray()
#4 /var/www/humhub/protected/humhub/modules/user/widgets/PermissionGridEditor.php(64): humhub\modules\user\widgets\PermissionGridEditor->getDataProvider()
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\user\widgets\PermissionGridEditor->init()
#6 [internal function]: yii\base\BaseObject->__construct()
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(143): yii\BaseYii::createObject()
#11 /var/www/humhub/protected/humhub/modules/space/modules/manage/views/security/permissions.php(37): yii\base\Widget::widget()
#12 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('...')
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(258): yii\base\View->renderPhpFile()
#14 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(157): yii\base\View->renderFile()
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render()
#16 /var/www/humhub/protected/humhub/modules/space/modules/manage/controllers/SecurityController.php(86): yii\base\Controller->render()
#17 [internal function]: humhub\modules\space\modules\manage\controllers\SecurityController->actionPermissions()
#18 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#19 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#20 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#21 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#22 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#23 /var/www/humhub/index.php(28): yii\base\Application->run()
#24 {main}
 Collapse

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.1
| PHP version      | 8.3.4
| Operating system | Debian

**Comment by ArchBlood** [comment]
Unable to reproduce, what modules do you have installed that interact with Spaces and space settings?

**Comment by marc-farre** [comment]
Can you test by removing all configuration in your `protected/config/common.php` file?
Have you got custom modules or a custom theme?
