### ISSUE TITLE
Unknown Method – yii\base\UnknownMethodException / Calling unknown method: humhub\modules\user\models\User::isModuleEnabled()

### ISSUE THREAD

**Issue by blu-IT** [humhub/humhub#7260]
### What steps will reproduce the problem?

When clicking on the directory of users/people or my own profile I get the following error.

### What is the expected result?
See details of the profile/user.

### What do you get instead?
The following error:

```
Unknown Method – [yii\base\UnknownMethodException] - Calling unknown method: humhub\modules\user\models\User::isModuleEnabled()

in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/Component.php at line 308
    299300301302303304305306307308309310311312313314315316317

         */
        public function __call($name, $params)
        {
            $this->ensureBehaviors();
            foreach ($this->_behaviors as $object) {
                if ($object->hasMethod($name)) {
                    return call_user_func_array([$object, $name], $params);
                }
            }
            throw new UnknownMethodException('Calling unknown method: ' . get_class($this) . "::$name()");
        }
     
        /**
         * This method is called after the object is created by cloning an existing one.
         * It removes all behaviors because they are attached to the old object.
         */
        public function __clone()
        {
            $this->_events = [];

    2. in /kunden/my_path/forum-test/protected/modules/bookmark/Events.php at line 52 – [yii\base\Component::__call](https://www.yiiframework.com/doc-2.0/yii-base-component.html#__call()-detail)()
    46474849505152535455565758

            ]);
        }
     
        public static function onProfileMenuInit($event)
        {
            $user = $event->sender->user;
            if ($user->isModuleEnabled('bookmark')) {
                    if ($user->permissionManager->can(new ViewBookmarkStream())) {
                    $event->sender->addItem([
                        'label' => Yii::t('BookmarkModule.base', 'Bookmarks'),
                        'url' => $user->createUrl('/bookmark/profile/show'),
                        'icon' => '<i class="fa fa-bookmark"></i>',
                        'isActive' => (Yii::$app->controller->module && Yii::$app->controller->module->id == 'bookmark'),

    3. humhub\modules\bookmark\Events::onProfileMenuInit()
    4. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/Event.php at line 312 – call_user_func()
    5. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/Component.php at line 650 – [yii\base\Event::trigger](https://www.yiiframework.com/doc-2.0/yii-base-event.html#trigger()-detail)()
    6. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/Widget.php at line 72 – [yii\base\Component::trigger](https://www.yiiframework.com/doc-2.0/yii-base-component.html#trigger()-detail)()
    7. in /kunden/my_path/forum-test/protected/humhub/modules/user/widgets/ProfileMenu.php at line 68 – [yii\base\Widget::init](https://www.yiiframework.com/doc-2.0/yii-base-widget.html#init()-detail)()
    62636465666768697071727374

                'url' => $this->user->createUrl('/user/profile/about'),
                'sortOrder' => 300,
                'isActive' => MenuLink::isActiveState('user', 'profile', 'about'),
                'isVisible' => $this->user->permissionManager->can(ViewAboutPage::class),
            ]));
     
            parent::init();
        }
     
        /**
         * @inheritdoc
         */
        public function run()

    8. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/BaseObject.php at line 109 – humhub\modules\user\widgets\ProfileMenu::init()
    9. [yii\base\BaseObject::__construct](https://www.yiiframework.com/doc-2.0/yii-base-baseobject.html#__construct()-detail)()
    10. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/di/Container.php at line 419 – ReflectionClass::newInstanceArgs()
    11. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/di/Container.php at line 170 – [yii\di\Container::build](https://www.yiiframework.com/doc-2.0/yii-di-container.html#build()-detail)()
    12. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/BaseYii.php at line 365 – [yii\di\Container::get](https://www.yiiframework.com/doc-2.0/yii-di-container.html#get()-detail)()
    13. in /kunden/my_path/forum-test/protected/humhub/components/Widget.php at line 59 – [yii\BaseYii::createObject](https://www.yiiframework.com/doc-2.0/yii-baseyii.html#createObject()-detail)()
    53545556575859606162636465

            \yii\base\Event::trigger(static::class, self::EVENT_CREATE, new WidgetCreateEvent($config));
     
            ob_start();
            ob_implicit_flush(false);
            try {
                /* @var $widget Widget */
                $widget = Yii::createObject($config);
                $out = '';
                if ($widget->beforeRun()) {
                    $result = (empty($widget->widgetLayout)) ? $widget->run() : $widget->render($widget->widgetLayout, $widget->getLayoutViewParams());
                    $out = $widget->afterRun($result);
                }
            } catch (\Throwable $e) {

    14. in /kunden/my_path/forum-test/protected/humhub/modules/user/views/profile/_layout.php at line 18 – humhub\components\Widget::widget()
    12131415161718192021222324

            <div class="col-md-12">
                <?= ProfileHeader::widget(['user' => $user]); ?>
            </div>
        </div>
        <div class="row profile-content">
            <div class="col-md-2 layout-nav-container">
                <?= ProfileMenu::widget(['user' => $user]); ?>
            </div>
            <div class="col-md-<?= ($this->hasSidebar()) ? '7' : '10' ?> layout-content-container">
                <?= $content; ?>
                <?php if (!$this->hasSidebar()): ?>
                    <?= FooterMenu::widget(['location' => FooterMenu::LOCATION_FULL_PAGE]); ?>
                <?php endif; ?>

    15. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/View.php at line 348 – require('/kunden/my_path/forum-test/...')
    16. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/View.php at line 258 – [yii\base\View::renderPhpFile](https://www.yiiframework.com/doc-2.0/yii-base-view.html#renderPhpFile()-detail)()
    17. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/View.php at line 157 – [yii\base\View::renderFile](https://www.yiiframework.com/doc-2.0/yii-base-view.html#renderFile()-detail)()
    18. in /kunden/my_path/forum-test/protected/humhub/components/Controller.php at line 144 – [yii\base\View::render](https://www.yiiframework.com/doc-2.0/yii-base-view.html#render()-detail)()
    138139140141142143144145146147148149150

         * @since 1.2
         */
        public function renderContent($content)
        {
            // Apply Sublayout if provided
            if ($this->subLayout !== null) {
                $content = $this->getView()->render($this->subLayout . '.php', ['content' => $content], $this);
            }
     
            // Return Pjax Snippet
            if (Yii::$app->request->isPjax) {
                return $this->renderAjaxContent($content);
            }

    19. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/Controller.php at line 408 – humhub\components\Controller::renderContent()
    20. in /kunden/my_path/forum-test/protected/humhub/modules/user/controllers/ProfileController.php at line 84 – [yii\base\Controller::render](https://www.yiiframework.com/doc-2.0/yii-base-controller.html#render()-detail)()
    78798081828384858687888990

            if ($this->module->profileDisableStream) {
                return $this->redirect(Url::to(['/user/profile/about', 'container' => $this->getUser()]));
            }
     
            return $this->render('home', [
                'user' => $this->contentContainer,
                'isSingleContentRequest' => !empty(Yii::$app->request->getQueryParam('contentId')),
            ]);
        }
     
        public function actionAbout()
        {
            if (!$this->contentContainer->permissionManager->can(new ViewAboutPage())) {

    21. in /kunden/my_path/forum-test/protected/humhub/modules/user/controllers/ProfileController.php at line 73 – humhub\modules\user\controllers\ProfileController::actionHome()
    67686970717273747576777879

        public function actionIndex()
        {
            if ($this->module->profileDefaultRoute !== null) {
                return $this->redirect(Url::to([$this->module->profileDefaultRoute, 'container' => $this->getUser()]));
            }
     
            return $this->actionHome();
        }
     
        public function actionHome()
        {
            if ($this->module->profileDisableStream) {
                return $this->redirect(Url::to(['/user/profile/about', 'container' => $this->getUser()]));

    22. humhub\modules\user\controllers\ProfileController::actionIndex()
    23. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array()
    24. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/Controller.php at line 178 – [yii\base\InlineAction::runWithParams](https://www.yiiframework.com/doc-2.0/yii-base-inlineaction.html#runWithParams()-detail)()
    25. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/Module.php at line 552 – [yii\base\Controller::runAction](https://www.yiiframework.com/doc-2.0/yii-base-controller.html#runAction()-detail)()
    26. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/web/Application.php at line 103 – [yii\base\Module::runAction](https://www.yiiframework.com/doc-2.0/yii-base-module.html#runAction()-detail)()
    27. in /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/Application.php at line 384 – [yii\web\Application::handleRequest](https://www.yiiframework.com/doc-2.0/yii-web-application.html#handleRequest()-detail)()
    28. in /kunden/my_path/forum-test/index.php at line 28 – [yii\base\Application::run](https://www.yiiframework.com/doc-2.0/yii-base-application.html#run()-detail)()
    222324252627282930313233

        (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
        require(__DIR__ . '/protected/config/common.php'),
        require(__DIR__ . '/protected/config/web.php')
    );
     
    try {
        (new humhub\components\Application($config))->run();
    } catch (\Throwable $ex) {
        if (null === DatabaseHelper::handleConnectionErrors($ex)) {
            throw $ex;
        }
    }

$_GET = [
    'r' => 'user/profile',
    'cguid' => '64138df7-81a7-4617-b99f-e81f9537790c',
];

$_COOKIE = [
    'PHPSESSID' => 'iv1lgcg26blq4iufqeoapupkb1',
    '_csrf' => 'ab38f133d9902deb386f71b26336ec891192795bdc3965550fa341d1db49eeffa:2:{i:0;s:5:"_csrf";i:1;s:32:"gDezAO50eojmJSiss-hHB3HNiOx7Ti1E";}',
    'cookieconsent_status' => 'dismiss',
    '_identity' => 'd725206306c6275f4a6079e69781ce1edc908f1bcc347a301c3a670dd8da63dea:2:{i:0;s:9:"_identity";i:1;s:50:"[1,"64138df7-81a7-4617-b99f-e81f9537790c",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => 'https://forum.pressenz.com/',
    '__id' => 1,
    '__authKey' => '64138df7-81a7-4617-b99f-e81f9537790c',
    '__expire' => 1729098348,
    'currentAuthClientId' => 'local',
    'legalModuleChecked' => 'true',
    'security-script-src-nonce' => '5eWWPkB6QHgJKTHzB0/CBp1y',
    'user.canSeeAdminSection' => true,
    'live.poll.lastQueryTime' => 1729094711,
];

Yii Framework

2024-10-16, 18:05:48

[Apache](https://httpd.apache.org/)

[Yii Framework](https://yiiframework.com/)/[2.0.51-dev](https://github.com/yiisoft/yii2/)
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.2 CE
| PHP version      | 8.1
| Operating system | unkown linux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

```
Error: Class "humhub\modules\search\engine\Search" not found in /kunden/my_path/forum-test/protected/modules/questionanswer/config.php:45
Stack trace:
#0 /kunden/my_path/forum-test/protected/humhub/components/bootstrap/ModuleAutoLoader.php(124): include()
#1 /kunden/my_path/forum-test/protected/humhub/components/bootstrap/ModuleAutoLoader.php(87): humhub\components\bootstrap\ModuleAutoLoader::getModuleConfigByPath()
#2 /kunden/my_path/forum-test/protected/humhub/components/bootstrap/ModuleAutoLoader.php(55): humhub\components\bootstrap\ModuleAutoLoader::findModules()
#3 /kunden/my_path/forum-test/protected/humhub/components/bootstrap/ModuleAutoLoader.php(39): humhub\components\bootstrap\ModuleAutoLoader::locateModules()
#4 /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/Application.php(325): humhub\components\bootstrap\ModuleAutoLoader->bootstrap()
#5 /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#6 /kunden/my_path/forum-test/protected/humhub/components/Application.php(61): yii\web\Application->bootstrap()
#7 /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/Application.php(271): humhub\components\Application->bootstrap()
#8 /kunden/my_path/forum-test/protected/humhub/components/Application.php(42): yii\base\Application->init()
#9 /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\components\Application->init()
#10 /kunden/my_path/forum-test/protected/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
#11 /kunden/my_path/forum-test/protected/humhub/components/ApplicationTrait.php(51): yii\base\Application->__construct()
#12 /kunden/my_path/forum-test/index.php(28): humhub\components\Application->__construct()
#13 {main} 
```

**Comment by marc-farre** [comment]
@blu-IT I look like you have outdated modules.
1. Update all your modules from the Marketplace
2. Check if everything's green in Administration -> Information -> Prerequisites

**Comment by blu-IT** [comment]
Hi,

there was a module "Scroll up" in version 1.0.6 that could not be updated due to license changes (?!) and I removed it now, but the error still persists.
Maybe there is still an older module that was not installed via the marketplace, but via ftp-upload directly, but I'm not sure how to figure that out.

**Comment by blu-IT** [comment]
@marc-farre 

OK, thanks for your hint! 
Indeed there were two old modules (bookmarks and scroll-up) and after removing them, everything works fine again!

**Comment by marc-farre** [comment]
@blu-IT GitHub is for issues about HumHub code.
But you can ask on https://community.humhub.com/, someone (maybe me) will try to help you.

**Comment by ArchBlood** [comment]
The error states that the issue is in regards to `/protected/modules/questionanswer/config.php:45` which isn't the module within the marketplace and is very outdated and has been achieved by the [owner](https://github.com/ConnectedCommunities/humhub-modules-questionanswer) as well as all of their modules, the Scroll Up module had nothing to do with this specific error and should work regardless of version of HumHub, it just wouldn't be possible to update to future versions of the module itself.
