### ISSUE TITLE
Favicon fail

### ISSUE THREAD

**Issue by 8l4ckSh33p** [humhub/humhub#983]
Here my log:

exception.CHttpException.404
```
exception 'CHttpException' with message 'Konnte den Request "ico/apple-touch-icon-144-precomposed.png" nicht auflösen.' in /www/htdocs/w0124xxx/social2/protected/vendors/yii/web/CWebApplication.php:286 Stack trace: #0 /www/htdocs/w0124xxx/social2/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('ico/apple-touch...') #1 /www/htdocs/w0124xxx/social2/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #2 /www/htdocs/w0124xxx/social2/index.php(39): CApplication->run() #3 {main} REQUEST_URI=/ico/apple-touch-icon-144-precomposed.png --- 
```

**Comment by andystrobel** [comment]
These files was replaced with new ones with the 0.11er release. Maybe you updated HumHub but have an older main.php file in your own themes folder!?!

**Comment by 8l4ckSh33p** [comment]
Where is the main.php file?

**Comment by WASasquatch** [comment]
`themes/YourActiveTheme/css/`

**Comment by 8l4ckSh33p** [comment]
Nothing in themes. The other files are fresh form github...
